### ISSUE TITLE
Cannot start/stop/pass arguments to analtyics and broker startup scripts

### ISSUE THREAD

**Issue by sinthuja** [wso2/product-iots#1000]
Cannot pass arguments into the analytics.sh and broker.sh scripts in the PRODUCT_HOME/bin directory.

**Comment by sinthuja** [comment]
Merged with product master.

**Comment by chamaraanu** [comment]
Has it fixed for iot-server.sh as well?

**Comment by sinthuja** [comment]
Yes, it's fixed for iot-server, analytics, and broker scripts as well. You need to get an updated distribution with those changes inorder to verify. Please wait for the next milestone release.

**Comment by sinthuja** [comment]
Please reopen if it's existing in the next milestone pack.
