### ISSUE TITLE
When activities api is called without a limit, only 20 records are returned

### ISSUE THREAD

**Issue by ruwany** [wso2/product-iots#1002]
When the API : /api/device-mgt/v1.0/activities is called without a limit, only 20 records are returned. We should either throw an error asking users to specify a limit or either maintain across api standard when it comes to No. of records returned when a limit is not specified.

**Comment by harshanL** [comment]
This has been limited purposefully for safeguard against expensive operations to fetch all records from db. This can be configured via <PaginationConfiguration> in cdm-config.xml
