### ISSUE TITLE
If a user changes his password he will be logged out of the console

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#1008]
**Steps**

1. Register a user
2. Login from the user and change the password

**Issue**
Ones the password is changed the user is logged out from the console

**Comment by jsonds** [comment]
**Labels -** 3.1.0-M8, Bug, High

**Comment by chaturadilan** [comment]
How do we define the user experience. 
If the user changes the password, the system should show a message to user that the user is going to logout and he will have to re-login again. His session should be invalidated immediately after he change the password.
