### ISSUE TITLE
[Improvement] [Device cloud] Explicit error message should be instead of 500

### ISSUE THREAD

**Issue by kavithasub** [wso2/product-iots#1025]
Scenario : Login to device cloud with wrong domain
Actual outcome : 500 internal Server error

Improvement : There should be an explicit error message for wrong domain

**Comment by milanperera** [comment]
This issue is fixed in [1] and will be available in the next cloud release. 

[1] wso2/carbon-devicemgt-proprietary-plugins#112

**Comment by milanperera** [comment]
This is fixed in the cloud
