### ISSUE TITLE
[Policy] Published policy is applied to the device before it is been applied

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#1030]
**Steps**

- Create a user and a role.
- Create a simply policy (camera disable) and assign the above role for the policy
- Publish the policy ( Do not click on apply changes to devices )
- Enrol an android device using the above created user

**Issue**
The enrolled device is having the policy that was created applied to the device before the policy change is been applied.

**Comment by jsonds** [comment]
**Labels - 3.1.0-M8, bug, high**

**Comment by inoshperera** [comment]
@geethkokila is the behaviour expected?

**Comment by geethkokila** [comment]
This is how it should behave when device enrolled, it should automatically get the effective policy. "Apply changes" is only for when policies are edited and those should be reflected in the devices. It does not need "Apply Changes" for a policy to be applied to the device unless the policy is changed.
