### ISSUE TITLE
Agent-android.apk

### ISSUE THREAD

**Issue by Darkpiou** [wso2/product-iots#1032]
Hello,

How can i force the agent synchronisation ?
Actually, I must synchronize manually my agent (3.1.18) with the option Last server Sync.

Thank you.
IOT 3.1.0 M8

**Comment by harshanL** [comment]
Hi Darpiou,

It depends on the notification mechanism you have configured. In "Local-polling" mode agent will contact the server with configured time-interval and sync with it. If it's FCM then the device will contact the server for each operation it sends. Please refer to doc [1] for more information.

[1]. https://docs.wso2.com/display/IoTS310/Android+Platform+Configurations

Thanks,
Harshan
