### ISSUE TITLE
Remove webapp related permission from permission tree

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#1058]
Since webapps are not supported remove the related permission section for webapps from the permission tree.

![webapp](https://user-images.githubusercontent.com/17248809/27523369-5bfd0d5c-5a4a-11e7-882a-0bcdcdd68b33.jpg)

**Comment by jsonds** [comment]
**Labels -** 3.1.0-Alpha, Bug, High

**Comment by harshanL** [comment]
Hi Jason,

We need to show this permission as this is required for webclips.

Thanks,
Harshan
