### ISSUE TITLE
Make the Default device type non clickable

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#1059]
When you start the pack and view the device types, you are taken to the device types page.
The windows, android-sense, android (ios, raspberry-Pi) device types that come by default are currently clickable. 
Nothing happens when you click them. Can we put some sign to say they are not clickable, please? :)

**Comment by lasanthaDLPDS** [comment]
This issue is fixed with https://github.com/wso2/carbon-device-mgt/pull/819. Hence closed.
