### ISSUE TITLE
[Operations] Once the operation is completed, there should be a way to go back.

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1064]
Pre-Conditions:-
- IoT server should be up and running.
- An Android device should be registered.

Steps:-
1. Login to device management console and perform an operation for the device mentioned in pre-condition.

Expected Results:-
- Once the operation is completed user should be able to go back to the operations UI by clicking anywhere outside the pop-up

Actual Results:
- Pop-up is displayed on a black background
- There is no option to access the operations UI on screen (screenshot attached)

![device_details___wso2_iot_server](https://user-images.githubusercontent.com/13449310/27582122-795497f4-5b4d-11e7-94ec-68bc2d74c0e6.jpg)

**Comment by pubudup** [comment]
Critical,3.1.0-alpha

**Comment by Nirothipan** [comment]
This issue is still prevailing.

**Comment by inoshperera** [comment]
Fixed with, https://github.com/wso2/carbon-device-mgt/pull/814

**Comment by pubudup** [comment]
Fixed in 3.1.0-Beta pack.
