### ISSUE TITLE
[Startup Errors] Exceptions on startup after enrolling a device

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1065]
I was able to start the server/enrol a device and perform some operations. Then I restarted the server. Following exceptions are triggered constantly when I attempt to start the server. The server doesn't get completely started in this state.

OS: Windows
JDK.1.8.0_131-b11

[error_log.txt](https://github.com/wso2/product-iots/files/1105076/error_log.txt)

**Comment by pubudup** [comment]
Critical, 3.1.0-alpha

**Comment by pubudup** [comment]
Attached errors keep continuously printing on the logs.

**Comment by pubudup** [comment]
Looks like this is happening if the server goes down while the devices are connected.

**Comment by harshanL** [comment]
This will be fixed with https://github.com/wso2/product-iots/issues/1057

**Comment by geethkokila** [comment]
https://github.com/wso2/product-iots/pull/1098

**Comment by pubudup** [comment]
Haven't seen this error is 3.1.0-Beta pack.
