### ISSUE TITLE
[Windows/Startup] More startup errors in Windows after executing 

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1069]
Pre-conditions:
- OS should be Windows
- Configure the IoTS to be accessed via IP [1]
- Add the hostname of the server to a cert and add it to the trust store
- Run the sample mobile-qsg.jar with java -jar mobile-qsg.jar (while following the doc as explained at [2])

Steps:-
1. Stop the server
2. Start the server
3. Observe server logs

Expected Results:-
- Server should start up smoothly

Actual Results:-
- A bunch of exceptions keep getting triggered on start-up (attached)
- The server doesn't get started successfully.

[1] https://docs.wso2.com/display/IoTS310/Configuring+WSO2+IoT+Server+with+the+IP
[2] https://docs.wso2.com/display/IoTS310/Android+Device
[startuplog.txt](https://github.com/wso2/product-iots/files/1107668/startuplog.txt)

**Comment by pubudup** [comment]
Tags: Critical, 3.1.0-alpha

**Comment by inoshperera** [comment]
No longer reproducible in the latest builds

**Comment by pubudup** [comment]
Verified in 3.1.0-RC not reproducible.
