### ISSUE TITLE
[Connection error] An exception triggered when the device attempts to connect when it's disconnected from network

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1072]
Pre-Condition:-
- OS Windows
- IoTS should be configured to access via IP [1]
- An Android device should be enrolled successfully
- Device should be disconnected from WIFI

Steps:-
1. Stop the IoTS
2. Start the IoTS
3. Enable WIFI connection in Android Device
4. Observe server logs

Expected Results:-
- There should be no connection related exceptions

Actual Results:-
- Connection refused exceptions are being printed in server logs (attached)

[1] https://docs.wso2.com/display/IoTS310/Configuring+WSO2+IoT+Server+with+the+IP

[connectionrefused.txt](https://github.com/wso2/product-iots/files/1107798/connectionrefused.txt)

**Comment by pubudup** [comment]
Labels: High, 3.1.0-alpha

**Comment by hasuniea** [comment]
You get this error if the analytics module is not started.I was able to reproduce the issue by running only iot-server.sh.But It's not related with that disconnection of the device.

**Comment by pubudup** [comment]
Verified in 3.1.0-RC not reproducible.
