### ISSUE TITLE
Documentation Issue on start up scripts 

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1078]
Quick Start Guide 

https://docs.wso2.com/display/IoTS310/Enterprise+IoT+solution

While going through the docs, it indicates starting three individual profiles; core, analytics , broker
However when the pack is extracted, such is not available

**Comment by shavidissa** [comment]
Thank you!
I update the doc.
[1] https://docs.wso2.com/display/IoTS310/Enterprise+IoT+solution
