### ISSUE TITLE
Enhance the Application installation process

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#1079]
As discussed, let's look at enhancing the install application form as follows or any other method that is intuitive to the user.

- Add back the Instant Install checkbox.
- Enable the Yes button only if the instant install checkbox is selected or the data and time is specified for scheduled install.
-Else the Yes button is disabled by default

**Comment by madhawap** [comment]
This issue is fixed with https://github.com/wso2/carbon-appmgt/pull/667. Hence closed.
