### ISSUE TITLE
App Publisher - Add an error message if a png is added to the icon

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#1080]
Currently, we have put a validation in the app publisher, saying that if a PNG image is added to the icon the app creation process will not be completed.

I accidentally added a JPG to the icon and was clicking the create button but nothing was happening. Afterward, I added a PNG icon and clicked create and then the app was created.

Therefore, we need an error message to pop up and say that the icon image has to be in the PNG format. Else the users will not know what happened and will think it's a bug in the product.

**Comment by chaturadilan** [comment]
There is no restriction in adding jpg in app manager and it will not fail, because it accepts jpg/png image formats. Hence I'm closing this issue.
