### ISSUE TITLE
Web Clip doesn't get installed on the device

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#1081]
Can we test and confirm the following please:
- Created a webclip: https://docs.wso2.com/display/IoTS310/Creating+a+Web+Clip
- Clicked installed and selected the COSU device

But it didn't get installed on the device.

**Comment by chaturadilan** [comment]
Actually we do not talk about installing we clips in COSU devices, since It need to launch the web browser. COSU always associate with enterprise apps. I tested the web clips with BYOD scenario and it worked, hence we can close this issue.

**Comment by shavidissa** [comment]
Thank you, Update the IoT Server docs with this info too.
