### ISSUE TITLE
Remove the advanced agent in the virtual Fire-alarm

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#1086]
Hi Team,

Currently, there are 2 agents for the virtual fire-alarm. The simple and advanced agent. The only difference is in the simple agent we can't add a policy and in the advanced, we can add a policy.

Can we remove the simple and advanced separation and just have one single agent for the virtual fire-alarm? This way it's intuitive for the users who try things out too. Sharing this as discussed with Ayyoob.

Later on like we do for mobile devices, we can add a policy for the virtual fire alarm too.

**Comment by shavidissa** [comment]
Also, can we have a drop down for the following:
When we go to ring the alarm, we have to enter on or off in the form. Instead of entering can we have a drop-down with on and off so it's easy for the user to select.
Or can we have on off as radio button options. 

This will make things easier for the user too.

**Comment by Nirothipan** [comment]
Fixes https://github.com/wso2/carbon-device-mgt-plugins/commit/77da76ecd48af128406331336bc8cd4cf869b8e1

**Comment by lasanthaDLPDS** [comment]
Added radio button options for ring alarm operation. 
https://github.com/wso2/carbon-device-mgt/pull/829
https://github.com/wso2/carbon-device-mgt-plugins/pull/745
Since the advance agent removed and radio button option added, this issue is closed.
