### ISSUE TITLE
Registering the device after inactive state is failing for android OS 4.4.2

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-iots#1087]
I connected a device after that I performed some operations,
then after switching the network connection(WiFi) off and connecting back to the same network , the device is not getting connected to the server. ( Still in in active state).

I tried this with Android tab of OS 4.4.2

**Comment by jsonds** [comment]
@Nirothipan Did you try syncing the device from the agent app?

**Comment by Nirothipan** [comment]
This has occurred due to the change in IP address of the server as the WiFi connection got interrupted in between.
