### ISSUE TITLE
Device details not shown properly

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-iots#1088]
In the device details page, the memory percentages are shown as below and when the device is connected for the first time, it is shown as NaN .
![screenshot from 2017-06-29 14-25-40](https://user-images.githubusercontent.com/24619763/27680997-507dcfb4-5cdb-11e7-8e47-0c7ac412df7a.png)

**Comment by dunithd** [comment]
Fixed with https://github.com/wso2/carbon-device-mgt-plugins/pull/746
