### ISSUE TITLE
Update the Arduino diagram in the UI with a Wi-Fi shield 

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#1093]
We need to update the diagram in the UI and docs with the Wi-Fi shield.  Need your help to do this, please.

**Comment by shavidissa** [comment]
I am closing this JIRA as Arduino is not shipped with WSO2 IoT Server 3.1.0

**Comment by rasika** [comment]
Please check this.
![graph](https://user-images.githubusercontent.com/1448489/27811144-5c2336f8-6080-11e7-9b34-b53324020071.jpg)

**Comment by shavidissa** [comment]
Thank you, Rasika! This is perfect. I updated the docs. Will we be able to update the Arduino part in the device management console too?

**Comment by rasika** [comment]
Sure thing Shavindri. I have updated the diagram on device management console.
