### ISSUE TITLE
Cannot connect to MQTT Broker Server if client_id not provided for raspberry agent

### ISSUE THREAD

**Issue by tonny1983** [wso2/product-iots#1103]
I got `MQTT_LISTENER: Connected with result code 2` message when using the raspberry agent. According to the document of paho.mqtt.python, rc equals 2 means `2: Connection refused - invalid client identifier`, but for MQTT v3.1.1, if a zero length client id is sent to the broker,  the broker should generate a random for the client, and there should be no such error.

If client_id is provided in mqttClient = mqtt.Client(client_id="xxx"), the raspberry agent works then.

**Comment by lasanthaDLPDS** [comment]
This issue is fixed with  https://github.com/wso2/carbon-device-mgt-plugins/pull/707. Hence closed.
