### ISSUE TITLE
[Operations] Label should be centre aligned

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1105]
Pack: 3.1.0-Beta
Please refer to the attached screenshot. Text should centre aligned. Currently, this is left aligned.
![alignment](https://user-images.githubusercontent.com/13449310/27790878-1cd5c2f6-6010-11e7-9b81-5265e5bf4550.jpg)

**Comment by pubudup** [comment]
@chamaraanu : Labels - 3.1.0-beta, Medium

**Comment by lasanthaDLPDS** [comment]
This issue is fixed with https://github.com/wso2/carbon-device-mgt/pull/831 and https://github.com/wso2/carbon-device-mgt-plugins/pull/747. Hence this issue is closed.

**Comment by pubudup** [comment]
Verified in 3.1.0-RC
