### ISSUE TITLE
[Virtual Fire Alarm] [Simple Agent] [Device Details ]Policies and Operation Log can be removed

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-iots#1106]
Enroll Virtual Fire Alarm Simple Agent.
Go to Device details of it . 
There we have Policies and Operation Log.
We can remove the policies and Operation Log form the UI since it is not supported for Simple Agent.
![screenshot from 2017-07-03 17-58-28](https://user-images.githubusercontent.com/24619763/27792873-58f15724-6019-11e7-975a-7051ba355c98.png)

**Comment by madhawap** [comment]
Fixed with https://github.com/wso2/carbon-device-mgt-plugins/pull/738. Hence closed.
