### ISSUE TITLE
Application Install / Uninstall silently

### ISSUE THREAD

**Issue by cs-anderson-cavalcante** [wso2/product-iots#1108]
Hi,

Im using release 3.1.0-Alpha and trying to achieve installation/un-installation of apk applications, but stumbled on some problems, our main goal here is to automate install of new version through Continuous Integration, so each new build on Jenkins we un-install the previous app and install from the Jenkins url the new one.

Install:

When we try to call the API: 

https://localhost:8243/api/device-mgt/android/v1.0/admin/devices/install-application

it returns:

```
* upload completely sent off: 224 out of 224 bytes
< HTTP/1.1 201 Created
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET, POST, DELETE, PUT
< Access-Control-Allow-Headers: Content-Type
< Content-Type: application/json
< Date: Mon, 03 Jul 2017 14:58:46 GMT
< Transfer-Encoding: chunked
< 
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
{"activityId":"ACTIVITY_2480","code":"INSTALL_APPLICATION","type":"PROFILE","createdTimeStamp":"Mon Jul 03 11:58:46 BRT 2017","activityStatus":[{"deviceIdentifier":{"id":"a226374b71c34c28","type":"android"},"status":"PENDING"}]}%  
```

But nothing happens on device, here's my curl:

```
curl -u user:pass -X POST --header 'Content-Type: application/json' --header 'Accept: application/json'  --header 'authorization: Bearer bf8e1122-60ca-39e8-8bf1-8567c16d7066' -d '{
  "deviceIDs": [
    "a226374b71c34c28"
  ],
  "operation": {
    "appIdentifier": "com.nemo.vidmate",
    "type": "ENTERPRISE",
    "url": "https://localhost:9443/publisher/api/mobileapp/getfile/vH3GDDvi66CcsB0.apk"
  }
}' 'https://localhost:8243/api/device-mgt/android/v1.0/admin/devices/install-application' -v
```

Tried the public type and works, but we need it silently because we have a big park of devices to install, so public opens the Play store but our app is corporate and doesn't go to the Playstore.

Un-install:

For the uninstall problem, we managed to call it, but it prompts on each device and doesn't uninstall silently.

We are calling:
https://localhost:8243/api/device-mgt/android/v1.0/admin/devices/install-application

Is there anyone that could help us out?

**Comment by rodrigosiviero** [comment]
I'm highly interested on the as well.

**Comment by nascimento** [comment]
+1

**Comment by nascimento** [comment]
+1

**Comment by jferreira23** [comment]
+1

**Comment by chaturadilan** [comment]
Hi Anderson,
If you your devices are COPE (corporate owned), silently install /uninstall apps are possible with the system app enabled[1] or making the system app as the device owner[2]. You can find more on the system app from the shared links.

[1] - https://docs.wso2.com/display/IoTS300/Integrating+the+Android+System+Service+Application
[2] - https://docs.wso2.com/display/IoTS300/Device+Ownership+Application

**Comment by milanperera** [comment]
There was a similar issue with respect to this functionality that is reported in #1090 and it is already fixed in the master branch. However, in order to use the silent app installation function, the [system-app](https://github.com/wso2/cdmf-agent-android/tree/master/system-service) has to be installed along with the agent. This system service is capable of downloading and installing apks in background without user's consent. Please refer [this doc](https://docs.wso2.com/display/IoTS310/Integrating+the+Android+System+Service+Application) for further details on installing system service.
