### ISSUE TITLE
Minor typo in the device-plugins-deployer.xml script

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#1109]
We say Ardino instead of Arduino. 
Example:
![screen shot 2017-07-04 at 10 23 31 am](https://user-images.githubusercontent.com/22474854/27815588-ec468c68-60a2-11e7-9ba3-6840360de5cd.png)

**Comment by madhawap** [comment]
This is fixed with https://github.com/wso2/product-iots/pull/1114. Hence closed.
