### ISSUE TITLE
Creating a new device type -UI

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#1110]
Noticed the following:

- The help tips are not configured to show info when we hover over the question mark.
- If you give a name with spaces in between and move to create the event stream, the name is shown as follows:
![screen shot 2017-07-03 at 12 58 50 pm](https://user-images.githubusercontent.com/22474854/27816282-30030ed6-60a8-11e7-90cb-f7d2677d164d.png)

If spacing is not allowed for the name can we put a note saying "There should be no white-spaces in the name"

**Comment by lasanthaDLPDS** [comment]
This issue is fixed in IoT-3.1.0 beta.
