### ISSUE TITLE
[Android Agent] Agent app getting stuck in android 4.4.2

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1111]
Pre-Conditions:-
- Should be tested on a device with Android 4.4.2 (Tested on a Samsung tab SM-T520)

1. Download the Agent app by using the QA scanner in 3.1.0-beta pack
2. Register the Android device 
3. Observe the app after registration is complete

Expected Results:-
- User should be able to complete the registration using the agent app

Actual Results:-
- Agent app gets stuck during the registration process. Unable to resume after this.

**Comment by pubudup** [comment]
@geethkokila , @chamaraanu : Labels - 3.1.0-beta, Highest

**Comment by hasuniea** [comment]
This issue can't be reproduced.
Here find the steps which I have tried:
1. Start the IoT server
2. Debug and build Android emulator 4.4.2
3. Register the Android device and could able to activate the app successfully

**Comment by pubudup** [comment]
Verified in 3.1.0-RC
