### ISSUE TITLE
[Android] Setting up work profile and Skip and go to enrollment options are not displayed for android 4.4.2

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1116]
The options displayed in document [1] mentioned in the title are not displayed for devices with Android 4.4.2 and directly prompted to enrollment. For later Android versions both options were displayed.

Tested with SM-T520

[1] https://docs.wso2.com/display/IoTS310/Setting+Up+the+Work+Profile

**Comment by pubudup** [comment]
@geethkokila , @madhawap : labels - 3.1.0-beta, Highest

**Comment by pasindujw** [comment]
Hi pubudu, the work profile option is supported from Android – 5.0 Lollipop upwards only. Therefore when the agent is launched, it checks for the device OS version and avoid displaying the work-profile option for the devices which are below Android 5.0 and instead directly launches the enrollment process.

**Comment by pubudup** [comment]
Just double checked with the documentation. It is already mentioned there. Hence closing the ticket.
