### ISSUE TITLE
[Android / Policies] When multiple items are added via a policy only one item got applied

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1117]
Pre-Conditions:-
- IoTS should be up and running
- A policy should be created to block the cam, block user from uninstalling the apps, block from changing the phone volume
- Policy should be applied to the relevant device

1. Access the device and check if the cam is blocked (applied)
2. Access the device and check if user can change the volume (not applied)
3. Access the device and check if user can uninstalll an app (not applied)

Expected Results:-
- All three policies should be applied to the device

Actual Results:-
- Only the cam is blocked other items in the policy are not applied

Note:-
- Tested with HTC phone
- OS: Android 5.0.2

**Comment by pubudup** [comment]
@geethkokila , @madhawap : Label - 3.1.0-beta, Highest

**Comment by milanperera** [comment]
This is not an issue. In order to work block user from uninstalling the apps and block from changing the phone volume restrictions, device has to be enrolled via Android for Work profile.

**Comment by pubudup** [comment]
Created the JIRA below to address this issue.
https://wso2.org/jira/browse/DOCUMENTATION-4566
