### ISSUE TITLE
[Android / Device State] Device list page shows as active but device details page shows inactive for the same device

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1120]
Please check the attached screenshots for the same device. Device list page shows as "Active". When you click on the device and go to the device details page it shows as "Inactive". Please make this constant across all pages.

![inactivestate](https://user-images.githubusercontent.com/13449310/27849606-fc38be92-616b-11e7-9a51-93571c9a8ec5.jpg)

![activestate](https://user-images.githubusercontent.com/13449310/27849611-07b5d44e-616c-11e7-8dde-bf152f77d699.jpg)

**Comment by pubudup** [comment]
@geethkokila @madhawap : Labels - Highest, 3.1.0-beta

**Comment by madhawap** [comment]
This issue is similar to https://github.com/wso2/product-iots/issues/1089

**Comment by pubudup** [comment]
Created #1200 for a slightly different issue.
