### ISSUE TITLE
iOS Agent appends the port 9443 to the registration url in the Start Registration process

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#1137]
When the iOS agent is run for the first time in an iOS Device, it asks for the server address to start registration. When the server address is typed in and hit the start registration button, a new browser tab will be opened with the url but with the 9443 port appended by default. 

Even if the port is specified in the server url, still 9443 will be appended.

**Comment by madhawap** [comment]
This issue is fixed with https://github.com/wso2/cdmf-agent-ios/pull/6. Hence closed.
