### ISSUE TITLE
Both admin and non-admin users cannot install apps on Android devices

### ISSUE THREAD

**Issue by dilee** [wso2/product-iots#1139]
Both admin and normal users cannot install applications on Android devices through the device management console. Tried with two different users with different user roles assigned and the issue remains.

**Comment by pubudup** [comment]
@madhawap @chamaraanu : Please increase the priority of this as blocker

**Comment by dunithd** [comment]
Verified this against with an admin user and a non-admin user on an Android device. But the functionality worked as expected. 
There could be situations where the device and the server are not on the same network so that device can't download the APK file since the server is unreachable.
