### ISSUE TITLE
Thumbnails in the API store are not properly aligned 

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-iots#1140]
**Description**
When you navigate to the API Store related to WSO2 IoTS, the thumbnails seem to be not properly aligned. It could be due to the lengthy API names. Please have a look. 

**Steps to recreate** 
1. Sign in to "Device Management Console".
2. Click on "Enroll New Device" button.
3. Click on "Try" button on Virtual Fire Alarm device and navigate to the VIRTUAL FIRE ALARM page.
4. Click on the "View API" button and navigate to the API Store.
5. Click on the "APIs" menu-item on the API Store, and navigate to the "APIs" page.

![image](https://user-images.githubusercontent.com/9816314/28062811-b7634586-664c-11e7-8efd-1ffa168f0793.png)

**Comment by amalhub** [comment]
Relates to : #1156

**Comment by ruwany** [comment]
Duplicate issue.

https://github.com/wso2/product-iots/issues/1156 has now been addressed.
