### ISSUE TITLE
[Andriod Agent] Unable to enroll a device with Android 4.4.2

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1144]
When attempting to enrol a device with Android 4.4.2., once the user enters credentials it prompts back to enter the server URL.  This happens continuously as a loop. But enrolment works fine for Android 5.0.2 devices

Tested in Samsung tab (4.4.2)

**Comment by pubudup** [comment]
@chamaraanu  , @geethkokila , @madhawap : Labels: 3.1.0-beta2, High

**Comment by pubudup** [comment]
This might be a regression issue introduced due to: #1121

**Comment by madhawap** [comment]
This fix with https://github.com/wso2/cdmf-agent-android/pull/64

**Comment by pubudup** [comment]
Verified.
