### ISSUE TITLE
[EMM 2.2.0] Enforce SD card Encryption feature request

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1145]
Hi there,

One of our clients is using EMM 2.2.0 for enforcing security on their employee phones by enforcing encryption of the device storage. Now they would like to extend this to the SD card in the phone but this functionality is currently not available.
We would like to request the following:
Enforcing SD card encryption from the policy assigned to the device.

**Comment by HexaGarantine** [comment]
Please remove or close this one.
