### ISSUE TITLE
Ring, Send Notification and Location does not work for iOS devices in the Clustered setup

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#1154]
Enrolled an iOS device (iPhone 5S) to the iots clustered setup. 
The Ring, Send Notification and Location operations are not working. 

Even if those operations are added to the operations log, those disappear after a while.

**Comment by madhawap** [comment]
This issue is fixed with https://github.com/wso2/cdmf-agent-ios/pull/6. Hence closed.
