### ISSUE TITLE
Can't login in to api-store as a self singed user.

### ISSUE THREAD

**Issue by charithag** [wso2/product-iots#1155]
Steps to reproduce:

1. Register new user to IoTS as a self signed user.
2. Try to log in to https://localhost:9443/api-store with newly registered user. 

Even after clicking login button in login UI, api-store still shows the sign in button instead of user name in right most corner.

**Comment by hasuniea** [comment]
admin can define the particular role in user update panel.
Then after clicking login button in login UI, api-store  shows the username in right most corner
