### ISSUE TITLE
[Cluster] For a new user other than admin, iOS device has been added but already in removed state without ever going into active state

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#1162]
Steps: 
1. Add a new User. (with admin role or either minimum permission for registering a device)
2. Register an iOS device. 

The device will be added however will be in removed state without ever going into active state. 
(But by this time, before this test begun, the same device had been registered by the admin user and removed already)

![iphone_61](https://user-images.githubusercontent.com/6646840/28117654-efdecf86-672b-11e7-9868-d44ce5d2b24c.png)

**Comment by hasuniea** [comment]
https://github.com/wso2/carbon-device-mgt/pull/855
