### ISSUE TITLE
[App Manager] Deleting the mobile application with role restrictions, doesn't remove role_restriction resource from registry

### ISSUE THREAD

**Issue by sinthuja** [wso2/product-iots#1163]
An application is published with role visibility.
In Carbon, the resource browser displays 2 lines in _system/governance/mobileapps/:
1 for the application
1 for the role restriction

This application is then deleted in the publisher. Only the line for the application is deleted in carbon. The role restriction is not deleted.  When I publish the application with same name next time, without any visibility restrictions, as the role_restrictions wasn't get removed, the visibility restrictions got the effect to the new application as well. 

This issue was encountered in EMM 2.2.0, please check whether the same exists in current IoT 3.1.0 as well.

**Comment by dilee** [comment]
This issue exists in the 3.1.0-beta2 as well. Only the line for the application is deleted but not the role restriction. As a workaround, we can delete old role restrictions from the registry when creating a new application with the same name.
