### ISSUE TITLE
Incorrect text on Device Statistics Dashboard footer

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-iots#1167]
The footer of the Device Statistics Dashboard states "WSO2 Dashboard Server v2.0.0". It should be "WSO2 IoT Server v3.1.0".

![image](https://user-images.githubusercontent.com/9816314/28121018-69fe772a-6737-11e7-8632-06b33162aec6.png)

**Comment by charithag** [comment]
This UI is depreciated and will not use from next release. hence invalid
