### ISSUE TITLE
Add  required steps to follow in order to use a PostgreSQL database with IoTS.

### ISSUE THREAD

**Issue by lasanthaDLPDS** [wso2/product-iots#1180]
There is a subsection in IoTS 3.1.0 documentation named as **setting up PostgreSQL** but it doesn't have a section for steps that should be followed when IoTS configure with PostgreSQL. Therefore add required steps to follow in order to use a PostgreSQL database with IoTS 3.1.0 and there are some specific configurations should be included when we configure IoTS with PostgreSQL. Hence update the documentation with relative changes.

**Comment by shavidissa** [comment]
Thank you, Lasantha for the content and guidance given offline. Updated the docs [1].

[1] https://docs.wso2.com/display/IoTS310/Changing+to+PostgreSQL
