### ISSUE TITLE
[IoT / README] Update how to run section with product version and update wso2iot-3.0.0/core/bin as wso2iot-3.0.0/bin

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1182]
We need to update the readme file [1] as mentioned in title of the ticket.

[1] https://github.com/wso2/product-iots/tree/v3.1.0-RC

**Comment by pubudup** [comment]
@chamaraanu , @madhawap , @geethkokila : Labels: medium, 3.1.0-rc1

**Comment by harshanL** [comment]
This is fixed in the latest version.
