### ISSUE TITLE
The Android agent apk in the RC1 pack shows the Agent Version as debug v3.1****** 

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#1186]
![agent_version](https://user-images.githubusercontent.com/6646840/28264369-4530f5a6-6b08-11e7-9d2e-c3741e5406a8.png)

**Comment by harshanL** [comment]
This issue is no longer in latest pack.

**Comment by charithag** [comment]
Please note that Agent versions are no longer bonded with IoT Server versions. Please refer https://github.com/wso2/cdmf-agent-android/releases
