### ISSUE TITLE
[Geofencing] After exporting one geofence, cannot export another one - throws an error

### ISSUE THREAD

**Issue by sherenem** [wso2/product-iots#1192]
steps to reproduce.

1. Set up geo fencing
2. Enrol android device
3. Draw area and export it. The json gets downloaded to the machine.
4. Draw another area and try to export it - nothing happens and I get this error:

[2017-07-18 11:31:20,279] [IoT-Core] ERROR - {org.wso2.carbon.device.mgt.core.geo.service.GeoServcieManagerImpl} Error while reading the registry path: /_system/governance/geo/alerts/Within/60e0b4aeab34bbb6/

**Comment by sherenewso2** [comment]
Closing this because this worked in another browser. I first tried it in chrome and it didnt work but on safari it worked. Turns out it was because there was a setting in my chrome browser that stopped it from downloading multiple files from one site.

**Comment by sherenem** [comment]
Closing this because this worked in another browser. I first tried it in chrome and it didnt work but on safari it worked. Turns out it was because there was a setting in my chrome browser that stopped it from downloading multiple files from one site.
