### ISSUE TITLE
Need a Done button in the iOS Agent App for iPhone 5S

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#1199]
![img_0057](https://user-images.githubusercontent.com/6646840/28404128-a67a2e56-6d45-11e7-9cdd-31d1bcb94d5c.jpg)

There's no Done button, so cannot get the Enroll button after typing in the URL.

**Comment by milanperera** [comment]
This is fixed in https://github.com/wso2/cdmf-agent-ios/pull/7
