### ISSUE TITLE
[Management Console] A blank screen is displayed when accessed the management console

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1213]
Please refer to the attached screenshot. This occurred after starting all three components (broker, analytics, core) of the server and running for about 2 hours.

![blankscreen](https://user-images.githubusercontent.com/13449310/28456722-e04c7c02-6e20-11e7-98cb-a54922cff98a.jpg)

**Comment by pubudup** [comment]
@chamaraanu : High, 3.1.0-RC

**Comment by pubudup** [comment]
This issue is appearing when the analytics node is up. If you stop the analytics node, this issue is not reproducible.

**Comment by madhawap** [comment]
This could be avoided by starting the server with following order;
Broker, Analytics and Core

**Comment by charithag** [comment]
Closing as this is not reproducible .
