### ISSUE TITLE
For iOS devices, Location is not fetched 

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#1215]
1. Put the device operation "Location" on a newly registered device. 
2. You can see the operation in the operations log. 
3. Later-on the operation will have been completed but the location is not fetched.
4. However on the device side location permissions, the location service have been accessed by the agent app. 

![operations_log](https://user-images.githubusercontent.com/6646840/28460825-754a563e-6e31-11e7-93ea-3ad5f5f5342d.png)

![location_not_fetched](https://user-images.githubusercontent.com/6646840/28460831-7b6110b2-6e31-11e7-8cf8-92c8a5b90b5d.png)

![img_0009](https://user-images.githubusercontent.com/6646840/28460840-81fb504a-6e31-11e7-9f10-136f7182bcca.jpg)

**Comment by milanperera** [comment]
This is fixed in https://github.com/wso2/carbon-devicemgt-proprietary-plugins/pull/129
