### ISSUE TITLE
IoT Server version in welcome note should be updated in documentation home page. 

### ISSUE THREAD

**Issue by menakaj** [wso2/product-iots#1220]
Currently, it says v 3.0.0.
Welcome to the WSO2 IoT Server 3.0.0 documentation!

[https://docs.wso2.com/display/IoTS310/WSO2+IoT+Server+Documentation](https://docs.wso2.com/display/IoTS310/WSO2+IoT+Server+Documentation)

**Comment by shavidissa** [comment]
Thank you, Updated!
