### ISSUE TITLE
Android App installation cannot be completed

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-iots#1222]
**Description**
When attempting to do an instant app installation via App Store, the screen gets stuck.

**Steps to re-create**
1. Navigate to the App Store using https://<IOTS_HOST>:9443/store.
2. Sign in using alex and alexuser as the username and password.
3. Click the Con-App-Android mobile application, and click Install. 
4. Select Instant install, and click Yes. The screen will display two inactive buttons 'Prev' and 'Next'.

![image](https://user-images.githubusercontent.com/9816314/28528038-2dbe88fa-70aa-11e7-855a-ff8e4f774c19.png)

**Comment by pubudup** [comment]
@YvonneW : When you click on instant install it shows registered devices on the server to select from. I assume (by looking at the localhost url) this is displayed since there are no registered devices in the server. This should go away as soon as you register a device.

**Comment by hasuniea** [comment]
This issue can't be reproduced. Here find the steps to re create the issue
1. create an admin user rob and enrolled a device to him.
2. sign in using rob to the publisher and created an Application by uploading apk file 
3. publish the apk
4. sign in using rob to the store and click on install, then instant install
5. select the registerd device

**Comment by YvonneW** [comment]
I tested this on a mac and managed to recreate the issue with the steps given by me previously. I tried syncing the agent, and even restarting the IoT Server. But the issue persists.

Further, when I close the pop-up, the Store remains frozen in a dull shade, as if the Store is in inactive.

**Comment by shavidissa** [comment]
Hi Yvonne,

I tested this on my pack via the admin user and it worked for me. Maybe something went wrong when unzipping the pack. We can try again with new unzipped pack and see if you still get it.

**Comment by pubudup** [comment]
Looks like this happens when the devices are not synched with the server. I experienced this after unregistering a device.  If operations come through to the device (meaning properly synched with server), then the registered devices should be displayed on this page.

**Comment by YvonneW** [comment]
Tested the device installation by granting admin permissions to the 'alex' user, and the issue was not there. So, looks like it's privilege issue with the 'alex' user that gets auto created when you run the mobile-qsg sample.

**Comment by pubudup** [comment]
I compared the permission tree of user Alex in role 'iotMobileUser' in RC1 and RC2. Permissions seem to be exactly the same in both RC1 and RC2 for user Alex. Only difference was, in RC2 view-analytics permission is allowed where as in RC1 this permission does not exist.

**Comment by ghost** [comment]
There is also this problem in the RC3 version

**Comment by harshanL** [comment]
This issue is no longer reproducible in the latest pack.
