### ISSUE TITLE
[Mobile App] Uninstalled mobile app still displayed in App list on UI for Android

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1224]
Pre-Condition:-
- IoTS should be up and running
- A device should be enrolled
- The enrolled device should be Android 4.4.2

1. Install WSO2 con app on device
2. Manually uninstall the app from device
3. Make sure the device is synched with the IoTS after uninstalling the app
4. Go to device management UI and check installed apps

Expected Results:-
- Uninstalled apps should not be displayed on Applications list

Actual Results:-
- Uninstalled app (WSO2 con) is being displayed on applications list (screenshot attached)

![app](https://user-images.githubusercontent.com/13449310/28566737-acb1601c-714d-11e7-9bf9-5a64bf9750ea.jpg)

**Comment by pubudup** [comment]
@rasika @chamaraanu : Labels: 3.1.0-RC2 , Medium

**Comment by harshanL** [comment]
This issue is no longer reproducible.
