### ISSUE TITLE
WARN log getting printed when registering new device type 

### ISSUE THREAD

**Issue by sinthuja** [wso2/product-iots#1229]
Register a new device type in the UI, and there is a warning message as below.

[2017-07-25 20:38:48,138] [IoT-Core]  WARN - {org.wso2.carbon.device.mgt.extensions.device.type.template.DeviceTypeManager} smart-bulb-default-platform-configuration.xml is not available, hence default smart-bulbplatform configuration cannot be loaded.

When I checked further this log needs to be removed. The variable PATH_MOBILE_PLUGIN_CONF_DIR is pointing to etc IoT_CORE/conf/etc/device-mgt-plugin-configs directory, but that directory is not there in the default pack. Also, the default device types are available in the deployment directory, and hence the above mentioned config location is not used and also not needed.

Let's fix this.

[1] https://github.com/wso2/carbon-device-mgt/blob/master/components/device-mgt/org.wso2.carbon.device.mgt.extensions/src/main/java/org/wso2/carbon/device/mgt/extensions/device/type/template/DeviceTypeManager.java#L405

**Comment by milanperera** [comment]
This was added to get the default configuration for an each and every device type if the relevant config file is available. For an example, in the device cloud, we need to be able to provide default platform configurations for the iOS until user set it by themselves. Otherwise they wont be able to test the iOS. Once they created their owned certificates, then they can add them into the configurations and use.

**Comment by ayyoob** [comment]
@milanperera Can we move this configs as part of existing device type config file rather having a separate config file? :)

**Comment by sumedharubasinghe** [comment]
There are few more thing to be refactored here.
eg:
String platformConfigurationPath =
PATH_MOBILE_PLUGIN_CONF_DIR + File.separator + deviceType + "-default-platform-configuration.xml";

- Concept of platform is not there anymore.
- Variable name PATH_MOBILE_PLUGIN_CONF_DIR is misleading. There is nothing as such now.
- Like Ayyoob said, default configurations for a device type should be introduced with device type. Why do it separately?

I understand this cannot be fixed immediately. But this need to be fixed after 3.1.0.

**Comment by rasika** [comment]
This is not reproducible in the latest pack.
