### ISSUE TITLE
[Devices] Inactive device is displayed as active for a long time since the device has been inactive

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1235]
Pre-Conditions:-
- IoTS should be up and running
- A device should have been registered and it should be disconnected from server for some time (3-4 hour - Tested on a device with Android 4.4.2)

Steps:-
1 . Login to the device management UI
2. Check the status of the device mentioned in pre-condition (screenshot attached)

Expected Results:-
- Device should be displayed as inactive when it's not connected to the network

Actual Results:-
- The device is displayed as active even though it's not connected to the network.

![device_state](https://user-images.githubusercontent.com/13449310/28606235-8d3fbc6e-71f3-11e7-9050-26cba9465caf.jpg)

**Comment by pubudup** [comment]
@Kamidu : Labels: 3.1.0-RC2, High

**Comment by milanperera** [comment]
According to the screenshot, I can see that only one monitoring operation is pending at the time of checking this. AFAIK, In order to device to be set as inactive, at least 3 monitoring operations have to be failed/pending.
@pubudup Would you be able to check this with the trunk?

**Comment by harshanL** [comment]
This is an issue in the device details page UI. The status of the device is getting updated properly. But it is not reflected in this UI.

**Comment by harshanL** [comment]
The device status change functionality is working as expected. The device object to render this page will be fetched from the cache and the status change won't be reflected in the device-cache until the cache element is evicted and loaded back from the db.
