### ISSUE TITLE
[Self Signed Cert] Add a check on maven build to verify the self signed cert is not expired when building the product. 

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1237]
This will be a useful check to have so that we know when the cert gets expired. Please see attached screenshot.

![screen shot 2017-07-25 at 10 36 34 pm](https://user-images.githubusercontent.com/13449310/28609793-b2844f20-7203-11e7-960a-203ac5e4161d.png)

**Comment by pubudup** [comment]
@chamaraanu , @geethkokila , @madawas : Labels 3.1.0-RC2, medium

**Comment by sumedharubasinghe** [comment]
Pubudu,
We can either use exec-maven-plugin or write a mojo to do this @ build time.

**Comment by geethkokila** [comment]
I think this issue will not come until 2027, because current certificate will not expire until 2027.

**Comment by ruwany** [comment]
Marking this issue as closed as per above comment by @geethkokila
