### ISSUE TITLE
[Policies] Policy deactivate option is not available

### ISSUE THREAD

**Issue by pubudup** [wso2/product-iots#1243]
Admin user should be able to deactivate currently activated policies.

Pre-Conditions:-
- There should be an active policy
- The policy should be applied to devices

Steps:-
1. Login to device management UI as admin user
2. Go to policies
3. Select the applied policy

Expected Results:-
- There should be an option to deactivate the policy

Actual Results:-
- Unable to deactivate the policy (screenshot attached)

![policystatuschange](https://user-images.githubusercontent.com/13449310/28658640-ef5c2f32-72c9-11e7-8f20-58c4d99d82b2.jpg)

**Comment by pubudup** [comment]
@geethkokila , @madhawap , @inoshperera : Labels : Blocker, 3.1.0-RC3

**Comment by DimalChandrasiri** [comment]
fixes with #869
