### ISSUE TITLE
Device location is not displayed for Android Sense

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-iots#1251]
**Description**
The 'Device Location' tab under the 'Device Details' page does not show anything.

**Steps to Recreate**

1. Sign in to the Device Management console with admin/admin login credentials.
2. Click Device Management >> Enroll Device >> Android Sense
3. Enroll the device and install Android Sense agent on a device (HTC One M9PLUS).
4. Register the device.
5. Open Android sense application.
6. Select all sensors and publish stats.
7. Navigate to Device Management Console >> Device Management >> Devices and select the respective android sense device.
8. The graphs under the 'Device Statistics' tab gets populated, but the ‘Device Location’ remains blank.

![image](https://user-images.githubusercontent.com/9816314/28717213-747af550-73be-11e7-976d-c0a2ea31eb52.png)
![image](https://user-images.githubusercontent.com/9816314/28717226-8d07abfe-73be-11e7-9a64-4c283dbc5417.png)

@madhawap Please check. Found in 3.1.0-RC2. Severity: Medium.

**Comment by menakaj** [comment]
I did a test run and confirmed that this is working now. 
And also the history view is also working.

**Comment by menakaj** [comment]
I did a test run and confirmed that this issue is fixed.
