### ISSUE TITLE
Android SDK location

### ISSUE THREAD

**Issue by alegomes** [wso2/product-iots#1253]
What are the heuristics used to realize whether an Android SDK location is correct or not? I'm not having a good experience trying to add a virtual device on WSO2 IoT Server. Is it an UX issue?

**Steps**

1. Download WSO2 IoT Server 3.1.0
2. Unpack it
3. Start it (broker.sh + iot-server.sh + analytics.sh)
4. Open https://localhost:9443/devicemgt
5. Devices > Add > Virtual Devices Type >  Try our virtual Android device
6. Download and unpack android-tryit.zip
7. Run startEmulator.sh
8. "Do you have an Android SDK installed on your computer (y/N) ?" : y
9. "Please provide android SDK location :"

```
Please provide android SDK location :
/Applications/Android\ Studio.app
Invalid SDK location

Please provide android SDK location :
/Applications/Android\ Studio.app/Contents/MacOS/
Invalid SDK location

Please provide android SDK location :
"/Applications/Android Studio.app/Contents/MacOS/"
Invalid SDK location

Please provide android SDK location :
/Applications/Android\ Studio.app/Contents
Invalid SDK location

Please provide android SDK location :
/Applications/Android\ Studio.app/Contents/bin
Invalid SDK location

Please provide android SDK location :
/Applications/Android\ Studio.app/Contents/MacOS
Invalid SDK location

Please provide android SDK location :
/Applications/Android\ Studio.app/Contents/plugins/android
Invalid SDK location

Please provide android SDK location :
/Applications/Android\ Studio.app/Contents/Resources
Invalid SDK location
```

:-/

**Comment by madhawap** [comment]
Hi alegomes,

It seems like you are providing an incorrect SDK location here, which is the default path where we installed the Android Studio is "/Applications/Android\ Studio.app/Contents/".

What we expect here is the Android SDK path. 
If you are using Android studio, you can go to  Tools -> Android -> SDK Manager
Most probably you will find the Android SDK location there.

In most cases android SDK location is similar to below: 
"/Users/madhawa/Library/Android/sdk"

Thank you
Best Regards,
Madhawa
