### ISSUE TITLE
Default parameters not working on Virtual Android Device installation

### ISSUE THREAD

**Issue by alegomes** [wso2/product-iots#1254]
AFAIK, capital letters should be used for default parameters, which is not the case when installing Virtual Android Device. I spend a whole day to realize the problem was not with my network. If the capital "N" is not intended to be the default parameter, then, I think it should be changed to "n".

Supposing N is the default parameter and hitting Enter...

```
→ ./startEmulator.sh
Welcome
Detected OS macosx
Do you have an Android SDK installed on your computer (y/N) ? :
(NOTHING HAPPENS)
^C
```
Now, specifying N argument explicitly:
```
→ ./startEmulator.sh
Welcome
Detected OS macosx
Do you have an Android SDK installed on your computer (y/N) ? : n
Downloading _Android-sdk-tools.zip
Downloading: 100.00 %
(...)
```
And the same happens for next questions:
```
→ ./startEmulator.sh
Welcome
Detected OS macosx
Do you have an Android SDK installed on your computer (y/N) ? : n
Downloading _Android-sdk-tools.zip
Downloading: 100.00 %
(...)
Do you want to create WSO2_AVD with default configs (Y/n)?:
(NOTHING HAPPENS)
^C

→ ./startEmulator.sh
Welcome
Detected OS macosx
Do you want to create WSO2_AVD with default configs (Y/n)?: y
Creating a new AVD device
Auto-selecting single ABI x86
Android 6.0 is a basic Android platform.
(...)
```

Steps:

- Download WSO2 IoT Server 3.1.0
- Unpack it
- Start it (broker.sh + iot-server.sh + analytics.sh)
- Open https://localhost:9443/devicemgt
- Devices > Add > Virtual Devices Type > Try our virtual Android device
- Download and unpack android-tryit.zip
- Run startEmulator.sh
- "Do you have an Android SDK installed on your computer (y/N) ?" :

**Comment by madhawap** [comment]
This issue is fixed with above PR. Hence closed.
