### ISSUE TITLE
Android emulator not starting during Virtual Android Device installation

### ISSUE THREAD

**Issue by alegomes** [wso2/product-iots#1256]
```
→ ./startEmulator.sh --help
Welcome
Detected OS macosx
+----------------------------------------------------------------+
|                        WSO2 Android TryIt                      |
+----------------------------------------------------------------+
Starting : WSO2_AVD
```
Nothing happens.

Environment:

- MacOS 10.12.5
- Java 1.8.0_13

**Comment by Nirothipan** [comment]
This is because intel HAXM is not properly installed . 
Sequence of https://github.com/wso2/product-iots/issues/1255 issue .
Fixed in https://github.com/wso2/carbon-device-mgt-plugins/pull/779 .
