### ISSUE TITLE
WSO2 IOT RC3 & RC4 : apk deployment with STORE does not work on ANDROID 7.0

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1272]
Hi

I am looking for several days because the deployment of application does not work on all smartphones.

I have validated the installation of application apk and web application on the virtual smartphone  without any problems.

On smartphones, (MOTOROLA G5 and XIAOMI MI5), I can install web applications without any problem. However, no apk applications can be deployed. Looking at the Download folder of my smartphone, I find myself with an apk named "update.apk".  I do not have the apk application installed.

Someone would have an idea?

For information, this bug is on Android 7.0

**Comment by ghost** [comment]
Hello everyone,
So no one has an answer to give me? I think not be the only ...

Thank you for your help and support

Christophe

**Comment by sameerawickramasekara** [comment]
Hi Christophe,

This issue no longer occurs in IoTS version 3.1.0 (latest release). hence closing this issue
@Kamidu please note.

**Comment by Kamidu** [comment]
Hi Christophe and Sameera,

Close this after re validation Sameera's statement with IoT Server 3.1.0

Thanks.

**Comment by ghost** [comment]
HI,
The error is always present
