### ISSUE TITLE
wso2 iot das dashboard not found

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1298]
HI all,
The dashboard does not appear in WSo2 DAS of WSO2IOT

![capture_das](https://user-images.githubusercontent.com/22862175/29244702-fc6d9f24-7fbe-11e7-9959-e755c695f067.png)

**Comment by ghost** [comment]
Can someone explain?

**Comment by charithag** [comment]
Hi,

This portal application was designed to display device details and stats. However this was depreciated and not configured to function out of the box in IoTS-3.1.0.

This application will remove with next release.
