### ISSUE TITLE
Spelling error on the "Visibility" field

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1299]
On WSO2IOT-3.1.0-RC2&3&4, there is a big mistake while adding an application to the store:

To manage the rights in the creation of an application, the "Visibility" field does not concern who have the right to see the application! This is an error and this field refers to "Restrict Visibility"

![field visibility -01](https://user-images.githubusercontent.com/22862175/29249276-c3b86f42-802c-11e7-80b7-8c9b856166e3.png)

Once your application creates, edit it and here is what is found in the field "Visibility"

![field visibility _02](https://user-images.githubusercontent.com/22862175/29249282-cb567cc6-802c-11e7-9e0d-9cda3e2dfc70.png)

**Comment by rasika** [comment]
Yes we need to fix this. Thanks for reporting this issue.

**Comment by ghost** [comment]
Thanks I'm waiting for your update. I'm doing tests. If I see other things, I'll let you know

Best regards

**Comment by ghost** [comment]
To think about changing the documentation

https://docs.wso2.com/display/IoTS310/Creating+an+Android+Application

**Comment by charithag** [comment]
@Tofdu31, We have created DOC jira to ensure update the field name with next release.
https://wso2.org/jira/browse/DOCUMENTATION-4700
