### ISSUE TITLE
No synchronization between the WSO2IOT RC4 server and smartphones

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1305]
Hi all,

After putting the IP address to WSO2IOT-RC4, there is a bug with the synchronization between the IOT server and my Android 7 test smartphone

Synchronization on the smartphone is problematic, but on the server side, it remains in "Pending"

![capture_bug_rc4](https://user-images.githubusercontent.com/22862175/29279796-4ae37506-8119-11e7-93a2-14d9208bb72b.png)

I did tests with WSO2 IOT that I recovered on JENKINS and for information, versions 549,550 and 551 make this same bug.
https://wso2.org/jenkins/job/products/job/product-iots/org.wso2.iot$wso2iot/

See you soon

**Comment by Megala21** [comment]
Hi,
We did the testing on Android 7 before doing the release and it worked fine. Can you please try-out the same thing with our newly released pack http://wso2.com/iot and let us know the outcome. At the mean time can you please try to invoke some other operations(i.e. ring or message) and let us know the out come?
Thanks.

Regards,
Megala

**Comment by ghost** [comment]
Hi Megala,

Thank you for your help.
I did the test with the version from here : http://wso2.com/iot

I connected my test smartphone (Xiaomi MI5) and I left more than 30 minutes synchronization.
I lose the connection between my smartphone and the WSO2 IOT server:
![bug_rc4_01](https://user-images.githubusercontent.com/22862175/29311894-8c8a1696-81b3-11e7-99be-ac0227971cf5.png)

![bug_rc4_02](https://user-images.githubusercontent.com/22862175/29311898-91026192-81b3-11e7-8d17-e90e378bf261.png)

I do not have this problem on the versions of WSO2IOT:
- WSO2IOT 3.1.0 Beta
- WSO2IOT 3.1.0 Rc1
- WSO2IOT 3.1.0 Rc2
- WSO2IOT 3.1.0 Rc3
 See you soon

Christophe from France


EDIT : To give a little more information, the rights of wso2 agent are ok. I checked on the phone.
For battery management, I have applied to the WSO2 AGENT application no restrictions and everything allowed.

**Comment by ghost** [comment]
I can give you by mail the address of the server to test with your smartphone

**Comment by geethkokila** [comment]
I tried on the latest pack, but could not find any issue with operation response. 

To further investigate, can you please enable wire logs. To enable wire logs please go the log4j.properties file in the <IoT_Home>/conf/ and change following.

Please comment following. 
log4j.category.org.apache.synapse=WARN

Please uncomment following 
#log4j.logger.org.apache.synapse.transport.http.wire=DEBUG

Then please let the server and device run for some time and then attach the <IoT_Home>/repository/logs/wso2carbon.log file to the issue. 

And please check that log file records something similar to following.

[2017-08-16 11:27:03,985] [IoT-Core] DEBUG - {org.apache.synapse.transport.http.wire} HTTP-Listener I/O dispatcher-1 >> "PUT /api/device-mgt/android/v1.0/devices/6bbac7af195eafefsasaf452/pending-operations HTTP/1.1[\r][\n]"

Please attach the log file to the issue for us to investigate.

**Comment by ghost** [comment]
Hello,
Here are the logs. The server has been running for more than 30 minutes.

It is important to find the bug for me because, next week, I have to make a presentation for a large French industrial group for the management of at least 5500 devices. I am a mobility consultant and I have specialized on your product to promote it in France.

I remain at your disposal for any additional information.
[LOGS_WSO2_IOT_3.1.0.zip](https://github.com/wso2/product-iots/files/1231073/LOGS_WSO2_IOT_3.1.0.zip)

Christophe

**Comment by geethkokila** [comment]
Hi Christophe

Please provide the URL of the server for to do a test. And please share the credentials with geeth*at*wso2.com(replace *at* with @). 

Thanks
Geeth

**Comment by Megala21** [comment]
Hi Christophe,

Seems like this has happened due to application with the package name "com.swiftkey.languageprovider" does not have a version. Can you do the following,

1. Remove the package with the package name "com.swiftkey.languageprovider". This should be some application related with swift keyboard. 
The details related with this application is follow as per the logs, {\"name\":\"SwiftKey%20Preloaded%20Languages\",\"package\":\"com.swiftkey.languageprovider\",\"isSystemApp\":false,\"isActive\":false}
2. After that try to synchronize the agent with the server. 

This should solve the issue in synchronization.

Thanks.

Regards,
Megala

**Comment by ghost** [comment]
I just uninstall the application which is by default in xiaomi mi5.

I uninstalled the wso2 agent and then reinstalled it.

This is always to pending.


This this the new log 
[logs.zip](https://github.com/wso2/product-iots/files/1231295/logs.zip)

**Comment by Megala21** [comment]
Hi Christophe,

I could still see the application there as per the logs.
{\"name\":\"SwiftKey%20Preloaded%20Languages\",\"package\":\"com.swiftkey.languageprovider\",\"isSystemApp\":false|

Unless we remove, the issue will not be resolved.

Thanks.

**Comment by ghost** [comment]
I completely erased on the smartphone Xiaomi MI5 swiftkey and all the services associated with swiftkey.

It's all right, the server works.

Sometimes in companies, they create their own application, forgetting to put a version is a mistake that can be made

Thanks for your help

Best regards

**Comment by charithag** [comment]
Fixed with PR https://github.com/wso2/carbon-device-mgt/pull/917
