### ISSUE TITLE
[UI] Device details page gets messed up for some screen resolutions

### ISSUE THREAD

**Issue by dilee** [wso2/product-iots#1309]
**Prerequisites:**
1. A device should be enrolled

The device details page gets messed up for some screen resolutions
![screenshot from 2017-08-17 17-27-30](https://user-images.githubusercontent.com/7193470/29411240-9c71e272-8371-11e7-9272-d7e2f5feee79.png)

**Comment by charithag** [comment]
Duplicate of https://github.com/wso2/product-iots/issues/1218
