### ISSUE TITLE
wso2iot 3.1.0 : apk deployment with STORE don't work on XIAOMI MI5 and MOTOROLA G5

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1317]
Hi

I am looking for several days because the deployment of application does not work on all smartphones : XIAOMI MI5 and MOTOROLA G5

I have validated the installation of application apk and web application on the virtual smartphone without any problems. (Android 6.0)

On smartphones, (MOTOROLA G5 and XIAOMI MI5), I can install web applications without any problem.

However, no apk applications can be deployed. Looking at the folder of my smartphone, I find myself with an apk named "update.apk".
https://user-images.githubusercontent.com/22862175/29450083-952c8e40-83fd-11e7-907a-2125c09afebd.png

the originally file is named: Bubble_3.1.5_apk-dl.com.apk

This "update.zip" matches the application I want to install. But the file has been renamed, placed in my smartphone and has not been installed.

This is the same for all apk files

Someone would have an idea?

For information, this bug is on Android 7.0

Many thanks

**Comment by sameeragunarathne** [comment]
Hi,

Did you able to install update.apk manually by clicking on it? 

Thanks

**Comment by ghost** [comment]
HI,

Yes, I was able to manually install the update.apk and the application launches without any problems.

**Comment by ghost** [comment]
Hi,

I just tested again with the application WSO2 App Catalog. It's always the same. The application arrived in my smartphone with the name "update.zip"

 I have to make a presentation for a large French industrial group for the management of at least 5500 devices. I am a mobility consultant and I have specialized on your product to promote it in France.

I would be grateful if you could help me because not being able to deply of application under Android 7 is a blocking point for my customers.

For information, I have a screen that appears quickly white when I want to deploy an apk. This transition of white screen is done in 0.5 seconds

thank you for your reply

**Comment by sameerawickramasekara** [comment]
Hi,

This issue is fixed in the android agent repository. Until we do the next release ,
you can follow the steps below to build the agent.

1.  Clone the repository https://github.com/wso2/cdmf-agent-android

2. Build the Android agent with Android Studio. (You can refer **Prerequisites** in this doc [https://docs.wso2.com/display/IoTS300/White+Labeling+the+WSO2+Android+Agent.] )

3. Uninstall pre-existing agent and install the new agent using Android Studio.

Thanks and Regards,
Sameera

**Comment by ghost** [comment]
thank you very much for your help

I'm not an expert at all for Android Studio. I spent the day searching and reading tutorials.
Unfortunately, I can not compile apk

You can help me ?

**Comment by sameerawickramasekara** [comment]
Hi,
We have made a Release for the android agent with few updates.
Please follow this link https://github.com/wso2/cdmf-agent-android/releases/tag/v3.1.19
and find the apk for the agent in the **Downloads** section.

Thanks and Regards,
Sameera

**Comment by ghost** [comment]
Thank you for your help !
it works. By cons, I am amazed because the application is still called in my smartphone "update.apk"
But it works all the same.
