### ISSUE TITLE
Use maven to build IOTS in windows7, get error: the command line is too long

### ISSUE THREAD

**Issue by jiangcluster** [wso2/product-iots#1318]
[INFO] --- carbon-p2-plugin:1.5.4:p2-profile-gen (3-p2-profile-generation) @ wso2iot-core-p2-profile ---
[INFO] Running Equinox P2 Director Application
[INFO] Command line:
        cmd.exe /X /C "D:\Java\jdk1.8.0_101_64bit\jre\bin\java.exe -jar D:\repo\org\eclipse\tycho\tycho-p2-runtime\0.13.0\eclipse\plugins\org.eclipse.equinox.launcher_1.2.0.v20110725-1610.jar -nosplash -application org.e
clipse.equinox.p2.director -metadataRepository file:D:/product-iots-3.1.0/modules/p2-profile/iot-core-profile/target/p2-repo -artifactRepository file:D:/product-iots-3.1.0/modules/p2-profile/iot-core-profile/target/p2-re
po -profileProperties org.eclipse.update.install.features=true -installIU org.wso2.carbon.identity.inbound.metadata.saml2.server.feature.group/0.1.1,org.wso2.carbon.identity.sp.metadata.saml2.server.feature.group/1.0.0,o
rg.wso2.iot.core.styles.feature.group/3.1.0,org.wso2.carbon.appmgt.mdm.osgiconnector.feature.group/4.0.55,org.wso2.carbon.appmgt.mdm.restconnector.feature.group/4.0.55,org.wso2.carbon.appmgt.core.feature.group/1.2.35,org
.wso2.carbon.appmgt.mdm.wso2emm.feature.group/1.2.35,org.wso2.carbon.appmgt.mobile.feature.group/1.2.35,org.wso2.carbon.appmgt.publisher.feature.group/1.2.35,org.wso2.carbon.appmgt.services.api.feature.group/1.2.35,org.w
so2.carbon.store.feature.group/1.5.1,org.wso2.carbon.appmgt.store.feature.group/1.2.35,org.wso2.carbon.social.feature.group/1.5.1,org.wso2.carbon.appmgt.rest.api.store.feature.group/1.2.35,org.wso2.carbon.appmgt.rest.api
.publisher.feature.group/1.2.35,org.wso2.carbon.appmgt.oauth.feature.group/1.2.35,org.wso2.carbon.device.mgt.feature.group/3.0.67,org.wso2.carbon.device.mgt.extensions.feature.group/3.0.67,org.wso2.carbon.policy.mgt.serv
er.feature.group/3.0.67,org.wso2.carbon.apimgt.application.extension.feature.group/3.0.67,org.wso2.carbon.apimgt.integration.client.feature.group/3.0.67,org.wso2.carbon.email.sender.feature.group/3.0.67,org.wso2.carbon.c
ertificate.mgt.server.feature.group/3.0.67,org.wso2.carbon.certificate.mgt.api.feature.group/3.0.67,org.wso2.carbon.certificate.mgt.cert.admin.api.feature.group/3.0.67,org.wso2.carbon.webapp.authenticator.framework.serve
r.feature.group/3.0.67,org.wso2.carbon.apimgt.webapp.publisher.feature.group/3.0.67,org.wso2.carbon.apimgt.handler.server.feature.group/3.0.67,org.wso2.carbon.device.mgt.oauth.extensions.feature.group/3.0.67,org.wso2.car
bon.identity.jwt.client.extension.feature.group/3.0.67,org.wso2.carbon.device.mgt.analytics.data.publisher.feature.group/3.0.67,org.wso2.carbon.device.mgt.extensions.device.type.deployer.feature.group/3.0.67,org.wso2.car
bon.device.mgt.extensions.push.notification.provider.mqtt.feature.group/3.0.67,org.wso2.carbon.device.mgt.extensions.push.notification.provider.http.feature.group/3.0.67,org.wso2.carbon.device.mgt.extensions.push.notific
ation.provider.fcm.feature.group/3.0.67,org.wso2.carbon.device.mgt.extensions.push.notification.provider.xmpp.feature.group/3.0.67,org.wso2.carbon.device.mgt.analytics.dashboard.feature.group/3.0.67,org.wso2.carbon.devic
e.mgt.mobile.android.feature.group/4.0.55,org.wso2.carbon.device.mgt.mobile.windows.feature.group/4.0.55,org.wso2.carbon.device.mgt.iot.androidsense.ui.feature.group/4.0.55,org.wso2.carbon.device.mgt.iot.androidsense.bac
kend.feature.group/4.0.55,org.wso2.carbon.device.mgt.notification.listener.feature.group/4.0.55,org.wso2.carbon.device.mgt.adapter.feature.group/4.0.55,org.wso2.carbon.webapp.mgt.feature.group/4.7.3,org.wso2.carbon.modul
e.mgt.feature.group/4.7.3,org.wso2.carbon.as.runtimes.cxf.feature.group/4.7.3,org.wso2.carbon.service.mgt.server.feature.group/4.7.3,org.wso2.carbon.application.deployer.webapp.feature.group/4.7.3,org.jaggeryjs.feature.g
roup/0.12.8,org.jaggeryjs.modules.carbon.feature.group/1.5.5,org.jaggeryjs.modules.process.feature.group/1.5.5,org.jaggeryjs.modules.uuid.feature.group/1.5.5,org.jaggeryjs.modules.sso.feature.group/1.5.5,org.jaggeryjs.mo
dules.i18n.feature.group/1.5.5,org.jaggeryjs.modules.ws.feature.group/1.5.5,org.wso2.carbon.dashboards.shindig.feature.group/2.0.7,org.wso2.carbon.dashboards.portal.feature.group/2.0.7,org.wso2.carbon.dashboard.deploymen
t.feature.group/2.0.7,org.wso2.carbon.iot.device.statistics.dashboard.feature.group/4.0.55,org.wso2.carbon.apimgt.keymanager.feature.group/6.1.95,org.wso2.carbon.apimgt.core.feature.group/6.1.95,org.wso2.carbon.apimgt.re
st.api.dcr.feature.group/6.1.95,org.wso2.carbon.apimgt.rest.api.publisher.feature.group/6.1.95,org.wso2.carbon.identity.mgt.feature.group/5.7.5,org.wso2.carbon.apimgt.rest.api.store.feature.group/6.1.95,org.wso2.carbon.a
pimgt.gateway.feature.group/6.1.95,org.wso2.carbon.forum.server.feature.group/6.1.95,org.wso2.carbon.databridge.datapublisher.feature.group/5.1.17,org.wso2.carbon.event.input.adapter.server.feature.group/5.1.17,org.wso2.
carbon.application.mgt.feature.group/4.5.8,org.wso2.carbon.logging.mgt.feature.group/4.5.8,org.wso2.carbon.ntask.feature.group/4.5.8,org.wso2.carbon.tenant.mgt.common.feature.group/4.5.8,org.wso2.carbon.tenant.usage.agen
t.feature.group/4.6.1,org.wso2.carbon.tenant.throttling.agent.feature.group/4.6.1,org.wso2.carbon.tenant.deployment.feature.group/4.6.1,org.wso2.carbon.tenant.common.feature.group/4.6.1,org.wso2.carbon.tenant.mgt.core.fe
ature.group/4.6.1,org.wso2.carbon.security.mgt.feature.group/5.7.5,org.wso2.carbon.um.ws.service.feature.group/5.1.4,org.wso2.carbon.identity.oauth.server.feature.group/5.3.11,org.wso2.carbon.identity.provider.server.fea
ture.group/5.1.1,org.wso2.carbon.identity.thrift.authentication.feature.group/5.7.5,org.wso2.carbon.identity.core.feature.group/5.7.5,org.wso2.carbon.idp.mgt.feature.group/5.7.5,org.wso2.carbon.user.mgt.feature.group/5.7
.5,org.wso2.carbon.directory.service.mgr.server.feature.group/5.7.5,org.wso2.carbon.identity.application.authz.xacml.server.feature.group/1.0.0,org.wso2.carbon.identity.application.authenticator.basicauth.server.feature.
group/5.3.1,org.wso2.carbon.identity.application.authentication.framework.server.feature.group/5.7.5,org.wso2.carbon.identity.authenticator.saml2.sso.feature.group/5.2.1,org.wso2.carbon.identity.sso.saml.feature.group/5.
3.1,org.wso2.carbon.identity.user.profile.feature.group/5.7.5,org.wso2.carbon.identity.application.mgt.feature.group/5.7.5,org.wso2.carbon.claim.mgt.server.feature.group/5.7.5,org.wso2.carbon.claim.mgt.feature.group/5.7.
5,org.wso2.carbon.identity.oauth.ui.feature.group/5.3.11,org.wso2.carbon.identity.notification.mgt.feature.group/5.7.5,org.wso2.carbon.identity.xacml.server.feature.group/5.7.5,org.wso2.carbon.identity.user.registration.
feature.group/5.7.5,org.wso2.carbon.identity.application.authenticator.basicauth.server.feature.group/5.3.1,org.wso2.carbon.identity.application.authenticator.requestpath.basicauth.server.feature.group/5.1.1,org.wso2.car
bon.identity.application.authenticator.requestpath.oauth.server.feature.group/5.1.1,org.wso2.carbon.identity.application.authenticator.samlsso.server.feature.group/5.1.4,org.wso2.carbon.registry.core.feature.group/4.6.8,
org.wso2.carbon.registry.ui.menu.feature.group/4.6.8,org.wso2.carbon.registry.resource.properties.feature.group/4.6.8,org.wso2.carbon.registry.associations.dependencies.feature.group/4.6.8,org.wso2.carbon.registry.commun
ity.features.feature.group/4.6.8,org.wso2.carbon.registry.ws.feature.group/4.6.8,org.wso2.carbon.registry.contentsearch.feature.group/4.6.8,org.wso2.carbon.registry.ui.menu.governance.feature.group/4.6.8,org.wso2.carbon.
registry.task.server.feature.group/4.6.8,org.wso2.carbon.governance.metadata.feature.group/4.7.8,org.wso2.carbon.governance.lifecycle.management.feature.group/4.7.8,org.wso2.carbon.registry.extensions.feature.group/4.7.8
,org.apache.axis2.transport.mail.feature.group/1.1.0.wso2v17,org.apache.synapse.wso2.feature.group/4.6.10,org.apache.synapse.transport.nhttp.feature.group/4.6.10,org.wso2.carbon.mediation.initializer.feature.group/4.6.10
,org.wso2.carbon.mediation.ntask.feature.group/4.6.10,org.wso2.carbon.inbound.endpoints.server.feature.group/4.6.10,org.wso2.carbon.mediators.server.feature.group/4.6.10,org.wso2.carbon.mediation.admin.feature.group/4.6.
10,org.wso2.carbon.task.server.feature.group/4.6.10,org.wso2.carbon.mediation.ui.feature.group/4.6.10,org.wso2.carbon.mediator.cache.feature.group/4.6.10,org.wso2.ciphertool.feature.group/1.0.0.wso2v5,caramel.feature.gro
up/1.0.1,org.wso2.carbon.core.feature.group/4.4.16,org.wso2.carbon.core.runtime.feature.group/4.4.16,org.wso2.carbon.core.ui.feature.group/4.4.16,org.wso2.carbon.module.mgt.server.feature.group/4.7.3,org.wso2.carbon.ndat
asource.feature.group/4.5.8,org.wso2.carbon.ndatasource.capp.deployer.server.feature.group/4.5.8,org.wso2.carbon.ntask.core.feature.group/4.5.8,org.wso2.carbon.identity.authenticator.saml2.sso.server.feature.group/5.2.1,
org.wso2.carbon.identity.authenticator.saml2.sso.ui.feature.group/5.2.1,org.wso2.carbon.identity.application.mgt.server.feature.group/5.7.5,org.wso2.carbon.directory.service.mgr.feature.group/5.7.5,org.wso2.carbon.idp.mg
t.server.feature.group/5.7.5,org.wso2.carbon.identity.user.registration.server.feature.group/5.7.5,org.wso2.carbon.identity.oauth.feature.group/5.3.11,org.wso2.carbon.registry.community.features.server.feature.group/4.6.
8,org.wso2.carbon.registry.community.features.ui.feature.group/4.6.8,org.wso2.carbon.registry.extensions.server.feature.group/4.7.8,org.wso2.carbon.governance.lifecycle.management.server.feature.group/4.7.8,org.wso2.carb
on.governance.metadata.server.feature.group/4.7.8,org.wso2.carbon.apimgt.store.feature.group/6.1.95,org.wso2.carbon.apimgt.authenticator.oidc.feature.group/6.1.95,org.wso2.carbon.apimgt.hostobjects.oidc.feature.group/6.1
.95,org.wso2.carbon.application.mgt.synapse.server.feature.group/4.6.10,org.wso2.carbon.application.deployer.synapse.feature.group/4.6.10,org.apache.axis2.transport.tcp.feature.group/1.1.0.wso2v17,org.wso2.carbon.relay.s
erver.feature.group/4.6.10,org.wso2.carbon.mediation.configadmin.feature.group/4.6.10,org.wso2.carbon.webapp.mgt.server.feature.group/4.7.3,org.wso2.carbon.system.statistics.feature.group/4.5.8,org.wso2.carbon.databridge
.streamdefn.filesystem.server.feature.group/5.1.17,org.wso2.carbon.analytics.api.client.feature.group/1.3.3,org.wso2.carbon.analytics.jsservice.feature.group/1.3.3,org.wso2.carbon.event.stream.feature.group/5.1.17,org.ws
o2.carbon.event.application.deployer.feature.group/5.1.17,org.wso2.carbon.metrics.feature.group/1.2.2,org.wso2.carbon.identity.oauth2.grant.jwt.feature.group/1.0.2,org.wso2.carbon.device.mgt.analytics.dashboard.feature.g
roup/3.0.67,org.wso2.carbon.device.mgt.cdmf.analytics.feature.group/4.0.55,org.wso2.carbon.iot.geo.dashboard.feature.group/4.0.55, -bundlepool D:\product-iots-3.1.0\modules\p2-profile\iot-core-profile/target/wso2carbon-c
ore-4.4.16/wso2/components -shared D:\product-iots-3.1.0\modules\p2-profile\iot-core-profile/target/wso2carbon-core-4.4.16/wso2/components\p2 -destination D:\product-iots-3.1.0\modules\p2-profile\iot-core-profile/target/
wso2carbon-core-4.4.16/wso2/components\default -profile default -roaming"
The command line is too long.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] WSO2 IoT - Parent .................................. SUCCESS [  1.028 s]
[INFO] WSO2 IoT - Components Module ....................... SUCCESS [  0.156 s]
[INFO] WSO2 IoT - UI Styles ............................... SUCCESS [  2.212 s]
[INFO] WSO2 IoT - Features Module ......................... SUCCESS [  0.187 s]
[INFO] WSO2 IoT - Styles Feature .......................... SUCCESS [  1.418 s]
[INFO] WSO2 IoT - Scripts ................................. SUCCESS [  0.140 s]
[INFO] WSO2 IoT - QSG Script .............................. SUCCESS [  4.876 s]
[INFO] WSO2 IoT - Tools ................................... SUCCESS [  0.109 s]
[INFO] WSO2 IoT - Device Type Archetype ................... SUCCESS [  1.900 s]
[INFO] WSO2 IoT - P2 Profile Module ....................... SUCCESS [  0.125 s]
[INFO] WSO2 IoT - Core P2 Profile Gen ..................... FAILURE [02:00 min]
[INFO] WSO2 IoT - Analytics P2 Profile Gen ................ SKIPPED
[INFO] WSO2 IoT - Broker P2 Profile Gen ................... SKIPPED
[INFO] WSO2 IoT - Distribution ............................ SKIPPED
[INFO] WSO2 IoT - Integration Module ...................... SKIPPED
[INFO] WSO2 IoT - Integration Test Common ................. SKIPPED
[INFO] WSO2 IoT - Integration Common ...................... SKIPPED
[INFO] WSO2 IoT - Integration Test Common Web UI Pages .... SKIPPED
[INFO] WSO2 IOT - Integration Test Module ................. SKIPPED
[INFO] WSO2 IoT - Integration Test UI Module .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:14 min
[INFO] Finished at: 2017-08-21T08:52:56+08:00
[INFO] Final Memory: 60M/524M

**Comment by pedy711** [comment]
I have the same problem with this. Did anyone manage to find a solution?

**Comment by ten2net** [comment]
:+1: 
I have the same problem with this.  
### error message: 
Failed to execute goal org.wso2.maven:carbon-p2-plugin:1.5.4:p2-profile-gen (3-p2-profile-generation) on project wso2iot-core-p2-profile: P2 publisher return code was 1
### my builder env:
>  version : 3.2.0-update1-SNAPSHOT 
> os: windows 8
> jdk: jdk1.8.0_45-64

**Comment by charithag** [comment]
On Microsoft Windows XP or later, the maximum command length is limited to [8191  characters[1]](https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation). Since maven build use dynamically generated commands, it may exceed that limit during the execution.

Please try to run build by placing source files in to drive root in order to reduce command argument length.

[1] https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation

**Comment by smhasan11** [comment]
@ten2net , @jiangcluster , weer you able to fix the issue? I'm having the same problem and stuck.
