### ISSUE TITLE
Wso2 agent not connecting to my wso2-iot server (3.0.0)

### ISSUE THREAD

**Issue by thusithathilina** [wso2/product-iots#1334]
Environment - wso2-iot (3.0.0)server installed in Ubuntu 16.04 server
My device is not connecting to the server after 2 days. I installed my agent app in the device and it was switched off for 2 days.after switching on my device is not communicating with the wso2-iot server.

1. Will wso2-agent app got expired after a paticular time period if its in offline?
2. How can I solve this issue?

Originally reported by jones Thomas https://wso2.org/jira/projects/CARBON/issues/CARBON-16148

**Comment by charithag** [comment]
This issue has been fixed with https://github.com/wso2/cdmf-agent-android/pull/25. Please use latest agent from https://github.com/wso2/cdmf-agent-android/releases/download/v3.1.19/client-standalone.apk

Cannot automate this as this a agent related issue.

**Comment by jonesthomaz** [comment]
Thank you client-standalone.apk work like charm.
