### ISSUE TITLE
wso2 agent app got expired. it is not communicating with the server, but device state is active in the wso2 dashboard

### ISSUE THREAD

**Issue by thusithathilina** [wso2/product-iots#1335]
wso2 agent app got expired ..it is not communicating with the server, but device state is active in the wso2 dashboard
Originally reported by jones Thomas https://wso2.org/jira/projects/CARBON/issues/CARBON-16149

**Comment by harshanL** [comment]
This has been already fixed in : https://github.com/wso2/product-iots/issues/518.
