### ISSUE TITLE
Documentation missing for the Resetting the password in the manage users page

### ISSUE THREAD

**Issue by sinthuja** [wso2/product-iots#1341]
There is an option to reset the password of the other users in the manage users page. Please refer the attached screenshot here with which shows the functionality. Let's add this to our IoT Docs. 

<img width="1417" alt="screen shot 2017-08-29 at 10 57 14 am" src="https://user-images.githubusercontent.com/7677649/29806592-d647c076-8cad-11e7-8f03-0798ef23d092.png">

**Comment by shavidissa** [comment]
Thank you! @yvonne is working on this.

**Comment by YvonneW** [comment]
@sinthuja The corresponding content can be found on the [Resetting a User Password](https://docs.wso2.com/display/IoTS310/Resetting+a+User+Password) page.

**Comment by yvonne** [comment]
You got the wrong person. Please stop tagging me

**Comment by shavidissa** [comment]
Sorry about it @yvonne! :)

**Comment by shavidissa** [comment]
Thank you for documenting the content @YvonneW. I am closing this issue.
