### ISSUE TITLE
Documentation for configuring external IS as IDP 

### ISSUE THREAD

**Issue by Megala21** [wso2/product-iots#1343]
We need to add the documentation for configuring external IS as IDP . This is not available now.

**Comment by shavidissa** [comment]
Thank you! @yvonne can you look into this too, please!

**Comment by shavidissa** [comment]
sorry for the wrong tag. @yvonneW will look into this.

**Comment by YvonneW** [comment]
@Megala21 This was documented under the section Integrating a [Third-Party Identity Provider for SSO](https://docs.wso2.com/display/IoTS310/Integrating+a+Third-Party+Identity+Provider+for+SSO).

**Comment by ruwany** [comment]
Marking as closed, since documentation has been added.
