### ISSUE TITLE
iOS enroll without agent documents should be updated

### ISSUE THREAD

**Issue by madawas** [wso2/product-iots#1347]
Since we have enabled the DEVICE_LOCATION operation to be executed by the task by default, If someone is enrolling a device without iOS Agent, #1345 will occur. So we must mention in the docs to disable the DEVICE_LOCATION operation before enrolling the device.

**Comment by shavidissa** [comment]
Thank you! Updated [1] with a note.
[1] https://docs.wso2.com/display/IoTS310/Enrolling+Without+the+iOS+Agent
