### ISSUE TITLE
Device details of one user is redirected to device details of another user when device is registered with same device ID

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-iots#1348]
I have created 2 users ( useraaa and userbbb ) and registered a device for useraaa, then registered the same device for userbbb.

Though in the device details page, the device is shown as removed for useraaa , when clicked on it, it got redirected to the device details page of userbbb.

![1111](https://user-images.githubusercontent.com/24619763/29821421-71f8360e-8ce5-11e7-9ae8-6d6e3ceb7c03.png)
![22222](https://user-images.githubusercontent.com/24619763/29821420-71f63ab6-8ce5-11e7-96a3-5750192a260b.png)

**Comment by sinthuja** [comment]
@Nirothipan will wok on this.
