### ISSUE TITLE
Bug : Deleting devices WSO2 IoT Server 3.1.0-UPDATE1

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1352]
Hi all,

I found that if I delete a device in wso2 iot server 3.1.0 update, all other devices are also deleted.

Can you make patches so that not all devices are disabled.

Also, once deleted, it would be nice that one no longer sees the device.

Thanks
![bug_devices](https://user-images.githubusercontent.com/22862175/29837846-ad2f3510-8cf9-11e7-81dc-5bdf1d0d1cee.png)

**Comment by madawas** [comment]
@Tofdu31 Once a device is removed we are moving it to the removed state and keep the record for auditing purposes. Anyway, we'll look into the issue of removing multiple devices.

**Comment by ghost** [comment]
thank you,
I am waiting for your return

**Comment by madawas** [comment]
@Tofdu31 I was unable to reproduce the issue of getting multiple devices removed. Did you follow any specific steps to reproduce the issue? If so could you mention them?

![screenshot from 2017-08-31 10-14-16](https://user-images.githubusercontent.com/4003137/29906824-2f28be7e-8e35-11e7-9f42-eacf2ac2efec.png)

**Comment by harshanL** [comment]
@Tofdu31 Were you able to test this again? If it has happened again please share the steps to reproduce this issue.

**Comment by ghost** [comment]
I am in the process of finishing another problem. I switch to this one quickly and I keep you informed

Tof

**Comment by charithag** [comment]
@Tofdu31, We are closing this issue as this was not reproducible from our end. Please feel free to open this issue and share the exact steps you have followed if this is still reproducible form your end.
