### ISSUE TITLE
When a new user is added without assigning roles ( not a mandatory field) , User get added but  an error message is shown in UI

### ISSUE THREAD

**Issue by Nirothipan** [wso2/product-iots#1357]
_Steps to reproduce_
Go to  User Management -> Users -> Add user
and add a user without giving a role ( all other fields filled). An error message will be shown as in screen shot. But the user will be added.

![error](https://user-images.githubusercontent.com/24619763/29865277-c273e792-8d92-11e7-8673-a5cf8e88bd9c.png)

**Comment by pasindujw** [comment]
(self-assigned)
