### ISSUE TITLE
Update the configuration to change admin password and username

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#1370]
Currently, we need to update many areas to successfully update the username and password. As discussed, can we look at changing this method to how other products handle it (changing only one place)?

**Comment by ruwany** [comment]
This script is now shipped with the IoT Server: https://github.com/wso2/product-iots/blob/master/modules/scripts/change-superadmin-credentials.sh

Once this script is run, all the admin usernames/passwords will be changed in one go.

**Comment by rasika** [comment]
Have we updated docs for this?
