### ISSUE TITLE
Upgrade wso2iot server from 3.0.0 to 3.1.0

### ISSUE THREAD

**Issue by omindu** [wso2/product-iots#1380]
Redirecting from - https://wso2.org/jira/browse/IDENTITY-6338

> I need to upgrade the wso2iot server from 3.0.0 to wso2iot 3.1.0.guide me step by step please

**Comment by Quizzical23** [comment]
Any updates?

**Comment by rasika** [comment]
@lasanthaDLPDS did we finished the migration scripts?

**Comment by Quizzical23** [comment]
?

**Comment by lasanthaDLPDS** [comment]
We have created data migration scripts and currently, we are testing the migration steps. We will update you once we complete the migration scripts and documention for the migration steps that required to follow when you are migrating from a prior version of IoTS 3.1.0 to IoTS 3.1.0.
