### ISSUE TITLE
Error 403 - Forbidden accessing the broker

### ISSUE THREAD

**Issue by omindu** [wso2/product-iots#1381]
Redirecting from https://wso2.org/jira/browse/IDENTITY-6337

> when i access the broker port i get the following error. 
> https://${serverip}:9446 Error 403 - Forbidden

**Comment by ghost** [comment]
It's normal to have an error.  https://github.com/wso2/product-iots/issues/316

**Comment by madawas** [comment]
@omindu The broker management console is blocked intentionally.

**Comment by jonesthomaz** [comment]
how to solve this error.

**Comment by madawas** [comment]
@jonesthomaz this is not an error. Access to the broker ui is intentionally blocked.
