### ISSUE TITLE
Upgrade WSO2 IoT Server 3.1.0 -> WSO2 IoT Server 3.1.0-UPDATE2

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1384]
HI,
Can you explain how we can move from the WSO2 version IoT Server 3.1.0 to the WSO2 version IoT Server 3.1.0-UPDATE1

It will also allow to be able to upgrade to WSO2 IoT Server 3.1.0-UPDATE2 (or  WSO2 version IoT Server 3.1.1)  which will be released soon

Thanks

**Comment by geethkokila** [comment]
Hi @Tofdu31,

We will release migration scripts for each release if required. The requirements will come if we make any schema changes only.

Thanks
Geeth

**Comment by ruwany** [comment]
Migration scripts for 3.1.0 -> 3.2.0 tracked here : https://github.com/wso2/product-iots/issues/1517
