### ISSUE TITLE
Implement a scheduled task to archive activity data

### ISSUE THREAD

**Issue by dunithd** [wso2/product-iots#1394]
In a production deployment of IoT server, activities and relevant data keep accumulating over time. So tables such as DM_OPERATION, DM_DEVICE_OPERATION_RESPONSE, and DM_ENROLMENT_OP_MAPPING will grow in size eventually. Due to this reason, reading activities will get slower.
To address this, a scheduled task needs to implemented to run once a day and move all records that are older than 30 days to another set of archival tables. This helps the system to retain activities only for the last month and will make the getActivities() endpoint faster to some extent.

There will be two scheduled tasks, both run exactly once a day.
Task #1 performs following on DM_OPERATION, DM_DEVICE_OPERATION_RESPONSE and DM_ENROLMENT_OP_MAPPING tables.

Read all records that are older than 30 days.
Insert them into corresponding tables in a new database. Those tables will be suffixed with "_arch".
From source tables, delete all records that are older than 30 days.
Task #2 performs following on the tables with "_arch" prefix.

Read all records that are older than 30 days( this retention period can be customized) and delete them.
These operations will be implemented with atomicity in mind. During the data move, records will be broken into a set of batches and they will be inserted and deleted in a transactional manner, batch after batch. We'll have to do some load tests and determine a suitable value for the batch size.

**Comment by charithag** [comment]
PR has not merged. Hence re opening the issue.
https://github.com/wso2/carbon-device-mgt/pull/977

**Comment by charithag** [comment]
Closing the issue as all PRs are merged
