### ISSUE TITLE
APIMClientOAuthException error after using change-ip.sh script on remote machine

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [wso2/product-iots#1396]
Hello.

I have uploaded and unzipped this application into my remote machine with static ip address. Then I have run `change-ip.sh` script in order to change ip addresses for redirections.

I have changed `localhost` to my own static ip address.

After changing complete I have tried to login to device management console. However it throws me this error:

    org.wso2.carbon.apimgt.integration.client.exception.APIMClientOAuthException: failed to retrieve oauth token using jwt

In my carbon dashboard logs shows this:

    TID[-1234] [IoT] [2017-09-09 16:28:47,538] ERROR {auth-module} - An exception thrown when executing the script '/app/modules/login.js'. 

    TID[-1234] [IoT] [2017-09-09 16:28:47,540] ERROR {auth-module} - org.wso2.carbon.apimgt.integration.client.exception.APIMClientOAuthException: failed to retrieve oauth 
    token using jwt org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754) 
    org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148) 
    org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225) 
    org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85) 
    org.jaggeryjs.rhino.devicemgt.app.modules.c3._c_anonymous_2(/devicemgt/app/modules/login.js:31) 
    org.jaggeryjs.rhino.devicemgt.app.modules.c3.call(/devicemgt/app/modules/login.js) 
    org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) 
 

My steps during tha launching `change-ip.sh` script 

     ----------------------------------------
     WSO2 IoT Server IP configuration tool
     ----------------------------------------

     >>> Step 1: Change current IP address of the IoT server

     Please enter the IoT Core IP that you need to replace (if you are trying out IoT                                                                 
     server for the first time this will be localhost)
     localhost

     Please enter your current IP
     x.x.x.x
    --------------------------------------
     All your  + localhost +  IP's are replaced with  +x.x.x.x
    --------------------------------------
    Changing <IoT_HOME>/conf/carbon.xml
    sed: can't read : No such file or directory
    sed: can't read : No such file or directory
    Completed!!
    Changing <IoT_HOME>/conf/app-manager.xml
    sed: can't read : No such file or directory
    Completed!!
    Changing <IoT_HOME>/conf/identity/sso-idp-config.xml
    sed: can't read : No such file or directory
    Completed!!
    Changing <IoT_HOME>/conf/iot-api-config.xml
    sed: can't read : No such file or directory
    Completed!!
    Changing <IoT_HOME>/repository/deployment/server/jaggeryapps/devicemgt/app/conf/                                                                
    app-conf.json
    Completed!!
    Changing <IoT_HOME>/repository/deployment/server/jaggeryapps/api-store/site/conf                                                                /site.json
    Completed!!
    Changing <IoT_HOME>/repository/deployment/server/jaggeryapps/portal/configs/desi                                                                gner.json
    Completed!!
    Changing  <IoT_HOME>/conf/api-manager.xml
    found
    found
    sed: can't read : No such file or directory
    Completed!!
    Changing <IoT_HOME>/conf/etc/webapp-publisher-config.xml
    sed: can't read : No such file or directory
    Completed!!
    Changing  <IoT_HOME>/bin/iot-server.sh
    Completed!!

    Changing hostURL of <IoT_HOME>/wso2/broker/conf/broker.xml

    Changing tokenEndpoint of <IoT_HOME>/wso2/broker/conf/broker.xml

    Changing deviceMgtServerUrl of <IoT_HOME>/wso2/broker/conf/broker.xml
    Changing  <IoT_HOME>/wso2/analytics/bin/wso2server.sh
    Completed!!
    Changing  <IoT_HOME>/wso2/analytics/repository/deployment/server/jaggeryapps/por                                                                tal/configs/designer.json
    Completed!!

    >>> Step 2: Change current IP address of the IoT Broker
    -------------------------------------------------------
    Changing  <IoT_HOME>/wso2/analytics/bin/wso2server.sh
    Completed!!
    Changing  <IoT_HOME>/bin/iot-server.sh
    Completed!!
    Changing <IoT_HOME>/wso2/broker/conf/carbon.xml
    sed: can't read : No such file or directory
    sed: can't read : No such file or directory
    Completed!!

    >>> Step 3: Change current IP address of the IoT Analytics
    -------------------------------------------------------
    Changing  <IoT_HOME>/bin/iot-server.sh
    Completed!!
    Changing  <IoT_HOME>/wso2/analytics/repository/deployment/server/jaggeryapps/por                                                                tal/configs/designer.json
    Completed!!
    Changing <IoT_HOME>/wso2/analytics/conf/carbon.xml
    sed: can't read : No such file or directory
    sed: can't read : No such file or directory
    Completed!!

    -----------------------------------------------
    Generating SSL certificates for the IoT Server
    -----------------------------------------------

    mkdir: cannot create directory ‘tmp’: File exists

    =======Enter Values for IoT Core SSL Certificate=======
    Please provide Country. Press Enter to skip.

    Please provide State. Press Enter to skip.

    Please provide Location. Press Enter to skip.

    Please provide Organization. Press Enter to skip.

    Please provide Organizational Unit. Press Enter to skip.

    Please provide Email Address. Press Enter to skip.

    Please provide Common Name

    Common name(your server IP/hostname) cannot be null. Please enter the Common name.
    x.x.x.x

    Provided IoT Core SSL Subject :  /CN=35.156.112.74
    If you have a different IoT Core Keystore password please enter it here. Press Enter to use the default password.

    Generating SSL Certificate for IoT Core
    Generating RSA private key, 4096 bit long modulus
    ................................................................................                                                                 
    ................................................................................                                                                
    ................................................................................                                                                .
    e is 65537 (0x10001)
    Signature ok
    subject=/CN=x.x.x.x
    Getting Private key
    Export to PKCS12
    Export PKCS12 to JKS
    Warning: Overwriting existing alias wso2carbon in destination keystore
    Entry for alias wso2carbon successfully imported.
    Import command completed:  1 entries successfully imported, 0 entries failed or                                                                 cancelled
    Warning: Overwriting existing alias wso2carbon in destination keystore
        Entry for alias wso2carbon successfully imported.
    Import command completed:  1 entries successfully imported, 0 entries failed or                                                                 cancelled
    Warning: Overwriting existing alias wso2carbon in destination keystore
    Entry for alias wso2carbon successfully imported.
    Import command completed:  1 entries successfully imported, 0 entries failed or                                                                 cancelled
    Warning: Overwriting existing alias wso2carbon in destination keystore
    Entry for alias wso2carbon successfully imported.
    Import command completed:  1 entries successfully imported, 0 entries failed or                                                                 cancelled
    Warning: Overwriting existing alias wso2carbon in destination keystore
    Entry for alias wso2carbon successfully imported.
    Import command completed:  1 entries successfully imported, 0 entries failed or                                                                 cancelled
    Warning: Overwriting existing alias wso2carbon in destination keystore
    Entry for alias wso2carbon successfully imported.
    Import command completed:  1 entries successfully imported, 0 entries failed or                                                                 cancelled

    Setting up the public certificate for the default idp

    Printing certificate
    -----------------------
    I will skip this 
    DuweX8HB6A9jssnviqGcyXT7PPc2fVri70v82bTpeaHivTEg0st8zCL6i5+/Ghj900TG/zE28w==
    sed: can't read : No such file or directory

    Configuration Completed!!!

I have changed my real IP address with `x.x.x.x`. Even if I this script shows `No such file or directory` it makes changes to these files. However, I still get this error.

I think it is connected to #1126 

**WSO2 IoTS 3.1.0**

**Comment by SuperMasterBlasterLaser** [comment]
Now I have unzipped and launched `wso2iot-3.1.0-update2.zip` file with steps above. I still get this error.

![1](https://user-images.githubusercontent.com/8684688/30249683-cced2854-9662-11e7-81c8-8eadf9664457.PNG)

I think session is somehow works, but Jaggery frontend not getting tokens.

**Comment by geethkokila** [comment]
Hi,

Can you please send us the wso2carbon.log file with debug enabled for us to narrow down the issue?

Please follow these steps to enable debug logs. 

Go to the IOT_HOME/conf/log4j.properties file. 
Uncomment the following
#log4j.logger.org.apache.synapse.transport.http.wire=DEBUG
#log4j.logger.feign=DEBUG

Comment the following
log4j.category.org.apache.synapse=WARN

Then restart the IoT server and try to login to the devicemgt application.
After the error happens, please upload IoT_HOME/repository/logs/wso2carbon.log file to here.

**Comment by SuperMasterBlasterLaser** [comment]
@geethkokila Here. I have uncommented these configs and restarted iot-server. Errors you can see when you will scroll to the bottom of file.


[wso2carbon.log.txt](https://github.com/wso2/product-iots/files/1290768/wso2carbon.log.txt)

**Comment by geethkokila** [comment]
Hi 
It seems that localhost is being referred by the server. 
Can you please verify the values in /etc/hosts file that it does not have an entry that is pointing "your ip" to localhost.

**Comment by geethkokila** [comment]
If above does not solve the issue, can you please upload your IOT_HOME/conf directory for us to check the configs, (Please obfuscate any password on config file before attaching)

**Comment by geethkokila** [comment]
With the conf directory, please upload the IOT_HOME/bin/iot-server.sh file too

**Comment by SuperMasterBlasterLaser** [comment]
@geethkokila Before I have found this script I have changed my `etc/hosts` in my machine

I have made my ip point to localhost.

Now I have changed it to default settings and now Device Management works properly.

However, now I can't open carbon console!

When I open `https://my_ip:9443/carbon` it opens just white page and does nothing.

**Comment by geethkokila** [comment]
Hi, It is great that first issue is solved. There is a known issue about the "carbon" console. I hope you have started all 3 servers (broker, analytics, and iot-core) or at least 2 of them. If yes, can you restart only the iot-core server and it will fix the "carbon" console issue for iot-core. To make sure that you can log in to carbon console of the iot-core server, start that server at last after other two servers (broker and analytics) started.

**Comment by SuperMasterBlasterLaser** [comment]
@geethkokila Thank you for help. I thought that should start components with this sequence:

broker -> server -> analytics

Because it was written in documentation.

**Comment by geethkokila** [comment]
That is the recommended sequence it should be started on, but we have a known issue with that sequence. We will fix the issue soon. This happens only when you try to start all the servers in a single machine. 

Hope everything is ok

**Comment by SuperMasterBlasterLaser** [comment]
Now it works properly. Thank you!
