### ISSUE TITLE
When using the WSO2 IS as external IDP, signature validation failed even if we use  "wso2carbon" as certification alias

### ISSUE THREAD

**Issue by Megala21** [wso2/product-iots#1400]
May be this is because of using a different wso2carbon.jks. Since wso2 carbon 4.4.17 is released, we need to move with the default wso2carbon.jks shipped. Otherwise user need to configure the wso2carbon.jks to make it work with WSO2 identity server.

**Comment by ruwany** [comment]
FIxed with Kernel upgrade to 4.4.17 

PR : https://github.com/wso2/product-iots/pull/1436
