### ISSUE TITLE
Existing whitelisting policy doesn't appear in view policy page

### ISSUE THREAD

**Issue by charithag** [wso2/product-iots#1403]
Steps to reproduce:

1. Add policy for app whitelist
2. Publish and apply policy to devices.
3. Click on policy and explore app restrictions.

![screenshot from 2017-09-13 13-11-03](https://user-images.githubusercontent.com/3184302/30365358-1c89b1ec-9885-11e7-80e4-c4694bbfc7cd.png)

**Comment by ruwany** [comment]
Closing as this is fixed.
