### ISSUE TITLE
wso2iot 3.1.0 update2 uses cpu Memory to 100%

### ISSUE THREAD

**Issue by jonesthomaz** [wso2/product-iots#1406]
Wso2-3.1.0 update 2 is getting cpu usage to 100%.This happens when only running the wso2 service.
java JAVA_OPTS="-Xms1024m -Xmx2048m".

**Comment by geethkokila** [comment]
Can you please share the machine details, os, version, ram, memory, cpu. ?

**Comment by ruwany** [comment]
Are you using WSO2 IoT Server with iOS device type, installed?
We have identified a possible cause for this related to notnoop library. 
This is fixed with the latest update releases. Please let us know if you encounter this issue once again in the future.
