### ISSUE TITLE
wsoiot 3.1.0 update2 Carbon is not loading

### ISSUE THREAD

**Issue by jonesthomaz** [wso2/product-iots#1407]
@Error/Bug

 installing the self signed certificate wso2iot carbon is not loading. and in device management i have this error.
![untitled](https://user-images.githubusercontent.com/26079581/30431097-1c0a433e-997b-11e7-8764-556cc2bf6754.png)

How to solve this issue?

**Comment by geethkokila** [comment]
Hi @jonesthomaz, 

Please refer followings. They had the same issue and the answers are provided there too. Would please have a look.

https://stackoverflow.com/questions/46128761/wso2-iots-apimclientoauthexception-failed-to-retrieve-oauth-token-using-jwt/
https://stackoverflow.com/questions/45979615/error-when-changing-ip-and-certificate-on-wso2-iot/
https://github.com/wso2/product-iots/issues/1396

Thanks
Geeth

**Comment by geethkokila** [comment]
Hi @jonesthomaz 
Were you able to resolve the issue?
Thanks
Geeth

**Comment by geethkokila** [comment]
Closing the issue as an answer is provided
