### ISSUE TITLE
Questions: Tenants and Certificates ?

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#1411]
Looking at wso2 carbon from WSO2 IOT, I realized that a certificate is created if we set up a new Tenants.

I see in carbon the certificates of my new tenants : 
![certificates_tenants_01](https://user-images.githubusercontent.com/22862175/30480177-cc13ffb6-9a18-11e7-96d7-ff13fedee5d6.png)

On carbon, when i go to /_system/governance/repository/security/key-stores with Browse, i see a new certificates. For my example, my new Tenants is : test.fr 
![certificates_tenants_02](https://user-images.githubusercontent.com/22862175/30480202-e8eabd32-9a18-11e7-9c72-448800553dba.png)

In the Actions I can download it. But, In the wso2iot folder I tried to look for it and it is impossible for me to find the file test-fr.jks

Can anyone explain why? and tell me where the information is stored

Thank for your help.

**Comment by geethkokila** [comment]
This information is stored in the registry. The registry is a database which acts like a virtual file system. Therefore you will not find that in the file structure. 

http://wso2.com/library/tutorials/2010/04/sharing-registry-space-across-multiple-product-instances/

**Comment by ruwany** [comment]
Marking as closed, since answer was provided.
