### ISSUE TITLE
How to show advanced android device information?

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [wso2/product-iots#1414]
I have enrolled BYOD deviceto my own WSO2 IoTS and in device management it shows me that kind of information:

![1](https://user-images.githubusercontent.com/8684688/30511821-cfc066dc-9b02-11e7-8733-2f49ffd141d5.PNG)

However, I want also view `IMEI`, `IMSI`, `MAC`, `OS_VERSION` and `CPU_INFO`. Also there is a possiblilty that I need to show data of SIM Card.

I know that Android Agent sends far more data tjan it is shown in dashboard.

How to show them? And how to send and show custom data?

**Comment by SuperMasterBlasterLaser** [comment]
@geethkokila I have deployed UPDATE3 version of 3.1.0 and I devices detail dashboard does not have any changes

![1](https://user-images.githubusercontent.com/8684688/30772686-7f9125ea-a082-11e7-8583-47c10c9e3f89.PNG)

**Comment by geethkokila** [comment]
@SuperMasterBlasterLaser, You will have to customize the dashboard for your requirement. We have added the API support from the backend. At the moment, we will not show those details in our generic UI. You will have to customize it as you wish. Or you can talk with one of our account managers, and they will guide you how to get WSO2 to customize this for you.

**Comment by SuperMasterBlasterLaser** [comment]
@geethkokila [in this page](https://docs.wso2.com/display/IoTS310) I can't find any documentation to customize Android Device Info Dashboard.
