### ISSUE TITLE
Blacklisting and whitelisting not working in AFW

### ISSUE THREAD

**Issue by inoshperera** [wso2/product-iots#1432]
In Android for work, work profile, the Blacklisting and whitelisting not working  as the command set to the device has no effect. This is due to an old implementation that is not compatible with work profile being executed. This affects IoT 3.1.0 GA.

**Comment by ghost** [comment]
Any update on this issue? Would quite like to have white list working in work profile.

**Comment by inoshperera** [comment]
@Whevw - This has been fixed in  the master branch of the agent
