### ISSUE TITLE
[IOT] Unable to install pip and Paho-MQTT

### ISSUE THREAD

**Issue by YvonneW** [wso2/product-iots#1435]
**Description**

When attempted to create a Virtual Fire Alarm by following the [tutorial](https://docs.wso2.com/display/IoTS310/Creating+a+Fire+Alarm+Device+Type+via+the+Console), installing pip and Paho-MQTT was not successful.

**Suggested Labels**
IoTS, Custom Device Types

**Suggested Assignees**
@geethkokila, @ruwany, @GDLMadushanka  

**Affected Product Version:**
[3.1.0_Update3](https://github.com/wso2/product-iots/releases/tag/v3.1.0-update3)

**OS, DB, other environment details and versions**    
TBD

**Steps to reproduce** 
1. Installed python.
2. Entered "pip -V" and received the response "-bash: pip: command not found".
3. Next, tried typing the following commands:
     cd /Library/Frameworks/Python.framework/Versions/3.6/bin/
     ls -l
4. The terminal displayed that the pip is already installed.

![image](https://user-images.githubusercontent.com/9816314/31112361-dbeacc78-a830-11e7-8d45-59e5ea8560d5.png)

**Related Issues:**
N/A

**Comment by rasika** [comment]
need to use "pip3" instead of "pip" when using python3.x. Raised a DOC JIRA https://wso2.org/jira/browse/DOCUMENTATION-4980

**Comment by shavidissa** [comment]
Thank you! Updated docs [1].

[1] https://docs.wso2.com/display/IoTS310/Creating+a+Fire+Alarm+Device+Type+via+the+Console

**Comment by YvonneW** [comment]
As per @geethkokila's comment on the [JIRA ticket](https://wso2.org/jira/browse/DOCUMENTATION-4980), need to do the following updates:

Change the line 36 as follows in the SampleClient.py
print ("Cannot read the configuration file")
Run as follows
python3 SampleClient.py

**Comment by charithag** [comment]
Documentation and agent source has been updated. Hence closing the issue.
https://github.com/wso2/samples-iots/blob/master/DeviceTypeAPI_PythonSample/SampleClient.py#L36
