### ISSUE TITLE
[Android agent] Restrictions which can perform as Device owner are redirecting to SystemApp.

### ISSUE THREAD

**Issue by pasindujw** [wso2/product-iots#1446]
**Description:**
- ALLOW_PARENT_PROFILE_APP_LINKING
- DISALLOW_CONFIG_VPN
- DISALLOW_INSTALL_APPS 

These restrictions are redirecting to System app if the agent is set as Device Owner. But those can be done from the agent itself since those permissions are received as 'Device Owner'

Refer these lines with IF condition:
1. https://github.com/wso2/cdmf-agent-android/blob/b60233fa114a5a083be141eb66b4a13bf69070cd/client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationProcessor.java#L171
2. https://github.com/wso2/cdmf-agent-android/blob/b60233fa114a5a083be141eb66b4a13bf69070cd/client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationProcessor.java#L178
3. https://github.com/wso2/cdmf-agent-android/blob/b60233fa114a5a083be141eb66b4a13bf69070cd/client/client/src/main/java/org/wso2/iot/agent/services/operation/OperationProcessor.java#L185

**Proposing solution**
Make those IF conditions to check if the systemapp is installed instead of checking if the agent is the Device Owner. As below:

> if (CommonUtils.isSystemAppInstalled(context)) { 
operationManager.passOperationToSystemApp(operation);
}

**Affected Product Version:**
IoT 3.1.0 + Android agent 3.1.21

**Comment by charithag** [comment]
Fixed with PR https://github.com/wso2/cdmf-agent-android/pull/122
