### ISSUE TITLE
Problem in enroll Raspberry Pi 3 with wso2 iot server 3.1.0

### ISSUE THREAD

**Issue by alirezan74** [wso2/product-iots#1509]
**Description:**

I do all steps in https://docs.wso2.com/display/IoTS310/Raspberry+Pi and now when i run testAgent.sh on raspberry pi, shown below result:

```
MQTT_LISTENER: MQTT_ENDPOINT is ['tcp', '//', '1886']
MQTT_LISTENER: MQTT_TOPIC is carbon.super/raspberrypi/sksc2lir038h
MQTT_LISTENER: Sun Dec  3 10:29:44 2017 Connected to MQTT Broker - :1886
MQTT_LISTENER: Connected with result code 4
Agent disconnected from broker
Obtaining new access token
MQTT_LISTENER: Exception in MQTTServerThread (either KeyboardInterrupt or Other)
MQTT_LISTENER: 'refresh_token'
MQTT_LISTENER: Sun Dec  3 10:29:45 2017 Connection to Broker closed - :1886
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
MQTT_LISTENER: Sun Dec  3 10:29:45 2017 Connected to MQTT Broker - :1886
MQTT_LISTENER: Exception in MQTTServerThread (either KeyboardInterrupt or Other)
MQTT_LISTENER: 'refresh_token'
Agent disconnected from broker
Obtaining new access token
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./src/RaspberryAgent.py", line 305, in run
    mqttConnector.main()
  File "/home/pi/tempdevice/src/mqttConnector.py", line 156, in main
    mqttClient.disconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 1152, in disconnect
    return self._send_disconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 2156, in _send_disconnect
    return self._send_simple_command(DISCONNECT)
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 2096, in _send_simple_command
    return self._packet_queue(command, packet, 0, 0)
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 2290, in _packet_queue
    return self.loop_write()
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 1309, in loop_write
    rc = self._packet_write()
  File "/usr/local/lib/python2.7/dist-packages/paho_mqtt-1.3.1-py2.7.egg/paho/mqtt/client.py", line 1908, in _packet_write
    self.on_disconnect(self, self._userdata, 0)
  File "/home/pi/tempdevice/src/mqttConnector.py", line 105, in on_disconnect
    response = token.updateTokens()
  File "/home/pi/tempdevice/src/token_updater.py", line 52, in updateTokens
    self.updateFile(response)
  File "/home/pi/tempdevice/src/token_updater.py", line 27, in updateFile
    newRefreshToken = response['refresh_token']
KeyError: 'refresh_token'
```

please help me...

**Comment by charithag** [comment]
As per the log output you have shared, it seems like token renewal is not happening properly due to issue in token retrieval from the response. I have also tried this out and wasn't able to reproduce the issue you are facing with. Anyway this issue might be happen if Refresh token you have used to obtain new token pair is invalid. 

So one thing you can do is obtain new token pair for your agent and update your deviceConfig.properties file manually with correct tokens. In order to obtain new token pair use following curl command by replacing contents between < and > (Including < and >).

curl -k -d "grant_type=password&username=<username>&password=<password>" -H "Authorization: Basic <application-key>" -H "Content-Type: application/x-www-form-urlencoded" https://<IoTS_IP>:8243/token

Anyway if you are facing the same issue again and again please let us know the steps you have followed.

**Comment by alirezan74** [comment]
I use this command but shown below result:
`
<html><head><title>Apache Tomcat/7.0.77 - Error report</title><style></style> </head><body><h1>HTTP Status 500 - 1</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>1</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>java.lang.ArrayIndexOutOfBoundsException: 1
        org.apache.cxf.transport.http.AbstractHTTPDestination.getAuthorizationPolicyFromMessage(AbstractHTTPDestination.java:163)
        org.apache.cxf.transport.http.AbstractHTTPDestination.setupMessage(AbstractHTTPDestination.java:372)
        org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:234)
        org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)
        org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)
        org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)
        org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)
        org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)
        org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:209)
        javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)
        org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        org.wso2.carbon.ui.filters.cache.ContentTypeBasedCachePreventionFilter.doFilter(ContentTypeBasedCachePreventionFilter.java:53)
        org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:124)
</pre></p><p><b>note</b> <u>The full stack trace of the root cause is available in the Apache Tomcat/7.0.77 logs.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.77</h3></body></html>`

**Comment by charithag** [comment]
Could you please share the cURL command you have used?

**Comment by charithag** [comment]
I'm closing this issue as we haven't heard back from you with additional details and can not reproduce from our end. Please feel free to reopen this issue if you are still facing this.
