### ISSUE TITLE
Regression according to previous version of WSO2 iot 3.1.0-UPDATE8

### ISSUE THREAD

**Issue by Nfoudikue** [wso2/product-iots#1512]
Wso2 IoT 3.1.0-Update8 does'nt has geofence alert exit and in zone in, full and custome geo alert history in device management console. 
![geofencealertmissingdevicemgt](https://user-images.githubusercontent.com/24441895/33572116-49b8fbb2-d932-11e7-92b3-95a0fa5e1ed6.jpg)

Bellow  is what we had in older version. Ours users still need it.

![geofencealertinolderdevicemgt](https://user-images.githubusercontent.com/24441895/33572936-b8e0aec0-d934-11e7-8251-c9372a0e1350.jpg)

Please how can we do to have geofence alert with all features plus the current one in Update8?

**Comment by charithag** [comment]
This is not reproducible with IoTS 3.1.0-Update8. Hence closing the issue. Please see attached screenshot.

![device-details-page](https://user-images.githubusercontent.com/3184302/33869096-0ce22b68-df2d-11e7-9953-315f5d16681c.png)

**Comment by Nfoudikue** [comment]
Indeed. A fresh installation solved the issue.
