### ISSUE TITLE
Shared device group is not visible

### ISSUE THREAD

**Issue by charithag** [wso2/product-iots#1529]
**Description:**
Once device group is shared with user A, by user B, the group is not visible to User A.

**Affected Product Version:**
3.1.0-Update8

**OS, DB, other environment details and versions:**    
Fedora 23 (x64), MySQL 5.6, JDK 1.8

**Steps to reproduce:**
1. Register new user with username 'user1'
2. Login in as Admin
3. Create role with name 'test' and assign devicemgt permissions except any-device.
4. Assign 'test' role to 'user1'
5. Create device group with name 'Group1'
6. Assign device to the Group1
7. Share Group1 with 'user1'
8. Login in as 'user1' and navigate to device groups.

*Expected:* Device group with name 'Group1' under 'user1's device groups.
*Actual:* Showing button to create new device group

**Comment by milanperera** [comment]
I have tested the same scenario as you mentioned in the following environment and it works as expected without any issues.

Product version:
3.1.1-SNAPSHOT

Environment details:
Mac OSX 10.1.3.2, MySQL 5.7
