### ISSUE TITLE
[iOS] Device vitals are not getting updated

### ISSUE THREAD

**Issue by milanperera** [wso2/product-iots#1533]
**Description:**
iOS device vitals are not getting updated after the initial enrolment. At the time of the enrolment, device publishes its initial vitals and then after, it will not get changed.

**Affected Product Version:**
IoT-3.1.0

**OS, DB, other environment details and versions:**
Mac OSX 10.13.2
MySQL 5.7

**Steps to reproduce:**
Enrol an iOS device and wait for few minutes until vital are changed from the device.
Then check the device details page.

**Comment by inoshperera** [comment]
This is an OS bug in iOS 11.x, and the device seems to be sending updated info only after a reboot. However following is being fixed, https://github.com/wso2/product-iots/issues/1605
