### ISSUE TITLE
WSO2 EMM 2.2.0 Wipe Data and Reboot operations doesn't work with androids devices (was ESBJAVA-5252)

### ISSUE THREAD

**Issue by isudana** [wso2/product-iots#1534]
**Description:**
Issue is originally reported in ESBJAVA-5252

Following is the content in the above jira,

Hello,
I have a problem with WSO2 EMM 2.2.0.
When I want to proceed to Wipe data operation or system reboot, It tells me it's done but nothing happens on my android devices.
Please help me, it's an important thing to my company.
Thank you for your understanding.
Regards.

Reporter:
Emilien Masson
E.MASSON@europetechnologies.com

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EMM 2.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
![wipeproblem](https://user-images.githubusercontent.com/748819/34033114-f7ebbe44-e19e-11e7-968d-0b3c85652007.png)

**Related Issues:**
https://wso2.org/jira/browse/ESBJAVA-5252

**Comment by ruwany** [comment]
Please try the latest version of EMM (now called IoT Server 3.1.0), this issue has now been addressed.
