### ISSUE TITLE
Problem with history and speed in  geofence WSO2IOT3.1.0.0-Update8

### ISSUE THREAD

**Issue by Nfoudikue** [wso2/product-iots#1547]
Hi,
Nothing appear when we seize the date for Full History in geofence.
OS: Centos 6.7 and 7.4, 64 bit, DB:H2base
![image](https://user-images.githubusercontent.com/24441895/34153062-0643f06e-e4b1-11e7-8604-5633750ffe2b.png)

Even when we  do it manually, we have a windows asking to seize start and end date.
![image](https://user-images.githubusercontent.com/24441895/34153248-b1ec4a60-e4b1-11e7-80a0-16de00d408e8.png)

When we set speed alert, is impossible to save the data.
![image](https://user-images.githubusercontent.com/24441895/34153370-1499bbb6-e4b2-11e7-9a29-4a78d665cdee.png)

Regards

**Comment by lasanthaDLPDS** [comment]
This issue is reproduced in IoTS 3.1.0 update9.
