### ISSUE TITLE
Error in documentation for Monitoring Devices Using Location Based Services

### ISSUE THREAD

**Issue by vasvlad** [wso2/product-iots#1557]
**Description:**
According to the article
https://docs.wso2.com/display/IoTS320/Monitoring+Devices+Using+Location+Based+Services#MonitoringDevicesUsingLocationBasedServices-Settingupgeofencing
we need  to change properties under the "GeoLocationConfiguration" tag to true in file cdm-config.xml
But I couldn't find this property.
Seem like  this property now is "OperationAnalyticsConfiguration"
Also I saw description of this problem here: https://stackoverflow.com/questions/47572498/geofence-alert-and-remote-feature
**Affected Product Version:**
wso2iot-3.1.0-UPDATE5 and later

**Comment by charithag** [comment]
Hi @vasvlad,

We have updated the documentation accordingly. Thanks for the contribution.
