### ISSUE TITLE
Geo fencing feature should support device groups

### ISSUE THREAD

**Issue by madawas** [wso2/product-iots#1567]
**Description:**
In the latest release, the IOT server only supports adding geofences and generating alerts for one device at a time. This feature should be extended to provide support to add geofence and track groups of devices.

**Affected Product Version:**
wso2iot-3.1.0 GA (wum updates), wso2iot-3.1.0-UPDATE9

**Comment by Kamidu** [comment]
The same issue is addressed on https://github.com/wso2/product-iots/issues/986
