### ISSUE TITLE
Add Tenancy for agent download

### ISSUE THREAD

**Issue by ruwany** [wso2/product-iots#1573]
**Description:**
No tenancy in the way the agents are stored or downloaded

It should be possible to have tenantwise agents, for each device-type.

E.g. : Specific android agent for TenantX, different from agent of TenantY

**Comment by rasika** [comment]
You can have tenant based android agents APKs as below;

1. Suppose your tenant name(aka. tenant-domain) is "abc.com"
2. Copy and paste unit named `cdmf.unit.device.type.android.type-view` as `abc.com.cdmf.unit.device.type.android.type-view` inside `<IOT_HOME>/repository/deployment/server/jaggeryapps/devicemgt/app/units` folder.
3. Add your all customizations into `abc.com.cdmf.unit.device.type.android.type-view`.
4. Above unit will be picked by devicemgt app when you are logged as the abc.com tenant user.

**If you only need to change the android agent download url** per each tenant and all other content is same; you can simply extend the existing unit `cdmf.unit.device.type.android.type-view` with the following **optional** steps.

5. If you copy pasted the content from the unit `cdmf.unit.device.type.android.type-view` file; remove all files inside `abc.com.cdmf.unit.device.type.android.type-view` folder named `type-view.hbs, type-view.js, type-view.json`
6. Create a new file named `type-view.js` inside the `abc.com.cdmf.unit.device.type.android.type-view` and add the following content;

```
function onRequest(context) {
    var viewModel = {};
    var devicemgtProps = require("/app/modules/conf-reader/main.js")["conf"];
    var isCloud = devicemgtProps["isCloud"];
    viewModel["isVirtual"] = request.getParameter("type") == 'virtual';
    viewModel["isCloud"] = isCloud;
    viewModel["hostName"] = devicemgtProps["httpsURL"];
    viewModel["enrollmentURL"] = "http://abc.com";
    return viewModel;
}
```

7. Create a new file named "type-view.json" inside the "abc.com.cdmf.unit.device.type.android.type-view" and add the following content;

```
{
    "version": "1.0.0",
    "extends": "cdmf.unit.device.type.android.type-view"
}
```
