### ISSUE TITLE
App publisher redirects to localhost instead of remote IP address of machine

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [wso2/product-iots#1595]
Hello.

I have hosted 3.1.0-UPDATE9 release in my remote virtual machine with static IP addres.

I have configured it by following this guide

https://docs.wso2.com/display/IoTS300/Configuring+WSO2+IoT+Server+with+the+IP+or+Hostname

After that is successfully opens **device management and carbon dashboards**

However, when I try to open `https://my.ip.address:9443/publisher` it redirects to localhost.

Where I can configure this in order to make application store in `https://my.ip.address:9443/publisher` to redirect to correct IP address instead of localhost.

**Comment by SuperMasterBlasterLaser** [comment]
I have found that there is `./change-ip.sh` script that will do all work for me.

**Comment by samat21** [comment]
Can you share the script?

**Comment by ajayparmar311** [comment]
where we will find ./change-ip.sh
