### ISSUE TITLE
Unable to view Virtual Firealarm to enroll a device of the type Virtual Fire-alarm

### ISSUE THREAD

**Issue by shubhirastogi** [wso2/product-iots#1603]
**Description:**
Unable to view Virtual Firealarm to enroll a device of the type Virtual Fire-alarm.
We have newly installed  WSO2 IOT Server v3.1.0 on Windows 10 platform. We wish to try out virtual fire alarm device. However we cannot see that as an option, instead we only see a virtual device of type android to try. Could you please help us with this issue.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
3.1.0
**OS, DB, other environment details and versions:**    
Windows 10
**Steps to reproduce:**
Installed the WSO2 IOTS.
Logged in device management console.
Click Enroll New Device. ( You only see virtual device of type - Android) Virtual Fire-Alarm device type is not displayed.

**Related Issues:**

**Comment by rasika** [comment]
Hi @shubhirastogi;

Thanks for trying out WSO2 IoT Server. Virtual Fire Alarm is not packaged with the default setup. As per the docs https://docs.wso2.com/display/IoTS310/Enterprise+IoT+solution; You need to navigate to the WSO2 IoT Server pack's samples directory and run the device-plugins-deployer.xml file with the following commands;

```
cd <IOTS_HOME>/samples
mvn clean install -f device-plugins-deployer.xml
```

Please feel free to re-open the ticket if the above suggestion doesn't work.

**Comment by shubhirastogi** [comment]
Thanks Rasika. Yes we noticed that earlier and were able to execute the virtual firealarm sample after deploying the xml.
