### ISSUE TITLE
Add a clustering guide documentation for IoTS 

### ISSUE THREAD

**Issue by lasanthaDLPDS** [wso2/product-iots#1616]
**Description:**
It is required to add the IoTS clustering documentation into WSO2 clustering guide [1]. 

[1] - https://docs.wso2.com/display/CLUSTER44x/Configuring+Clustering+for+Specific+Products
 
**Suggested Labels:**
Documentation, Improvement

**Affected Product Version:**
IoTS 3.0.0, IoTS 3.1.0

**Comment by madawas** [comment]
We should probably move this documentation to the above space.

https://docs.wso2.com/display/IoTS310/Clustering+WSO2+IoT+Server

**Comment by rasika** [comment]
This is fixed now. https://docs.wso2.com/display/CLUSTER44x/Clustering+IoT+Server
