### ISSUE TITLE
Work profile can't be created because you've reached the maximum number of users on your device.

### ISSUE THREAD

**Issue by lashanfaliq95** [wso2/product-iots#1617]
When a work profile is created with an already existing work profile it asks to delete it and create a new one. But when you keep repeating it then we get the following error.
![image](https://user-images.githubusercontent.com/20104168/35258482-d9973cb6-0025-11e8-9111-2613c95157ce.png)

To solve this we need to go to accounts and remove the workprofile. Then we can add a workprofile again.
![image](https://user-images.githubusercontent.com/20104168/35258486-e499d2fe-0025-11e8-818e-84fb434c0b36.png)

**Comment by rasika** [comment]
Ack. We'll add this into the docs in https://docs.wso2.com/display/IoTS320/Setting+Up+the+Work+Profile

**Comment by shavidissa** [comment]
Thank you! Updated docs with this info in the "before you begin" section.

[1] https://docs.wso2.com/display/IOTS320/Setting+Up+the+Work+Profile
Updated in the 310, 320, and EMM330 docs.
