### ISSUE TITLE
Bug when selecting all in policy management window of IOT 3.1.0/updatell

### ISSUE THREAD

**Issue by lashanfaliq95** [wso2/product-iots#1629]
**Description:**
If you click select and then chose a policy you get the following options.

![image](https://user-images.githubusercontent.com/20104168/35318483-99ee2106-0101-11e8-8f0f-581bb9b18db9.png)

But if you click select and then select all those buttons don’t appear initially. They appear when you click on a policy once after choosing select all.
![image](https://user-images.githubusercontent.com/20104168/35318495-a46bcafc-0101-11e8-871e-4bd820bdf2a8.png)
![image](https://user-images.githubusercontent.com/20104168/35318498-a864c9a6-0101-11e8-92f5-d49846a36408.png)

**Suggested Labels:**
Type/Bug

**Comment by rasika** [comment]
This issue also exists in Devices, Users and in Roles that selection tabs. Roles page also doesn't need "Select" and "Select All" options as there is no group actions available.
