### ISSUE TITLE
When the licence text is updated from a tenant, it overrides the licence text of other tenants

### ISSUE THREAD

**Issue by madawas** [wso2/product-iots#1682]
**Description:**
When a licence text is changed from the device management console in the platform configuration section, the text overrides the licence text of the other tenants as well.

**Affected Product Version:**
3.1.0 WUM updated, 3.2.0

**OS, DB, other environment details and versions:**
Ubuntu 16.04, H2, JDK 1.8.0_161

**Steps to reproduce:**
Create two tenants,
Update the licence text of one tenant.
Check the licence text of the other tenant.

**Comment by lasanthaDLPDS** [comment]
This is fixed. Fixes will be included in the next IoTS release.
