### ISSUE TITLE
Device Owner Silent App Install

### ISSUE THREAD

**Issue by omerstack** [wso2/product-iots#1705]
**Description:**
Almost all my device owner operations are working. However, the user is asking if I want to install the application silently. In other words, the backplane can not perform the application installation. He wants user permission. It is not throwing in any error. Could this be a bug?

**Affected Product Version:**
Wso2 3.2.0 & Agent 3.1.30

**Comment by TrueSkrillor** [comment]
This is not a bug, it is currently not implemented in the agent. I've created a pull request in order to allow silent app installation/uninstallation if the agent is device owner:
https://github.com/wso2/cdmf-agent-android/pull/165

**Comment by charithag** [comment]
This has been implemented with PR https://github.com/wso2/cdmf-agent-android/pull/165

**Comment by omercelikceng** [comment]
Ub
Uuub7w7ttuuuuuuuuuUuub7w7ttuuuuuuuuuutttttb5it
17 Nis 2018 Sal 11:01 tarihinde Charitha Goonetilleke <
notifications@github.com> şunu yazdı:
