### ISSUE TITLE
iOS configurator doesn't create when installing the latest iOS feature.

### ISSUE THREAD

**Issue by lasanthaDLPDS** [wso2/product-iots#1708]
**Description:**
After executing the following command it doesn't create the <IOTS_HOME>/ios-configurator directory.
mvn clean install -f ios-feature-deployer.xml

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**
3.2.0 RC

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**

- Follow the iOS feature installing procedure by referring the [documentation](https://docs.wso2.com/display/IoTS310/Enrolling+With+the+iOS+Agent#EnrollingWiththeiOSAgent-ConfiguringiOSsupportinWSO2IoTServer).
- Get the latest iOS feature by building the master branch.
- Navigate to the ios-feature-deployer folder and execute the following command to install the iOS feature.
- **mvn clean install -f ios-feature-deployer.xml**
- Once the ios-feature-deployer script has finished running, can't see the **ios-configurator** directory in the <IOTS_HOME> directory.

**Related Issues:**
N/A

**Comment by rasika** [comment]
Fixed with https://github.com/wso2/carbon-devicemgt-proprietary-plugins/commit/6f0e31a92be4d223b966d2bbf1484621b7d377b5
