### ISSUE TITLE
WSO2 profile deployment order incorrect in docs

### ISSUE THREAD

**Issue by ctienshi** [wso2/product-iots#1746]
**Description:**
As mentioned in [1], the IoT profile deployment order is incorrect. While enabling analytics and running the IoT Server before deploying the Analytics server gives and error as follows.

ERROR {org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker} -  Error while trying to connect to ssl://localhost:7712 {org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker}

[1] https://docs.wso2.com/display/IoTS310/Running+the+Product

**Steps to reproduce:**
Enable Analytics in Api-manager.xml
Run iot-server
Run analytics server

**Comment by rasika** [comment]
Thanks for reporting this issue. FYI, actually, this error is harmless. Databridge connection pool will eventually succeed and connect to the port 7712 when it is available. Have you experienced any issues with the functionality of the product when you startup the product as mentioned order?

**Comment by shavidissa** [comment]
Closing as the steps work as documented. You don't need to do any additional configurations, you only need to start the analytics profile.
