### ISSUE TITLE
Android 8.1 (API level 27) Oreo support?

### ISSUE THREAD

**Issue by daviddean99** [wso2/product-iots#1753]
The WSO2 documentation says:

"WSO2 IoT Server supports devices on Android version 4.2.x to 7.0 (Android Jelly Beans to Nougat)."

I have some Android 8.1 Oreo (API 27) devices which I need to deploy the MDM in COSU mode.

I've tried deploying the agent and service which run, but there are lots of management APIs which are deprecated and no longer work. There is probably quite a bit of porting which needs to be done.

Before I started working on this myself I wanted to ask:

Are there any plans to support Android 8.1?  Is anybody already working on this?

Thanks.

**Comment by rasika** [comment]
We have currently tested all functionalities only for the Android version 4.2.x to 7.0 (Android Jelly Beans to Nougat). With that being said; Yes, we have already started working on Android 8.1 Oreo. We'll provide support for the Android 8.1 Oreo (API 27) in the near future.

**Comment by nidico** [comment]
Is there any update? The docs still state *up to 7.0*.

@stale bot, the automatic closure of issues is not really useful, it encourages some sort of throwaway issue management instead of collaborative wiki-style caretaking.

**Comment by nidico** [comment]
@stale: cool :)

**Comment by rasika** [comment]
@nidico Apology for the late reply. Looping @charithag @milanperera. We'll get back to you on this soon.

**Comment by renegyetvai** [comment]
@rasika Is there any update still coming and around which time? It's almost April 2019 and there is no way to use Android 8 or 9 as COSU Device. My Company would really need this feature! Appreciate to hear from you soon!

**Comment by rasika** [comment]
@geethkokila @charithag @milanperera  @inoshperera Do you have any update on this?

**Comment by Noreu** [comment]
Bump, any update ?
Thanks

**Comment by milanperera** [comment]
Support for API 27 is being provided by https://gitlab.com/entgra/android-agent.
