### ISSUE TITLE
Wso2 İot - Change password on admin panel vs change-superadmin-credentials.sh on command

### ISSUE THREAD

**Issue by omerstack** [wso2/product-iots#1755]
**Description:**
What is the difference between changing the password on the admin panel and changing the password on the command?

If I use the command **change-superadmin-credentials.sh** I do not get an error. But changing the password from the interface throws an error. I want to be able to change the password through the interface.

different change-superadmin-credentials.sh command vs photo ? 
**Error : [2018-03-09 17:23:42,841] [IoT-Core] ERROR - {org.wso2.carbon.apimgt.rest.api.util.interceptors.auth.BasicAuthenticationInterceptor} Authentication failed. Please check your username/password
[2018-03-09 17:23:42,842] [IoT-Core] ERROR - {org.wso2.carbon.apimgt.webapp.publisher.APIPublisherStartupHandler} failed to publish api.**

![screenshot from 2018-03-09 17 10 47](https://user-images.githubusercontent.com/36436955/37211483-1a8b78d0-23bd-11e8-86da-ff35fe86c4f6.png)

**Affected Product Version:**
Wso2 iot 3.2.0 Rc4 - Agent 3.1.31

**Comment by rasika** [comment]
@omerstack When you change the password from the UI console; it simply changes the login password of the user. Next time you would be able to login with the new password. We recommend this feature for the all other users **except** for the super admin.

But when you change the super admin password; you need to change several other configurations in the product. These steps are can be found in https://docs.wso2.com/display/IOTS320/Changing+the+Super+Administrator+Username+and+Password.

**Comment by omerstack** [comment]
Thank you very much for the information you provide.  It was really useful. 
Can we just say that there can be only one super admin?
 Also, does the server need to be restarted after the super admin password is changed?
Finally, I want to change the super admin password from the ui console. Is there a way we can do it by implementing it?

**Comment by rasika** [comment]
Hi @omerstack yes, there's only one super admin and you need a server restart after a change of super admin credentials. I am afraid that this is feasible with the current pack since there are some manual configuration changes need to be done when you change super admin credentials. 

Still, when you create a tenant; tenant administrator's password can be changed from the carbon ui console.
