### ISSUE TITLE
how to deal with video streaming

### ISSUE THREAD

**Issue by micuentadecasa** [wso2/product-iots#1761]
Hi, I want to use WSO2 to make a centralized video portal, I mean, I want to send to the ESB the list of CCTV cameras from different places, only location and url, so I can present that information in a map, so is a map with the location of the cameras, thats simple, but now I want that if anyone click on the camera icon they can see the streaming from the camera, so:

is it possible to transfer video through WSO2 IOT?
how can be it , via RTMP?

**Comment by rasika** [comment]
RTMP is not supported OOB through the IoT Server. Same as XMPP you could use an external server to handle the RTMP communication and write an inbound/outbound adapters for the IoT Server(Have a look in [docs](https://docs.wso2.com/display/IoTS330/Writing+Transport+Extensions)).
