### ISSUE TITLE
Wso2 İot Server - Docker İp Problem 

### ISSUE THREAD

**Issue by omerstack** [wso2/product-iots#1763]
**Description:**
I have a docker in my computer. And I can not remove the docker.  **My ip address https://192.168.1.3** When I run Server:
**Broker.sh :**        Mgt Console URL  : https://172.17.0.1:9446/carbon/
**İot-Server.sh :**   Mgt Console URL  : https://192.168.1.3:9443/carbon/   ------ IoT Server Default Context : https://192.168.1.3:9443/devicemgt
**Analytics.sh :**     Mgt Console URL  : https://172.17.0.1:9445/carbon/

My ip address https://192.168.1.3
When I run the broker and analytics.sh it works via docker ip.(https://172.17.0.1:9446)
How do I solve this problem without lifting the docker?

**Affected Product Version:**
Wso2 iot Server 3.2.0 RC4 - Agent v3.1.31

**OS, DB, other environment details and versions:**
Ubuntu 14.04.1 LTS / Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

**Comment by madawas** [comment]
The server should still be accessible through 192.168.1.3. Are you facing any issues when accessing the server through the IP 192.168.1.3?

**Comment by rasika** [comment]
@omerstack Running the server with localhost is the bare minimum configuration for the WSO2 IoT Server. When multiple network interfaces available, server tries to bind into first available IP. But this may break some functionalities of the server such as inter-component communication using JWT tokens(When the certificate's hostname and HTTP client's sender's hostname differs).

If it is difficult to remove docker virtual network interface, you need to setup IP address of the server by running the `change-ip.sh` the script from the $IOT_HOME/scripts folder.
