### ISSUE TITLE
Steps on Installing WSO2 IoT Server using Docker Composer

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#1797]
**Description:**
Suggesting the following:

- Have the following heading when starting the steps : **Installing WSO2 IoT Server using the Docker Composer**

- _Current_: Install Docker by following Docker installation instructions.
_Suggested_: Follow the Docker installation instructions to install Docker.

- _Current_: Login to WSO2 Docker registry by executing following Docker command.
_Suggested_: Log in to the WSO2 Docker registry by executing the following Docker command.
When prompted, enter the username and password of your free trial account.

- _Current_: Clone WSO2 IoT Server Docker git repository and switch to the relevant resource directory by executing following commands.
_Suggested_: Clone the WSO2 IoT Server Docker git repository and switch to the relevant resource directory by executing the following commands.

- _Current_: Execute following Docker command to start the selected deployment.
_Suggested_: Execute the following Docker command to deploy the repository you just downloaded.

- _Current_: Once the deployment is started, try to access the web UI via following URLs on your favorite web browser.
_Suggested_: Once WSO2 IoT Server is successfully deployed on docker, access the following URLs on your favorite web browser using the following credentials:
Username: admin
Password: admin
(Remove this part after the command: Access the servers using following credentials. Username: admin. Password: admin)

**Affected Product Version:**
3.2.0 3.3.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

**Comment by VimukthiPerera** [comment]
@shavidissa could you please create an issue in https://github.com/wso2/docker-iot/issues and close this one? Thanks.

**Comment by shavidissa** [comment]
Closing this as a new one was created [1].

[1] https://github.com/wso2/docker-iot/issues/6
