### ISSUE TITLE
Wso2 İot Server - Why are the WSDL files publicly accessible?

### ISSUE THREAD

**Issue by omercelikceng** [wso2/product-iots#1805]
**Description:**
Accessing **WSDL** files is causing security vulnerabilities.  Can we take security precautions for web services located in **/services** directory?
Or could you suggest me a way? 
Or what kind of problems arise if I delete these files?

**Screenshots :** 
![untitled](https://user-images.githubusercontent.com/34758411/38090364-fe430144-336a-11e8-832f-e09ee07fdf0c.png)

![untitled3](https://user-images.githubusercontent.com/34758411/38090475-68f6753e-336b-11e8-8e42-b2ba0fdcd83f.png)

**Affected Product Version:**
Wso2 iot Server 3.2.0 RC4 - Agent v3.1.31

**OS, DB, other environment details and versions:**
Ubuntu 14.04.1 LTS / Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

**Comment by rasika** [comment]
@omercelikceng AFAIK there's no security vulnerability in exposing WSDLs as those are meant to be publicly accessible for any client to refer and built stubs upon them. You can safely remove workflow WSDL file but the version endpoint has no physical file and it is auto-generated. Maybe you can use a front-end LB / Firewall rules to hide them.

**Comment by omerstack** [comment]
Hello , I studied the project in detail. In Axis2.xml files we can turn off wsdl by making the **exposeservicemetadata** variable false.I wanted to tell you for information.
