### ISSUE TITLE
Routing IoT Server HTTP/HTTPS calls through a Proxy server fails

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#1806]
**Description:**
In an IoT server cluster setup if we configure the worker or manager node calls to be routed through a proxy the communication fails. 

It appears that certain HTTP calls from IoT Server's worker node to the gateway is bypassing the configured proxy. This could be due to the HTTP client that we are using. We use library call Feign in IoT server. Feign is a Java to HTTP client binder. 

**Affected Product Version:**
IoTS v3.1.0, v3.2.0

**OS, DB, other environment details and versions:**   
IoT Server cluster step up 

**Steps to reproduce:**
Create an IoT Server cluster setup
Configure Worker, Manager and Gateway calls to be routed through a proxy server

**Comment by madawas** [comment]
Closing as commit wso2/carbon-device-mgt#1244 fixes the issue.
