### ISSUE TITLE
Wso2 iot Server - How can we make a change in the project?

### ISSUE THREAD

**Issue by omerstack** [wso2/product-iots#1807]
**Description:**
I want to put an authentication mechanism to project. But I do not know what to do. How can I build the project? I can not make changes to this code. Because it's made into a bundle.
Can you help me ?

**Comment by madawas** [comment]
@omerstack you can find information about working with the source code in the following documentation.
https://docs.wso2.com/display/IOTS320/Working+with+the+Source+Code

Please note that the main component repositories that the IoT server is dependent on are,
https://github.com/wso2/carbon-device-mgt
https://github.com/wso2/carbon-device-mgt-plugins
