### ISSUE TITLE
Tenant Management SOAP API: Authentication failure

### ISSUE THREAD

**Issue by kamranIoTDeveloper** [wso2/product-iots#1844]
**Description:**

Trying to manage tenant through SOAP API, but getting error.

**Error:**

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
   <soapenv:Body>
      <soapenv:Fault xmlns:axis2ns2="http://schemas.xmlsoap.org/soap/envelope/">
         <faultcode>axis2ns2:50977</faultcode><faultstring>Authentication failure</faultstring><detail/>
      </soapenv:Fault>
   </soapenv:Body>
</soapenv:Envelope>

**Comment by kamranIoTDeveloper** [comment]
![image](https://user-images.githubusercontent.com/25499251/42279262-a9eaa898-7fb6-11e8-85f1-be1038d4f5b2.png)

**Comment by madawas** [comment]
@kamran000 can you remove the Domain parameter and try again?

**Comment by kamranIoTDeveloper** [comment]
@madawas Thanks, issue resolved by following this article: https://www.dilan.me/2016/03/01/how-to-call-wso2-admin-service-using-curl/
