### ISSUE TITLE
[AppManager] Create a new application and create a new version via API calls fails

### ISSUE THREAD

**Issue by saadsahibjan** [wso2/product-iots#1912]
**Description**
While trying to publish a new mobile application via app publisher API following error was thrown;
[IoT-Core] ERROR - {org.wso2.carbon.governance.api.common.GovernanceArtifactManager} Failed to add artifact: artifact id: 98a41ffb-74a7-4b1c-b0c5-d244a33712c7. The path '/_system/governance/mobileapps/admin@wso2.com/android/timetable/2.0.0' contains one or more illegal characters (~!@#;%^*()+={}|\<>"',)

While trying to create a new version of an existing application via app publisher API following error was thrown; [2019-04-11 17:33:42,398] [IoT-Core] ERROR - {org.wso2.carbon.appmgt.impl.DefaultAppRepository} Error occurred while creating the mobile application : zxc
org.wso2.carbon.governance.api.exception.GovernanceException: Type is a required field, Please provide a value for this parameter.

**Affected Product Version**
EMM 2.2.0 IoT Server 3.x.x

**Steps to reproduce**
Enable using email address as username and create a new application via an API call to reproduce the create application error.
Call create a new version API call to reproduce the create a new version of an application error.

**Comment by lasanthaDLPDS** [comment]
This is fixed in the latest version of the IoT server.
