### ISSUE TITLE
[AppManager] Public apps are installed as Enterprise apps

### ISSUE THREAD

**Issue by saadsahibjan** [wso2/product-iots#1918]
Description
While trying to install a public app, the app is being installed as enterprise app.

Affected Product Version
EMM 2.2.0 IoT Server 3.x.x

Steps to reproduce
Install a public app and the app would have been installed as an enterprise app

**Comment by lasanthaDLPDS** [comment]
This is fixed in WUM updated IoT server product and the IoTS 3.6.0 release.
