### ISSUE TITLE
Mutual SSL fails when CN is not available at the end of the certificate subject

### ISSUE THREAD

**Issue by milanperera** [wso2/product-iots#1930]
**Description:**
Mutual SSL fails when CN is not available at the end of the certificate subject.
Apart from that, when verifying the certificate, it invokes an additional HTTP call to retrieve an access token which is an unnecessary call and can be removed if it uses the basic authentication.

**Affected Product Version:**
3.3.1

**Steps to reproduce:**
Configure the environment to support mutual SSL authentication

**Comment by lasanthaDLPDS** [comment]
This is fixed in the latest release of the IoTS.
