### ISSUE TITLE
Create a CAR file to Manage Event Publishing - Android Device Type

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#309]
In the current implementation, we ask the users to create a stream and receiver to manage the event publishing [1]. But as mentioned by Ayyoob all the other device types have CAR files that do this task.

Therefore, can we implement the same for the Android device type too?

[1] https://docs.wso2.com/display/IoTS310/Managing+Event+Publishing+with+WSO2+Data+Analytics+Server - 3rd step

**Comment by sinthuja** [comment]
@sameerawickramasekara will check on this.

**Comment by sinthuja** [comment]
This document is mainly focusing on how to configure with external IoT Analytics Server, and hence let's change the title to address that. And we don't need the step3 at all in the doc. We have only the location based geo analytics with an android agent, and the relavant car file is already deployed in the IoT analtyics server.

**Comment by shavidissa** [comment]
Thank you! Updated docs as discussed.
