### ISSUE TITLE
http://localhost:9446/carbon can't access

### ISSUE THREAD

**Issue by yujie123jw** [wso2/product-iots#316]
Hi everyone!
I installed  wso2 iot  ,but http://localhost:9446/carbon can't access
it is  display "403 Forbidden ".

**Comment by yujie123jw** [comment]
OS  IS    WINDOW 2007  X64.

**Comment by ayyoob** [comment]
We have blocked the broker UI intentionally, since there aren't any UI to view mqtt topics.

**Comment by yujie123jw** [comment]
why??

**Comment by ayyoob** [comment]
There were few security issues that we found on the carbon console and since there weren't any valid use cases to enable the UI, we disabled it. Is there any reason why you wanted to access the node ?

**Comment by yujie123jw** [comment]
i want to test broker cluster.Multi-connect situation.

**Comment by ayyoob** [comment]
To enable cluster you have to follow the following docs https://docs.wso2.com/display/CLUSTER44x/Clustering+MB+3.0.0

All the configurations are file based so I think we won't need the UI functionalities for this.

**Comment by geethkokila** [comment]
If you any more question, please reopen.
