### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found) 

### ISSUE THREAD

**Issue by tony358** [wso2/product-iots#318]
Hello,
     I use the wso2iot-3.0.0\samples\connectedcup example to install the device type plugin。Starting Connected Cup by following the steps given below documentation：
    Https://docs.wso2.com/display/IoTS300/Device+Manufacturer+Guide

   After installation, access https://localhost:9443/devicemgt。
   
![image](https://cloud.githubusercontent.com/assets/26424684/23932923/f355c746-0975-11e7-95f2-2b8fb06564de.png)
   Error creating a device instance：
 
![image](https://cloud.githubusercontent.com/assets/26424684/23933036/9f2ff410-0976-11e7-9a4e-2361881b4d00.png)
  
  Wrong information：
    [HTTP/1.1 404 Not Found 89ms]  https://localhost:9443/devicemgt/api/invoker/execute/

**Comment by ayyoob** [comment]
What is OS that you are trying this with ?

**Comment by sinthuja** [comment]
This issue doesn't happen anymore in IoT server 3.1.0. Please try with the latest release.
