### ISSUE TITLE
Device Mgt info dashboard operations doesn't work and all icons are the same

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#330]
In M2 release, device-mgt info dashboard message operation doesn't display the text box to insert the message and all the operation icons are the same.

![operations](https://cloud.githubusercontent.com/assets/7391925/24400788/51bc65d4-13cf-11e7-9d23-1662b579a8b8.png)

![message](https://cloud.githubusercontent.com/assets/7391925/24400748/2edae82e-13cf-11e7-98ab-24ebba4941f1.png)

**Comment by amalhub** [comment]
Device status also missing.

**Comment by geethkokila** [comment]
This is fixed in latest IoT server master branch
