### ISSUE TITLE
how to use WSO2 IoT Server 3.1.0-M2

### ISSUE THREAD

**Issue by eggeggss** [wso2/product-iots#331]
hi, how to start at M2 , I can not find core/bin/wso2server.bat

**Comment by eggeggss** [comment]
when i run bin\iot-server.bat , all file was deleted..

**Comment by sinthuja** [comment]
We have verified this in Linux, and Mac systems, will check on windows machine and get back to you soon.

**Comment by sinthuja** [comment]
The fix for the windows server bat file is added, and will be available in the next milestone.

**Comment by eggeggss** [comment]
hi Sinthuja, that's great  , it's work, thanks ! but I still cannot open devicemg,it redirect to about:blank at windows 7 , do you have any advice?

**Comment by harshanL** [comment]
@eggeggss : Could you please get the latest IoT server 3.1.0 and see if this issue still occurs?
