### ISSUE TITLE
Device status update has to be implemented as a task

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#337]
In the current implementation device status update happens using the policy monitoring, in policy monitoring cycle (as configured) if the device is not active it will update the status as configured. We cannot expect every device has to have a policy. Therefore this needs to be handled from a separate task to update the device status.

**Comment by geethkokila** [comment]
@harshanL , Please comment and close

**Comment by harshanL** [comment]
This issue is already closed. Please refer [1].
[1]. https://github.com/wso2/product-iots/issues/518
