### ISSUE TITLE
CARBON_HOME

### ISSUE THREAD

**Issue by rddewan** [wso2/product-iots#355]
inside wso2iot folder there are  analytics,broker and core .. do i need to run this all 3 in same server or need to install in 3 different server as i am installing on  win server 2012 i can set CARBON_HOME to only  1 dir C:\wso2iot\broker 
so when i try to run 
 <IoTS_HOME>\broker\bin
.\wso2server.bat
cd <IoTS_HOME>\core\bin
.\wso2server.bat
cd <IoTS_HOME>/analytics/bin
./wso2server.sh

i can start only i server at a time please let me know what i am missing 
thank you

**Comment by guptaabhinav1512** [comment]
@rijudewan : I am getting error CARBON_HOME not or incorrectly set. How should I fix this?

**Comment by rddewan** [comment]
@guptaabhinav1512  : you i can run .. i notice you don't need to run broker for EMM . You just need to run  Core and Analytics  from bin folder directly .. i was able to lunch EMM  but after i change the default password its giving lot off error ... maybe its a bug

**Comment by guptaabhinav1512** [comment]
What all dependencies did you install before running it on Windows?

It won't run, just gives me CARBON_HOME not set or found error.

**Comment by sinthuja** [comment]
@Nirothipan will check this.

**Comment by Nirothipan** [comment]
Hi, When you run the scripts ( broker, core, analytics ) CARBON_HOME variable will be set automatically. This was an issue in 3.0.0 and it has been fixed in 3.1.0.

Thank you.

**Comment by sinthuja** [comment]
Thanks Nirothipan for verifying this issue and closing this issue based on that. Further we need to perform the integration testing on a windows machine as well to avoid such issues in future. As the current framework will support running the tests on windows, and with that the startups will be automatically verified, there is no new integration tests needed to be added and It's already available.
