### ISSUE TITLE
CARBON_HOME Issue

### ISSUE THREAD

**Issue by guptaabhinav1512** [wso2/product-iots#357]
I am using windows and have Installed JAVA. On running the .bat script, I am getting error CARBON_HOME not or incorrectly set. How should I fix this?

**Comment by sumedharubasinghe** [comment]
Hi,
Could you be more specific about the version of IoT Server your trying out?

**Comment by guptaabhinav1512** [comment]
@sumedharubasinghe : Hey I am using version 3.0.0.

**Comment by sinthuja** [comment]
@Nirothipan , will work on this.

**Comment by Nirothipan** [comment]
Hi, This issue has been fixed in 3.1.0.
It prevailed in 3.0.0 pack while starting analytics script.

**Comment by sinthuja** [comment]
Thanks Nirothipan for verifying this. I'm closing this issue as this is no longer exists in the latest distribution of WSO2 IoT v3.1.0.

**Comment by sinthuja** [comment]
We need to run the automation tests on windows as well to avoid such issues. The automation framework has already support for this, but we need to run this windows machine as well.
