### ISSUE TITLE
H2 console is not working

### ISSUE THREAD

**Issue by Megala21** [wso2/product-iots#368]
Enabled the H2-configuration in {IOT_HOME}/conf/carbon.xml with following,

```
        <H2DatabaseConfiguration>
		<property name="web" />
		<property name="webPort">8082</property>
		<property name="webAllowOthers" />
	</H2DatabaseConfiguration>

```

Cannot access the H2 database management console in localhost:8082

**Comment by milanperera** [comment]
@Megala21 : H2 web server is disabled by kernel team due to a security vulnerability [1].
Hence, in order to work with H2, you need to use a 3rd party client application.

[1] http://www.securityfocus.com/bid/58536/info

**Comment by h20lee** [comment]
Documentation should be updated to reflect this, such as https://docs.wso2.com/display/Carbon420/Configuring+carbon.xml.
