### ISSUE TITLE
Security issue - Content-Type Header Missing

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#375]
https://localhost:9443/devicemgt/api/data-tables/invoker?draw=1&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&filter=%7B%22null%22%3A%22%22%2C%22filter%22%3A%22%22%7D&offset=0&limit=10&url=%2Fapi%2Fdevice-mgt%2Fv1.0%2Fusers&_=1492413847739

**Comment by rasika** [comment]
Issue created on cdmf repo https://github.com/wso2/carbon-device-mgt/issues/703
