### ISSUE TITLE
-DosgiConsole option is not working with the analytics.sh script in the <Iot_Home>/bin 

### ISSUE THREAD

**Issue by Megala21** [wso2/product-iots#381]
This works fine if we start the analytics server from <iot_Home>/wso2/analytics/bin

**Comment by sinthuja** [comment]
Verified now with the latest IoT 3.1.1-SNAPSHOT pack as per 28 Aug 2017, and this issue is no longer there. I was able to start the analytics.sh with additional params such as  -DosgiConsole.

**Comment by sinthuja** [comment]
The automation test for passing with params can be verified when adding the automation test for -Dsetup with different databases. And hence we don't need a separate automation test to address specifically this issue.
