### ISSUE TITLE
Swagger docs shows validation error 

### ISSUE THREAD

**Issue by Megala21** [wso2/product-iots#390]
Please refer the docs at 
https://docs.wso2.com/display/IoTS300/swagger/?url=https://docs.wso2.com/display/IoTS300/swagger/apis/certificate-mgt.json and https://docs.wso2.com/display/IoTS300/swagger/?url=https://docs.wso2.com/display/IoTS300/swagger/apis/device-mgt.json

Please refer the screen-shot below,
![screenshot from 2017-04-28 10-11-18](https://cloud.githubusercontent.com/assets/4003116/25514497/13d9caa6-2bfb-11e7-82de-545bc2732f6b.png)

**Comment by shavidissa** [comment]
This is now fixed. Thank you!
https://docs.wso2.com/display/IoTS300/swagger/?url=https://docs.wso2.com/display/IoTS300/swagger/apis/certificate-mgt.json and https://docs.wso2.com/display/IoTS300/swagger/?url=https://docs.wso2.com/display/IoTS300/swagger/apis/device-mgt.json
