### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by joyhope** [wso2/product-iots#394]
I tried to build with iots project,  but meet this error.  How could solve the following problem?

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.930 s
[INFO] Finished at: 2017-04-30T20:08:21+08:00
[INFO] Final Memory: 47M/917M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wso2.maven:carbon-p2-plugin:1.5.4:p2-profile-gen (3-p2-profile-generation) on project wso2iot-core-p2-profile: P2 publisher return code was 1 -> [Help 1]
[ERROR]

**Comment by geethkokila** [comment]
Build is successful now, hence closing
