### ISSUE TITLE
Error 500 when logging into Device Management Console

### ISSUE THREAD

**Issue by alegomes** [wso2/product-iots#398]
* Download WSO2-IoT Server 3.0.0
* Unpack it
* Initialize broker, core and analytics profiles
  * cd <IoT_HOME>/broker/bin
    * ./wso2server.sh
  * cd <IoT_HOME>/core/bin
    * ./wso2server.sh
  * cd <IoT_HOME>/analytics/bin
    * ./wso2server.sh
* Access Device Management Console
  * https://localhost:9443/devicemgt
* Log into Device Management Console
  * admin:admin
* BOOM!
  * An Error Occurred! | HTTP Status : 500 | Unexpected token: <

As previously reported in https://wso2.org/jira/browse/IOTS-526

**Comment by amalhub** [comment]
Thanks for reporting!
Fixed in https://github.com/wso2/carbon-device-mgt/commit/b54bf3000f0baa81f444a51f0b39ae2b7e3bd616
