### ISSUE TITLE
Password Field seems to be incorrect

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#404]
The password field does not get auto-filled rather it gives username suggestions again.

Check the screenshot attached. 
![password_field](https://cloud.githubusercontent.com/assets/6646840/25701048/319c64da-30e8-11e7-9684-814e2b703c83.png)

**Comment by amalhub** [comment]
This was intentionally done to avoid password autocomplete due to Zap security scan high threat alert.
We have disabled the password autocomplete.

**Comment by chamaraanu** [comment]
Yet it is wrong. Whenever the password field is clicked upon, all the past usernames are given as suggestions. 

This might not be the correct fix to avoid password auto-completion.

**Comment by Kamidu** [comment]
This is the password you have saved or asked to be remember earlier you can simply select one of the user names them the associated password will be put as a input to the password. this is your browser behavior we have only disabled the auto filling of the password.
I am closing the issue with the above response if you have any more clarification regarding this please do reopen this ticket.

**Comment by chamaraanu** [comment]
Your explanation is correct about the browser behaviour of remembering password with associated usernames. 

But the product defect is different as, when you enter the username, no associated password is filled although then if you click on the password field, there's a drop down comes to select the password.

**Comment by Nirothipan** [comment]
Fixes in : - https://github.com/wso2/carbon-device-mgt/pull/822

**Comment by madhawap** [comment]
Fixed with https://github.com/wso2/carbon-device-mgt/pull/822. Hence closed.
