### ISSUE TITLE
404 when updated user role is viewed

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#416]
**Steps**

1. Create a role and then update the role name
2. Click on "VIEW UPDATE ROLE" provided in the role successfully updated page.

**Issue**
VIEW UPDATE ROLE will navigate to a 404 page. Refer below screenshot.

![image](https://cloud.githubusercontent.com/assets/17248809/25796081/c95576b2-33f5-11e7-9255-7a433b0b812e.png)

**Comment by jsonds** [comment]
Labels - Bug, 3.1.0-M6, High

**Comment by geethkokila** [comment]
Cannot be reproduced in the latest master pack (build after m8)
