### ISSUE TITLE
Fail to execute carbon device mgt cdmf analytics-1.0.0.car

### ISSUE THREAD

**Issue by pasindujw** [wso2/product-iots#420]
Build failure when building on current cabon-device-mgt & carbon-device-mgt-plugins repos.
As showed in console:
Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.0.0:single (2-dist) on project wso2iot: Failed to create assembly: Error adding file to archive: /home/pasindu/Developments/iot/product-iots/modules/distribution/../p2-profile/iot-core-profile/target/wso2carbon-core-4.4.14/wso2/resources/devicetypes/org_wso2_carbon_device_mgt_cdmf_analytics-1.0.0.car

**Comment by geethkokila** [comment]
As @ayyoob comments, this has been fixed in the latest pack, hence resolving the issue.
