### ISSUE TITLE
On a fresh pack when no device notifications are available the messages shown should be swaped with unread and all notifications

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#427]
On a fresh pack when there are no device notifications available the messages should be swapped to be meaningful.

**Issue**

1. Unread device notification message shows as - you do not have any notifications
2. All notifications message shows as - you do not have any unread notifications

These messages should be swapped.  

![notifications](https://cloud.githubusercontent.com/assets/17248809/25981263/c2e437d8-36f1-11e7-84e7-ed214d5aac7f.jpg)
![unreadnotifications](https://cloud.githubusercontent.com/assets/17248809/25981264/c2f15daa-36f1-11e7-9442-dfa2cef340b3.jpg)

**Comment by jsonds** [comment]
Labels - Bug, 3.1.0-M7, Medium

**Comment by milanperera** [comment]
This is fixed in [1].

[1] https://github.com/milanperera/carbon-device-mgt/commit/4994fddfd8de90823c6ef2f8d83e3e5bca52e365
