### ISSUE TITLE
When all unread notifications are read the message shown should be meaningful

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#428]
Read the unread notifications from the notifications tab When all unread messages are read the message shown is "**no data available in table**" 

This should be a meaningful message e.g - There are no unread messages.

![no data](https://cloud.githubusercontent.com/assets/17248809/25981571/a916eccc-36f3-11e7-8a11-01ef7945787b.jpg)

**Comment by jsonds** [comment]
Labels - Bug, 3.1.0-M7, Medium

**Comment by milanperera** [comment]
This is fixed in the latest IoTs 3.1.0-alpha.

<img width="1207" alt="screen shot 2017-06-28 at 6 13 29 pm" src="https://user-images.githubusercontent.com/11870191/27637504-97e96b0a-5c2d-11e7-9a53-00f2d4fd22b2.png">
