### ISSUE TITLE
Cannot edit a policy when users are assigned to a policy

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#443]
**Steps**

1. Create a policy e.g android / windows policy by providing couple of users by selecting set user radio button.
2. Edit the policy and navigate to "Edit Assignment group"

**Issue**

1. The selected users while creating the policy are not shown
2. Users are not filtered and shown when typing few letters hence it is not possible to edit the policy

**Comment by jsonds** [comment]
**Labels -**  3.1.0-M7, bug, blocker

**Comment by sinthuja** [comment]
Merged the PR with master.
