### ISSUE TITLE
Error found file config.json

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#444]
hi all,

I study WSO2 IOT for several months. I get WSO2 iOT on Jenkins to see the evolutions.

I managed to parameterize it with my IP. By browsing the files, I found an error:

In the folder :
`[home_wso2iot] / repository / deployment / server / jaggeryapps / devicemgt / app / conf`

Open file:
config.json

In line 5, you have forgotten a symbol : **%**
Before change:
`"HttpURL": "http: //%iot.gateway.host%:% iot.gateway.http.port",`

After change:
`"HttpURL": "http: //%iot.gateway.host%:% iot.gateway.http.port%",`

Hoping to have contributed to this immense work. Think about correcting your side

Best regards,

Christophe - France

**Comment by Tofdu31** [comment]
Think about correcting your side

**Comment by sinthuja** [comment]
Thanks for your contribution, and notifying us on this issue. We'll fix this soon.
