### ISSUE TITLE
AnalyticsServiceRemoteException: Error while connecting to the remote service

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#445]
When I click on a device in devicemgt, in the console, I have an error:
```
IoT-Core] ERROR - {org.wso2.carbon.analytics.api.internal.client.AnalyticsAPIHttpClient} Unable to connect to remote service, have retried 5 times, but unable to reach. 
org.wso2.carbon.analytics.api.exception.AnalyticsServiceRemoteException: Error while connecting to the remote service. Connection refused (Connection refused)
	at org.wso2.carbon.analytics.api.internal.client.AnalyticsAPIHttpClient.authenticate(AnalyticsAPIHttpClient.java:202)
	at org.wso2.carbon.analytics.api.internal.client.AnalyticsAPIHttpClient.validateAndAuthenticate(AnalyticsAPIHttpClient.java:213)
	at org.wso2.carbon.analytics.api.CarbonAnalyticsAPI.get(CarbonAnalyticsAPI.java:320)
	at org.wso2.carbon.analytics.jsservice.AnalyticsJSServiceConnector.getRecordsByRange(AnalyticsJSServiceConnector.java:330)
	at org.wso2.carbon.analytics.jsservice.AnalyticsCachedJSServiceConnector.getRecordsByRange(AnalyticsCachedJSServiceConnector.java:109)
	at org.wso2.carbon.analytics.jsservice.AnalyticsJSServiceConnector.getRecordsByRange(AnalyticsJSServiceConnector.java:307)
	at org.wso2.carbon.analytics.jsservice.AnalyticsCachedJSServiceConnector.getRecordsByRange(AnalyticsCachedJSServiceConnector.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.app.modules.c4._c_anonymous_5(/devicemgt/app/modules/batch-provider-api.js:125)
	at org.jaggeryjs.rhino.devicemgt.app.modules.c4.call(/devicemgt/app/modules/batch-provider-api.js)
	at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c1._c_anonymous_5(/devicemgt/app/modules/business-controllers/device.js:76)
	at org.jaggeryjs.rhino.devicemgt.app.modules.business_controllers.c1.call(/devicemgt/app/modules/business-controllers/device.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)
```

In case of need, I can provide you with my logs

Thank you for your reply

**Comment by Megala21** [comment]
Hi,

With the logs, seems like IoTs-analytics server is not up. This will be thrown when it tries to connect to analytics server.

Thanks.

**Comment by ghost** [comment]
thank you for your reply
To tell you how to do this, I unzip wso2iot and make changes for my IP address to work.
Then in the / bin folder I run, iot-server.sh
IoTs-analytics is not running with iot-server.sh?
This link is ok for me : https://@myip:9443/portal/dashboards/device-statistics-dashboard
Thanks.

**Comment by ghost** [comment]
Could you tell me if this link to a relationship with my bug

https://wso2.org/jira/projects/IOTS/issues/IOTS-487?filter=allopenissues

**Comment by sinthuja** [comment]
Analytics server is not started with iot-server.sh. You need to start the server separately, and It can be started by executing the IoT_HOME/bin/analytics.sh script. In case if you are running the analytics server in different machine with different port, then please do configure the analytics server location in the wso2iot-3.1.0-SNAPSHOT/conf/analytics/analytics-data-config.xml and wso2iot-3.1.0-SNAPSHOT/bin/iot-server.sh for below JVM properties.
-Diot.analytics.host="localhost" \
-Diot.analytics.https.port="9445" \

**Comment by ghost** [comment]
The set is on one server: 192.168.1.100
This means that I have to set each folder:
/ analytics
/ broker
And modify carbon.xml ... of each of the folders? Change I made for the folder :
wso2iot3.1.0/conf

**Comment by sinthuja** [comment]
I believe you have all analytics, IoT, broker etc, on one server. Please correct me if I'm wrong. 

In that case, you don't need to modify anything further. You can just start the analytics server by executing the script IoT_HOME/bin/analytics.sh. By default, analytics server starts with port offset =2, which doesn't contradict with your other servers. And hence it would just work.

**Comment by ghost** [comment]
On my server, I unzipped wso2iot_V3.1.0 that I downloaded on Jenkins
It's ok with `sh start-all.sh`

I go to the address:
https://192.168.1.100:9443/portal/t/carbon.super/dashboards

I do not see my smartphone which is well registered as BYOD

**Comment by sinthuja** [comment]
Just for more information, start-all.sh scripts all runtimes (iot-core, analytics, and broker). And you also can start each runtimes individually by executing iot-server.sh, analytics.sh and broker.sh in the IoT_HOME/bin directory.

**Comment by sinthuja** [comment]
I'm closing this issue given that you confirmed all worked now. Please reopen if you face any problems on this regard.

**Comment by ghost** [comment]
OK very thanks, 
I re-opens a post to my few problems

**Comment by pkarthikeyanmca** [comment]
hi
I am using AWS linux instance , Can you please tell me how to start all servers at a time in single machine(./broker.sh ./iot-server.sh ./analytics.sh).

Thanks,
P.Karthikeyan

**Comment by ghost** [comment]
hi,

You have to start the broker first and wait for it to be functional. Then you have to start iot-server.sh and wait for it to start completely. And finally you start analtycs.sh

If you start the 3 at the same time, you will have errors.

Christophe

**Comment by pkarthikeyanmca** [comment]
Thanks, Also one more issues found on moving to device management ( https://xx.xx.xx.xx:9443/devicemgt
getting error like 
 [IoT-Core] ERROR - {org.wso2.carbon.identity.sso.saml.processors.SPInitSSOAuthnRequestProcessor} ALERT: Invalid Assertion Consumer URL value '

I tried to add service provider in carbon console but many parameters not known ( I am using 3.3.3 iot server). Please help on to set up this .

Thanks,
P.Karthi

**Comment by ghost** [comment]
To understand, explain to me what you did before. As you replace localhost with your IP address

**Comment by pkarthikeyanmca** [comment]
1. i ran change.ip.sh ( since i am using AWS Linux instance so i have given my static ip as input (local host+ip both were given as same ip)
Apart from that i am not changing anything just start the server and enter into the device management page with username and passwd.
2.After given passwd it redirects to some page and shows below
"SAML 2.0 based Single Sign-On"
"Error when processing authentication request! "
"Please try login again! "

Thanks,
P.Karthikeyan

**Comment by ghost** [comment]
To understand, explain to me what you did before. As you replace localhost with your IP address

All your problem is there! You used change.ip.sh but it is totally wrong and with a lot of missing instructions.

I worked 7 months to produce the scripts that are functional!

And of course, Wso2 does not answer questions and does not provide a solution. Yet they announce that it's Opensource ...

**Comment by pkarthikeyanmca** [comment]
is there any solution please help?

Thanks,
P.Karthikeyan

**Comment by ghost** [comment]
unfortunately, we are a company and have paid a person for 7 months to bring us a script that works. (nbility.fr) We can not offer it.

Browse through the files to study the localhosts that you need to replace and those that do not need to be replaced.

Do not hesitate to send me your email.

**Comment by zblue89** [comment]
> To understand, explain to me what you did before. As you replace localhost with your IP address
> 
> All your problem is there! You used change.ip.sh but it is totally wrong and with a lot of missing instructions.
> 
> I worked 7 months to produce the scripts that are functional!
> 
> And of course, Wso2 does not answer questions and does not provide a solution. Yet they announce that it's Opensource ...

Yea, agreed. I'm facing the same issue and doing the same things as what you have done right now.

**Comment by sumedharubasinghe** [comment]
zblue89,
https://entgra.io/ is now owning the future roadmap of WSO2 IoT Server.
We would like to understand your use case better and see how we can support you.

Please drop a note to 'contact AT entgra.io' with your contact details.
Thanks,
Sumedha
