### ISSUE TITLE
iOS device enrollment DynamicClientRegistrationEndpoint has been changed 

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#449]
In **iot-api-config.xml** the DynamicClientRegistrationEndpoint URL needs to be updated from **/dynamic-client-web/register**  to **/client-registration/v0.11/register**

**Comment by malintha** [comment]
With that fix, we do not need the 7th configuration in the script anymore right?

**Comment by madawas** [comment]
@Malintha yes.
