### ISSUE TITLE
Standalone server - iOS device enrollment page UI show cloud related certificate install button

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#450]
![image](https://cloud.githubusercontent.com/assets/7391925/26103990/980ecec2-3a59-11e7-90c8-0d894247f311.png)

**Comment by madawas** [comment]
@amalhub Can you check whether the `isCloud` value is set to `false` in **ios-web-agent/app/conf/config.json**

**Comment by amalhub** [comment]
Checked and it was set to `true`. For the standalone pack, shall we change this to have the default value as `false` ?
