### ISSUE TITLE
If a policy which was applied to a device is deleted it will still be available under device policy compliance

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#460]
**Steps**

1. Enrol a device
2. Create a policy and apply it to the enrolled device
3. Unpublish the policy and then remove the policy
4. Navigate device -> Policy compliance

**Issue**
The removed policy is still shown as active

**Comment by jsonds** [comment]
**Labels -** 3.1.0-M7, bug, high

**Comment by jsonds** [comment]
This happens because when there is only one policy available and if it is deleted the "apply changes to devices" button is not shown.

**Comment by geethkokila** [comment]
Fixed in https://github.com/wso2/carbon-device-mgt/commit/fe67d251d5642f2e5b6f0648d65c4c20d68eb6ec
