### ISSUE TITLE
Incorrect confirmation message shown when users are sent the invite email

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#475]
**Steps**

Create a user
From UI select the created user and perform "Invite Selected"

**Issue**
The confirmation message that is shown is misleading. It again shows " **An invitation mail will be sent to the selected user(s)...** " This should be omitted.

![emailinvitevalidation](https://cloud.githubusercontent.com/assets/17248809/26236943/97d2305a-3c90-11e7-92ca-583dbfd6c356.jpg)

**Comment by jsonds** [comment]
**Labels -** 3.1.0-M7, bug, medium

**Comment by milanperera** [comment]
This is fixed in [1].

[1] https://github.com/milanperera/carbon-device-mgt/commit/c605ffbd5817f0dd236cf86d15462578bca22ea0
