### ISSUE TITLE
iOS features are not getting activated in bundles.info when installing ios feature

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#476]

**Comment by madawas** [comment]
The issue still exists in the M8 pack. Reproduced in the following environment

Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /opt/java/jdk1.8.0_45/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-78-generic", arch: "amd64", family: "unix"

**Comment by madawas** [comment]
This issue was fixed after using maven 3.0.5
