### ISSUE TITLE
IoT-Analytics   -  Broker is unreachable, Waiting.....

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#477]
Hi all,
I study WSO2 IOT for several months. I get WSO2 iOT on Jenkins to see the evolutions.

I finally managed to run the WSO2 IoT server with my ip : 192.168.1.100
But, in the console, i have a error.  Here is an excerpt of the console. I run the WSO2 iOT server with the command sh start-all.sh

`[2017-05-19 14:03:27,198] [IoT-Analytics]  WARN {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Broker is unreachable, Waiting.....
[2017-05-19 14:04:27,357] [IoT-Analytics]  WARN {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Broker is unreachable, Waiting.....
[2017-05-19 14:04:48,722] [IoT-Broker]  INFO {org.wso2.andes.kernel.AndesRecoveryTask} -  Running DB sync task.
[Stage 1914:(45 + 1) / 200][Stage 1918:(0 + 0) / 200][Stage 1924:(0 + 0) / 200][2017-05-19 14:05:27,522] [IoT-Analytics]  WARN {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Broker is unreachable, Waiting.....
[2017-05-19 14:06:27,680] [IoT-Analytics]  WARN {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Broker is unreachable, Waiting.....
[Stage 2084:(59 + 1) / 200][Stage 2098:(0 + 0) / 200][Stage 2102:(0 + 0) / 200][2017-05-19 14:10:28,334] [IoT-Analytics]  WARN {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Broker is unreachable, Waiting.....
[2017-05-19 14:13:28,807] [IoT-Analytics]  WARN {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Broker is unreachable, Waiting.....
[2017-05-19 14:19:48,722] [IoT-Broker]  INFO {org.wso2.andes.kernel.AndesRecoveryTask} -  Running DB sync task.
[Stage 2417:(155 + 1) / 200][Stage 2425:(0 + 0) / 200][Stage 2431:(0 + 0) / 200][2017-05-19 14:20:30,034] [IoT-Analytics]  WARN {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} -  Broker is unreachable, Waiting....`

In the folder homewso2iot/wso2/**broker**/conf , I modified only carbon.xml
```
<HostName>192.168.1.10</HostName>
<MgtHostName>192.168.1.10</MgtHostName>
```
In the folder homewso2iot/wso2/**analytics**/conf , I modified carbon.xml
```
<HostName>192.168.1.10</HostName>
<MgtHostName>192.168.1.10</MgtHostName>
```
I have several questions :
**1.** In In the folder homewso2iot/wso2/analytics/conf
File : event-processor.xml
What means `<hostName>0.0.0.0</hostName>`

**2.** In In the folder homewso2iot/wso2/analytics/conf
File : input-event-adapters.xml
Do I have to change with my ip 192.168.1.10?
Ligne 43 : `<property key="tokenValidationUrl">https://${iot.keymanager.host}:${iot.keymanager.https.port}</property>`
Ligne 46 :` <property key="tokenUrl">https://${iot.gateway.host}:${iot.gateway.https.port}/token</property>`
Linge 47 : `<property key="deviceMgtServerUrl">https://${iot.gateway.host}:${iot.gateway.https.port}</property>`
Ligne 57 : `<property key="dcrUrl">https://${iot.keymanager.host}:${iot.keymanager.https.port}/client-registration/v0.11/register</property>`
Ligne 58 : `<property key="url">tcp://${mqtt.broker.host}:${mqtt.broker.port}</property>`

**3.** In In the folder homewso2iot/wso2/analytics/conf
File : output-event-adapters.xml
The parameters of the mail.smtp.user are not commented on and with test information
We must therefore modify this part in relation to our mail server
Also, ligne 131 :` <property key="url">tcp://${mqtt.broker.host}:${mqtt.broker.port}</property>` Do I have to change with my ip 192.168.1.10?

Here is a summary so that you have a maximum of information. The documentation is really succinct. Thank you for your help.

**Comment by ayyoob** [comment]
you don't need to change the parameterized value, However add the correct IP for mqtt authorization and authentication configuration in wso2/broker/conf/broker.xml

**Comment by ghost** [comment]
Thanks but I have to modify what parameters?

**Comment by ghost** [comment]
Finally I found
If you have this error : 
`[IoT-Analytics] WARN {org.wso2.carbon.device.mgt.input.adapter.mqtt.util.MQTTAdapterListener} - Broker is unreachable, Waiting.....`

Open file: homewso2iot/wso2/analytics/bin/wso2server.sh
**Search the line**
`-Dmqtt.broker.host="locahost" \`

**Replace with**
`-Dmqtt.broker.host="your_IP" \`
