### ISSUE TITLE
Iot-Analytics : ERROR  JSONObject["value"] not found

### ISSUE THREAD

**Issue by ghost** [wso2/product-iots#478]
Hi all,

When I go to dashboard Analytics https://localhost:9445/portal/dashboards/  , I authenticate and I access well and without error to the portal.
When I click on the Android-IOT dashboard, i have an error in the console : 
`[IoT-Analytics] ERROR {org.wso2.carbon.event.output.adapter.ui.JaggeryWebSocketHelper} -  JSONObject["value"] not found.
org.json.JSONException: JSONObject["value"] not found`

I'm looking for where it might come from. Anyone to help me?

**Comment by ghost** [comment]
Hello everyone,

For several days, I am looking for a solution for this error code. I can not find. Someone would have an idea?

```
[IoT-Analytics] ERROR {org.wso2.carbon.event.output.adapter.ui.JaggeryWebSocketHelper} -  JSONObject["value"] not found.
org.json.JSONException: JSONObject["value"] not found.
```

Thank for your help.

**Comment by ghost** [comment]
I just checked with Ubuntu in localhost.

The error is also present:

```
[IoT-Analytics] ERROR {org.wso2.carbon.event.output.adapter.ui.JaggeryWebSocketHelper} -  JSONObject["value"] not found.
org.json.JSONException: JSONObject["value"] not found.
```

**Comment by sinthuja** [comment]
@Nirothipan will work on this.

**Comment by ghost** [comment]
@sinthuja Thank you for your information

I can see the work in progress where?

**Comment by Nirothipan** [comment]
Hi, 

With the IoT 3.1.0 release, we have removed the android-iot dashboard from the analytics portal applciation and the statistics related to devices are displayed in the Device details page itself.
Hence this issue is invalid in IoT 3.1.0.

Thank you
