### ISSUE TITLE
Migration Mysql error

### ISSUE THREAD

**Issue by Darkpiou** [wso2/product-iots#479]
Hi,

With the database H2, the product start normally.
But when i migrate the database with mysql 5.7, i have this error
Database Error - com.mysql.jdbc.Driver cannot be found by jdbc-pool_7.0.34.wso2v2.
I've followed this documentation:
https://docs.wso2.com/display/IoTS300/Setting+up+MySQL

Thanks

**Comment by Megala21** [comment]
Hi,
This error will be shown if we do not put the driver class correctly. Did you download the mysql-jdbc connector and added the jar inside the zip file correctly to <IoTS_HOME>/repository/components/lib

Thanks.

**Comment by Darkpiou** [comment]
Hello,

Thanks for your answer but i've always the error.
This my architecture :

+bin
+conf
+dbscripts
+dropins
+lib
LICENSE.txt
+modules
+patches
+dplugins
README.txt
release-notes.html
-repository
   +data
   +database
   +deployment
   +logs
   +resources
   +tenants
+resources
+samples
+servicepacks
+tmp
- wso2
  + analytics
   + broker
   - components
      - plugins
   + lib

I don't have <IoTS_HOME>/repository/components/lib.
I try to create this but i have the same message Database Error - com.mysql.jdbc.Driver cannot be found by jdbc-pool_7.0.34.wso2v2.
Or i try to put the connector  to wso2/components/plugins -> the same message.

I've already done the database migration H2 to Mysql but with emm and it was a succes.
I don't understand why i have this error.

Thanks.

**Comment by Darkpiou** [comment]
Hello,

Any idea ?

Thanks

**Comment by ayyoob** [comment]
Are you trying this on IoTS-3.1.0 SNAPSHOT? If so please follow this docs [1].

[1] https://docs.wso2.com/display/IoTS310/Setting+up+MySQL

**Comment by Darkpiou** [comment]
Hy ayyoob,

I'll try your documentation.

Thanks.

**Comment by Darkpiou** [comment]
Re,

Ok my mysql client speak with my database, cool.
I've another error with the creation table but it' s an another problem lol. 
ERROR 1067 (42000) at line 51: Invalid default value for 'REG_CREATED_TIME'

Thanks a lot. I close this problem.
