### ISSUE TITLE
A policy with monitor compliance restricts using the camera

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#480]
Created a policy with compliance rule set to **Monitor** with the **camera disabled**. When the device user is trying to use the camera app it restricts using the camera.

As the compliance rule is to monitor this should allow the user to use the camera.

**Comment by jsonds** [comment]
**Labels -** 3.1.0-M7, bug, high

**Comment by inoshperera** [comment]
Compliance actions is removed since only enforce is available. Fixed with - https://github.com/wso2/carbon-device-mgt/pull/785/commits/88054f9075a2b47c77b17f29517aa2750f547101
