### ISSUE TITLE
Even if most of the host address bind configurations are set to wlan interface in the iot-server, during the ios registration, the iPhone try to connect to the docker network interface

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#491]
1. All the given configurations (according to docs) are modified so that the iot-server will bind to the wlan ipaddress (10.100.1.90) of the machine. 
2. The machine have several network interfaces including the docker interface. (172.17.0.1)
3. During the device registration, the iPhone will try to connect to the docker interface and it fails. 
4. A fix needs to be introduced to configure all the network interfaces the iot-server connects to be configured to the desired network interface. 

![img_3674](https://cloud.githubusercontent.com/assets/6646840/26438288/b9c31ff4-413f-11e7-978d-0e3d5b75db64.PNG)

**Comment by ayyoob** [comment]
Did you add the IP to the hostname element in carbon.xml?, This field is used to bind to the correct interface.

**Comment by sameeragunarathne** [comment]
This is fixed in https://github.com/wso2/carbon-devicemgt-proprietary-plugins/pull/151/commits/6f04e6c67d15231f5561bdc8365c34626430e07c
