### ISSUE TITLE
Android Sense  - Analytics CAR file missing

### ISSUE THREAD

**Issue by shavidissa** [wso2/product-iots#493]
I was testing how Android sense functioned in the 3.1.0 m7 pack. After installing Android Sense publishing data, I clicked View device analytics.

I was given a 400 error saying it's not available. When discussed with Sinthuja, she mentioned that the CAR file that's needed for the analytics component is missing in the pack.

**Comment by sinthuja** [comment]
@sameerawickramasekara will work on this.

**Comment by sinthuja** [comment]
This issue is already fixed, and the andriod sense car file is there in the analytics profile by default. And hence closing this issue.
