### ISSUE TITLE
[CDMF-2] Managing license agreements upon device enrollment

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#499]
<p>There has to be a mechanism in CDM-Framework where it enforces an end-user a step for agreeing upon a given license as part of the device enrollment process.</p><p>Reference: <a href='https://wso2.org/jira/browse/CDMF-2'>https://wso2.org/jira/browse/CDMF-2</a></p>

**Comment by inoshperera** [comment]
CDMF already has a license management component and it the responsibility of the plugin developer to enforce the user to agree to a license
