### ISSUE TITLE
[CDMF-12] Need to validate the ownership of user before executing any action on a device

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#501]
<p>There should be a way to verify the ownership of the device before executing any action on a device. Intention of this functionality is to prevent users (not emm-admins) from executing actions on other users devices.</p><p>Reference: <a href='https://wso2.org/jira/browse/CDMF-12'>https://wso2.org/jira/browse/CDMF-12</a></p>

**Comment by geethkokila** [comment]
This is fixed, hence closing.  (This is for operation level)
