### ISSUE TITLE
[MDM-407] Emm is sending all of its devices in a specific tenant to AppM when user's devices are needed.

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#502]
<p>In AppM EMM integration from OSGI<span class="error">&#91;1&#93;</span> (line 163). I can see EMM retrieve all of its devices and send it to AppM when user's devices are needed. This should be filtered to get only users devices by AppM, not all devices which is in the tenant.</p><p><span class="error">&#91;1&#93;</span> - <a href="https://github.com/wso2/product-mdm/blob/master/modules/components/app-mgt/org.wso2.mdm.appmgt/src/main/java/org/wso2/mdm/appmgt/service/MDMOperationsImpl.java" class="external-link" rel="nofollow">https://github.com/wso2/product-mdm/blob/master/modules/components/app-mgt/org.wso2.mdm.appmgt/src/main/java/org/wso2/mdm/appmgt/service/MDMOperationsImpl.java</a></p><p>Reference: <a href='https://wso2.org/jira/browse/MDM-407'>https://wso2.org/jira/browse/MDM-407</a></p>

**Comment by inoshperera** [comment]
This will be improved with the new rewrite of app management component.
