### ISSUE TITLE
[MDM-377] User after login to EMM console can click on EMM logo view admin dashboard 

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#503]
<p>Steps<br/>1. Login to EMM console and create a user<br/>2. Login to EMM console with the created user credentials<br/>3. Click on the EMM logo on top left corner</p><p>Issue - The user with no admin role can also see the admin dashboard (refer attachments)</p><p>Reference: <a href='https://wso2.org/jira/browse/MDM-377'>https://wso2.org/jira/browse/MDM-377</a></p>

**Comment by inoshperera** [comment]
These issue was addressed in later releases.
