### ISSUE TITLE
[MDM-294] LICENSE.txt shipped with MDM by default is obsolete

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#505]
<p>Need to get the LICENSE.txt regenerated so that it would capture all applicable elements (jars, etc) shipped with the product.</p><p>Reference: <a href='https://wso2.org/jira/browse/MDM-294'>https://wso2.org/jira/browse/MDM-294</a></p>

**Comment by inoshperera** [comment]
Issue is not clear enough. When releasing the product, LICENSE.txt must be updated.
