### ISSUE TITLE
[MDM-293] README.txt of MDM is not descriptive enough

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#506]
<p>README.txt needs to be refactored in a way that any user can read it up and figure out how to configure the product, etc intuitively.</p><p>Reference: <a href='https://wso2.org/jira/browse/MDM-293'>https://wso2.org/jira/browse/MDM-293</a></p>

**Comment by inoshperera** [comment]
The README.txt of the current product is descriptive enough. Hence resolving the issue.
