### ISSUE TITLE
[MDM-375] Create a user from carbon console  - "Ask password from user" scenario fails

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#507]
<p>Steps<br/>1. Login to carbon console and navigate "User and roles" section<br/>2. Create a user - add user name and select radio button "Ask password from user"<br/>3. Click next and then finish</p><p>Issue - error shown(refer attachment) in popup and exception thrown</p><div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"><pre class="code-java">[2015-07-22 13:21:54,694] ERROR {org.wso2.carbon.user.mgt.ui.UserAdminClient} -  Credential not valid. Credential must be a non <span class="code-keyword">null</span> string with following format, ^[\S]{5,30}$org.wso2.carbon.user.mgt.stub.UserAdminUserAdminException: UserAdminUserAdminExceptionat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.lang.reflect.Constructor.newInstance(Constructor.java:526)at java.lang.<span class="code-object">Class</span>.newInstance(<span class="code-object">Class</span>.java:379)at org.wso2.carbon.user.mgt.stub.UserAdminStub.addUser(UserAdminStub.java:1575)at org.wso2.carbon.user.mgt.ui.UserAdminClient.addUser(UserAdminClient.java:94)at org.apache.jsp.user.add_002dfinish_jsp._jspService(add_002dfinish_jsp.java:145)at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:604)at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:543)at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:37)at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.include(ContextPathServletAdaptor.java:369)at org.apache.jasper.runtime.JspRuntimeLibrary.include(JspRuntimeLibrary.java:954)at org.apache.jasper.runtime.PageContextImpl.doInclude(PageContextImpl.java:688)at org.apache.jasper.runtime.PageContextImpl.include(PageContextImpl.java:682)at sun.reflect.GeneratedMethodAccessor178.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:606)at org.apache.tiles.jsp.context.JspUtil.doInclude(JspUtil.java:87)at org.apache.tiles.jsp.context.JspTilesRequestContext.include(JspTilesRequestContext.java:88)at org.apache.tiles.jsp.context.JspTilesRequestContext.dispatch(JspTilesRequestContext.java:82)at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:465)at org.apache.tiles.jsp.taglib.InsertAttributeTag.render(InsertAttributeTag.java:140)at org.apache.tiles.jsp.taglib.InsertAttributeTag.render(InsertAttributeTag.java:117)at org.apache.tiles.jsp.taglib.RenderTagSupport.execute(RenderTagSupport.java:171)at org.apache.tiles.jsp.taglib.RoleSecurityTagSupport.doEndTag(RoleSecurityTagSupport.java:75)at org.apache.tiles.jsp.taglib.ContainerTagSupport.doEndTag(ContainerTagSupport.java:80)at org.apache.jsp.admin.layout.template_jsp._jspx_meth_tiles_005finsertAttribute_005f7(template_jsp.java:640)at org.apache.jsp.admin.layout.template_jsp._jspService(template_jsp.java:356)at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)at org.wso2.carbon.ui.JspServlet.service(JspServlet.java:155)at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:80)at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)at org.eclipse.equinox.http.servlet.internal.RequestDispatcherAdaptor.forward(RequestDispatcherAdaptor.java:30)at org.eclipse.equinox.http.helper.ContextPathServletAdaptor$RequestDispatcherAdaptor.forward(ContextPathServletAdaptor.java:362)at org.apache.tiles.servlet.context.ServletTilesRequestContext.forward(ServletTilesRequestContext.java:198)at org.apache.tiles.servlet.context.ServletTilesRequestContext.dispatch(ServletTilesRequestContext.java:185)at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:419)at org.apache.tiles.impl.BasicTilesContainer.render(BasicTilesContainer.java:370)at org.wso2.carbon.ui.action.ActionHelper.render(ActionHelper.java:52)at org.wso2.carbon.ui.TilesJspServlet.service(TilesJspServlet.java:101)at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)at org.eclipse.equinox.http.helper.ContextPathServletAdaptor.service(ContextPathServletAdaptor.java:37)at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(ProxyServlet.java:128)at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyServlet.java:68)at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.service(DelegationServlet.java:68)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.wso2.carbon.tomcat.ext.filter.CharacterSetFilter.doFilter(CharacterSetFilter.java:61)at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticatorFrameworkValve.invoke(WebappAuthenticatorFrameworkValve.java:40)at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1698)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745)</pre></div></div><p>Reference: <a href='https://wso2.org/jira/browse/MDM-375'>https://wso2.org/jira/browse/MDM-375</a></p>

**Comment by inoshperera** [comment]
Password is a compulsory field, therefore this is no longer applicable.
