### ISSUE TITLE
[MDM-362] Fix log4j warnings printed while deploying "mdm-android-agent" webapp

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#508]
<p>Please refer the following log snippet for more details.</p><p><span class="error">&#91;2015-07-17 17:14:27,847&#93;</span>  INFO </p>{org.wso2.carbon.webapp.mgt.TomcatGenericWebappsDeployer}<p> -  Deployed webapp: StandardEngine<span class="error">&#91;Catalina&#93;</span>.StandardHost<span class="error">&#91;localhost&#93;</span>.StandardContext<span class="error">&#91;/mdm-android-agent&#93;</span>.File<span class="error">&#91;/Users/WSO2USER08/WSO2/git/cdm/test-17072015/pack/wso2mdm-2.0.0-SNAPSHOT/repository/deployment/server/webapps/mdm-android-agent.war&#93;</span><br/><b>log4j:WARN No appenders could be found for logger(org.springframework.core.io.support.PathMatchingResourcePatternResolver).</b><br/><b>log4j:WARN Please initialize the log4j system properly.</b><br/><b>log4j:WARN See <a href="http://logging.apache.org/log4j/1.2/faq.html#noconfig" class="external-link" rel="nofollow">http://logging.apache.org/log4j/1.2/faq.html#noconfig</a> for more info.</b></p><p>Reference: <a href='https://wso2.org/jira/browse/MDM-362'>https://wso2.org/jira/browse/MDM-362</a></p>

**Comment by inoshperera** [comment]
This is no longer happening with "mdm-android-agent" webapp
