### ISSUE TITLE
[MDM-370] Contents of the email used as part of "enrolment invitation" is not clear enough

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#509]
<p>Please refer the following email body.</p><p>===============<br/>Dear Prabath,</p><p>You have been registered to the WSO2 MDM. Below is the link to enroll.</p><p><a href="https://10.100.1.206:9443/mdm/download-agent" class="external-link" rel="nofollow">https://10.100.1.206:9443/mdm/download-agent</a></p><p>Best Regards,<br/>WSO2 MDM Team.<br/><a href="http://www.wso2.com" class="external-link" rel="nofollow">http://www.wso2.com</a></p><p>===============</p><p>The link sent in the mail is used only to download the agent. Therefore, the aforementioned line should be properly highlighted in the mail body. Further, the message conveyed to the users should clearly define the steps that need to be followed from the point where the agent application is downloaded to the device till the enrolment process is fully done.</p><p>Reference: <a href='https://wso2.org/jira/browse/MDM-370'>https://wso2.org/jira/browse/MDM-370</a></p>

**Comment by inoshperera** [comment]
This is fixed in IoT 3.0.0 and the email body is configurable.
