### ISSUE TITLE
[MDM-404] When an admin creates a user account, show the user's default password

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#511]
<p>In EMM 1.1.0, when an admin would create a new user, it would show the admin the user's default password along with the QR code for downloading the app.</p><p>This functionality appears to have been removed in 2.0.0, opting to instead only send the user their password via email. Unfortunately this will not work for anyone intending on using this software on a network without internet access, like myself. Please enable this functionality again!</p><p>Reference: <a href='https://wso2.org/jira/browse/MDM-404'>https://wso2.org/jira/browse/MDM-404</a></p>

**Comment by sinthuja** [comment]
IoT 3.1.0 onwards we do have password reset functionality and hence for the newly created user, the admin user can provide the password for that user after the successful user creation. Please refer the attached screenshot. This functionality doesn't require, any internet connection for you to proceed with this operation. As this requirement is already handled with different feature, I'm closing this issue. 

<img width="1417" alt="screen shot 2017-08-29 at 10 57 14 am" src="https://user-images.githubusercontent.com/7677649/29805732-1fa6b614-8ca9-11e7-93be-b5d93c8d7d37.png">
