### ISSUE TITLE
[MDM-399] User search does not work when adding a role

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#512]
<p>401 unauthorized error is sending from the backend when searching for users.</p><p>Reference: <a href='https://wso2.org/jira/browse/MDM-399'>https://wso2.org/jira/browse/MDM-399</a></p>

**Comment by inoshperera** [comment]
@chamaraanu Is this reproducible in 3.1.0-beta?

**Comment by inoshperera** [comment]
Tested and no longer reproducible, hence closing
