### ISSUE TITLE
[MDM-381] No validations messge is shown in iOS device enrollment login form

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#513]
<p>Steps<br/>1. Create a user and login to the email from an iOS device<br/>2. Click on the link of the registration email and download the CA and client app.<br/>3. Add the correct IP and click on "Start Registration"<br/>4. In the webpage opened click on "Login" without any credentials / wrong user credentials</p><p>Issue - No validations message is shown instead "Sorry!, Error occured " is shown </p><p>Reference: <a href='https://wso2.org/jira/browse/MDM-381'>https://wso2.org/jira/browse/MDM-381</a></p>

**Comment by milanperera** [comment]
This is fixed in the latest ios-web-agent
