### ISSUE TITLE
[MDM-288] {product.name} and {product.version} variables are not properly replaced with values specific to MDM

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#514]
<p>Please refer the following console output.</p><p><span class="error">&#91;2015-01-29 18:27:00,728&#93;</span>  INFO </p>{org.wso2.carbon.core.init.JMXServerManager}<p> -  JMX Service URL  : service:jmx:rmi://localhost:11111/jndi/rmi://localhost:9999/jmxrmi<br/><span class="error">&#91;2015-01-29 18:27:00,853&#93;</span>  INFO </p>{org.wso2.carbon.core.internal.StartupFinalizerServiceComponent} -  Server           :  ${product.name}-${product.version}<br/><span class="error">&#91;2015-01-29 18:27:00,853&#93;</span>  INFO {org.wso2.carbon.core.internal.StartupFinalizerServiceComponent}<p> -  WSO2 Carbon started in 20 sec<br/><span class="error">&#91;2015-01-29 18:27:01,012&#93;</span>  INFO </p>{org.wso2.carbon.ui.internal.CarbonUIServiceComponent}<p> -  Mgt Console URL  : <a href="https://10.100.1.206:9443/carbon/" class="external-link" rel="nofollow">https://10.100.1.206:9443/carbon/</a></p><p>Reference: <a href='https://wso2.org/jira/browse/MDM-288'>https://wso2.org/jira/browse/MDM-288</a></p>

**Comment by geethkokila** [comment]
This is fixed, hence closing
