### ISSUE TITLE
[MDM-303] Fix sql script issue on plugins db

### ISSUE THREAD

**Issue by amalhub** [wso2/product-iots#516]
<p>The -Dsetup gives error due to issue in plugin db script</p><p>Reference: <a href='https://wso2.org/jira/browse/MDM-303'>https://wso2.org/jira/browse/MDM-303</a></p>

**Comment by sinthuja** [comment]
I verified by pointing Device management database, Android database, windows database and GEO location database pointing to mysql databse, and started with -Dsetup. Didn't encounter any start-up issues, performed some smoke testing and didn't find any issues. Therefore I'm closing this ticket as this issue doesn't exist anymore.
