### ISSUE TITLE
[EMM-1328] Validation for BYOD - Setting the work profile - Data containerization

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#521]
The data containerization process is for the BYOD registration process. In the current implementation after setting the work profile, the user goes through the normal process of enrolling an Android device.  Here the user should not have the need of selecting if the device type is BYOD or COPE. The agent should identify that since the work profile was set up, the registration is for a BYOD device type? <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1328'>https://wso2.org/jira/browse/EMM-1328</a></p>

**Comment by sinthuja** [comment]
This issue is not applicable, as we  are specifying whether BYOD or COPE during the build time.
