### ISSUE TITLE
iot-server.sh file start/stop commands doesn't work

### ISSUE THREAD

**Issue by sinthuja** [wso2/product-iots#522]
Cannot start/stop the server with 'sh iot-server.sh start'

**Comment by sumedharubasinghe** [comment]
@inoshperera , @geethkokila 
Remember to resolve comment in https://docs.google.com/document/d/1r4nO1CsCmtfDQexfmnNIqwMd5J9Q8njkzvW1BtiAIV8/edit?ts=593e4ff1#heading=h.8pzuzk4dclkf
when your marking this as resolved.

**Comment by sinthuja** [comment]
This issue is fixed.
