### ISSUE TITLE
[EMM-1892] End user has registered his device in Android for work but is required to re-login every time

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#525]
After the end user registered himself in android for work in the android agent, the work profile is generated successfully. However, whenever he reopens the android agent app, he is required to re-login and this would sometimes cause re-registering of the same device.         <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1892'>https://wso2.org/jira/browse/EMM-1892</a></p>

**Comment by inoshperera** [comment]
Fixed with https://github.com/wso2/cdmf-agent-android/pull/49
