### ISSUE TITLE
[EMM-1898] Problem when using secondary user store AD : UserManagementServiceImpl Error occurred while retrieving the list of users

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#527]
https://myip:9443/emm/users/               :                        ERROR            {org.wso2.carbon.device.mgt.jaxrs.service.impl.UserManagementServiceImpl}                           - Error occurred while retrieving the list of users.                              org.wso2.carbon.user.core.UserStoreException: UserNotFound: User $3BD000-31C3TD21ILBHdoes not exist in: PRIMARY                              at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:168)                              at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValue(AbstractUserStoreManager.java:580)                              at org.wso2.carbon.device.mgt.jaxrs.service.impl.UserManagementServiceImpl.getClaimValue(UserManagementServiceImpl.java:505)                              at org.wso2.carbon.device.mgt.jaxrs.service.impl.UserManagementServiceImpl.getUsers(UserManagementServiceImpl.java:326)                              at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                              at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                              at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                              at java.lang.reflect.Method.invoke(Method.java:498)                              at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:188)                              at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104)                              at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:204)                              at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:101)                              at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58)                              at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:94)                              at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272)                              at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)                              at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:249)                              at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:248)                              at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:222)                              at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:153)                              at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)                              at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:289)                              at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:214)                              at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)                              at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:265)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.wso2.carbon.device.mgt.jaxrs.ApiOriginFilter.doFilter(ApiOriginFilter.java:33)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)                              at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)                              at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:614)                              at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)                              at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)                              at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:59)                              at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)                              at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)                              at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)                              at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.processRequest(WebappAuthenticationValve.java:143)                              at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:68)                              at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)                              at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)                              at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)                              at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)                              at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)                              at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)                              at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)                              at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082)                              at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623)                              at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756)                              at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715)                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                              at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)                              at java.lang.Thread.run(Thread.java:748)                              Caused by: java.security.PrivilegedActionException: java.lang.reflect.InvocationTargetException                              at java.security.AccessController.doPrivileged(Native Method)                              at org.wso2.carbon.user.core.common.AbstractUserStoreManager.callSecure(AbstractUserStoreManager.java:158)                              ... 58 more                              Caused by: java.lang.reflect.InvocationTargetException                              at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                              at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                              at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                              at java.lang.reflect.Method.invoke(Method.java:498)                              at org.wso2.carbon.user.core.common.AbstractUserStoreManager$2.run(AbstractUserStoreManager.java:161)                              ... 60 more                              Caused by: org.wso2.carbon.user.core.UserStoreException: UserNotFound: User $3BD000-31C3TD21ILBHdoes not exist in: PRIMARY                              at org.wso2.carbon.user.core.common.AbstractUserStoreManager.getUserClaimValue(AbstractUserStoreManager.java:594)                              ... 65 more                        Thanks for help, I really need it !         <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1898'>https://wso2.org/jira/browse/EMM-1898</a></p>

**Comment by harshanL** [comment]
Fixed with commit : https://github.com/wso2/carbon-device-mgt/commit/9206f747907cdf972106fb3aceeab533a743cd6e
