### ISSUE TITLE
[EMM-1897] Some app manager tables are missing in the postgres db scripts

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#528]
Some app manager tables are missing in the postgres db scripts.                           +Following tables are missing +                              APM_API_CONSUMER_APPS                              APM_APP                              APM_APP_DEFAULT_VERSION                              APM_APP_HITS                              APM_APP_JAVA_POLICY                              APM_APP_JAVA_POLICY_MAPPING                              APM_APP_LC_EVENT                              APM_APPLICATION                              APM_APP_URL_MAPPING                              APM_BUSINESS_OWNER                              APM_BUSINESS_OWNER_PROPERTY                              APM_ENTITLEMENT_POLICY_PARTIAL                              APM_EXTERNAL_STORES                              APM_FAVOURITE_APPS                              APM_ONE_TIME_DOWNLOAD_LINK                              APM_POLICY_GROUP                              APM_POLICY_GROUP_MAPPING                              APM_POLICY_GRP_PARTIAL_MAPPING                              APM_STORE_FAVOURITE_PAGE                              APM_SUBSCRIBER                              APM_SUBSCRIPTION                              APM_TIER_PERMISSIONS                              APM_WORKFLOWS                              APPMGR_APP                              APPMGR_APP_COMMENTS                              APPMGR_APP_LC_EVENT                              APPMGR_APP_RATINGS                              APPMGR_APP_URL_MAPPING                              HYBRID_ROLE                              HYBRID_USER_ROLE                              APM_STORE_FAVOURITE_PAGE                     <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1897'>https://wso2.org/jira/browse/EMM-1897</a></p>

**Comment by harshanL** [comment]
This issue is fixed with commit : https://github.com/wso2/carbon-appmgt/pull/547/commits/e016fe0bcfb0d06766d1a900bd3f6c440f2c49ac
