### ISSUE TITLE
[EMM-1894] End User registering an iOS Device - enters incorrect password and it encounters HTTP 500 Page

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#529]
When the end user registers an iOS device in enrollment page, if he enters an incorrect password, he is directed to a HTTP 500 page.         <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1894'>https://wso2.org/jira/browse/EMM-1894</a></p>

**Comment by milanperera** [comment]
This issue is fixed in [1].

[1] https://github.com/wso2/carbon-devicemgt-proprietary-plugins/pull/112
