### ISSUE TITLE
[EMM-1865] Problem when inserting "Last Name" with multiple words in EMM console.

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#531]
Form validation error when inserting "Last Name" with multiple words in EMM console.                              The reason for the issue is,The regular expression contains for last name does not allow spaces in UI as below:                              &lt;input type="text" id="lastname" data-regex="^               &#91;\S&#93;                        {3,30}            $" data-errormsg="Provided last name is invalid." class="form-control"&gt;         <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1865'>https://wso2.org/jira/browse/EMM-1865</a></p>

**Comment by inoshperera** [comment]
This is no longer present in current releases.
