### ISSUE TITLE
[EMM-1846] Assigned roles can not be deleted from the user.

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#532]
1. Login to dashboard                              2. Roles can be assigned to the user.                              3. Given roles can not removed from the user.                     <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1846'>https://wso2.org/jira/browse/EMM-1846</a></p>

**Comment by inoshperera** [comment]
This is fixed in the latest releases of IoT server(3.0.0)
