### ISSUE TITLE
[EMM-1876] Policy not deployed after role changed

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#535]
<p>Reference: <a href='https://wso2.org/jira/browse/EMM-1876'>https://wso2.org/jira/browse/EMM-1876</a></p>

**Comment by sinthuja** [comment]
@Nirothipan will check this.

**Comment by sinthuja** [comment]
I verified this with the latest pack 29th Aug 2017 as per the provided scenario.  Followed below steps with andriod emulator and worked without any issue.
1) Created two roles roleA and roleB
2) Created two profiles camera-on and camera-off. Assigned camera-on profile to roleA, and camera-off profile to roleB.
3) create a user testuser and assigned roleA.
4) registered a device for testuser
5) Verified camara is off
6) unregistered the device
7) changed the role for testuser to roleB
8) Now connect again with the same device
9) Confirmed the camera is working again. 

therefore closing this issue.
