### ISSUE TITLE
[EMM-1896] Some features are missing after creating a policy.

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#537]
When creating a policy the ticket and unticked states of the check boxes are not saved.         <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1896'>https://wso2.org/jira/browse/EMM-1896</a></p>

**Comment by sinthuja** [comment]
Pasindu will check this.

**Comment by sameeragunarathne** [comment]
This is already fixed in latest release.
