### ISSUE TITLE
[EMM-1891] Making Webclip and Application Undeletable

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#538]
Allow users to make web clips which are installed via WSO2 EMM not removable.         <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1891'>https://wso2.org/jira/browse/EMM-1891</a></p>

**Comment by geethkokila** [comment]
@menakaj , Please comment.

**Comment by menakaj** [comment]
The fix is added. 
[Making WEB Clip uninstallation configurable](https://github.com/wso2/carbon-appmgt/pull/614)

Need to be merged to APPM.
