### ISSUE TITLE
[EMM-1875] Device Model Based Policies

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#541]
User should be able to create policies for specific device models.                           For example;                              1. When user navigate into "Policy Management" and try to create a new Policy.                              2. User can select the platform "Android/Windows/iOS"                              3. If user selects iOS; User should be able to select whether this policy is applicable to "All" devices or "Only iPads" or "Only iPhones".                              4. These product models should be configurable through the config.json file.                     <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1875'>https://wso2.org/jira/browse/EMM-1875</a></p>

**Comment by geethkokila** [comment]
Duplicate 
https://github.com/wso2/product-iots/issues/775
Closing
