### ISSUE TITLE
[EMM-1885] Device Status should be changed to 'Removed' state once the device get wiped.

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#542]
Currently device state is not changing when we do a device wipe operation. It shows the device state as 'Active' even after the device get wiped. This should be changed to 'Removed' state.         <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1885'>https://wso2.org/jira/browse/EMM-1885</a></p>

**Comment by sinthuja** [comment]
Pasindu will check.

**Comment by sameeragunarathne** [comment]
This is already fixed in the latest release.
