### ISSUE TITLE
[EMM-1882] AppDownloadURLHost config is not used as App download URL

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#543]
<p>Reference: <a href='https://wso2.org/jira/browse/EMM-1882'>https://wso2.org/jira/browse/EMM-1882</a></p>

**Comment by geethkokila** [comment]
Tested on the IoT 3.1.0 cluster and issue did not occur, hence resolving the issue

**Comment by geethkokila** [comment]
Tested the issue on IoT Server 3.1.0 cluster and issue did not occur, hence resolving the issue.
