### ISSUE TITLE
[EMM-1880] Installation of apk fails for different content-type other than application/octet-stream

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#544]
When trying to install an apk via POST /admin/devices/install-application it fails for a content-type other than application/octet-stream.         <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1880'>https://wso2.org/jira/browse/EMM-1880</a></p>

**Comment by sameeragunarathne** [comment]
fixed in d907f1bc512d3c94c6191419ec6c0753172f1421
