### ISSUE TITLE
[EMM-1873] Issues with -Dsetup

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#546]
Tables are not properly created when started with -Dsetup            eg : Error when adding mobile applications                           &#91;2017-03-03 12:14:07,406&#93;               ERROR                        {org.wso2.carbon.appmgt.impl.dao.AppMDAO}                           - Failed to retrieve business owners.                              org.postgresql.util.PSQLException: ERROR: relation "apm_business_owner" does not exist                              Position: 15                              at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2310)                              at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2023)                              at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217)                              at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:421)                              at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)                              at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)                              at org.wso2.carbon.appmgt.impl.dao.AppMDAO.getBusinessOwners(AppMDAO.java:358)                              at org.wso2.carbon.appmgt.impl.APIProviderImpl.getBusinessOwners(APIProviderImpl.java:172)                              at org.wso2.carbon.appmgt.impl.UserAwareAPIProvider.getBusinessOwners(UserAwareAPIProvider.java:36)                              at org.wso2.carbon.appmgt.hostobjects.APIProviderHostObject.jsFunction_getBusinessOwners(APIProviderHostObject.java:378)                              at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                              at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                              at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                              at java.lang.reflect.Method.invoke(Method.java:498)                              at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)                              at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)                              at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)                              at org.jaggeryjs.rhino.publisher.assets.default.c1._c_getBusinessOwner_2(/publisher/assets/default/asset.jag:53)                              at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)                              at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)                              at org.jaggeryjs.rhino.publisher.assets.default.c1._c_anonymous_3(/publisher/assets/default/asset.jag:109)                              at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)                              at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)                              at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183)                              at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js)                              at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)                              at org.jaggeryjs.rhino.publisher.assets.default.c1._c_anonymous_1(/publisher/assets/default/asset.jag:701)                              at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)                              at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)                              at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)                              at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)                              at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)                              at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438)                              at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)                              at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)                              at org.jaggeryjs.rhino.&lt;store&gt;.scripts.c0._c_anonymous_17(&lt;store&gt;/scripts/server.js:286)                              at org.jaggeryjs.rhino.&lt;store&gt;.scripts.c0.call(&lt;store&gt;/scripts/server.js)                              at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)                              at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433)                              at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)                              at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)                              at org.jaggeryjs.rhino.publisher.assets.default.c1._c_script_0(/publisher/assets/default/asset.jag:24)                              at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)                              at org.jaggeryjs.rhino.publisher.assets.default.c1.exec(/publisher/assets/default/asset.jag)                              at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)                              at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)                              at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:309)                              at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:149)                              at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                              at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                              at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                              at java.lang.reflect.Method.invoke(Method.java:498)                              at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)                              at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)                              at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)                              at org.jaggeryjs.rhino.publisher.controllers.c3._c_anonymous_1(/publisher/controllers/asset_router.jag:87)                              at org.jaggeryjs.rhino.publisher.controllers.c3.call(/publisher/controllers/asset_router.jag)                              at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)                              at org.jaggeryjs.rhino.publisher.controllers.c3._c_script_0(/publisher/controllers/asset_router.jag:8)                              at org.jaggeryjs.rhino.publisher.controllers.c3.call(/publisher/controllers/asset_router.jag)                              at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)                              at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)                              at org.jaggeryjs.rhino.publisher.controllers.c3.call(/publisher/controllers/asset_router.jag)                              at org.jaggeryjs.rhino.publisher.controllers.c3.exec(/publisher/controllers/asset_router.jag)                              at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)                              at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)                              at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)                              at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)                              at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)                              at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)                              at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)                              at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)                              at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)                              at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)                              at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.wso2.carbon.ui.filters.cache.URLBasedCachePreventionFilter.doFilter(URLBasedCachePreventionFilter.java:57)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)                              at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)                              at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)                              at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)                              at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)                              at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:59)                              at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)                              at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)                              at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)                              at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45)                              at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)                              at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)                              at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)                              at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)                              at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)                              at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)                              at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)                              at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082)                              at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623)                              at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756)                              at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715)                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                              at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)                              at java.lang.Thread.run(Thread.java:745)                              &#91;2017-03-03 12:14:07,419&#93;               ERROR                        {org.jaggeryjs.jaggery.core.manager.WebAppManager}                           - org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.api.AppManagementException: Failed to retrieve business owners. (/publisher/assets/default/asset.jag#53) (/publisher/controllers/asset_router.jag#87)                              org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.api.AppManagementException: Failed to retrieve business owners. (/publisher/assets/default/asset.jag#53) (/publisher/controllers/asset_router.jag#87)                              at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)                              at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)                              at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)                              at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)                              at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)                              at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)                              at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)                              at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)                              at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)                              at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)                              at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.wso2.carbon.ui.filters.cache.URLBasedCachePreventionFilter.doFilter(URLBasedCachePreventionFilter.java:57)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)                              at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)                              at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)                              at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218)                              at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)                              at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)                              at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)                              at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)                              at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:59)                              at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)                              at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)                              at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)                              at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45)                              at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)                              at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)                              at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)                              at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)                              at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)                              at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)                              at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442)                              at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082)                              at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623)                              at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756)                              at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715)                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)                              at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)                              at java.lang.Thread.run(Thread.java:745)                              Caused by: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.api.AppManagementException: Failed to retrieve business owners. (/publisher/assets/default/asset.jag#53) (/publisher/controllers/asset_router.jag#87)                              at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)                              at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)                              at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)                              at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)                              at org.jaggeryjs.rhino.publisher.controllers.c3._c_anonymous_1(/publisher/controllers/asset_router.jag:87)                              at org.jaggeryjs.rhino.publisher.controllers.c3.call(/publisher/controllers/asset_router.jag)                              at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)                              at org.jaggeryjs.rhino.publisher.controllers.c3._c_script_0(/publisher/controllers/asset_router.jag:8)                              at org.jaggeryjs.rhino.publisher.controllers.c3.call(/publisher/controllers/asset_router.jag)                              at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)                              at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)                              at org.jaggeryjs.rhino.publisher.controllers.c3.call(/publisher/controllers/asset_router.jag)                              at org.jaggeryjs.rhino.publisher.controllers.c3.exec(/publisher/controllers/asset_router.jag)                              at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)                              ... 49 more                              Caused by: org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.api.AppManagementException: Failed to retrieve business owners. (/publisher/assets/default/asset.jag#53)                              at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)                              at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)                              at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:309)                              at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:149)                              at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                              at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                              at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                              at java.lang.reflect.Method.invoke(Method.java:498)                              at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)                              ... 61 more                              Caused by: org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.appmgt.api.AppManagementException: Failed to retrieve business owners. (/publisher/assets/default/asset.jag#53)                              at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)                              at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)                              at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)                              at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)                              at org.jaggeryjs.rhino.publisher.assets.default.c1._c_getBusinessOwner_2(/publisher/assets/default/asset.jag:53)                              at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)                              at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)                              at org.jaggeryjs.rhino.publisher.assets.default.c1._c_anonymous_3(/publisher/assets/default/asset.jag:109)                              at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)                              at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)                              at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183)                              at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js)                              at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)                              at org.jaggeryjs.rhino.publisher.assets.default.c1._c_anonymous_1(/publisher/assets/default/asset.jag:701)                              at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)                              at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)                              at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)                              at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)                              at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)                              at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438)                              at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)                              at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)                              at org.jaggeryjs.rhino.&lt;store&gt;.scripts.c0._c_anonymous_17(&lt;store&gt;/scripts/server.js:286)                              at org.jaggeryjs.rhino.&lt;store&gt;.scripts.c0.call(&lt;store&gt;/scripts/server.js)                              at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)                              at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433)                              at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)                              at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)                              at org.jaggeryjs.rhino.publisher.assets.default.c1._c_script_0(/publisher/assets/default/asset.jag:24)                              at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)                              at org.jaggeryjs.rhino.publisher.assets.default.c1.exec(/publisher/assets/default/asset.jag)                              at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)                              ... 69 more                              Caused by: org.wso2.carbon.appmgt.api.AppManagementException: Failed to retrieve business owners.                              at org.wso2.carbon.appmgt.impl.dao.AppMDAO.handleException(AppMDAO.java:4979)                              at org.wso2.carbon.appmgt.impl.dao.AppMDAO.getBusinessOwners(AppMDAO.java:374)                              at org.wso2.carbon.appmgt.impl.APIProviderImpl.getBusinessOwners(APIProviderImpl.java:172)                              at org.wso2.carbon.appmgt.impl.UserAwareAPIProvider.getBusinessOwners(UserAwareAPIProvider.java:36)                              at org.wso2.carbon.appmgt.hostobjects.APIProviderHostObject.jsFunction_getBusinessOwners(APIProviderHostObject.java:378)                              at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                              at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                              at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                              at java.lang.reflect.Method.invoke(Method.java:498)                              at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)                              ... 99 more                              Caused by: org.postgresql.util.PSQLException: ERROR: relation "apm_business_owner" does not exist                              Position: 15                              at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2310)                              at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2023)                              at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:217)                              at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:421)                              at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:166)                              at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)                              at org.wso2.carbon.appmgt.impl.dao.AppMDAO.getBusinessOwners(AppMDAO.java:358)                              ... 107 more                     <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1873'>https://wso2.org/jira/browse/EMM-1873</a></p>

**Comment by rasika** [comment]
This is not reproduced in current master IoT Server v310.
