### ISSUE TITLE
[EMM-1870] Unable to use special characters for passwords

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#548]
Setting a password from the web interface will show a "Invalid credentials" when attempting to enroll that device. I specifically tried a password ending with "!!".         <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1870'>https://wso2.org/jira/browse/EMM-1870</a></p>

**Comment by inoshperera** [comment]
This is fixed in IoT 3.1.0-M7
