### ISSUE TITLE
[EMM-1851] Duplicate iOS App and webclip install occurs when one user registers two devices

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#550]
STR:                              Register a iPhone and a iPad under one user.                              Then perform a iOS webclip install to the user.                              Two webclips are installed on both iphone and iPad.                     <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1851'>https://wso2.org/jira/browse/EMM-1851</a></p>

**Comment by Malintha** [comment]
Hi Hasunie,

We have fixed that in the EMM 2.0.1 in the support branch. Please check the fix there.

BR,
Malintha

**Comment by milanperera** [comment]
It was due to an issue in the app manager component and it was fixed in the latest version.
