### ISSUE TITLE
[EMM-1828] When trying to add a user/role in EMM console while SSO is enabled, exception is thrown

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#554]
Following exception is thrown in back-end                                                                  [2016-11-16 12:10:34,478] ERROR {java.lang.                     Class                     } - Access Denied. Failed authorization attempt to access service 'UserStoreConfigAdminService' operation 'getSecondaryRealmConfigurations' by 'admin@carbon.                     super                     ' [2016-11-16 12:10:34,504] ERROR {/app/modules/business-controllers/user.js} - Error retrieving secondary user stores org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: Access Denied. (/emm/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function)#2) at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148) at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.emm.app.modules.oauth.c0._c_anonymous_10(/emm/app/modules/oauth/token-                     protected                     -service-invokers.js:228) at org.jaggeryjs.rhino.emm.app.modules.oauth.c0.call(/emm/app/modules/oauth/token-                     protected                     -service-invokers.js) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.emm.app.modules.oauth.c0._c_anonymous_11(/emm/app/modules/oauth/token-                     protected                     -service-invokers.js:250) at org.jaggeryjs.rhino.emm.app.modules.oauth.c0.call(/emm/app/modules/oauth/token-                     protected                     -service-invokers.js) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.emm.app.modules.business_controllers.c0._c_anonymous_26(/emm/app/modules/business-controllers/user.js:614) at org.jaggeryjs.rhino.emm.app.modules.business_controllers.c0.call(/emm/app/modules/business-controllers/user.js) at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85) at org.jaggeryjs.rhino.emm.app.pages.cdmf.page.user.create.c1._c_onRequest_1(/emm/app/pages/cdmf.page.user.create/create.js:41) at org.jaggeryjs.rhino.emm.app.pages.cdmf.page.user.create.c1.call(/emm/app/pages/cdmf.page.user.create/create.js) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.emm.lib.modules.handlebars.c0._c_executeScript_8(/emm/lib/modules/handlebars/handlebars.js:239) at org.jaggeryjs.rhino.emm.lib.modules.handlebars.c0.call(/emm/lib/modules/handlebars/handlebars.js) at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63) at org.jaggeryjs.rhino.emm.lib.modules.handlebars.c0._c_pageHelper_10(/emm/lib/modules/handlebars/handlebars.js:295) at org.jaggeryjs.rhino.emm.lib.modules.handlebars.c0.call(/emm/lib/modules/handlebars/handlebars.js) at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430) at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269) at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97) at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1473) at script.anonymous(/emm/lib/modules/handlebars/handlebars-v2.0.0.js#2236(Function):2) at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815) at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430) at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269) at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.emm.lib.modules.handlebars.c2._c_anonymous_44(/emm/lib/modules/handlebars/handlebars-v2.0.0.js:558) at org.jaggeryjs.rhino.emm.lib.modules.handlebars.c2.call(/emm/lib/modules/handlebars/handlebars-v2.0.0.js) at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430) at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269) at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.emm.lib.modules.handlebars.c2._c_anonymous_142(/emm/lib/modules/handlebars/handlebars-v2.0.0.js:2029) at org.jaggeryjs.rhino.emm.lib.modules.handlebars.c2.call(/emm/lib/modules/handlebars/handlebars-v2.0.0.js) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.emm.lib.modules.handlebars.c0._c_anonymous_16(/emm/lib/modules/handlebars/handlebars.js:706) at org.jaggeryjs.rhino.emm.lib.modules.handlebars.c0.call(/emm/lib/modules/handlebars/handlebars.js) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.emm.lib.c6._c_anonymous_4(/emm/lib/dynamic-files-renderer.js:97) at org.jaggeryjs.rhino.emm.lib.c6.call(/emm/lib/dynamic-files-renderer.js) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.emm.lib.c6._c_anonymous_3(/emm/lib/dynamic-files-renderer.js:80) at org.jaggeryjs.rhino.emm.lib.c6.call(/emm/lib/dynamic-files-renderer.js) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.emm.lib.c2._c_anonymous_5(/emm/lib/pages-router.js:181) at org.jaggeryjs.rhino.emm.lib.c2.call(/emm/lib/pages-router.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.emm.lib.c0._c_script_0(/emm/lib/pages.jag:23) at org.jaggeryjs.rhino.emm.lib.c0.call(/emm/lib/pages.jag) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) at org.jaggeryjs.rhino.emm.lib.c0.call(/emm/lib/pages.jag) at org.jaggeryjs.rhino.emm.lib.c0.exec(/emm/lib/pages.jag) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567) at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273) at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588) at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508) at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24) at javax.servlet.http.HttpServlet.service(HttpServlet.java:624) at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747) at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485) at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377) at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337) at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:59) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47) at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57) at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45) at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956) at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.                     Thread                     .run(                     Thread                     .java:745) Caused by: org.jaggeryjs.scriptengine.exceptions.ScriptException: Access Denied. at org.jaggeryjs.modules.ws.WSRequestHostObject.jsFunction_send(WSRequestHostObject.java:404) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) ... 100 more Caused by: org.apache.axis2.AxisFault: Access Denied. at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531) at org.apache.axis2.description.OutInAxisOperationClient.handleResponse(OutInAxisOperation.java:370) at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:445) at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:225) at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) at org.apache.axis2.client.ServiceClient.sendReceive(ServiceClient.java:554) at org.jaggeryjs.modules.ws.WSRequestHostObject.jsFunction_send(WSRequestHostObject.java:379) ... 105 more                                                      <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1828'>https://wso2.org/jira/browse/EMM-1828</a></p>

**Comment by geethkokila** [comment]
This is tested on the IoT server 3.1.0 cluster and did not occur. Hence resolving the issue.
