### ISSUE TITLE
[EMM-1816] By default https://localhost:9443/ redirect to carbon console - redirect to /emm instead

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#555]
By default when you try to load               https://localhost:9443               it redirects to carbon console. Better to change this behavior to redirect to /emm instead. If you look at API Manager it redirect to /publisher by default. This make user experience a little better IMHO                     <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1816'>https://wso2.org/jira/browse/EMM-1816</a></p>

**Comment by sinthuja** [comment]
@Nirothipan will work on this.
