### ISSUE TITLE
[EMM-1484] VPN Operation creates a new VPN everytime

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#556]
WSO2 EMM Version: 2.0.1                              Database: MySQL                                       I am setting VPN on iOS device using               https://docs.wso2.com/display/EMM201/Setting+Up+a+VPN+on+iOS+Devices+via+the+REST+API               API.                        But every time I call an API, WSO2EMM is creating a new VPN. I just want to update an existing VPN connection or remove the VPN connection if an update is not possible.                           Stackoverflow link:               http://stackoverflow.com/questions/38633661/wso2-emm-everytime-creates-a-new-vpn                     <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1484'>https://wso2.org/jira/browse/EMM-1484</a></p>

**Comment by sameeragunarathne** [comment]
This cannot be controlled at the device level since vpn operation is executed from iOS system app.
