### ISSUE TITLE
[EMM-1428] Refer keystore password details from carbon.xml file

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#557]
EMM uses config.josn file located at &lt;EMM_HOME&gt;/repository/deployment/server/jaggeryapps/emm/config location, which contains the key store related details. Since key store related details are maintained in carbon.xml file it would be better to refer key store information from carbon.xml, rather than maintaining separate configuration files.            Note - If a user wants to encrypt the key store information in json.config file, manual configuration can be used, but the component should be capable of decrypting the value.         <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1428'>https://wso2.org/jira/browse/EMM-1428</a></p>

**Comment by sinthuja** [comment]
@Nirothipan will work on this.

**Comment by Nirothipan** [comment]
These details have been currently removed from config.json and no longer exists. Hence closed.

**Comment by sinthuja** [comment]
Cannot automate, as this configuration has been removed for some time, and we just verified and closed the issue.
