### ISSUE TITLE
[EMM-1098] [EMM Cluster] Hazelcast Task issue in the worker node after the startup

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#559]
After sometime of the startup of the server, the following exception can be seen.                                                                  [2015-12-15 14:33:08,985] ERROR {com.hazelcast.spi.impl.eventservice.impl.EventServiceImpl} - [192.168.48.88]:4100 [wso2.emm.domain] [3.5.2] hz.wso2.emm.domain.instance.event-2 caught an exception                     while                     processing task:com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher@67a82eda java.lang.NullPointerException at org.wso2.carbon.caching.impl.CacheImpl$MapEntryListenerImpl.entryUpdated(CacheImpl.java:1115) at org.wso2.carbon.core.clustering.hazelcast.HazelcastDistributedMapProvider$DistMap$1.entryUpdated(HazelcastDistributedMapProvider.java:88) at com.hazelcast.map.impl.MapListenerAdaptors$4$1.onEvent(MapListenerAdaptors.java:125) at com.hazelcast.map.impl.InternalMapListenerAdapter.onEvent(InternalMapListenerAdapter.java:51) at com.hazelcast.map.impl.MapEventPublishingService.callListener(MapEventPublishingService.java:90) at com.hazelcast.map.impl.MapEventPublishingService.dispatchEntryEventData(MapEventPublishingService.java:102) at com.hazelcast.map.impl.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:46) at com.hazelcast.map.impl.MapEventPublishingService.dispatchEvent(MapEventPublishingService.java:33) at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:91) at com.hazelcast.map.impl.MapService.dispatchEvent(MapService.java:61) at com.hazelcast.spi.impl.eventservice.impl.LocalEventDispatcher.run(LocalEventDispatcher.java:63) at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:190) at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:174)                                                      <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1098'>https://wso2.org/jira/browse/EMM-1098</a></p>

**Comment by geethkokila** [comment]
Use of Hazelcast is deprecated in the IoT  3.1.0. Hence resolving
