### ISSUE TITLE
[EMM-1648] Table 'nameTag.REG_LOG' doesn't exist when started with -Dsetup

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#560]
Table '&lt;name&gt;.REG_LOG' doesn't exist when started with -Dsetup and same issue was observed IS, ESB and APIM packs            Mail Thread : Table 'REG_LOG' doesn't exist                                             https://wso2.org/jira/browse/APIMANAGER-2199                                                https://wso2.org/jira/browse/IDENTITY-3750                                                https://wso2.org/jira/browse/ESBJAVA-2539                                                                        [2016-09-28 02:03:42,153] ERROR {org.wso2.carbon.registry.core.jdbc.dao.JDBCLogsDAO} - Failed to update log batch records . Table 'emm22regdb.REG_LOG' doesn't exist java.sql.BatchUpdateException: Table 'emm22regdb.REG_LOG' doesn't exist at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) at com.mysql.jdbc.Util.getInstance(Util.java:387) at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1161) at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773) at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257) at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958) at org.wso2.carbon.registry.core.jdbc.dao.JDBCLogsDAO.addLogRecords(JDBCLogsDAO.java:159) at org.wso2.carbon.registry.core.jdbc.dao.JDBCLogsDAO.saveLogBatch(JDBCLogsDAO.java:123) at org.wso2.carbon.registry.core.utils.LogWriter.logWrite(LogWriter.java:106) at org.wso2.carbon.registry.core.utils.LogWriter.run(LogWriter.java:91) Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'emm22regdb.REG_LOG' doesn't exist at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) at com.mysql.jdbc.Util.getInstance(Util.java:387) at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942) at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966) at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902) at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526) at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673) at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549) at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073) at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751) ... 6 more [2016-09-28 02:03:42,157] INFO {org.wso2.carbon.registry.core.jdbc.EmbeddedRegistryService} - Configured Registry in 569ms [2016-09-28 02:03:42,163] ERROR {org.wso2.carbon.registry.core.utils.LogWriter} - Unable to save log records org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to update log batch records . Table 'emm22regdb.REG_LOG' doesn't exist at org.wso2.carbon.registry.core.jdbc.dao.JDBCLogsDAO.addLogRecords(JDBCLogsDAO.java:176) at org.wso2.carbon.registry.core.jdbc.dao.JDBCLogsDAO.saveLogBatch(JDBCLogsDAO.java:123) at org.wso2.carbon.registry.core.utils.LogWriter.logWrite(LogWriter.java:106) at org.wso2.carbon.registry.core.utils.LogWriter.run(LogWriter.java:91) Caused by: java.sql.BatchUpdateException: Table 'emm22regdb.REG_LOG' doesn't exist at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) at com.mysql.jdbc.Util.getInstance(Util.java:387) at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1161) at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1773) at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1257) at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:958) at org.wso2.carbon.registry.core.jdbc.dao.JDBCLogsDAO.addLogRecords(JDBCLogsDAO.java:159) ... 3 more Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'emm22regdb.REG_LOG' doesn't exist at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.lang.reflect.Constructor.newInstance(Constructor.java:423) at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) at com.mysql.jdbc.Util.getInstance(Util.java:387) at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942) at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966) at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902) at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526) at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673) at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549) at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861) at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073) at com.mysql.jdbc.PreparedStatement.executeBatchSerially(PreparedStatement.java:1751) ... 6 more                                    <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1648'>https://wso2.org/jira/browse/EMM-1648</a></p>

**Comment by sinthuja** [comment]
Unable to reproduce this issue. I verified with IoT 3.1.0 and 3.1.1-SNAPSHOT as per today, and this issue is no longer exists.

**Comment by sinthuja** [comment]
As a whole scenario, there should be test cases added for different databases and starting with -Dsetup and check for any errors.
