### ISSUE TITLE
[EMM-1578] Can't distinguish registered devices, if the same mobiles with the same model in the EMM console

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#563]
There should be a way to change the name of the mobiles (android) in the EMM console. Otherwise, we can not identify them separately, if devices are registered with the same mobiles with the same model.         <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1578'>https://wso2.org/jira/browse/EMM-1578</a></p>

**Comment by geethkokila** [comment]
This is fixed with adding the device renaming option. Hence closing the issue.
