### ISSUE TITLE
[EMM-1409] Provide the android.os.Build.PRODUCT parameter value in device details

### ISSUE THREAD

**Issue by hasuniea** [wso2/product-iots#566]
The device name or the value o the android.os.Build.PRODUCT parameter is required when upgrading the firmware of a device               &#91;1&#93;               .                                       It will be easy for the user to get this info if we provide this on the WSO2 EMM console under device details               &#91;2&#93;               .                              /mdm-admin/devices/name/                        {name}            /            {tenatDomain}                           &#91;1&#93;               https://docs.wso2.com/display/EMM210/Upgrading+Firmware+of+an+Android+Device                              &#91;2&#93;               
https://docs.wso2.com/display/EMM210/Getting+Details+of+a+Device                     <p>Reference: <a href='https://wso2.org/jira/browse/EMM-1409'>https://wso2.org/jira/browse/EMM-1409</a></p>

**Comment by sinthuja** [comment]
Pasindu will check this.

**Comment by sinthuja** [comment]
This is no longer valid. OTA firmware can only hosted by the people who have signing keys for the firmware. i.e. device vendor. Hence the device vendor will define that parameter value. So it is a known value to them. Therefore closing this issue.
