### ISSUE TITLE
[IOTS-448] UI issue in immediate reload after deleting an artifact in publisher console

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#571]
Steps to reproduce :  1. Login to the EMM publisher console.  2. Add 2 artifacts (apps, or web services, any artifact). 3. Delete the artifact listed as "first" in the publisher page.  Notice that just upon clicking the reload button, the page is displayed with no artifacts. After refreshing a couple times, the remaining artifact will be displayed.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-448'>https://wso2.org/jira/browse/IOTS-448</a></p>

**Comment by sameeragunarathne** [comment]
This is already fixed. Not reproducible in latest release.
