### ISSUE TITLE
[IOTS-532] Error with android-tryit

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#576]
I unzipped wso2iot-3.1.0 I go to the Device Management console to add a virtual Android device.    I have nothing to modify in the configuration files of wso2iot and I work in localhost under Ubuntu with Java 1.8. When I go to the android-tryit folder, I run the sh start command in a console. I have 2 errors displayed. Here is the screen impression:    Could you help me fix this bug. Best regards Christophe<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-532'>https://wso2.org/jira/browse/IOTS-532</a></p>

**Comment by Nirothipan** [comment]
Please try starting the script with ./ instead of sh and now we have changed the script. can be referred in https://docs.wso2.com/display/IoTS310/Android+Virtual+Device .
