### ISSUE TITLE
[IOTS-531] WSO2 IOT with Mysql

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#577]
I have changed the Database configuration from H2 to Mysql the wso2iot server 3.0.0. All the three servers run perfect, but still I am not able to access the device management. I have gone through all the documentation and tried still I could not get that. Please find the error screen captures below. I have been working on the for a week, Still I could not configure the mysql database in the iot server. It runs perfect when I try with the default H2 database, It happens only when I use mysql. Error:<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-531'>https://wso2.org/jira/browse/IOTS-531</a></p>

**Comment by geethkokila** [comment]
This issue is fixed and tested in 3.1.0, hence closing.
