### ISSUE TITLE
[IOTS-530] Starting IoT server in nohup mode

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#578]
The following doc &#91;1&#93; gives instructions for starting the product as a service/nohup mode for Solaris. When trying this out, came across the following bug.. The iot-server.sh file in &lt;IOTS_HOME&gt;/bin contains the following: `nohup sh $CARBON_HOME/bin/wso2server.sh $args > /dev/null 2>&1 &` AFAIU, this should be corrected to: `nohup sh $CARBON_HOME/bin/iot-server.sh $args > /dev/null 2>&1 &` Please check and correct this.  &#91;1&#93; https://docs.wso2.com/display/IoTS310/Running+the+Product#ecd28e7e78fb472ab7e8b7119c411dd3<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-530'>https://wso2.org/jira/browse/IOTS-530</a></p>

**Comment by rasika** [comment]
This is already fixed in latest doc. Reader can switch into profiles and get the necessary command that need to be replaced.

<img width="1066" alt="screen shot 2017-06-28 at 12 33 00 pm" src="https://user-images.githubusercontent.com/1448489/27624386-22730f68-5bfe-11e7-913e-1159a1932cf4.png">
