### ISSUE TITLE
Device statistics does not show details of the enrolled android device

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#579]
I have enrolled an android device and performed some operations too. When I navigate to the device statistics portal the. Device count is 0 and there are no information displayed for the enrolled device.

**Comment by jsonds** [comment]
**Labels -** 3.1.0-M8, Bug, Blocker

**Comment by geethkokila** [comment]
This portal will be removed from the IoT server 3.1.0. Hence no fixes are needed.
