### ISSUE TITLE
NoClassDefFoundError thrown when starting the pack in Windows 2012

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#582]
When starting a fresh pack with start-all.bat in a windows 2012 instance the below exception is thrown. 

![noclassdeff](https://cloud.githubusercontent.com/assets/17248809/26665354/a1e229e4-46b6-11e7-88f9-370192d57377.jpg)

**Comment by jsonds** [comment]
**Labels -**  3.1.0-M8, Bug, High

**Comment by milanperera** [comment]
Snappy is a dependent jar which needs to be copied to the lib folder prior to starting the server in windows as pointed in [1].
However if it is missing in the IoT documentation, then that should be added to the prerequisites section of the doc.
@shavidissa do we have that in the doc? I cant seem to find it.

**Comment by jsonds** [comment]
I added the snappy jar as mentioned in the doc [1\] but still the same exception is thrown at start-up

[1\] https://docs.wso2.com/display/DAS301/Installing+on+Windows

**Comment by sinthuja** [comment]
Hi Jason,

I just tried to reproduce the above mentioned error on Windows 2012, and I was able to reproduce this error initially before placing the jar in the IoT_HOME/lib directory.

Please note as the IoT server is having different directory structure opposed to DAS. Therefore DAS_HOME/repository/components/lib directory is mapped to IoT_HOME/lib directory. Therefore the snappy jar needs to be placed under IoT_HOME/lib/ directory than IoT_HOME/repository/components/lib as mentioned in [1].

We need to include this in the documentation. Not further code level fixes needed for this. @shavidissa Can you please add this information on running Analytics IoT in Windows section.

[1] https://docs.wso2.com/display/DAS301/Installing+on+Windows

**Comment by sinthuja** [comment]
@shavidissa Please close this issue once the documentation is added.

**Comment by shavidissa** [comment]
Thank you, Sinthuja, Jason, and Milan! I updated the docs with the info.
[1] https://docs.wso2.com/display/IoTS310/Installing+on+Windows
