### ISSUE TITLE
The iOS Agent packed in the M8 release is having issues which cause the Agent download failure

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#584]
The iOS Agent app which is packed inside the M8 release is causing some unknown issues which result in a failure of the download in the device side. We may need to replace it with a correct app. 

Failed app md5: 3d84bf8dd0695f0436c50bef3d33e094

**Comment by milanperera** [comment]
Added a new ios agent to the ios-configurator [1]. Also from iOS 10 onwards, self signed ssl certificates will not be accepted by the OS, hence it fails to download and install the configuration profile.
For this to overcome, iOS has introduced a new configuration in the settings and wso2 docs will be updated [2].

[1] https://github.com/wso2/carbon-devicemgt-proprietary-plugins/pull/110
[2] https://wso2.org/jira/browse/DOCUMENTATION-4527
