### ISSUE TITLE
iOS Agent download url is HTTP in the app config file. 

### ISSUE THREAD

**Issue by chamaraanu** [wso2/product-iots#585]
The iOS Agent download url is mentioned as: 
"location": "%http.ip%/ios-web-agent/public/mdm.page.enrollments.ios.download-agent/asset/ios-agent.ipa",

in the repository/deployment/server/jaggeryapps/ios-web-agent/app/conf/config.json. 

This needs to be fixed to have https.ip.

**Comment by milanperera** [comment]
This is fixed in https://github.com/wso2/carbon-devicemgt-proprietary-plugins/pull/105
