### ISSUE TITLE
[IOTS-533] wso2 iot server with postgresql case insensitive

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#588]
I have configured the wso2 iot server with postgreSQL, everything works fine. Now the issue is with the adding new device. The error occurs while downloading the agent, the device id is generated and stored in various device management tables. Now the issue is with gm_group where device group details are stored each time while enrolling a new device. Please see the below error.  GroupDAOImpl is the file which makes such exception due to 50th line. This issue is may be with the UTF8 BOM and the collision also, but I am not sure. Please see the below screen capture for database info.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-533'>https://wso2.org/jira/browse/IOTS-533</a></p>

**Comment by thomsonimjd** [comment]
Please any one, provide solution for this.

**Comment by harshanL** [comment]
This issue has been fixed with PR : https://github.com/wso2/carbon-device-mgt/pull/783
