### ISSUE TITLE
[IOTS-497] EMM policies not pushing to device - Android

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#589]
When applying Android policies with IoT server 3.0 policies do not get applied to devices (not showing under Policy Compliance). Once servers are re-started only one policy gets applied. If there are multiple policies all others are hanging in queued state, no errors showing.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-497'>https://wso2.org/jira/browse/IOTS-497</a></p>

**Comment by geethkokila** [comment]
This is tested with Iot Server 3.1.0 cluster and issue never appeared. Hence closing
