### ISSUE TITLE
[IOTS-471] Better to have confirmation pop ups when changing the life cycle of an application in Publisher

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#593]
Currently there're no pop ups to confirm changes in life cycle states from one another for applications listed in Publisher.  There's a higher possibility of accidental change of the life cycle states where user cannot revert back to previous state. As an example, user may press the deprecate button in the state of "published" of an application which cannot revert back. So it's better to provide confirmation alerts to user whenever a state change happens to avoid such accidental actions.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-471'>https://wso2.org/jira/browse/IOTS-471</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
