### ISSUE TITLE
[IOTS-444] Too many open files when an iOS device registered within the EMM server.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#595]
The number of open files dramatically increases over time when an iOS device is registered in EMM server.  Possible cause: too many open connections due to starting new connections without closing old connections.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-444'>https://wso2.org/jira/browse/IOTS-444</a></p>

**Comment by geethkokila** [comment]
This is was fixed with latest iOS components. Fixing the apns connection issues resolved above the issue.
