### ISSUE TITLE
[IOTS-456] Starting the EMM server on Windows 10 Fails

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#596]
Cannot start server on Windows, the following error occurs - Error: Could not find or load main class org.wso2.carbon.bootstrap.Bootstrap The issue prevails even if the path to JAVA_HOME has no white spaces<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-456'>https://wso2.org/jira/browse/IOTS-456</a></p>

**Comment by sinthuja** [comment]
This issue is not existing anymore and verrified with v 3.1.0 pack. Hence closing this issue.
