### ISSUE TITLE
[IOTS-405] Claim Menu Duplicated

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#599]
When working with the IOTS - RC2 pack I noticed that the claims menu was duplicated (see the screenshots) in the IOTS management console, which is incorrect. The claims menu options need to be checked, revised, and merged.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-405'>https://wso2.org/jira/browse/IOTS-405</a></p>

**Comment by sinthuja** [comment]
@sameerawickramasekara will check on this.
