### ISSUE TITLE
[IOTS-404] [UX] Andriod web agent page logo not appears as IOT logo

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#600]
Access android web agent page via device browser, and on top of the page EMM logo still appears (see attached logo.jpeg). It is good to change the logo to IOT.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-404'>https://wso2.org/jira/browse/IOTS-404</a></p>

**Comment by inoshperera** [comment]
This is not reproducible in the current pack.
