### ISSUE TITLE
[IOTS-403] Buttons on the Virtual fire alarm emulator don't function

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#601]
The Control device and View device data buttons in the emulator don't function (see attached screenshot). As a fix, as discussed with Ayyoob and Rasika these buttons need to be removed from the emulator as it tries to contact port 8243 without going to 9443.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-403'>https://wso2.org/jira/browse/IOTS-403</a></p>

**Comment by inoshperera** [comment]
This is fixed in the IoT 3.1.0-M8
