### ISSUE TITLE
[IOTS-203] Messages delivered to command topic are not delivered to unavailable subscribers at reconnection

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#606]
When multiple devices are subscribed the same command topic, messages delivered to the command topic are not delivered to unavailable subscribers at re-connection even when QOS values are changed. to reproduce 1. change MQTT QOS level values. 2. enroll two custom devices. the devices should be subscribed to the same command topic. 3. make one device unavailable. 4. call /change-status?state=off 5. the command gets delivered to the available device. Once the unavailable device is made available the command is not delivered to it.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-203'>https://wso2.org/jira/browse/IOTS-203</a></p>

**Comment by geethkokila** [comment]
This is fixed with MB 3.2.0, Fix is adhering to QOS values.
