### ISSUE TITLE
[IOTS-524] No data in the analytics view for fire alarm and connected cup samples

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#610]
When running fire alarm and connected cup examples I notice that analytics view behaves very strange, i.e. usually it doesn't show any data, or on some occasions it shows the data, but then when trying to refresh the view it looses them. In the meanwhile, real time data are shown correctly, except that fire alarm data published with the period of 1 second can't be displayed in real time (multiple temperature values are shown for the same time value, resulting in orthogonal lines on the graph)<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-524'>https://wso2.org/jira/browse/IOTS-524</a></p>

**Comment by sinthuja** [comment]
The issue doesn't exist anymore.
