### ISSUE TITLE
[IOTS-521] samples-deployer.xml build fails with missing dependency

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#611]
Dear, performing Step 2.e: Creating a new device type (https://docs.wso2.com/display/IoTS300/Creating+a+New+Device+Type), the build failed because it could not resolve pendencies in one of projects. I am sending you attached the stacktrace of the command (mvn clean install -f samples-deployer.xml) and the pom of the project that gave error. For more information (http://stackoverflow.com/questions/43127409/wso2-iot-samples-deployer-xml-build-fails-with-missing-dependency)<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-521'>https://wso2.org/jira/browse/IOTS-521</a></p>

**Comment by geethkokila** [comment]
Fix is to add "<....filtered>true</filtered....>" for https://github.com/wso2/product-iots/blob/master/modules/distribution/src/assembly/bin.xml  

        <fileSet>
            <directory>src/core/samples</directory>
            <outputDirectory>${pom.artifactId}-${pom.version}/samples</outputDirectory>
            <includes>
                <include>*/**</include>
            </includes>
            <fileMode>644</fileMode>
        </fileSet>

**Comment by sinthuja** [comment]
This issue is not there anymore, and can run the samples without any issues.
