### ISSUE TITLE
[IOTS-517] The Device mutes after the ring operation

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#612]
Steps followed: Triggered the ring operation. Stopped the ring operation. The Android device goes to do-not-disturb state.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-517'>https://wso2.org/jira/browse/IOTS-517</a></p>

**Comment by sinthuja** [comment]
@Nirothipan will work on this.

**Comment by Nirothipan** [comment]
This issue is not reproduced in IoTs 3.1.0.
Tested enrolling an Android ( 7.0 ) device to the server.
I triggered the ring operation and stopped it in the device, the device did not enter do not disturb state.

**Comment by sinthuja** [comment]
Closing this issue as it was verified by Nirothipan.

**Comment by sinthuja** [comment]
As this requires the android agent code also to be involved in the test case, we cannot automate this.
