### ISSUE TITLE
[IOTS-516] AppDownloadURLHost config is not used as App download URL

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#613]
The configuration AppDownloadURLHost defined for this purpose in app manager xml is not in use. Currently it is set from hostname from the retrieved from carbon xml.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-516'>https://wso2.org/jira/browse/IOTS-516</a></p>

**Comment by geethkokila** [comment]
Tested on the iot 3.1.0 cluster, and did not occur the issue.
