### ISSUE TITLE
[IOTS-514] The cloud UI directs to the wrong doc.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#614]
In device cloud, the following text redirects to IoT Server docs &#91;1&#93;. Instead, it should direct to &#91;2&#93;. Need help? Read WSO2 Device Cloud documentation. &#91;1&#93; https://docs.wso2.com/display/IoTS300/Android &#91;2&#93; https://docs.wso2.com/display/DeviceCloud/Enrolling+an+Android+Device<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-514'>https://wso2.org/jira/browse/IOTS-514</a></p>

**Comment by sinthuja** [comment]
Verified with device cloud and the documentation page redirects to correct documentation - https://docs.wso2.com/display/DeviceCloud/Enrolling+an+Android+Device when clicking on text - 'Need help? Read WSO2 Device Cloud documentation' on the Android device enrollment page.

**Comment by sinthuja** [comment]
As it's a UI redirection issue, cannot add any automation tests for this.
