### ISSUE TITLE
[IOTS-495] Work-profile not authenticating

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#617]
I can successfully enroll devices into the IoT 3.0.0 and 3.1.0 with port 9763, however, when choosing to setup a work-profile the app hangs on "Authenticating" and eventually times out. I've tried 8280, 9443, 80, and 9763 with the work-profile.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-495'>https://wso2.org/jira/browse/IOTS-495</a></p>

**Comment by geethkokila** [comment]
This issue is fixed, hence closing.
