### ISSUE TITLE
[IOTS-491] Some Android agent screens mention "EMM" instead of "IoTs"

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#618]
When enrolling an Android device, the following screens still mention "EMM" instead of "WSO2 IoTs". See attached screenshots.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-491'>https://wso2.org/jira/browse/IOTS-491</a></p>

**Comment by sameeragunarathne** [comment]
This is already fixed with the new agent version.
