### ISSUE TITLE
[IOTS-490] Device Management shows incorrect device status

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#619]
After powering off the device and waiting approx 15-30 minutes will show the device Inactive in EMM 2.2.0. In IoT version 3.0 the device is always in a Active state. Tested the device off for 12 hours - still shows Active. Using Moto G 2nd Gen running 6.0.1 and LG Nexus 5x 7.1.1.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-490'>https://wso2.org/jira/browse/IOTS-490</a></p>

**Comment by geethkokila** [comment]
@harshanL, Please comment.

**Comment by harshanL** [comment]
This issue has been fixed.
