### ISSUE TITLE
[IOTS-486] Production environment maps not visible

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#622]
Modified the IP addresses to our public IP address and enrolled several devices. When going to Device Location it shows a grey box with no Openstreet Maps visible. Inspecting the page source shows that it's trying to show a map with the correct device coordinates.  Currently running EMM 2.2 on another server and we do not get this issue.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-486'>https://wso2.org/jira/browse/IOTS-486</a></p>

**Comment by geethkokila** [comment]
This is fixed hence resolving.
