### ISSUE TITLE
[IOTS-484] IOTS SAMPLE returns build failure error

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#624]
Hi,  I am trying to build the sample "connectedcup" device and found below error  not find the components, please kindly revice behind log, Thanks. BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US Framework arguments: -application org.eclipse.equinox.p2.director -metadataRepository file:/data/wso2iot-3.0.0/samples/p2-repo -artifactRepository file:/data/wso2iot-3.0.0/samples/p2-repo -profileProperties org.eclipse.update.install.features=true -installIU org.coffeeking.connectedcup.feature.group/1.0.0, -bundlepool /data/wso2iot-3.0.0/samples/../core/repository/components -shared /data/wso2iot-3.0.0/samples/../core/repository/components/p2 -destination /data/wso2iot-3.0.0/samples/../core/repository/components/default -profile default -roaming Command-line arguments: -debug -consoleLog -application org.eclipse.equinox.p2.director -metadataRepository file:/data/wso2iot-3.0.0/samples/p2-repo -artifactRepository file:/data/wso2iot-3.0.0/samples/p2-repo -profileProperties org.eclipse.update.install.features=true -installIU org.coffeeking.connectedcup.feature.group/1.0.0, -bundlepool /data/wso2iot-3.0.0/samples/../core/repository/components -shared /data/wso2iot-3.0.0/samples/../core/repository/components/p2 -destination /data/wso2iot-3.0.0/samples/../core/repository/components/default -profile default -roaming !ENTRY org.eclipse.equinox.p2.director 4 1 2017-02-13 02:54:04.113 !MESSAGE Cannot complete the install because one or more required items could not be found. !SUBENTRY 1 org.eclipse.equinox.p2.director 4 0 2017-02-13 02:54:04.113 !MESSAGE Software being installed: WSO2 IoTS(Device Types) - Connected Cup Feature 1.0.0 (org.coffeeking.connectedcup.feature.group 1.0.0) !SUBENTRY 1 org.eclipse.equinox.p2.director 4 0 2017-02-13 02:54:04.113 !MESSAGE Missing requirement: WSO2 IoTS(Device Types) - Connected Cup Feature 1.0.0 (org.coffeeking.connectedcup.feature.group 1.0.0) requires 'org.coffeeking.connectedcup.plugin &#91;3.0.8&#93;' but it could not be found &#91;INFO&#93; ------------------------------------------------------------------------ &#91;INFO&#93; Reactor Summary: &#91;INFO&#93;  &#91;INFO&#93; WSO2 IoTS(Device Types) - Connected Cup Component . SUCCESS &#91;0.313s&#93; &#91;INFO&#93; WSO2 IoTS(Device Types) - Connected Cup Component . SUCCESS &#91;0.018s&#93; &#91;INFO&#93; WSO2 IoTS(Device Types) - Connected Cup Analytics capp SUCCESS &#91;0.547s&#93; &#91;INFO&#93; WSO2 IoTS(Device Types) - Connected Cup CDMF Plugin SUCCESS &#91;2.385s&#93; &#91;INFO&#93; WSO2 IoTS(Device Types) - Connected Cup API ....... SUCCESS &#91;4.134s&#93; &#91;INFO&#93; WSO2 IoTS(Device Types) - Connected Cup Agent Web app SUCCESS &#91;0.237s&#93; &#91;INFO&#93; WSO2 IoTS(Device Types) - Connected Cup UI ........ SUCCESS &#91;0.073s&#93; &#91;INFO&#93; WSO2 IoTS(Device Types) - Connected Cup Feature Parent SUCCESS &#91;0.012s&#93; &#91;INFO&#93; WSO2 IoTS(Device Types) - Connected Cup Feature ... SUCCESS &#91;0.803s&#93; &#91;INFO&#93; Creating custom distribution ...................... FAILURE &#91;5.626s&#93; &#91;INFO&#93; ------------------------------------------------------------------------ &#91;INFO&#93; BUILD FAILURE &#91;INFO&#93; ------------------------------------------------------------------------ &#91;INFO&#93; Total time: 14.599s &#91;INFO&#93; Finished at: Mon Feb 13 02:54:04 GMT 2017 &#91;INFO&#93; Final Memory: 133M/1711M &#91;INFO&#93; ------------------------------------------------------------------------ &#91;ERROR&#93; Failed to execute goal org.wso2.maven:carbon-p2-plugin:1.5.4:p2-profile-gen (default-feature-install) on project iot-devicetype-samples: P2 publisher return code was 13 -&gt; &#91;Help 1&#93; org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.wso2.maven:carbon-p2-plugin:1.5.4:p2-profile-gen (default-feature-install) on project iot-devicetype-samples: P2 publisher return code was 13 --------------------------------------------------------------------------------------------------------<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-484'>https://wso2.org/jira/browse/IOTS-484</a></p>

**Comment by geethkokila** [comment]
Need to build to Connected cup sample before building the sample deployer. Hence closing
