### ISSUE TITLE
[IOTS-483] Virtual File Alarm cannot run on Windows

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#625]
It only has a start-device.sh No .bat or instructions on how to run it on Windows<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-483'>https://wso2.org/jira/browse/IOTS-483</a></p>

**Comment by GDLMadushanka** [comment]
Fixed in https://github.com/wso2/carbon-device-mgt-plugins/commit/5cf096c7aa1c98ded431d9ff4fb06cdcd1f3aee1
