### ISSUE TITLE
[IOTS-438] dm_enrollment table is not updated with the correct owner name on re-enrollment

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#627]
dm_enrollment table is not updated with the correct owner name on re-enrollment.  Reproduction steps :  Enroll the first user to emm via ios agent (simon.elbaz) Disenroll the first user Enroll a second user on the same device via ios agent (kevin.fontaine) Current behavior : The table dm_enrollment is not updated with the correct owner : owner "simon.elbaz" The emm console doesn't display the correct user : owner "simon.elbaz" Expected behavior The table dm_enrollment should be updated with the correct owner. (kevin.fontaine) The emm console should display the correct owner "kevin.fontaine"<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-438'>https://wso2.org/jira/browse/IOTS-438</a></p>

**Comment by geethkokila** [comment]
This is fixed and tested, hence closing
