### ISSUE TITLE
[IOTS-432] Dashboard related permission not showing while trying to adding a new role in through role creation wizard

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#629]
After creating a new user using user creating wizard, there won't list out any permission which are related to dashboard. This will be an issue while newly created user trying log into dashboard.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-432'>https://wso2.org/jira/browse/IOTS-432</a></p>

**Comment by geethkokila** [comment]
We have removed dashboard for analytics 3.1.0 hence resolving
