### ISSUE TITLE
[IOTS-453] QR code generate at auto enrollment is incorrect when fronted by a load balancer

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#630]
The QR code generate in the auto-enrolment is incorrect when the EMM is fronted with a load balancer.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-453'>https://wso2.org/jira/browse/IOTS-453</a></p>

**Comment by geethkokila** [comment]
This is tested in the IoT 3.1.0 cluster. Issue did not appear. hence closing
