### ISSUE TITLE
[IOTS-211] Accessing API with version number fails with 404

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#650]
Accessing API with version(as shown in the api-store) fail with 404. The same api call excluding the version number works.   dumiduh@dumiduh-Latitude-E6540:~/KEYS$ curl -X GET -H "Authorization: Bearer a7b38d3c9604d28b2e0075c0ee5701de" -H "Content-Type: application/json" -k https://localhost:9443/testdevice/1.0.0/devices -v * Hostname was NOT found in DNS cache * Trying 127.0.0.1... * Connected to localhost (127.0.0.1) port 9443 (#0) * successfully set certificate verify locations: * CAfile: none CApath: /etc/ssl/certs * SSLv3, TLS handshake, Client hello (1): * SSLv3, TLS handshake, Server hello (2): * SSLv3, TLS handshake, CERT (11): * SSLv3, TLS handshake, Server key exchange (12): * SSLv3, TLS handshake, Server finished (14): * SSLv3, TLS handshake, Client key exchange (16): * SSLv3, TLS change cipher, Client hello (1): * SSLv3, TLS handshake, Finished (20): * SSLv3, TLS change cipher, Client hello (1): * SSLv3, TLS handshake, Finished (20): * SSL connection using ECDHE-RSA-DES-CBC3-SHA * Server certificate: * subject: C=US; ST=CA; L=Mountain View; O=WSO2; CN=localhost * start date: 2010-02-19 07:02:26 GMT * expire date: 2035-02-13 07:02:26 GMT * issuer: C=US; ST=CA; L=Mountain View; O=WSO2; CN=localhost * SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway. &gt; GET /testdevice/1.0.0/devices HTTP/1.1 &gt; User-Agent: curl/7.35.0 &gt; Host: localhost:9443 &gt; Accept: */* &gt; Authorization: Bearer a7b38d3c9604d28b2e0075c0ee5701de &gt; Content-Type: application/json &gt; &lt; HTTP/1.1 404 Not Found &lt; Allow: DELETE,POST,GET,PUT,OPTIONS,HEAD &lt; Date: Tue, 07 Jun 2016 08:12:21 GMT &lt; Content-Length: 0 * Server WSO2 Carbon Server is not blacklisted &lt; Server: WSO2 Carbon Server &lt; * Connection #0 to host localhost left intact<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-211'>https://wso2.org/jira/browse/IOTS-211</a></p>

**Comment by geethkokila** [comment]
This is fixed in the IoT server 3.1.0. Hence closing
