### ISSUE TITLE
[IOTS-210] IOException thrown when same device is connected to the broker on MQTT multiple times

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#651]
Following error gets thrown when the same device is connected to the broker multiple times. Note that the clean session attribute is set to true on both sides.   [2016-06-07 12:48:08,979] WARN - MQTTopicManager A subscriber or a publisher with Connection with id paho/3639AFF3E7F2451728 cannot be found to disconnect. [2016-06-07 12:48:08,989] INFO - ProtocolProcessor cleaning old saved subscriptions for client paho/3639AFF3E7F2451728 [2016-06-07 12:48:08,989] ERROR - MessageMetricsHandler Connection reset by peer java.io.IOException: Connection reset by peer at sun.nio.ch.FileDispatcherImpl.read0(Native Method) at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) at sun.nio.ch.IOUtil.read(IOUtil.java:192) at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446) at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) at java.lang.Thread.run(Thread.java:745) [2016-06-07 12:48:08,994] INFO - ProtocolProcessor cleaning old saved subscriptions for client paho/3639AFF3E7F2451728 [2016-06-07 12:48:08,995] INFO - MQTTopicManager Disconnecting channel for clientID: paho/3639AFF3E7F2451728 [2016-06-07 12:48:08,995] WARN - MQTTopicManager A subscriber or a publisher with Connection with id paho/3639AFF3E7F2451728 cannot be found to disconnect.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-210'>https://wso2.org/jira/browse/IOTS-210</a></p>

**Comment by geethkokila** [comment]
@ayyoob , This is fixed
