### ISSUE TITLE
[IOTS-207] [External APIM] Invoking device API as shown in api-store fails with 302

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#653]
Invoking device API shown in /api-store fails with 302.    dumiduh@dumiduh-Latitude-E6540:~/WORK/IOT_REL_MAY_2016$ curl -X GET -H "Authorization: Bearer 9988bb27c9d6c7920a523320807f7394" -H "Content-Type: application/json" -k https://localhost:9445/testdevice/devices -v * Hostname was NOT found in DNS cache * Trying 127.0.0.1... * Connected to localhost (127.0.0.1) port 9445 (#0) * successfully set certificate verify locations: * CAfile: none CApath: /etc/ssl/certs * SSLv3, TLS handshake, Client hello (1): * SSLv3, TLS handshake, Server hello (2): * SSLv3, TLS handshake, CERT (11): * SSLv3, TLS handshake, Server key exchange (12): * SSLv3, TLS handshake, Server finished (14): * SSLv3, TLS handshake, Client key exchange (16): * SSLv3, TLS change cipher, Client hello (1): * SSLv3, TLS handshake, Finished (20): * SSLv3, TLS change cipher, Client hello (1): * SSLv3, TLS handshake, Finished (20): * SSL connection using ECDHE-RSA-DES-CBC3-SHA * Server certificate: * subject: C=US; ST=CA; L=Mountain View; O=WSO2; CN=localhost * start date: 2010-02-19 07:02:26 GMT * expire date: 2035-02-13 07:02:26 GMT * issuer: C=US; ST=CA; L=Mountain View; O=WSO2; CN=localhost * SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway. &gt; GET /testdevice/devices HTTP/1.1 &gt; User-Agent: curl/7.35.0 &gt; Host: localhost:9445 &gt; Accept: */* &gt; Authorization: Bearer 9988bb27c9d6c7920a523320807f7394 &gt; Content-Type: application/json &gt; &lt; HTTP/1.1 302 Found &lt; Set-Cookie: JSESSIONID=FD80E188C814852190FA1E1AC115FE7B; Path=/; Secure; HttpOnly &lt; Set-Cookie: requestedURI=../../testdevice/devices; Path=/ &lt; Location: https://localhost:9445/carbon/admin/login.jsp &lt; Content-Type: text/html;charset=UTF-8 &lt; Content-Length: 0 &lt; Date: Mon, 06 Jun 2016 11:07:49 GMT * Server WSO2 Carbon Server is not blacklisted &lt; Server: WSO2 Carbon Server &lt; * Connection #0 to host localhost left intact<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-207'>https://wso2.org/jira/browse/IOTS-207</a></p>

**Comment by geethkokila** [comment]
This is not occurring anymore, we have fixed these issues in the 3.1.0 and also in the cloud
