### ISSUE TITLE
[IOTS-199] Deleted agents are still receiving command events

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#656]
Agents are still able to receive command events over MQTT after they are deleted. + to reproduce + 1. enroll custom device type, start agent on device. 2. delete device by making a DELETE on /device/DEV_ID resource. 3. call command api of device(device/DEV_ID/change-status?state=off 4. check agent stdout.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-199'>https://wso2.org/jira/browse/IOTS-199</a></p>

**Comment by geethkokila** [comment]
This is fixed hence closing
