### ISSUE TITLE
[IOTS-197] Users created through signup are not able to access api-store

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#657]
Users created through /devicemgt signup are not able to login to /api-store. Following error is observed(deceptively short!) to reproduce 1. create user from /devicemgt 2. login and enroll vfirealarm device. 3. from /devicemgt/device/virtual_firealarm/enroll goto view API. 4. login to /api-store with credentials of the newly created user.    [2016-06-02 16:49:08,443] ERROR - APIStoreHostObject Login failed.Please recheck the username and password and try again.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-197'>https://wso2.org/jira/browse/IOTS-197</a></p>

**Comment by Megala21** [comment]
This issue is not re-producible in the latest pack with the given steps. Hence closing this issue.
