### ISSUE TITLE
[IOTS-186] WSO2 Sense Agent drains the battery

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#660]
I have experimented with the WSO2 sense agent and I noticed that the phone battery is getting drained drastically after I install it. I haven't executed the application and I don't know whether you have any startup routine/background process in place. When comes to the battery usage information it has took 58% of power which is a very high power usage.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-186'>https://wso2.org/jira/browse/IOTS-186</a></p>

**Comment by geethkokila** [comment]
Since this is a reference implementation and it requires all the sensors to publish data, we are not able to make changes for the battery draining issue. Hence resolving
