### ISSUE TITLE
[IOTS-143] Device firealarm: The alarm doesn't switch off in the defined time

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#661]
Steps: User configures the device to on/off within 5 seconds. Actual result: On works within 5 sec but the off takes 5 mins Configuration: define stream fireAlarmEventStream (deviceID string, temp int); from fireAlarmEventStream#window.time(5 sec) select deviceID, max(temp) as maxValue group by deviceID insert into analyzeStream for expired-events; from analyzeStream&#91;maxValue &gt; 90&#93; select maxValue insert into bulbOnStream; from fireAlarmEventStream&#91;temp &lt; 90&#93; select deviceID, temp insert into bulbOffStream;<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-143'>https://wso2.org/jira/browse/IOTS-143</a></p>

**Comment by geethkokila** [comment]
This is fixed hence closing
