### ISSUE TITLE
[IOTS-141] Policies: Device should have only one policy

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#662]
When multiple policies are added to a device, it can be from the device, the group or device type. The last added policy should be taken as the policy to be applied for the device.  It would be more clear for the user if the selected policy for the device is highlighted and showed. Only policies related to the device should be shown. The user should have the option to select the policy the user wishes for the particular device.<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-141'>https://wso2.org/jira/browse/IOTS-141</a></p>

**Comment by geethkokila** [comment]
This is not the intended behaviour of the policy. The user configures the policy and valid policy to the server is calculated using the device attributes and policy rules. Therefore above issue is not valid.
