### ISSUE TITLE
[IOTS-493] Database may be already in use: "Locked by another process".

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#663]
I´m beggining to use the Iot WSO2 MDM, and i´m following the quick start guide, launching first broker, then core an then analytics.
When i start broker all is ok. But when i start core the system return the following errors:

[2017-02-23 09:26:06,063] [] INFO - RegistryCoreServiceComponent Registry Mode : READ-WRITE
[2017-02-23 09:26:08,188] [] ERROR - GadgetDataServiceDAOFactory Error occurred while retrieving config.datasource connection.
org.h2.jdbc.JdbcSQLException: La base de datos puede que ya est├® siendo utilizada: "Locked by another process". Soluciones Posibles: cierre todas las otras conexiones; use el modo server
Database may be already in use: "Locked by another process". Possible solutions: close all other connection(s); use the server mode [90020-175]_

I need to change the h2 database and use mysql or oracle datasource?
Can you help me?

Reference: https://wso2.org/jira/browse/IOTS-493

**Comment by geethkokila** [comment]
Portal dependencies will be removed hence this issue will not occur, therefore resolving
