### ISSUE TITLE
[IOTS-401] [Intermittent] 404 thrown when loading the device mgt page with a fresh pack

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#664]
<p>When starting the server with a fresh pack, HTTP 404 thrown at first in the UI Intermittently. (check attachment)</p> <p>Note- Used private browsing in chrome and still getting this.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-401'>https://wso2.org/jira/browse/IOTS-401</a></p>

**Comment by geethkokila** [comment]
This is fixed hence closing
