### ISSUE TITLE
[IOTS-398] When creating a new user account on WSO2 IoTs, if the password given is less than six characters, pops-up a wrong error message

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#666]
<p>Steps to reproduce<br/> 1. Go to the login page of WSO2 IoT server UI<br/> 2. Click on the link \"create an account\"<br/> 3. Fill all the fields and give a 5 character password <br/> 4. Try to register the user and it gives a wrong error message</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-398'>https://wso2.org/jira/browse/IOTS-398</a></p>

**Comment by ruwany** [comment]
This is fixed in the latest release [3.1.0-update1](https://github.com/wso2/product-iots/releases/tag/v3.1.0-update1)
