### ISSUE TITLE
[IOTS-387] No permission error when user access to android sense portal dashboard.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#668]
Steps: 1. Create a new user 2. Give required permissions and enroll android sense device type. 3. Go to the android sense type view and click on view device analytics link. Portal dashboard returns the error message: *Error 401 You do not have permission to access this page.Please contact your administrator and request permission.*<p>Reference: <a href='https://wso2.org/jira/browse/IOTS-387'>https://wso2.org/jira/browse/IOTS-387</a></p>

**Comment by geethkokila** [comment]
Portal dependency is bieng removed from 3.1.0, hence resolving
