### ISSUE TITLE
[Policy] Unable to blacklist applications through an android policy

### ISSUE THREAD

**Issue by jsonds** [wso2/product-iots#669]
Applied a policy to an enrolled device  after configuring the policy to have two applications to be blacklisted but still the two applications can be used via the enrolled device which the policy is applied.
![blacklist](https://cloud.githubusercontent.com/assets/17248809/26779049/8a3269be-4a01-11e7-8671-b86640a2a047.jpg)

**Comment by jsonds** [comment]
**Labels -** 3.1.0 M8 ,  Bug, High

**Comment by madhawap** [comment]
The blacklisting operation has been built around the "getRunningAppProcesses()" function in the Android ActivityManager API. However, as of Android 5.1.1, this API has been deprecated. Therefore, we are unable to support this functionality for BYOD devices running Android version 5 or higher. For this purpose, in later releases, Android encourages developers to use work profiles, wherein which the blacklisted icon will disappear from the launcher itself. That being said, blacklisting works as expected in the COPE scenario as well as when using work profiles in EMM, where device owner has access to system-level functionalities.

**Comment by jsonds** [comment]
@shavidissa Lets update the docs according to Madawas comment.

**Comment by shavidissa** [comment]
Thank you, team!
Update docs [1].

[1] https://docs.wso2.com/display/IoTS310/Available+Mobile+Device+Management+Policies#AvailableMobileDeviceManagementPolicies-blacklisting
