### ISSUE TITLE
[IOTS-442] Application Whitelist/blacklist should be removed from iOS policy UI

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#671]
<p>Application whitelisting and blacklisting is only available for Android in EMM 2.2.0 and any reference to the feature should be removed from iOS policy creation UI.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-442'>https://wso2.org/jira/browse/IOTS-442</a></p>

**Comment by milanperera** [comment]
This has been removed in the latest IoTs 3.1.0 alpa.
