### ISSUE TITLE
[IOTS-350] When enrolling Android Device two modals shown up

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#672]
<p>1. Deploy Android device type plugin.<br/> 2. Goto <a href="https://localhost:9443/devicemgt/device/android/enroll" class="external-link" rel="nofollow">https://localhost:9443/devicemgt/device/android/enroll</a><br/> 3. Click on "Enroll"<br/> 4. Click on Close<span class="error">[X]</span> button / Click on background.</p> <p>You will see two modals shown up (When clicked on "Ok" this doesn't occur).</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-350'>https://wso2.org/jira/browse/IOTS-350</a></p>

**Comment by inoshperera** [comment]
This is no longer reproducible in the current version.
