### ISSUE TITLE
[IOTS-343] Issue when accessing device statistics dashboard as a tenant

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#673]
<p>Not able to view the device statistics dashboard as a tenant by trying to access it through the device mgt UI.<br/> Where device statistics directs to <a href="https://localhost:9443/portal/t/wso2.com/dashboards/device-statistics-dashboard/" class="external-link" rel="nofollow">https://localhost:9443/portal/t/wso2.com/dashboards/device-statistics-dashboard/</a> from the UI which works for carbon.super but not for the tenant.<br/> For tenant the url should be <a href="https://localhost:9443/portal/t/wso2.com/dashboards/device-statistics-dashboard/?shared=true" class="external-link" rel="nofollow">https://localhost:9443/portal/t/wso2.com/dashboards/device-statistics-dashboard/?shared=true</a><br/> And by default the device statistics dashboard should be shared with all tenants.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-343'>https://wso2.org/jira/browse/IOTS-343</a></p>

**Comment by geethkokila** [comment]
This is fixed hence closing
