### ISSUE TITLE
[IOTS-297] HTTP login page is accessible and do not redirect to HTTPS login page.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#675]
<p>Login page of devicemgt app do not work when accessed via HTTP.</p> <p>Ideally the HTTP login page should be disabled in the system and the app should be only accessible via HTTPS. </p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-297'>https://wso2.org/jira/browse/IOTS-297</a></p>

**Comment by geethkokila** [comment]
Tested on the cluster, issue does not occur, hence closing
