### ISSUE TITLE
[IOTS-443] In SSO Mode, when trying to logging out from portal app, exception is thrown

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#676]
<p>Following exception is thrown,</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> org.mozilla.javascript.EvaluatorException: Can't find method org.wso2.store.sso.common.util.Util.validateSignature(org.opensaml.saml2.core.impl.LogoutResponseImpl,java.lang.<span class="code-object">String</span>,java.lang.<span class="code-object">String</span>,string,<span class="code-keyword">null</span>,<span class="code-keyword">null</span>). (&amp;lt;sso&amp;gt;/scripts/sso.client.js#48) org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EvaluatorException: Can't find method org.wso2.store.sso.common.util.Util.validateSignature(org.opensaml.saml2.core.impl.LogoutResponseImpl,java.lang.<span class="code-object">String</span>,java.lang.<span class="code-object">String</span>,string,<span class="code-keyword">null</span>,<span class="code-keyword">null</span>). (&amp;lt;sso&amp;gt;/scripts/sso.client.js#48) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571) at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273) at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588) at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508) at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29) at javax.servlet.http.HttpServlet.service(HttpServlet.java:650) at javax.servlet.http.HttpServlet.service(HttpServlet.java:731) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747) at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485) at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377) at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337) at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at org.wso2.carbon.identity.auth.valve.AuthenticationValve.invoke(AuthenticationValve.java:59) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99) at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47) at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57) at org.wso2.carbon.webapp.authenticator.framework.WebappAuthenticationValve.invoke(WebappAuthenticationValve.java:45) at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62) at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956) at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1756) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1715) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) Caused by: org.mozilla.javascript.EvaluatorException: Can't find method org.wso2.store.sso.common.util.Util.validateSignature(org.opensaml.saml2.core.impl.LogoutResponseImpl,java.lang.<span class="code-object">String</span>,java.lang.<span class="code-object">String</span>,string,<span class="code-keyword">null</span>,<span class="code-keyword">null</span>). (&amp;lt;sso&amp;gt;/scripts/sso.client.js#48) at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77) at org.mozilla.javascript.Context.reportRuntimeError(Context.java:913) at org.mozilla.javascript.Context.reportRuntimeError(Context.java:969) at org.mozilla.javascript.Context.reportRuntimeError1(Context.java:932) at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:144) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.&amp;lt;sso&amp;gt;.scripts.c0._c_anonymous_3(&amp;lt;sso&amp;gt;/scripts/sso.client.js:48) at org.jaggeryjs.rhino.&amp;lt;sso&amp;gt;.scripts.c0.call(&amp;lt;sso&amp;gt;/scripts/sso.client.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.portal.controllers.c2._c_anonymous_1(/portal/controllers/acs.jag:128) at org.jaggeryjs.rhino.portal.controllers.c2.call(/portal/controllers/acs.jag) at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23) at org.jaggeryjs.rhino.portal.controllers.c2._c_script_0(/portal/controllers/acs.jag:20) at org.jaggeryjs.rhino.portal.controllers.c2.call(/portal/controllers/acs.jag) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) at org.jaggeryjs.rhino.portal.controllers.c2.call(/portal/controllers/acs.jag) at org.jaggeryjs.rhino.portal.controllers.c2.exec(/portal/controllers/acs.jag) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567) ... 46 more </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-443'>https://wso2.org/jira/browse/IOTS-443</a></p>

**Comment by Megala21** [comment]
This issue is already fixed with https://github.com/wso2/carbon-device-mgt/issues/650 . Hence closing this issue.
