### ISSUE TITLE
[IOTS-450] [Cluster] 500 Error when trying to log in

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#677]
<p>Following exception is observed in logs.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> TID: [-1234] [] [2016-11-07 00:00:32,970] ERROR {com.notnoop.apns.internal.ApnsConnectionImpl} - Couldn't connect to APNS server java.net.SocketException: Too many open files at java.net.Socket.createImpl(Socket.java:460) at java.net.Socket.connect(Socket.java:587) at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) at sun.security.ssl.SSLSocketImpl.&amp;lt;init&amp;gt;(SSLSocketImpl.java:427) at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88) at com.notnoop.apns.internal.ApnsConnectionImpl.socket(ApnsConnectionImpl.java:194) at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:239) at com.notnoop.apns.internal.ApnsConnectionImpl.sendMessage(ApnsConnectionImpl.java:230) at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:46) at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:56) at com.notnoop.apns.internal.ApnsServiceImpl.push(ApnsServiceImpl.java:36) at com.notnoop.apns.internal.AbstractApnsService.push(AbstractApnsService.java:45) at org.wso2.carbon.device.mgt.ios.apns.service.impl.MDMPushNotificationSender.pushToAPNS(MDMPushNotificationSender.java:45) at org.wso2.carbon.device.mgt.ios.apns.service.impl.MDMPushNotificationSenderService.sendNotification(MDMPushNotificationSenderService.java:29) at org.wso2.carbon.device.mgt.ios.apns.service.impl.PushNotificationServiceImpl.sendMDMNotification(PushNotificationServiceImpl.java:33) at org.wso2.carbon.device.mgt.mobile.impl.ios.IOSPolicyMonitoringService.notifyDevices(IOSPolicyMonitoringService.java:51) at org.wso2.carbon.policy.mgt.core.task.MonitoringTask.execute(MonitoringTask.java:113) at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67) at org.quartz.core.JobRunShell.run(JobRunShell.java:213) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-450'>https://wso2.org/jira/browse/IOTS-450</a></p>

**Comment by geethkokila** [comment]
This is fixed with latest iOS components, Issue was when initiating the apns connection, after data has transferred, connection was never closed
