### ISSUE TITLE
[IOTS-441] Android agent registration hangs upon invalid credentials

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#679]
<p>When we give server credentials to register the android device. By mistake, if we give wrong configurations the authentication window keeps on rolling and it basically stuck there forever. <br/> This needs to be handled with some error recovery mechanism. </p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-441'>https://wso2.org/jira/browse/IOTS-441</a></p>

**Comment by inoshperera** [comment]
This is no longer reproducible
