### ISSUE TITLE
[IOTS-451] A formatting text label in Message operation window contains as a text in IE 11

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#680]
<p>One of the 2 text fields (the one at bottom to enter the message) in "Message" operation window includes a formatting label as a text.</p> <p>== Steps ==<br/> 1. Enrolled at least one device.<br/> 2. Go to Device management and click on the enrolled device<br/> 3. Click <b>"Message Operation"</b> under operations and a popup window should appears.</p> <p>The bottom text field has filled with a text <b>Message here...</b> which suppose to be a formatting label.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-451'>https://wso2.org/jira/browse/IOTS-451</a></p>

**Comment by milanperera** [comment]
This is fixed in the latest IoTs 3.1.0 alpha pack.
