### ISSUE TITLE
[IOTS-264] Removing a user does not remove devices associated with the user

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#685]
<p>Removing a user does not remove devices associated with the user from the server. The devices will still be listed for the admin user and are able to send and receive events. </p> <p>As a workaround you could remove devices manually prior to user deletion. It would be better if the option to disable devices at a user level was also provided. </p> <p>IOT-73 seems related.</p> <p><ins>To reproduce</ins></p> <p>1. Create a new user, login as user and enroll a device.<br/> 2. Login as admin to /devicemgt and remove user.<br/> 3. Publish events to server from the agent downloaded from removed user.<br/> 4. Access device details page from admin.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-264'>https://wso2.org/jira/browse/IOTS-264</a></p>

**Comment by milanperera** [comment]
I think it would be better if we mark devices to 'REMOVED' state that are belong to a particular user when removing the respective user.
