### ISSUE TITLE
[IOTS-251] DSAxis2ConfigurationObserverImpl(FNF) printed at tenant login

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#687]
<p>Following two errors are printed at tenant login. To reproduce, create tenant bounce server and login to devicemgt as tenant admin. </p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> [2016-06-17 10:51:58,729] ERROR - DSAxis2ConfigurationObserverImpl Error <span class="code-keyword">while</span> initializing the tenant dashboard resources :dumiduh.com/home/dumiduh/WORK/IOT_REL_MAY_2016/ALPHA_TWO/TEMP/wso2iots-1.0.0-SNAPSHOT/repository/resources/sharedstore/layout (No such file or directory) [2016-06-17 10:51:58,729] ERROR - DSAxis2ConfigurationObserverImpl Error <span class="code-keyword">while</span> initializing the tenant dashboard resources :dumiduh.com/home/dumiduh/WORK/IOT_REL_MAY_2016/ALPHA_TWO/TEMP/wso2iots-1.0.0-SNAPSHOT/repository/resources/sharedstore/gadget (No such file or directory) </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-251'>https://wso2.org/jira/browse/IOTS-251</a></p>

**Comment by geethkokila** [comment]
We tested on device cloud, and issue did not occur, hence closing
