### ISSUE TITLE
[IOTS-249] [UI] devicemgt pages throw 500 Error in obtaining token with Refresh Token intermittently

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#688]
<p>devicemgt pages throw 500 (refer attachment) intermittently. Occurs after the app has been idle for some time.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> [2016-06-16 06:39:38,631] ERROR - handlebars-module An exception thrown when executing the script '/app/pages/cdmf.page.devices/devices.js'. [2016-06-16 06:39:38,633] ERROR - dynamic-files-renderer Error in obtaining token with Refresh Token Type </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-249'>https://wso2.org/jira/browse/IOTS-249</a></p>

**Comment by geethkokila** [comment]
This is fixed with new api subscription flow and new welcome page.
