### ISSUE TITLE
[IOTS-247] NPE thrown from connected cup sample client

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#690]
<p>Following NPE is thrown from the connected cup sample client after about 30 mins inactivity. </p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> [2016-06-16 06:15:45,052] WARN - MiscellaneousUtil Error loading properties from a file at from the <span class="code-object">System</span> defined location: nhttp.properties Exception in thread <span class="code-quote">"<span class="code-object">Thread</span>-270"</span> java.lang.NullPointerException at java.util.Hashtable.clear(Hashtable.java:532) at org.eclipse.paho.client.mqttv3.persist.MemoryPersistence.clear(MemoryPersistence.java:84) at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(ConnectActionListener.java:158) at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:497) at org.eclipse.paho.client.mqttv3.MqttClient.connect(MqttClient.java:238) at org.coffeeking.agent.transport.mqtt.MQTTTransportHandler.connectToQueue(MQTTTransportHandler.java:159) at org.coffeeking.agent.transport.mqtt.ConnectedCupMQttTransportHandler$1.run(ConnectedCupMQttTransportHandler.java:65) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) Exception in thread <span class="code-quote">"<span class="code-object">Thread</span>-300"</span> java.lang.NullPointerException at java.util.Hashtable.clear(Hashtable.java:532) at org.eclipse.paho.client.mqttv3.persist.MemoryPersistence.clear(MemoryPersistence.java:84) at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.connect(ConnectActionListener.java:158) at org.eclipse.paho.client.mqttv3.MqttAsyncClient.connect(MqttAsyncClient.java:497) at org.eclipse.paho.client.mqttv3.MqttClient.connect(MqttClient.java:238) at org.coffeeking.agent.transport.mqtt.MQTTTransportHandler.connectToQueue(MQTTTransportHandler.java:159) at org.coffeeking.agent.transport.mqtt.ConnectedCupMQttTransportHandler$1.run(ConnectedCupMQttTransportHandler.java:65) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-247'>https://wso2.org/jira/browse/IOTS-247</a></p>

**Comment by thisaripatabendi** [comment]
This issue is no longer in reproducible in 3.0.1-alpha. Hence closed.
