### ISSUE TITLE
[IOTS-246] AxisFault thrown in user creation flow due to incorrectly configured smtp that comes with the pack

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#691]
<p>Following error is thrown due to incorrectly configured smtp transport in default packs. If smtp configuration is a prerequisite for running the server it should be mention in the documentation. </p> <p>It would be better if this error could be hidden if the smtp has not been configured.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> [2016-06-16 06:01:01,407] ERROR - ClientUtils The system cannot infer the transport information from the mailto:user111@gmail.com URL. [2016-06-16 06:01:01,408] ERROR - EmailSenderServiceImpl Error occurred <span class="code-keyword">while</span> delivering the message, subject: 'You have successfully been registered in WSO2 IoT Server', to: 'user111@gmail.com' org.apache.axis2.AxisFault: The system cannot infer the transport information from the mailto:user111@gmail.com URL. at org.apache.axis2.description.ClientUtils.inferOutTransport(ClientUtils.java:81) at org.apache.axis2.client.OperationClient.prepareMessageContext(OperationClient.java:288) at org.apache.axis2.description.OutOnlyAxisOperationClient.executeImpl(OutOnlyAxisOperation.java:249) at org.apache.axis2.client.OperationClient.execute(OperationClient.java:149) at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:511) at org.apache.axis2.client.ServiceClient.fireAndForget(ServiceClient.java:488) at org.wso2.carbon.email.sender.core.service.EmailSenderServiceImpl$EmailSender.run(EmailSenderServiceImpl.java:117) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-246'>https://wso2.org/jira/browse/IOTS-246</a></p>

**Comment by milanperera** [comment]
@shavidissa: Have we mentioned about configuring mail server under prerequisite section? I think it's a valid scenario, if we are going to invite users to the system via mail

**Comment by shavidissa** [comment]
The content is in the following docs. we have explained it based on the scenario.

[1] Enrollig an Android device: https://docs.wso2.com/display/IoTS310/Android#7abfc9d679f548b6b7438a32525ba4b7
and 
[2] Inviting user: https://docs.wso2.com/display/IoTS310/Inviting+Users
