### ISSUE TITLE
[IOTS-238] RuntimeExceptions thrown when external IOT server pointed as analytics server

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#694]
<p>Following errors are thrown on IOT server side when it is pointed to another IOT server as the analytic server. Laptop device type and custom device type were installed on both sides.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> [2016-06-14 10:33:00,665] ERROR - TaskQuartzJobAdapter Error in executing task: Analytics Relation created with an empty schema <span class="code-keyword">for</span> tableORG_WSO2_IOT_DEVICES_BATTERY_USAGE java.lang.RuntimeException: Analytics Relation created with an empty schema <span class="code-keyword">for</span> tableORG_WSO2_IOT_DEVICES_BATTERY_USAGE at org.wso2.carbon.analytics.spark.core.sources.AnalyticsRelation.&amp;lt;init&amp;gt;(AnalyticsRelation.java:93) at org.wso2.carbon.analytics.spark.core.sources.AnalyticsRelationProvider.createRelation(AnalyticsRelationProvider.java:106) at org.wso2.carbon.analytics.spark.core.sources.AnalyticsRelationProvider.createRelation(AnalyticsRelationProvider.java:56) at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:269) at org.apache.spark.sql.sources.CreateTempTableUsing.run(ddl.scala:412) at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:57) at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:57) at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:68) at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:88) at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:88) at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147) at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:87) at org.apache.spark.sql.SQLContext$QueryExecution.toRdd$lzycompute(SQLContext.scala:950) at org.apache.spark.sql.SQLContext$QueryExecution.toRdd(SQLContext.scala:950) at org.apache.spark.sql.DataFrame.&amp;lt;init&amp;gt;(DataFrame.scala:144) at org.apache.spark.sql.DataFrame.&amp;lt;init&amp;gt;(DataFrame.scala:128) at org.apache.spark.sql.DataFrame$.apply(DataFrame.scala:51) at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:755) at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQueryLocal(SparkAnalyticsExecutor.java:780) at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQuery(SparkAnalyticsExecutor.java:741) at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeQuery(CarbonAnalyticsProcessorService.java:201) at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeScript(CarbonAnalyticsProcessorService.java:151) at org.wso2.carbon.analytics.spark.core.AnalyticsTask.execute(AnalyticsTask.java:59) at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67) at org.quartz.core.JobRunShell.run(JobRunShell.java:213) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [2016-06-14 10:33:00,665] ERROR - TaskQuartzJobAdapter Error in executing task: Analytics Relation created with an empty schema <span class="code-keyword">for</span> tableORG_WSO2_IOT_DEVICES_qadevice java.lang.RuntimeException: Analytics Relation created with an empty schema <span class="code-keyword">for</span> tableORG_WSO2_IOT_DEVICES_qadevice at org.wso2.carbon.analytics.spark.core.sources.AnalyticsRelation.&amp;lt;init&amp;gt;(AnalyticsRelation.java:93) at org.wso2.carbon.analytics.spark.core.sources.AnalyticsRelationProvider.createRelation(AnalyticsRelationProvider.java:106) at org.wso2.carbon.analytics.spark.core.sources.AnalyticsRelationProvider.createRelation(AnalyticsRelationProvider.java:56) at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:269) at org.apache.spark.sql.sources.CreateTempTableUsing.run(ddl.scala:412) at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:57) at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:57) at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:68) at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:88) at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:88) at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147) at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:87) at org.apache.spark.sql.SQLContext$QueryExecution.toRdd$lzycompute(SQLContext.scala:950) at org.apache.spark.sql.SQLContext$QueryExecution.toRdd(SQLContext.scala:950) at org.apache.spark.sql.DataFrame.&amp;lt;init&amp;gt;(DataFrame.scala:144) at org.apache.spark.sql.DataFrame.&amp;lt;init&amp;gt;(DataFrame.scala:128) at org.apache.spark.sql.DataFrame$.apply(DataFrame.scala:51) at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:755) at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQueryLocal(SparkAnalyticsExecutor.java:780) at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.executeQuery(SparkAnalyticsExecutor.java:741) at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeQuery(CarbonAnalyticsProcessorService.java:201) at org.wso2.carbon.analytics.spark.core.CarbonAnalyticsProcessorService.executeScript(CarbonAnalyticsProcessorService.java:151) at org.wso2.carbon.analytics.spark.core.AnalyticsTask.execute(AnalyticsTask.java:59) at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67) at org.quartz.core.JobRunShell.run(JobRunShell.java:213) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-238'>https://wso2.org/jira/browse/IOTS-238</a></p>

**Comment by geethkokila** [comment]
This is tested and issue did not occur, hence closing
