### ISSUE TITLE
[IOTS-221] hardcoded basic token passed to backend services

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#705]
<p>Following hardcoded transport header is set for each device type API that gets generated. If the header is not needed it would be better to remove it.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> &amp;lt;property name=<span class="code-quote">"Authorization"</span> expression=<span class="code-quote">"fn:concat('Basic ', 'bnVsbDpudWxs')"</span> scope=<span class="code-quote">"transport"</span>/&amp;gt; </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-221'>https://wso2.org/jira/browse/IOTS-221</a></p>

**Comment by geethkokila** [comment]
Checked on the IoT server 3.1.0 cluster, and above config is not shown.
