### ISSUE TITLE
[IOTS-220] Delete groups: Any user to whom the group is shared to is able to delete the group

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#706]
<p>Steps:<br/> Share a group from one to another.</p> <p>Actual result:<br/> The person who the group was shared to has permission to delete the group.</p> <p>Expected result:<br/> The user should only be able to delete the group if the user has permission.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-220'>https://wso2.org/jira/browse/IOTS-220</a></p>

**Comment by sameeragunarathne** [comment]
This is already fixed in latest release.
