### ISSUE TITLE
[IOTS-520] Connected cup sample agent failing to connect to MQTT broker

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#710]
<p>I have imported the Connected Cup sample device agent into Eclipse IDE, and when it tries to connect to MQTT broker a MQTTSecurityException is thrown which states that the user name or password in not valid. I see that user name is created from the token attribute in the request, but I don’t know how to support a right one, i.e. one that would be accepted by the OAuth2 service. There isn’t any hint in the documentation on this topic, so I would appreciate any advice.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-520'>https://wso2.org/jira/browse/IOTS-520</a></p>

**Comment by geethkokila** [comment]
Duplicate 
https://github.com/wso2/product-iots/issues/709
Hence closing
