### ISSUE TITLE
[IOTS-455] Notification count doesn't reduce after a notification has been viewed in publisher

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#711]
<p>The count of notifications stays same after a listed notification was clicked and viewed.</p> <p>== Steps ==<br/> 1. Logged in to publisher and notifications are listed at top.<br/> 2. Click notifications and all the notifications should be displayed as a drop down.<br/> 3. Click one notification in order to view it and that redirects back to application page (if the notification is for a rejected app)</p> <p>But the notification count remains same even after reading the listed notifications.(check attachment)</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-455'>https://wso2.org/jira/browse/IOTS-455</a></p>

**Comment by sameeragunarathne** [comment]
This option is disabled in publisher in the latest release.
