### ISSUE TITLE
[APPM-1272] Publisher, Click on an action button after Session Timeout goes to incorrect URL

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#712]
<p>1. Navigate to publisher create web or mobile app screen and go to halfway on creation.<br/> 2. Let the browser Idle for a long time so that IdP and Publisher both sessions to timeout.<br/> 3. After the sessions are timed out (after 30 mins) click on one of the action Icons visible.</p> <p>System redirects to URL like <span class="error">[1]</span> for login prompt. But the URL is invalid.<br/> <span class="error">[1]</span> <a href="https://localhost:9443/publisher/assets/webapp/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/login" class="external-link" rel="nofollow">https://localhost:9443/publisher/assets/webapp/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/undefined/login</a></p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1272'>https://wso2.org/jira/browse/APPM-1272</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
