### ISSUE TITLE
[APPM-1228] Proxy port is not pickedup when generating URLs on server startup

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#713]
<p>When starting the server with proxy ports it should be appended to the URLs not the default port. When publisher store URLs are generated on server startup proxy port is not appended. Refer the following segment.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> INFO - StartupFinalizerServiceComponent Server : WSO2 App Manager-1.1.0 [2015-12-22 17:02:51,275] INFO - StartupFinalizerServiceComponent WSO2 Carbon started in 46 sec [2015-12-22 17:02:51,571] INFO - CarbonUIServiceComponent Mgt Console URL : https:<span class="code-comment">//app11.wso2.com:9443/carbon/ </span>[2015-12-22 17:02:51,571] INFO - CarbonUIServiceComponent APP Publisher Default Context : http:<span class="code-comment">//app11.wso2.com:9763/publisher </span>[2015-12-22 17:02:51,571] INFO - CarbonUIServiceComponent APP Store Default Context : http:<span class="code-comment">//app11.wso2.com:9763/store </span> </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1228'>https://wso2.org/jira/browse/APPM-1228</a></p>

**Comment by geethkokila** [comment]
Tested on the clustered set up iot 3.1.0. Issue did not appear, hence closing the issue.
