### ISSUE TITLE
[APPM-1170] Improve the error message displayed when the user doesn't have permissions to edit

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#714]
<p><b>Steps</b></p> <p>1. Create a user with following permissions<br/> Login<br/> Manage &amp;gt; Add &amp;gt; Webapps<br/> Resources &amp;gt; Govern &amp;gt; Web Apps<br/> Web App &amp;gt; Create &amp;amp; Delete</p> <p>2. Now Create a App and try to edit the application.</p> <p><b>Issue</b> : Although a popup is visible when trying to update, the top error only has a time stamp. Refer the attached screenshot. </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1170'>https://wso2.org/jira/browse/APPM-1170</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
