### ISSUE TITLE
[APPM-591] Inconsistency between web-apps and mobile apps when saving the app owner name

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#717]
<p>As shown in the image attached the Owner name is shown in two different ways in mobile apps and in webapps. </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-591'>https://wso2.org/jira/browse/APPM-591</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
