### ISSUE TITLE
[APPM-487] Subscribed image doesn't contain any hyperlinks to the webapp

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#718]
<p>When you subscribe to a webapp, a subscribed image is shown over the webapp in the store. This image doesn't contain a hyperlink to the webapp detail page. That region is overlapping the base image hence user cannot click this region. Refer the screenshot. </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-487'>https://wso2.org/jira/browse/APPM-487</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
