### ISSUE TITLE
[APPM-31] Templates use png from http://b.content.wso2.com/

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#724]
<p>The deployed templates include references to a spacer image at <a href="http://b.content.wso2.com/wp-content/themes/wso2ng-v3/images/spacer.png" class="external-link" rel="nofollow">http://b.content.wso2.com/wp-content/themes/wso2ng-v3/images/spacer.png</a></p> <p>This means clients accessing our deployment of API-Manager are hitting the wso2 website to download this image. </p> <p>This causes the following issues:<br/> 1) Slower rendering, client needs to access a remote server<br/> 2) External dependancey, if wso2.com changes then local deploy may break.<br/> 3) HTTS warnings - When the rest of the page is protected via SSL, this image is accessed via http, causing a warning.</p> <p>Solution: <br/> Include the spacer image in all theme images folder.</p> <p>Replace all occurrences of:<br/> <a href="http://b.content.wso2.com/wp-content/themes/wso2ng-v3/images/spacer.png" class="external-link" rel="nofollow">http://b.content.wso2.com/wp-content/themes/wso2ng-v3/images/spacer.png</a><br/> With:<br/> &amp;lt;%=jagg.getAbsoluteUrl(jagg.getThemeFile("images/spacer.png"))%&amp;gt;<br/> or something similar.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-31'>https://wso2.org/jira/browse/APPM-31</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
