### ISSUE TITLE
[IOTS-461] Improve uniformness of the EMM API response codes

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#732]
<p>It would be better if EMM API are made to respond the same way. Having a uniform and accepted set of response codes will allow the API to be tested by anyone with confidence. </p> <p><ins>Response Codes</ins></p> <p>All invocations with invalid device id or other such parameters with a 400.<br/> Successful operation calls with 201 or 200.<br/> Server side errors with 500.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-461'>https://wso2.org/jira/browse/IOTS-461</a></p>

**Comment by geethkokila** [comment]
This is fixed hence closing
