### ISSUE TITLE
[IOTS-467] 'No device alert' should be more visible to the user when installing an application

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#738]
<p>When user tries to install an android mobile application in store without enrolling a device, an alert displayed. This alert should be visible a bit more than now since the alert pop ups at the top with black background, so user may find troubles to note this. </p> <p>== Steps ==<br/> 1. Create and publish an android mobile application in Publisher.<br/> 2. Logged into store, select the respective application and click "install"<br/> 3. A popup appears for a schedule install, tick "instant install" and Press <b>Yes</b> to proceed.</p> <p>An alert appeared at the top by saying "Sorry you don't have devices to install this app" and this should be more visible than now (check attachment)</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-467'>https://wso2.org/jira/browse/IOTS-467</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
