### ISSUE TITLE
[IOTS-463] UI: All the restrictions are selected by default - not very user friendly

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#739]
<p>When trying to add a restriction policy all the restrictions are selected by default as shown in the attachment. This is not very user-friendly if you only want to select a few restrictions.</p> <p>If users want to select all the restrictions or deselect all the restrictions can we have an option saying select and all deselect all so that this process will be made even more user-friendly?</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-463'>https://wso2.org/jira/browse/IOTS-463</a></p>

**Comment by menakaj** [comment]
This issue is already fixed.
