### ISSUE TITLE
[IOTS-410] Data table selected action buttons is shown without the selection triggered

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#744]
<p>Action buttons such as "Add to group", "Remove Device" is shown prior to selection being triggered. </p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-410'>https://wso2.org/jira/browse/IOTS-410</a></p>

**Comment by Kamidu** [comment]
This was fixed with the device listing improvements.
Now the bulk action icons will only be visible when there is a selection of items in all the listing pages.
