### ISSUE TITLE
[IOTS-417] Overall UX improvement for device advance search page

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#745]
<p>Overall UX of the advance search of devices should be enhanced.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-417'>https://wso2.org/jira/browse/IOTS-417</a></p>

**Comment by menakaj** [comment]
I'm looking into this issue.

**Comment by menakaj** [comment]
This issue is fixed with the PR,
https://github.com/wso2/carbon-device-mgt/pull/916

**Comment by menakaj** [comment]
Fixes with PR, https://github.com/wso2/carbon-device-mgt/pull/916
