### ISSUE TITLE
[IOTS-240] It would be better if the server could let the devices know when an HTTP event was not processed as a valid event

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#746]
<p>According to the HTTP receiver implementation found in the arduino sample, the receiver responds with a 200 OK for any request conforming to the expected format. As this is the case a 200 is sent regardless of validity of the data being sent(invalid json payloads, invalid device id query params etc). </p> <p>It would be better if the server could let the devices know that the event sent was not processed as a valid event. </p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-240'>https://wso2.org/jira/browse/IOTS-240</a></p>

**Comment by geethkokila** [comment]
This is removed hence closing, HTTP receiver is handle through loT core
