### ISSUE TITLE
[IOTS-88] need a way to generate the event publisher via maven archtype when generating a plugin

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#750]
<p>need a way to generate the event publisher via maven archtype when generating a plugin. The current project does not seem to generate a publisher which results in the publisher being created via the management console for generating alerts</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-88'>https://wso2.org/jira/browse/IOTS-88</a></p>

**Comment by geethkokila** [comment]
This is fixed in archtype hence closing
