### ISSUE TITLE
[IOTS-371] Use APIM DCR Implementation

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#751]
<p>Currently CDM has its own DCR implementation. Since APIM has introduced a DCR feature, we have to use that instead of our implementation.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-371'>https://wso2.org/jira/browse/IOTS-371</a></p>

**Comment by geethkokila** [comment]
This is fixed hence closing
