### ISSUE TITLE
[IOTS-290] Separate out operations in UI

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#753]
<p>Currently operations for Android, Windows and iOS devices are hard-corded in device details UIs and is not generic. Device operation UIs should be dynamically generated by default and should be able to customize when ever needed by editing specific UI unit for the device type.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-290'>https://wso2.org/jira/browse/IOTS-290</a></p>

**Comment by geethkokila** [comment]
This is fixed, all the operations are loaded from the respective device type plugins
