### ISSUE TITLE
[IOTS-265] Have a separate mechanisam to deploy the connected cup and connected laptop

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#754]
<p>Currently, we have a sample named connected cup, which was the only one that was deployed when running the device-deployer.xml file. This serves as the guide for the device manufacturers <span class="error">[1]</span>.</p> <p>Now Connected laptop too is deployed because we have configured it to work that was <span class="error">[2]</span>.</p> <p>Can we have a separation between deploying the connected laptop and the connected cup? This way we can explain things clearly in docs.</p> <p><span class="error">[1]</span> <a href="https://docs.wso2.com/display/IoTS100/Device+Manufacturer+Guide" class="external-link" rel="nofollow">https://docs.wso2.com/display/IoTS100/Device+Manufacturer+Guide</a><br/> <span class="error">[2]</span> <a href="https://docs.wso2.com/display/IoTS100/Connected+Laptop" class="external-link" rel="nofollow">https://docs.wso2.com/display/IoTS100/Connected+Laptop</a></p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-265'>https://wso2.org/jira/browse/IOTS-265</a></p>

**Comment by geethkokila** [comment]
This is fixed hence resolving
