### ISSUE TITLE
[IOTS-373] [UX] mouse overlapping on symbols should give tip message

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#755]
<p>In device management, it is better to have tip message(e.g. option name) when mouse overlapping on symbols (see attached)<br/> pages: "devicemgt/groups" , "devicemgt/device"</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-373'>https://wso2.org/jira/browse/IOTS-373</a></p>

**Comment by menakaj** [comment]
This is fixed for devices, groups, and users. 
Fix will be provided for roles.
