### ISSUE TITLE
[IOTS-252] It would be better to make the generated analytics car name to a combination that includes pom version

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#757]
<p>As for the current implementation source of device types cant be changed and redeployed to the server as is. </p> <p>If name of the analytics CAR file that gets generated can be made exclusive to the device type version number(in POM) multiple versions of a device type could be deployed(in theory). This would help in device type development and testing process.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-252'>https://wso2.org/jira/browse/IOTS-252</a></p>

**Comment by geethkokila** [comment]
Since this is a reference implementation, not fixing. And new device type adding apis are available with 3.1.0. hence closing
