### ISSUE TITLE
[IOTS-76] once an IOT application is deployed as a version we should be able to deprecated and update a newer version

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#758]
<p>once an application is deployed as a version we should be able to deprecated and update a newer version. A deployed device may be of one time scenario but if a new version comes we should be able to deprecated the older version</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-76'>https://wso2.org/jira/browse/IOTS-76</a></p>

**Comment by geethkokila** [comment]
This is fixed with APIM versioning strategy, hence closing
