### ISSUE TITLE
[IOTS-492] Replace default api#am#store.war with the patched war in IOT pack

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#763]
<p>Since api#am#store.war has been already released with API manager, we will be overriding the default war with the customized(patched) war which contains the fix. </p> <p>In future, once the latest war gets released with the fixes, we need to revert this change back to having the default war.</p> <p>changes are done in <br/> &amp;lt;product-iots&amp;gt;/modules/core/distribution/src/repository/resources/web-apps/api#am#store#v0.11.war<br/> &amp;lt;product-iots&amp;gt;/modules/core/distribution/src/assembly/bin.xml</p> <p><b>To keep track on this, make sure to resolve this ticket after reverting the changes once API manager releases the latest war</b></p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-492'>https://wso2.org/jira/browse/IOTS-492</a></p>

**Comment by geethkokila** [comment]
This is fixed by @ayyoob, hence resolving.
