### ISSUE TITLE
[IOTS-430] Adding support for STOMP

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#765]
<p>STOMP is the Simple (or Streaming) Text Orientated Messaging Protocol<span class="error">[1]</span> which is built on top of WebSocket. In this task, there will be output adapter needs to be created which warp STOMP functionality. </p> <p><span class="error">[1]</span>. <a href="https://stomp.github.io/" class="external-link" rel="nofollow">https://stomp.github.io/</a></p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-430'>https://wso2.org/jira/browse/IOTS-430</a></p>

**Comment by geethkokila** [comment]
Not planning to support, hence closing
