### ISSUE TITLE
[IOTS-428] Remove the pizzashack sample form the IoTS pack

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#766]
<p>The $subject is not required for IoTS. Therefore, it will be good if we can remove it.</p> <p><span class="error">[1]</span> sample/pizzashack/v1].File</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-428'>https://wso2.org/jira/browse/IOTS-428</a></p>

**Comment by geethkokila** [comment]
This is removed from the IoT 3.1.0 pack, hence resolving
