### ISSUE TITLE
[IOTS-258] Custom device type archetype needs to be updated to make it work on distributed setup

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#767]
<p>Custom device type archetype needs to be updated to make the sample device type work on distributed setup. </p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-258'>https://wso2.org/jira/browse/IOTS-258</a></p>

**Comment by geethkokila** [comment]
IoT 3.1.0 has introduced api based approach to add custom device types.
