### ISSUE TITLE
[IOTS-353] Clustering Docs needs to test for IoT

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#769]
<p>Clustering docs in EMM needs to tested for IoT Server. </p> <p>IoT server has profiles publisher, worker, keymanager, gateway and has distributions for Broker and DAS.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-353'>https://wso2.org/jira/browse/IOTS-353</a></p>

**Comment by geethkokila** [comment]
This is done 

https://docs.google.com/document/d/1r4nO1CsCmtfDQexfmnNIqwMd5J9Q8njkzvW1BtiAIV8/edit#
