### ISSUE TITLE
[IOTS-294] IoT-APIM Integration - Make IoT relying on external API Manager REST APIs

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#770]
<p>Use following apis, for DCR, token, publisher and store endpoints</p> <p><span class="error">[1]</span> - <a href="http://localhost:9763/client-registration/v0.9/register" class="external-link" rel="nofollow">http://localhost:9763/client-registration/v0.9/register</a><br/> <span class="error">[2]</span> - <a href="https://localhost:8243/token" class="external-link" rel="nofollow">https://localhost:8243/token</a><br/> <span class="error">[3]</span> - <a href="https://localhost:9443/api/am/publisher/v0.10/apis" class="external-link" rel="nofollow">https://localhost:9443/api/am/publisher/v0.10/apis</a><br/> <span class="error">[4]</span> - <a href="https://localhost:9443/api/am/publisher/v0.10/apis/change-lifecycle?apiId=" class="external-link" rel="nofollow">https://localhost:9443/api/am/publisher/v0.10/apis/change-lifecycle?apiId=</a>&amp;lt;id&amp;gt;<br/> <span class="error">[5]</span> - <a href="https://localhost:9443/api/am/store/v0.10/applications" class="external-link" rel="nofollow">https://localhost:9443/api/am/store/v0.10/applications</a><br/> <span class="error">[6]</span> - <a href="https://localhost:9443/api/am/store/v0.10/apis" class="external-link" rel="nofollow">https://localhost:9443/api/am/store/v0.10/apis</a><br/> <span class="error">[7]</span> - <a href="https://localhost:9443/api/am/store/v0.10/subscriptions" class="external-link" rel="nofollow">https://localhost:9443/api/am/store/v0.10/subscriptions</a><br/> <span class="error">[8]</span> - <a href="https://localhost:9443/api/am/store/v0.10/applications/generate-keys?applicationId=" class="external-link" rel="nofollow">https://localhost:9443/api/am/store/v0.10/applications/generate-keys?applicationId=</a>&amp;lt;id&amp;gt;</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-294'>https://wso2.org/jira/browse/IOTS-294</a></p>

**Comment by geethkokila** [comment]
This is done.
