### ISSUE TITLE
[IOTS-298] Re-enable IoT integration tests

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#771]
<p>Integration &amp;amp; UI Tests written for IoT Server are disabled. It is need to update test cases to comply with latest changes and need to re enabled.</p><p>Reference: <a href='https://wso2.org/jira/browse/IOTS-298'>https://wso2.org/jira/browse/IOTS-298</a></p>

**Comment by geethkokila** [comment]
This is done by @Megala21 

https://github.com/wso2/product-iots/commit/a1688140c5c8499541cfd24c83d9d5fe8d967d28

https://github.com/wso2/product-iots/commit/ed7e5749395637e0cd7a26cbd0e75dbf898c2f76

https://github.com/wso2/product-iots/commit/fbab71b0f7d2577ab51d3d58feb705ebe575da3b
