### ISSUE TITLE
[EMM-1108] [Cluster] The way a user is supposed to do the configurations in config.json in jaggeryapps needs to be improved by fixing the repetitive configuration values needed

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#777]
<p>Currently the config.json file inside the <br/> repository/deployment/server/jaggeryapps/emm/config/ </p> <p>needs to be configured with host names based on the type of the deployment. (Manager, Number of Workers, Key Manager, IDP).</p> <p>However, there are few places that the same hostname information needs to be provided repetitively. A proper way should be to give the user the option of adding one Hostname value just one time and the jaggery app itself need to do the constructing of urls accordingly. </p> <p>Example working config of a manager node is as following. </p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> { <span class="code-quote">"appContext"</span> : <span class="code-quote">"/emm/"</span>, <span class="code-quote">"webAgentContext"</span> : <span class="code-quote">"/emm-web-agent/"</span>, <span class="code-quote">"apiContext"</span> : <span class="code-quote">"api"</span>, <span class="code-quote">"httpsURL"</span> : <span class="code-quote">"https:<span class="code-comment">//mgt.emm.wso2.com"</span>, </span> <span class="code-quote">"httpURL"</span> : <span class="code-quote">"http:<span class="code-comment">//mgt.emm.wso2.com"</span>, </span> <span class="code-quote">"enrollmentDir"</span>: <span class="code-quote">"/emm-web-agent/enrollment"</span>, <span class="code-quote">"iOSConfigRoot"</span> : <span class="code-quote">"%https.ip%/ios-enrollment/"</span>, <span class="code-quote">"iOSAPIRoot"</span> : <span class="code-quote">"%https.ip%/ios/"</span>, <span class="code-quote">"dynamicClientRegistrationEndPoint"</span> : <span class="code-quote">"https:<span class="code-comment">//keymgt.emm.wso2.com/dynamic-client-web/register/"</span>, </span> <span class="code-quote">"adminService"</span>:<span class="code-quote">"https:<span class="code-comment">//mgt.emm.wso2.com"</span>, </span> <span class="code-quote">"idPServer"</span>:<span class="code-quote">"https:<span class="code-comment">//keymgt.emm.wso2.com"</span>, </span> <span class="code-quote">"callBackUrl"</span>:<span class="code-quote">"%https.ip%/mdm-admin"</span>, <span class="code-quote">"adminUser"</span>:<span class="code-quote">"admin"</span>, <span class="code-quote">"usernameLength"</span>:30, <span class="code-quote">"device"</span> : { <span class="code-quote">"ios"</span> : { <span class="code-quote">"location"</span> : <span class="code-quote">"%http.ip%/emm/<span class="code-keyword">public</span>/asset-download-agent-ios/asset/ios-agent.ipa"</span>, <span class="code-quote">"bundleID"</span> : <span class="code-quote">"org.wso2.carbon.emm.iOSMDMAgent"</span>, <span class="code-quote">"version"</span> : <span class="code-quote">"1.0"</span>, <span class="code-quote">"appName"</span> : <span class="code-quote">"EMM iOS Agent"</span> } }, <span class="code-quote">"androidAgentApp"</span> : <span class="code-quote">"android-agent.apk"</span>, <span class="code-quote">"windowsConfigRoot"</span> : <span class="code-quote">"%http.ip%/mdm-windows-agent/services/federated/bst/authentication"</span>, <span class="code-quote">"ssoConfiguration"</span> : { <span class="code-quote">"enabled"</span> : <span class="code-keyword">false</span>, <span class="code-quote">"issuer"</span> : <span class="code-quote">"mdm"</span>, <span class="code-quote">"appName"</span> : <span class="code-quote">"admin_emm"</span>, <span class="code-quote">"identityProviderURL"</span> : <span class="code-quote">"%https.ip%/sso/samlsso.jag"</span>, <span class="code-quote">"responseSigningEnabled"</span> : <span class="code-quote">"<span class="code-keyword">true</span>"</span>, <span class="code-quote">"keyStorePassword"</span> : <span class="code-quote">"wso2carbon"</span>, <span class="code-quote">"identityAlias"</span> : <span class="code-quote">"wso2carbon"</span>, <span class="code-quote">"keyStoreName"</span> : <span class="code-quote">"/repository/resources/security/wso2carbon.jks"</span> }, <span class="code-quote">"generalConfig"</span> : { <span class="code-quote">"host"</span> : <span class="code-quote">"http:<span class="code-comment">//localhost:9763"</span>, </span> <span class="code-quote">"companyName"</span> : <span class="code-quote">"WSO2 Enterprise Mobility Manager"</span>, <span class="code-quote">"browserTitle"</span> : <span class="code-quote">"WSO2 EMM"</span>, <span class="code-quote">"copyrightText"</span> : <span class="code-quote">"\u00A9 %date-year%, WSO2 Inc. (http:<span class="code-comment">//www.wso2.org) All Rights Reserved."</span> </span> } } </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/EMM-1108'>https://wso2.org/jira/browse/EMM-1108</a></p>

**Comment by geethkokila** [comment]
This has been fixed with the introduction of the system properties. No more configs are needed on the config.json file
