### ISSUE TITLE
[EMM-1497] Description for timestamp related parameters can be improved in the Device Management swagger def

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#779]
<p>Description for timestamp related parameters can be improved in the swagger definition. It would be better to say you need to provide the human readable conversion of the timestamp and not the actual timestamp value.</p><p>Reference: <a href='https://wso2.org/jira/browse/EMM-1497'>https://wso2.org/jira/browse/EMM-1497</a></p>

**Comment by geethkokila** [comment]
This is fixed and now we are using as follows "Thu, 01 Jun 2017 16:35:26 +0530"
