### ISSUE TITLE
[EMM-1359] Remove the Certificate configurations from iOS platform configurations

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#783]
<p>Currently we have the EMM iOS certificate configurations under the platform configurations. It must be removed and included under a separate section named server settings or something simillar.</p><p>Reference: <a href='https://wso2.org/jira/browse/EMM-1359'>https://wso2.org/jira/browse/EMM-1359</a></p>

**Comment by Kamidu** [comment]
This is fixed and certification configuration is moved to configuration management
