### ISSUE TITLE
[EMM-1278] Configuration management related code needs to be refactored

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#796]
<p>When working with configurations, all tenant configuration logic needs to be moved to device management core, instead of having plugin specific implementation, Currently it look like bellow, </p> <p>if(license != null &amp;amp;&amp;amp; configs != null) </p> { entry.setContentType(AndroidConstants.TenantConfigProperties.CONTENT_TYPE_TEXT); entry.setName(AndroidConstants.TenantConfigProperties.LICENSE_KEY); entry.setValue(license.getText()); configs.add(entry); tenantConfiguration.setConfiguration(configs); }<p>Reference: <a href='https://wso2.org/jira/browse/EMM-1278'>https://wso2.org/jira/browse/EMM-1278</a></p>

**Comment by inoshperera** [comment]
This is now in device mgt core instead of plugins.
