### ISSUE TITLE
[APPM-1588] Documentation add REST API bug

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#803]
<p>When we add the documentation by using REST API it does not add the doc content for it.<br/> So, if we called documentation GET API, it will check for the doc content and since doc content is not in there it will return 404 not found.</p> <p>Reproduce steps.<br/> 1. Add the documentation<br/> API - "http://localhost:9763/api/appm/publisher/v1.1/apps/webapp/id/<tt>webappId</tt>/docs" <br/> Body - </p> { "sourceType": "INLINE", "sourceUrl": null, "otherTypeName": null, "summary": "This is a sample documentation", "name": "Doc01", "type": "HOWTO" } <p>2. Call the documentation retrive,<br/> API - <a href="http://localhost:9763/api/appm/publisher/v1.1/apps/webapp/id/" class="external-link" rel="nofollow">http://localhost:9763/api/appm/publisher/v1.1/apps/webapp/id/</a><tt>webappId</tt>/docs<br/> Responce - </p> { "message": "Not Found", "error": [], "code": 404, "description": "Requested webapp with Id '6af0c01f-1b63-460d-af8e-82e8a59d51cc' not found", "moreInfo": "" } <p>Note : If we add the doc content using "http://localhost:9763/api/appm/publisher/v1.1/apps/webapp/id/<tt>webappId</tt>/docs/<tt>docId</tt>/content" API, it will returns the documentationlist.</p> <p><b><tt>webappId</tt> and <tt>docId</tt> are perameters.</b></p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1588'>https://wso2.org/jira/browse/APPM-1588</a></p>

**Comment by inoshperera** [comment]
This is not relevant to IoT server. Hence closing the issue
