### ISSUE TITLE
[APPM-1160] MDM devices can only be discovered from one tenant space at a time

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#807]
<p>According to current MDM integration configurations of app manager , devices will only be discovered from the tenant space of the 'AuthUser' defined in the following configuration of app-manager.xml<br/> Therefore devices are only discovered from one tenant space in MDM at a time.<br/> If devices are registered in multiple tenant spaces on MDM , APPM configurations need to be changes and the APPM server needs to be restarted.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> &amp;lt;MDM name=<span class="code-quote">"WSO2MDM"</span> bundle=<span class="code-quote">"org.wso2.carbon.appmgt.mdm.wso2mdm"</span>&amp;gt; &amp;lt;Property name=<span class="code-quote">"ServerURL"</span>&amp;gt;https:<span class="code-comment">//localhost:9450&amp;lt;/Property&amp;gt; </span> &amp;lt;Property name=<span class="code-quote">"TokenApiURL"</span>&amp;gt;https:<span class="code-comment">//localhost:9448/oauth2/token&amp;lt;/Property&amp;gt; </span> &amp;lt;Property name=<span class="code-quote">"ClientKey"</span>&amp;gt;b13C2PeKXaVKJwASIUMRFjHVlMwa&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"ClientSecret"</span>&amp;gt;8UDfqtH4J1vGaOo_PqPm7U1pLDQa&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"AuthUser"</span>&amp;gt;tenant1@tenant1.com&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"AuthPass"</span>&amp;gt;tenant1&amp;lt;/Property&amp;gt; &amp;lt;/MDM&amp;gt; </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1160'>https://wso2.org/jira/browse/APPM-1160</a></p>

**Comment by geethkokila** [comment]
As app manager is used internally in the 3.1.0 release with the manager node. This component is not used. hence closing the issue
