### ISSUE TITLE
[APPM-1342] Hide REST APIs also when type is hidden in app-manager.xml

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#809]
<p>When web app is disabled in app-manager.xml, all the UIs, URLs and REST APIs should be hidden. For this moment only UIs and accessible URLs are hidden but not REST APIs. Hide the REST API also according to the hidden type.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1342'>https://wso2.org/jira/browse/APPM-1342</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
