### ISSUE TITLE
[APPM-1092] Test failure when a port offset is set from the automation framework.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#810]
<p>When a port offset is set from the automation.xml, that change is not getting reflected in carbon.xml and the offset value remain 0. Since that the offset change is not picked by store.js and due that the Store login test case is failing. </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1092'>https://wso2.org/jira/browse/APPM-1092</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
