### ISSUE TITLE
[APPM-1622] storagePath of rxts common to API Manager and APP manager should be unique from each other

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#816]
<p>Currently, the storagePaths of the following rxts are the same for APP manager and API manager.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> * documentation * provider * reply * topic </pre> </div></div> <p>In case we add a resource for any of the rxts types above it would save to a common location. Assume the below scenario.</p> <ul> <li>Mount the same governance registry to both API Manager and APP Manager instance</li> <li>Startup the API Manager server first and it would write the content of the documentation.rxt which resides under the location <b>APIM-Home/repository/resources/rxts</b> to the registry under the path <b>/_system/governance/repository/components/org.wso2.carbon.governance/types/documentation.rxt</b></li> <li>Then start up the APP Manager server</li> <li>But when you add a document through the APP Manager instance it would save the document resource under <b>/_system/governance/apimgt</b> since this is what's given in the documentation.rxt</li> <li>Then when you try to delete the document, it would look for all the artifacts under /_system/governance/appmgt and since it's available under <b>/_system/governance/apimgt</b> instead, it would throw the below exception. <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> Caused by: org.wso2.carbon.registry.core.exceptions.ResourceNotFoundException: Resource does not exist at path /_system/governance/appmgt/applicationdata/provider/admin/RaviApp2/1.0.0/documentation/asdsa at org.wso2.carbon.registry.core.jdbc.handlers.builtin.MountHandler.get(MountHandler.java:449) at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.get(HandlerManager.java:2444) at org.wso2.carbon.registry.core.jdbc.handlers.UserDefinedHandlerManager.get(UserDefinedHandlerManager.java:200) at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.get(HandlerLifecycleManager.java:944) at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.get(EmbeddedRegistry.java:512) at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.getGhostResourceFromCache(CacheBackedRegistry.java:194) at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.get(CacheBackedRegistry.java:167) at org.wso2.carbon.registry.core.session.UserRegistry.getInternal(UserRegistry.java:620) at org.wso2.carbon.registry.core.session.UserRegistry.access$400(UserRegistry.java:60) at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:603) at org.wso2.carbon.registry.core.session.UserRegistry$5.run(UserRegistry.java:600) at java.security.AccessController.doPrivileged(Native Method) at org.wso2.carbon.registry.core.session.UserRegistry.get(UserRegistry.java:600) at org.wso2.carbon.appmgt.impl.APIProviderImpl.removeDocumentation(APIProviderImpl.java:1049) ... 65 more </pre> </div></div></li> <li>The same behaviour can be seen from API Manager side if you start up the App Manager instance first</li> </ul><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1622'>https://wso2.org/jira/browse/APPM-1622</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
