### ISSUE TITLE
[APPM-1586] Search by business owner does not support pattern match

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#821]
<p>Search by business owner do the exact string match of the searched text.<br/> e.g If business owner name is "John", search result for "jhon", "jo" does not return the apps which has business owners with above name pattern.Need to support pattern match.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1586'>https://wso2.org/jira/browse/APPM-1586</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
