### ISSUE TITLE
[APPM-1590] [Intermittent] CNF exception is occurred when server start up.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#822]
<p>Intermittently, following exception is occurred when server start up.</p> <p>INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - <span class="error">[2016-08-03 11:13:47,982]</span> ERROR - ApplicationContext StandardWrapper.Throwable<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mobileAppServiceV1': Cannot resolve reference to bean 'discoveryServiceV1' while setting bean property 'serviceBeans' with key <span class="error">[1]</span>; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'discoveryServiceV1' defined in URL <span class="error">[jndi:/localhost/api/WEB-INF/cxf-servlet.xml]</span>: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class <span class="error">[org.wso2.carbon.appmgt.services.api.v1.apps.discovery.service.DiscoveryService]</span>: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/wso2/carbon/appmgt/impl/discovery/DiscoveryCredentials<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:328)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:106)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedList(BeanDefinitionValueResolver.java:353)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:153)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1327)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1085)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:516)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:455)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:192)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:585)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:895)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:425)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.cxf.transport.servlet.CXFServlet.createSpringContext(CXFServlet.java:151)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.cxf.transport.servlet.CXFServlet.loadBus(CXFServlet.java:74)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.cxf.transport.servlet.CXFNonSpringServlet.init(CXFNonSpringServlet.java:76)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1282)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1195)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:866)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:134)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1749)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1708)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at java.lang.Thread.run(Thread.java:745)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'discoveryServiceV1' defined in URL <span class="error">[jndi:/localhost/api/WEB-INF/cxf-servlet.xml]</span>: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class <span class="error">[org.wso2.carbon.appmgt.services.api.v1.apps.discovery.service.DiscoveryService]</span>: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/wso2/carbon/appmgt/impl/discovery/DiscoveryCredentials<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:964)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:910)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:484)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:455)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:192)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:322)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - ... 43 more<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class <span class="error">[org.wso2.carbon.appmgt.services.api.v1.apps.discovery.service.DiscoveryService]</span>: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: org/wso2/carbon/appmgt/impl/discovery/DiscoveryCredentials<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:141)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:74)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:957)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - ... 51 more<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - Caused by: java.lang.NoClassDefFoundError: org/wso2/carbon/appmgt/impl/discovery/DiscoveryCredentials<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.wso2.carbon.appmgt.services.api.v1.apps.discovery.service.DiscoveryService.&amp;lt;init&amp;gt;(DiscoveryService.java:47)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at java.lang.reflect.Constructor.newInstance(Constructor.java:526)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:126)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - ... 53 more<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.appmgt.impl.discovery.DiscoveryCredentials<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.wso2.carbon.webapp.mgt.loader.CarbonWebappClassLoader.loadClass(CarbonWebappClassLoader.java:154)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1701)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - ... 59 more<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - <span class="error">[2016-08-03 11:13:47,983]</span> ERROR - StandardWrapperValve Allocate exception for servlet JAXServlet<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - java.lang.ClassNotFoundException: org.wso2.carbon.appmgt.impl.discovery.DiscoveryCredentials<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.wso2.carbon.webapp.mgt.loader.CarbonWebappClassLoader.loadClass(CarbonWebappClassLoader.java:154)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1701)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at org.wso2.carbon.appmgt.services.api.v1.apps.discovery.service.DiscoveryService.&amp;lt;init&amp;gt;(DiscoveryService.java:47)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br/> INFO <span class="error">[org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader]</span> - at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1590'>https://wso2.org/jira/browse/APPM-1590</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
