### ISSUE TITLE
[APPM-1580] Mobile app direct download does not work

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#823]
<p>steps to reprodcue<br/> 1. change direct download to true in app-manager.xml<br/> &amp;lt;Config name="EnableDirectDownload"&amp;gt;true&amp;lt;/Config&amp;gt;<br/> 2. upload an androind apk<br/> 3. Go to the store by mobile device<br/> 4. Click install, Page refresh happens no file downloading happens.</p> <p>Expected behavior apk file should be downloaded to mobile device.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1580'>https://wso2.org/jira/browse/APPM-1580</a></p>

**Comment by geethkokila** [comment]
Tested in the IoT server 3.1.0 cluster. Was able to directly download the APK file. hence closing
