### ISSUE TITLE
[APPM-1640] Create button is disabled after a trying to create a app without a mandatory field.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#824]
<p>Steps to reproduce<br/> --------------------------</p> <p>1) Try to create an app without a mandatory field (e.g. web app URL)</p> <p>2) An error message will be displayed on the same page and the create button is disabled.</p> <p>3) Even the missing field is entered the button is still disabled.</p> <p>Workaround<br/> ----------------</p> <p>Clicking on the disabled button makes it enabled. And clicking on the button again will create the app.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1640'>https://wso2.org/jira/browse/APPM-1640</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
