### ISSUE TITLE
[APPM-1636] When trying to login with secondary user store manager, solr exception occurs

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#827]
<p>Reference: <a href='https://wso2.org/jira/browse/APPM-1636'>https://wso2.org/jira/browse/APPM-1636</a></p>

**Comment by Megala21** [comment]
This is not re-producible with the default pack.

**Comment by Megala21** [comment]
This was re-producible when the "Use user store domain in local subject identifier" and "Use tenant domain in local subject identifier" is not checked under "Local & Outbound Authentication Configuration"  of service provider configuration of publisher and store in an external IDP. After checking them, this issue got resolved. Created a doc jira to add this to documentation #1343

**Comment by Megala21** [comment]
This is a user error, due to missing instructions in documentation. Since this involves an external IDP, it requires manual steps, hence cannot automate this.
