### ISSUE TITLE
[APPM-1631] Tags should be removed from mobile app create page.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#829]
<p>Tags should be removed from the mobile app create page.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1631'>https://wso2.org/jira/browse/APPM-1631</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
