### ISSUE TITLE
[APPM-1630] Performance issues when there are large number of web apps

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#830]
<p>It takes longer time to create the web apps and to retrieve the web apps when there are large number of web apps. I have 300 web apps and it takes 15secs to create a web app and 20 secs to display the list of web apps</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1630'>https://wso2.org/jira/browse/APPM-1630</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
