### ISSUE TITLE
[APPM-1620] Password under SSOConfiguration or app-manager.xml is not supported by Secure Vault

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#832]
<p>The password which is under SSOConfiguration is not read by Secure Vault. We need to provide the support for the same.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1620'>https://wso2.org/jira/browse/APPM-1620</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
