### ISSUE TITLE
[APPM-1608] App Store - Public App URL Constructed Incorrectly

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#834]
<p>Configuring new public apps in EMM App Store to be installed on iOS devices.But It appears to be a bug in the way the URL is constructed for new apps to be downloaded from Apple.</p> <p>For example, Instagram's URL in iTunes is this:</p> <p><a href="https://itunes.apple.com/en/app/instagram/id389801252?mt=8" class="external-link" rel="nofollow">https://itunes.apple.com/en/app/instagram/id389801252?mt=8</a></p> <p>After publishing the app and approving it, the URL (as indicated in the publisher app page with the QR Code) is this:</p> <p><a href="https://itunes.apple.com/en/app/idundefined" class="external-link" rel="nofollow">https://itunes.apple.com/en/app/idundefined</a></p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1608'>https://wso2.org/jira/browse/APPM-1608</a></p>

**Comment by geethkokila** [comment]
Fixed in https://github.com/wso2/carbon-appmgt/pull/524
