### ISSUE TITLE
[APPM-1603] Throwing solr exception in when we log into publisher with a role that has a colon

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#835]
<p>when we log into the publisher for the first time with a user from a secondary user store then it creates a role for that user which includes a colon character in that role. This character needs to be escaped before making registry calls</p> <p><span class="error">[2016-08-24 23:42:12,088]</span> ERROR - SolrCore org.apache.solr.common.SolrException: undefined field internal/private_bnymellon.net<br/> at org.apache.solr.schema.IndexSchema.getDynamicFieldType(IndexSchema.java:1298)<br/> at org.apache.solr.schema.IndexSchema$SolrQueryAnalyzer.getWrappedAnalyzer(IndexSchema.java:444)<br/> at org.apache.lucene.analysis.DelegatingAnalyzerWrapper$DelegatingReuseStrategy.getReusableComponents(DelegatingAnalyzerWrapper.java:74)<br/> at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:172)<br/> at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:199)<br/> at org.apache.solr.parser.SolrQueryParserBase.newFieldQuery(SolrQueryParserBase.java:370)<br/> at org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:753)<br/> at org.apache.solr.parser.SolrQueryParserBase.handleBareTokenQuery(SolrQueryParserBase.java:537)<br/> at org.apache.solr.parser.QueryParser.Term(QueryParser.java:299)<br/> at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:185)<br/> at org.apache.solr.parser.QueryParser.Query(QueryParser.java:139)<br/> at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:189)<br/> at org.apache.solr.parser.QueryParser.Query(QueryParser.java:107)<br/> at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:96)<br/> at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:151)<br/> at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50)<br/> at org.apache.solr.search.QParser.getQuery(QParser.java:141)<br/> at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:203)<br/> at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:229)<br/> at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)<br/> at org.apache.solr.core.SolrCore.execute(SolrCore.java:2064)<br/> at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:179)<br/> at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:135)<br/> at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:943)<br/> at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:958)<br/> at org.wso2.carbon.registry.indexing.solr.SolrClient.query(SolrClient.java:609)<br/> at org.wso2.carbon.registry.indexing.solr.SolrClient.query(SolrClient.java:526)<br/> at org.wso2.carbon.registry.indexing.service.ContentBasedSearchService.searchContentInternal(ContentBasedSearchService.java:166)<br/> at org.wso2.carbon.registry.indexing.service.ContentBasedSearchService.searchByAttribute(ContentBasedSearchService.java:279)</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1603'>https://wso2.org/jira/browse/APPM-1603</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
