### ISSUE TITLE
[APPM-1602] Move 'EnabledAssetTypeList' configuration in app-manager.xml as a tenant configuration

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#836]
<p>Move the property to appmgt-tenant-conf.xml and rename the property name to 'EnabledAssetTypes'</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1602'>https://wso2.org/jira/browse/APPM-1602</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
