### ISSUE TITLE
[APPM-1323] http://localhost:9763/store/resources/{app-type}/{version}/subscription/{userName} is not working for mobileapps

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#840]
<p><a href="http://localhost:9763/store/resources/" class="external-link" rel="nofollow">http://localhost:9763/store/resources/</a></p> {app-type} <p>/</p> {version} <p>/subscription/</p> {userName} <p> is not working for mobileapps</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1323'>https://wso2.org/jira/browse/APPM-1323</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
