### ISSUE TITLE
[APPM-1551] In Publisher Mobile app search, the page with 'No mobile applications added yet. ' is returned for empty set of searched apps

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#841]
<p>Reference: <a href='https://wso2.org/jira/browse/APPM-1551'>https://wso2.org/jira/browse/APPM-1551</a></p>

**Comment by geethkokila** [comment]
Tested on the IoT server 3.1.0 cluster, issue did not happen, hence closing the issue
