### ISSUE TITLE
[APPM-1540] Add Proper validation when search mobile apps with invalid characters

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#842]
<p>Add Proper validation when search mobile apps with invalid characters. If we search with invalid characters, back-end exception is occurred.</p> <p><span class="error">[2016-07-11 17:21:57,812]</span> ERROR - SolrCore org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse 'overview_displayName_s:<b>(</b>': Encountered "&amp;lt;EOF&amp;gt;" at line 1, column 26.<br/> Was expecting one of:<br/> &amp;lt;AND&amp;gt; ...<br/> &amp;lt;OR&amp;gt; ...<br/> &amp;lt;NOT&amp;gt; ...<br/> "+" ...<br/> "-" ...<br/> &amp;lt;BAREOPER&amp;gt; ...<br/> "(" ...<br/> ")" ...<br/> "*" ...<br/> "^" ...<br/> &amp;lt;QUOTED&amp;gt; ...<br/> &amp;lt;TERM&amp;gt; ...<br/> &amp;lt;FUZZY_SLOP&amp;gt; ...<br/> &amp;lt;PREFIXTERM&amp;gt; ...<br/> &amp;lt;WILDTERM&amp;gt; ...<br/> &amp;lt;REGEXPTERM&amp;gt; ...<br/> "[" ...<br/> "{" ...<br/> &amp;lt;LPARAMS&amp;gt; ...<br/> &amp;lt;NUMBER&amp;gt; ...</p> <p>at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:214)<br/> at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:229)<br/> at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)<br/> at org.apache.solr.core.SolrCore.execute(SolrCore.java:2064)<br/> at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:179)<br/> at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:135)<br/> at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:943)<br/> at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:958)<br/> at org.wso2.carbon.registry.indexing.solr.SolrClient.query(SolrClient.java:593)<br/> at org.wso2.carbon.registry.indexing.solr.SolrClient.query(SolrClient.java:510)<br/> at org.wso2.carbon.registry.indexing.service.ContentBasedSearchService.searchContentInternal(ContentBasedSearchService.java:166)<br/> at org.wso2.carbon.registry.indexing.service.ContentBasedSearchService.searchByAttribute(ContentBasedSearchService.java:279)<br/> at org.wso2.carbon.registry.indexing.internal.IndexingServiceComponent$AttributeSearchServiceImpl.search(IndexingServiceComponent.java:164)<br/> at org.wso2.carbon.registry.indexing.internal.IndexingServiceComponent$AttributeSearchServiceImpl.search(IndexingServiceComponent.java:177)<br/> at org.wso2.carbon.registry.indexing.internal.IndexingServiceComponent$AttributeSearchServiceImpl.search(IndexingServiceComponent.java:191)<br/> at org.wso2.carbon.registry.indexing.internal.IndexingServiceComponent$AttributeSearchServiceImpl.search(IndexingServiceComponent.java:158)<br/> at org.wso2.carbon.governance.api.util.GovernanceUtils.findGovernanceArtifacts(GovernanceUtils.java:1766)<br/> at org.wso2.carbon.governance.api.common.GovernanceArtifactManager.findGovernanceArtifacts(GovernanceArtifactManager.java:720)<br/> at org.wso2.carbon.governance.api.generic.GenericArtifactManager.findGenericArtifacts(GenericArtifactManager.java:274)<br/> at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.&amp;lt;carbon&amp;gt;.scripts.registry.c0._c_anonymous_10(&amp;lt;carbon&amp;gt;/scripts/registry/artifacts.js:187)<br/> at org.jaggeryjs.rhino.&amp;lt;carbon&amp;gt;.scripts.registry.c0.call(&amp;lt;carbon&amp;gt;/scripts/registry/artifacts.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0._c_anonymous_2(/publisher/assets/default/assets.jag:65)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0.call(/publisher/assets/default/assets.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0._c_anonymous_8(/publisher/assets/default/assets.jag:201)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0.call(/publisher/assets/default/assets.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183)<br/> at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0._c_anonymous_1(/publisher/assets/default/assets.jag:364)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0.call(/publisher/assets/default/assets.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.jaggeryjs.rhino.&amp;lt;store&amp;gt;.scripts.c0._c_anonymous_17(&amp;lt;store&amp;gt;/scripts/server.js:286)<br/> at org.jaggeryjs.rhino.&amp;lt;store&amp;gt;.scripts.c0.call(&amp;lt;store&amp;gt;/scripts/server.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0._c_script_0(/publisher/assets/default/assets.jag:14)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0.call(/publisher/assets/default/assets.jag)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0.exec(/publisher/assets/default/assets.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:309)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:149)<br/> at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)<br/> at org.jaggeryjs.rhino.publisher.controllers.c1._c_anonymous_1(/publisher/controllers/assets_router.jag:101)<br/> at org.jaggeryjs.rhino.publisher.controllers.c1.call(/publisher/controllers/assets_router.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.jaggeryjs.rhino.publisher.controllers.c1._c_script_0(/publisher/controllers/assets_router.jag:8)<br/> at org.jaggeryjs.rhino.publisher.controllers.c1.call(/publisher/controllers/assets_router.jag)<br/> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)<br/> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)<br/> at org.jaggeryjs.rhino.publisher.controllers.c1.call(/publisher/controllers/assets_router.jag)<br/> at org.jaggeryjs.rhino.publisher.controllers.c1.exec(/publisher/controllers/assets_router.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)<br/> at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)<br/> at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)<br/> at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)<br/> at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)<br/> at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1749)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1708)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/> at java.lang.Thread.run(Thread.java:745)<br/> Caused by: org.apache.solr.search.SyntaxError: Cannot parse 'overview_displayName_s:<b>(</b>': Encountered "&amp;lt;EOF&amp;gt;" at line 1, column 26.<br/> Was expecting one of:<br/> &amp;lt;AND&amp;gt; ...<br/> &amp;lt;OR&amp;gt; ...<br/> &amp;lt;NOT&amp;gt; ...<br/> "+" ...<br/> "-" ...<br/> &amp;lt;BAREOPER&amp;gt; ...<br/> "(" ...<br/> ")" ...<br/> "*" ...<br/> "^" ...<br/> &amp;lt;QUOTED&amp;gt; ...<br/> &amp;lt;TERM&amp;gt; ...<br/> &amp;lt;FUZZY_SLOP&amp;gt; ...<br/> &amp;lt;PREFIXTERM&amp;gt; ...<br/> &amp;lt;WILDTERM&amp;gt; ...<br/> &amp;lt;REGEXPTERM&amp;gt; ...<br/> "[" ...<br/> "{" ...<br/> &amp;lt;LPARAMS&amp;gt; ...<br/> &amp;lt;NUMBER&amp;gt; ...</p> <p>at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:155)<br/> at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50)<br/> at org.apache.solr.search.QParser.getQuery(QParser.java:141)<br/> at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:203)<br/> ... 118 more<br/> Caused by: org.apache.solr.parser.ParseException: Encountered "&amp;lt;EOF&amp;gt;" at line 1, column 26.<br/> Was expecting one of:<br/> &amp;lt;AND&amp;gt; ...<br/> &amp;lt;OR&amp;gt; ...<br/> &amp;lt;NOT&amp;gt; ...<br/> "+" ...<br/> "-" ...<br/> &amp;lt;BAREOPER&amp;gt; ...<br/> "(" ...<br/> ")" ...<br/> "*" ...<br/> "^" ...<br/> &amp;lt;QUOTED&amp;gt; ...<br/> &amp;lt;TERM&amp;gt; ...<br/> &amp;lt;FUZZY_SLOP&amp;gt; ...<br/> &amp;lt;PREFIXTERM&amp;gt; ...<br/> &amp;lt;WILDTERM&amp;gt; ...<br/> &amp;lt;REGEXPTERM&amp;gt; ...<br/> "[" ...<br/> "{" ...<br/> &amp;lt;LPARAMS&amp;gt; ...<br/> &amp;lt;NUMBER&amp;gt; ...</p> <p>at org.apache.solr.parser.QueryParser.generateParseException(QueryParser.java:649)<br/> at org.apache.solr.parser.QueryParser.jj_consume_token(QueryParser.java:531)<br/> at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:190)<br/> at org.apache.solr.parser.QueryParser.Query(QueryParser.java:139)<br/> at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:96)<br/> at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:151)<br/> ... 121 more</p> <p><span class="error">[2016-07-11 17:21:57,814]</span> ERROR - ContentBasedSearchService Invalid Search Query, query contains invalid characters<br/> org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse 'overview_displayName_s:<b>(</b>': Encountered "&amp;lt;EOF&amp;gt;" at line 1, column 26.<br/> Was expecting one of:<br/> &amp;lt;AND&amp;gt; ...<br/> &amp;lt;OR&amp;gt; ...<br/> &amp;lt;NOT&amp;gt; ...<br/> "+" ...<br/> "-" ...<br/> &amp;lt;BAREOPER&amp;gt; ...<br/> "(" ...<br/> ")" ...<br/> "*" ...<br/> "^" ...<br/> &amp;lt;QUOTED&amp;gt; ...<br/> &amp;lt;TERM&amp;gt; ...<br/> &amp;lt;FUZZY_SLOP&amp;gt; ...<br/> &amp;lt;PREFIXTERM&amp;gt; ...<br/> &amp;lt;WILDTERM&amp;gt; ...<br/> &amp;lt;REGEXPTERM&amp;gt; ...<br/> "[" ...<br/> "{" ...<br/> &amp;lt;LPARAMS&amp;gt; ...<br/> &amp;lt;NUMBER&amp;gt; ...</p> <p>at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:214)<br/> at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:229)<br/> at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)<br/> at org.apache.solr.core.SolrCore.execute(SolrCore.java:2064)<br/> at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:179)<br/> at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:135)<br/> at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:943)<br/> at org.apache.solr.client.solrj.SolrClient.query(SolrClient.java:958)<br/> at org.wso2.carbon.registry.indexing.solr.SolrClient.query(SolrClient.java:593)<br/> at org.wso2.carbon.registry.indexing.solr.SolrClient.query(SolrClient.java:510)<br/> at org.wso2.carbon.registry.indexing.service.ContentBasedSearchService.searchContentInternal(ContentBasedSearchService.java:166)<br/> at org.wso2.carbon.registry.indexing.service.ContentBasedSearchService.searchByAttribute(ContentBasedSearchService.java:279)<br/> at org.wso2.carbon.registry.indexing.internal.IndexingServiceComponent$AttributeSearchServiceImpl.search(IndexingServiceComponent.java:164)<br/> at org.wso2.carbon.registry.indexing.internal.IndexingServiceComponent$AttributeSearchServiceImpl.search(IndexingServiceComponent.java:177)<br/> at org.wso2.carbon.registry.indexing.internal.IndexingServiceComponent$AttributeSearchServiceImpl.search(IndexingServiceComponent.java:191)<br/> at org.wso2.carbon.registry.indexing.internal.IndexingServiceComponent$AttributeSearchServiceImpl.search(IndexingServiceComponent.java:158)<br/> at org.wso2.carbon.governance.api.util.GovernanceUtils.findGovernanceArtifacts(GovernanceUtils.java:1766)<br/> at org.wso2.carbon.governance.api.common.GovernanceArtifactManager.findGovernanceArtifacts(GovernanceArtifactManager.java:720)<br/> at org.wso2.carbon.governance.api.generic.GenericArtifactManager.findGenericArtifacts(GenericArtifactManager.java:274)<br/> at sun.reflect.GeneratedMethodAccessor169.invoke(Unknown Source)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.&amp;lt;carbon&amp;gt;.scripts.registry.c0._c_anonymous_10(&amp;lt;carbon&amp;gt;/scripts/registry/artifacts.js:187)<br/> at org.jaggeryjs.rhino.&amp;lt;carbon&amp;gt;.scripts.registry.c0.call(&amp;lt;carbon&amp;gt;/scripts/registry/artifacts.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0._c_anonymous_2(/publisher/assets/default/assets.jag:65)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0.call(/publisher/assets/default/assets.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0._c_anonymous_8(/publisher/assets/default/assets.jag:201)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0.call(/publisher/assets/default/assets.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183)<br/> at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0._c_anonymous_1(/publisher/assets/default/assets.jag:364)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0.call(/publisher/assets/default/assets.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.jaggeryjs.rhino.&amp;lt;store&amp;gt;.scripts.c0._c_anonymous_17(&amp;lt;store&amp;gt;/scripts/server.js:286)<br/> at org.jaggeryjs.rhino.&amp;lt;store&amp;gt;.scripts.c0.call(&amp;lt;store&amp;gt;/scripts/server.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0._c_script_0(/publisher/assets/default/assets.jag:14)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0.call(/publisher/assets/default/assets.jag)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c0.exec(/publisher/assets/default/assets.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:309)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:149)<br/> at sun.reflect.GeneratedMethodAccessor80.invoke(Unknown Source)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)<br/> at org.jaggeryjs.rhino.publisher.controllers.c1._c_anonymous_1(/publisher/controllers/assets_router.jag:101)<br/> at org.jaggeryjs.rhino.publisher.controllers.c1.call(/publisher/controllers/assets_router.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.jaggeryjs.rhino.publisher.controllers.c1._c_script_0(/publisher/controllers/assets_router.jag:8)<br/> at org.jaggeryjs.rhino.publisher.controllers.c1.call(/publisher/controllers/assets_router.jag)<br/> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)<br/> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)<br/> at org.jaggeryjs.rhino.publisher.controllers.c1.call(/publisher/controllers/assets_router.jag)<br/> at org.jaggeryjs.rhino.publisher.controllers.c1.exec(/publisher/controllers/assets_router.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.exec(WebAppManager.java:588)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:508)<br/> at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:747)<br/> at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:485)<br/> at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:377)<br/> at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:337)<br/> at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:120)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:99)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:57)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:62)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:159)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:57)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:436)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1078)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1749)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1708)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/> at java.lang.Thread.run(Thread.java:745)</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1540'>https://wso2.org/jira/browse/APPM-1540</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
