### ISSUE TITLE
[APPM-1541] When accessing skip Proxying app with disabling "CreateServiceProviderForSkipGatewayApps", there is a warning and error message

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#843]
<p>When accessing skip Proxying app with disabling "CreateServiceProviderForSkipGatewayApps", there is a warning and error message. </p> <p><span class="error">[2016-07-11 18:49:00,799]</span> WARN - ApplicationManagementAdminService Illegal Access! User admin does not have access to the application helloMyApp-1.0.0<br/> <span class="error">[2016-07-11 18:49:00,821]</span> ERROR - IS500SAMLSSOConfigurator Error retrieving identity providers for the service provider : 'helloMyApp-1.0.0'</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1541'>https://wso2.org/jira/browse/APPM-1541</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
