### ISSUE TITLE
[APPM-1528] APPM 1.1.0 : Version displayed by 'About'

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#844]
<p>The "about" link in APP manager 1.1.0 shows the version as 1.0.0.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1528'>https://wso2.org/jira/browse/APPM-1528</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
