### ISSUE TITLE
[APPM-1517] Refactor getAppHitsOverTime() method in org.wso2.carbon.appmgt.usage.client.impl.AppUsageStatisticsRdbmsClient

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#845]
<p>Refactor and use prepared statements in proper way to avoid security vulnarabilities. </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1517'>https://wso2.org/jira/browse/APPM-1517</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
