### ISSUE TITLE
[APPM-1495] User cannot login to admindashboard via Firefox 41 browser

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#846]
<p>User cannot login to admindashboard via Firefox 41 browser</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1495'>https://wso2.org/jira/browse/APPM-1495</a></p>

**Comment by geethkokila** [comment]
Tested on the Firefox on IoT 3.1.0 cluster.
