### ISSUE TITLE
[APPM-1173] Publisher button is not shown for approved webapps although publisher permission is assigned

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#847]
<p><b>Steps</b></p> <p>1. Create a role with the following permissions. (Refer the attachment Perm_1 and Perm_2)<br/> 2. By assigning the created role create a new user.<br/> 3. Now create a new web application.<br/> 4. Submit to review.<br/> 5. Login with admin and approve it.</p> <p><b>Issue</b> : The user is not shown the publisher button.</p> <p><b>Note</b> : The permission set given is almost identical to Internal/Creator role and to the Internal/Publisher roles combined. So the behavior should be consistent.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1173'>https://wso2.org/jira/browse/APPM-1173</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
