### ISSUE TITLE
[APPM-57] Resource level authorization with roles - Need to give proper error message to the user when is not authorized to access the resource

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#848]
<p>Currently there is no error message. Browser just shows "This webpage is not found".</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-57'>https://wso2.org/jira/browse/APPM-57</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
