### ISSUE TITLE
[APPM-1233] Although an app is advertised setting Allow Anonymous option set, the user is directed to the login page when accessing

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#850]
<p><b>Steps</b></p> <p>1. Create an web app by setting Allow Anonymous Access.<br/> 2. Publish the app to an external tenant store.<br/> 3. Now go to public store and click on the click on the advertised web app.</p> <p><b>Issue</b> : The user is directed to the login page. There is no need for the user be directed to the login page since allow anonymous access is set</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1233'>https://wso2.org/jira/browse/APPM-1233</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
