### ISSUE TITLE
[APPM-1424] Publisher web app search is not supported with '&' character

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#852]
<p>Even though registry supports to search artifacts with '&amp;amp;', publisher does not support web app search with '&amp;amp;'</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1424'>https://wso2.org/jira/browse/APPM-1424</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
