### ISSUE TITLE
[APPM-1400] In Webapp edit page, incompatible global policies are enabled

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#853]
<p>Steps to reproduce</p> <p>1) Create a webapp with 'Allow Anonymous Access' true. When this particular global policy is enabled, Restrict visibility policy option should be disabled.<br/> 2) Create a new version<br/> 3) Go to edit page of the new version<br/> 4) Expand the policies and Restrict visibility option is enabled. </p> <p>Expected behavior : Restrict Visibility option should be hidden when the anonymous access is enabled</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1400'>https://wso2.org/jira/browse/APPM-1400</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
