### ISSUE TITLE
[APPM-1383] Wrong details from the Get details API

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#854]
<p>I've published 2 apps with following names,</p> <p>gple<br/> gple_cpaas1</p> <p>When I try to get the details of 'gple' app, I'm always getting the details of gple_cpaas1 app.</p> <p>e..g<br/> Request<br/> curl -v "http://localhost:9763/store/apis/v1/assets/webapp/admin/gple/v1" --user admin:admin</p> <p>Response snippet<br/> {"id" : "c278c318-a28a-4c58-a55a-f06da12725dd", "type" : "webapp", "path" : "/_system/governance/appmgt/applicationdata/provider/admin/gple_cpaas1/v1/webapp", </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1383'>https://wso2.org/jira/browse/APPM-1383</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
