### ISSUE TITLE
[APPM-1368] Choose different icon to public store menu

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#855]
<p>currently public store is displayed as a separate menu(see attached image). if we are going to use this design then choose proper icon for public store.<br/> Or <br/> give a drop down option to select public store under "store" menu</p> <p>Also show the tenant store name in store menu instead of displaying it as "Store" when tenant stores available</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1368'>https://wso2.org/jira/browse/APPM-1368</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
