### ISSUE TITLE
[APPM-1325] sample app failing to deploy

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#857]
<p>deploy fail with below stacktrace</p> <p>java.io.FileNotFoundException: /Users/Lakshman/Documents/support/Verifone/wso2appm-1.2.0-SNAPSHOT/samples/plan-your-trip-1.2.0.war (No such file or directory)<br/> at java.io.FileInputStream.open(Native Method)<br/> at java.io.FileInputStream.&amp;lt;init&amp;gt;(FileInputStream.java:146)</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1325'>https://wso2.org/jira/browse/APPM-1325</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
