### ISSUE TITLE
[APPM-751] Disable 'Deploy samples' menu option if samples have already been deployed by the same user.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#858]
<p>Deploy samples menu option needs o be disabled for the logged in user, if that user has already deployed the samples.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-751'>https://wso2.org/jira/browse/APPM-751</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
