### ISSUE TITLE
[APPM-1196] Multiple user reviews are not displayed in firefox

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#860]
<p>When there are multiple user reviews for an APP, the scroll bar does not appear in firefox. Therefore only the top most review is visible.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1196'>https://wso2.org/jira/browse/APPM-1196</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
