### ISSUE TITLE
[APPM-1221] Error displayed if Edit option is clicked of a document after the session is invalidated

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#864]
<p><b>Steps</b></p> <p>1. Login to publisher and create a webapp.<br/> 2. Now add a document to the webapp.<br/> 3. Open the publisher in another tab and logout from the publisher.<br/> 4. Navigate to the first tab and click on Edit.</p> <p><b>Issue</b> : An error page is displayed when this happens. Refer the attachment. </p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> ERROR - WebAppManager org.mozilla.javascript.EcmaError: TypeError: Cannot read property <span class="code-quote">"registry"</span> from <span class="code-keyword">null</span> (/publisher/modules/rxt.manager.js#31) org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property <span class="code-quote">"registry"</span> from <span class="code-keyword">null</span> (/publisher/modules/rxt.manager.js#31) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571) at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273) at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536) at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24) at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748) at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486) at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378) at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338) at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178) at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47) at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56) at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141) at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot read property <span class="code-quote">"registry"</span> from <span class="code-keyword">null</span> (/publisher/modules/rxt.manager.js#31) at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687) at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665) at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3693) at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3712) at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:3725) at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1483) at org.jaggeryjs.rhino.publisher.modules.c0._c_anonymous_3(/publisher/modules/rxt.manager.js:31) at org.jaggeryjs.rhino.publisher.modules.c0.call(/publisher/modules/rxt.manager.js) at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_10(/publisher/modules/publisher.js:221) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_9(/publisher/modules/publisher.js:155) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:338) at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2349) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_8(/publisher/modules/publisher.js:149) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.controllers.c5._c_script_0(/publisher/controllers/inline-editor.jag:8) at org.jaggeryjs.rhino.publisher.controllers.c5.call(/publisher/controllers/inline-editor.jag) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) at org.jaggeryjs.rhino.publisher.controllers.c5.call(/publisher/controllers/inline-editor.jag) at org.jaggeryjs.rhino.publisher.controllers.c5.exec(/publisher/controllers/inline-editor.jag) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567) ... 37 more </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1221'>https://wso2.org/jira/browse/APPM-1221</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
