### ISSUE TITLE
[APPM-1236] Incorrect gateway endpoint creation

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#867]
<p>Bug - An erroneous gateway endpoint is created, when the context has a slash at the end.</p> <p>Steps to create:</p> <ol> <li>Navigate to App Publisher and start creating a Web app.</li> <li>Add a slash to the end of the context (e.g. /hello/)</li> <li>Submit, approve and publish the app.</li> <li>Navigate to the App Store and subscribe.</li> <li>Click on the 'Gateway Endpoint'. You will get the error as show in the attached image (Snip20160105_15.png).</li> </ol><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1236'>https://wso2.org/jira/browse/APPM-1236</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
