### ISSUE TITLE
[APPM-1238] It is possible to create web apps with banner and thumbnail fields containing files of unsupported file formats

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#868]
<p>It is possible to upload files of non image formats for banner and thumbnail fields.<br/> Web apps get created successfully without an image.<br/> Instead , an appropriate error message should be shown rather than allowing the user to save the web app.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1238'>https://wso2.org/jira/browse/APPM-1238</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
