### ISSUE TITLE
[APPM-1224] [Intermittent] Actions are not loaded after rejecting a webap

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#869]
<p><b>Steps</b></p> <p>1. Create two users with create and publisher permissions.<br/> 2. Logn with creator and create a webapp and pub to Review state.<br/> 3. Noe login with publisher and Reject the webapp.<br/> 4. Login again with the creator and check the Actions available.</p> <p><b>Issue</b> : Submit for review Action was not loaded for the webapp. Refer the attached screenshot.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1224'>https://wso2.org/jira/browse/APPM-1224</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
