### ISSUE TITLE
[APPM-1232] Reject notification not transferred properly to the creator

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#870]
<p>It was observed that intermittently the reject message is not properly sent back. A different notification is generated for the creator. Please refer the attached screenshot. Here the entered message was not sent to the creator a different message was sent.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1232'>https://wso2.org/jira/browse/APPM-1232</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
