### ISSUE TITLE
[APPM-1231] Add a max charater length for the Reason for Rejection text box

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#871]
<p>When rejecting a webapp we can generate a rejection notification, when adding text to Reason for Rejection window there is no maximum text length defined. If you add too many it will throw the following DB error in the backend but will not show any error in the UI.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> ERROR - JDBCCommentsVersionDAO Failed to add comments to the resource /_system/governance/appmgt/applicationdata/provider/creator/Super-App01/1.0/webapp. Data truncation: Data too <span class="code-object">long</span> <span class="code-keyword">for</span> column 'REG_COMMENT_TEXT' at row 1 com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too <span class="code-object">long</span> <span class="code-keyword">for</span> column 'REG_COMMENT_TEXT' at row 1 at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4224) at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4158) at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615) at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776) at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2840) at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082) at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2334) at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2262) at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2246) at org.wso2.carbon.registry.core.jdbc.dao.JDBCCommentsVersionDAO.addComment(JDBCCommentsVersionDAO.java:106) at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.addComment(EmbeddedRegistry.java:1743) at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.addComment(CacheBackedRegistry.java:369) at org.wso2.carbon.registry.core.session.UserRegistry.addCommentInternal(UserRegistry.java:1494) at org.wso2.carbon.registry.core.session.UserRegistry.access$2800(UserRegistry.java:60) at org.wso2.carbon.registry.core.session.UserRegistry$29.run(UserRegistry.java:1469) at org.wso2.carbon.registry.core.session.UserRegistry$29.run(UserRegistry.java:1466) at java.security.AccessController.doPrivileged(Native Method) at org.wso2.carbon.registry.core.session.UserRegistry.addComment(UserRegistry.java:1466) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.mozilla.javascript.gen.registry_osgi_16._c_anonymous_38(registry-osgi:363) at org.mozilla.javascript.gen.registry_osgi_16.call(registry-osgi) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.modules.c12._c_anonymous_4(/publisher/modules/comment.js:85) at org.jaggeryjs.rhino.publisher.modules.c12.call(/publisher/modules/comment.js) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.publisher.apis.v_1.c4._c_anonymous_9(/publisher/apis/v1/lifecycle_api_router.jag:214) at org.jaggeryjs.rhino.publisher.apis.v_1.c4.call(/publisher/apis/v1/lifecycle_api_router.jag) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183) at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.apis.v_1.c4._c_anonymous_1(/publisher/apis/v1/lifecycle_api_router.jag:513) at org.jaggeryjs.rhino.publisher.apis.v_1.c4.call(/publisher/apis/v1/lifecycle_api_router.jag) at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430) at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269) at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23) at org.mozilla.javascript.gen._store__server_js_5._c_anonymous_17([store]/server.js:286) at org.mozilla.javascript.gen._store__server_js_5.call([store]/server.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.publisher.apis.v_1.c4._c_script_0(/publisher/apis/v1/lifecycle_api_router.jag:24) at org.jaggeryjs.rhino.publisher.apis.v_1.c4.call(/publisher/apis/v1/lifecycle_api_router.jag) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) at org.jaggeryjs.rhino.publisher.apis.v_1.c4.call(/publisher/apis/v1/lifecycle_api_router.jag) at org.jaggeryjs.rhino.publisher.apis.v_1.c4.exec(/publisher/apis/v1/lifecycle_api_router.jag) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567) at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273) at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536) at org.jaggeryjs.jaggery.core.JaggeryServlet.doPut(JaggeryServlet.java:39) at javax.servlet.http.HttpServlet.service(HttpServlet.java:758) at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748) at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486) at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378) at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338) at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178) at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47) at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56) at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141) at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [2015-12-22 18:32:48,411] ERROR - EmbeddedRegistry Failed to add comment {<span class="code-quote">"type"</span>:<span class="code-quote">"lifecycle-change"</span>,<span class="code-quote">"order"</span>:<span class="code-quote">"16"</span>,<span class="code-quote">"comment"</span>:"lnajsdnasd repository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsrepository/deployment/server/jaggeryapps/publisher/themes/mobileapp/partials/ribbon.hbsreposito </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1231'>https://wso2.org/jira/browse/APPM-1231</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
