### ISSUE TITLE
[APPM-1230] Sample deploying option is shown to users with only publish permissions.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#872]
<p><b>Steps</b></p> <p>1. Create an user with only publisher permission and login to the store.</p> <p><b>Issue</b> : The user is shown the sample deploy option. plese refer the attached screenshot.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1230'>https://wso2.org/jira/browse/APPM-1230</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
