### ISSUE TITLE
[APPM-1229] External Stores Tab is not loaded for auto deployed samples

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#873]
<p><b>Steps</b></p> <p>1. Login to publisher and deploy the samples.<br/> 2. Now check for the External Stores tab of the published app.</p> <p><b>Issue</b> : External Stores tab is not available for sample apps.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1229'>https://wso2.org/jira/browse/APPM-1229</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
