### ISSUE TITLE
[APPM-1226] Author indicated for advertised webapps are incorrect

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#874]
<p>When a app is published to a external tenant store the App owner indicated is wrong. It shows the credentials used to publish the App. Ideally the Author should be the Original creator of the app. Reffer the attached screenshot.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1226'>https://wso2.org/jira/browse/APPM-1226</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
