### ISSUE TITLE
[APPM-1220] Can view webapp documents without login in

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#875]
<p><b>Steps</b></p> <p>1. Create a web-app with a Document.<br/> 2. Now go to store and and open the document.<br/> 3. Get the direct URL of the document. (e.g : "https://app11.wso2.com/store/extensions/assets/webapp/doc?Bla_Bla%20DOC&amp;amp;admin&amp;amp;1.0&amp;amp;Test&amp;amp;admin")<br/> 4. Logout from the store and try to access the URL.</p> <p><b>Issue</b> : The user can access the document directly.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1220'>https://wso2.org/jira/browse/APPM-1220</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
