### ISSUE TITLE
[APPM-1219] Remove unnecessary configs and API manager references from app-manager.xml

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#876]
<p>In the app-manager.xml there are lots of unnecessary configs for eg : &amp;lt;ExternalAPIStores&amp;gt; etc. </p> <p>And also there are many API Manager references as well, need to remove these from the file.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1219'>https://wso2.org/jira/browse/APPM-1219</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
