### ISSUE TITLE
[APPM-1217] webapprole_restrictions RXT is not getting deleted from the registry if the webap is edited

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#877]
<p><b>Steps</b></p> <p>1. Login to publisher and Add a webapp.<br/> 2. While adding Open Policies --&amp;gt; Global Policies and add a role to the Restrict Visibility: field. Save the created webapp.<br/> 3. Now check the registry RXTs created under. "/_system/governance/appmgt/applicationdata/provider/admin/App01/1.0"<br/> two files will be created <br/> webapprole_restrictions and webapp<br/> 4. Now go to publisher and open the webapp in edit mode.<br/> 5. Go to global policies and un-tick Restrict Visibility: and save the app.<br/> 6. Now check the above registry location.</p> <p><b>Issue</b> : The file webapprole_restrictions file is not getting deleted after editing the web app.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1217'>https://wso2.org/jira/browse/APPM-1217</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
