### ISSUE TITLE
[APPM-1213] Remove unnecessary fields of the registry RXT of an web APP

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#878]
<p>We need to remove all the unnecessary fields from the registry RXT which is created when an App is created. </p> <p>e.g : Tier Availability is not required in the registry anymore, seems its being moved to the DB.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1213'>https://wso2.org/jira/browse/APPM-1213</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
