### ISSUE TITLE
[APPM-1212] Mandatory fields are not filled in the registry resource when an App is created

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#879]
<p><b>Steps</b></p> <p>1. Login to publisher and create a web app with all mandatory information.<br/> 2. Login to management console and navigate to "/_system/governance/appmgt/applicationdata/provider/admin/App01/1.0/webapp"<br/> 3. Open the above resource.</p> <p><b>Issue</b> : Some mandatory fields are not filled when creating an API. lease refer the attached screen shot.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1212'>https://wso2.org/jira/browse/APPM-1212</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
