### ISSUE TITLE
[APPM-1207] Error 404 should be sent when invoking an Invalid URL

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#880]
<p><b>Steps</b></p> <p>1. Try to call a resource which doesn't exist.</p> <p><b>Issue</b> : Following error response is sent which is not descriptive neither correct. The correct response should be HTTP 404 Not found.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> &amp;lt;am:fault&amp;gt;&amp;lt;am:code&amp;gt;0&amp;lt;/am:code&amp;gt;&amp;lt;am:type&amp;gt;Status report&amp;lt;/am:type&amp;gt;&amp;lt;am:message&amp;gt;<span class="code-object">Runtime</span> Error&amp;lt;/am:message&amp;gt;&amp;lt;am:description&amp;gt;Error occured in the mediation of the class mediator&amp;lt;/am:description&amp;gt;&amp;lt;/am:fault&amp;gt; </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1207'>https://wso2.org/jira/browse/APPM-1207</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
