### ISSUE TITLE
[APPM-1204] Proxy port is not picked when SSO redirection URLs are generated

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#881]
<p><b>Steps</b></p> <p>1. Configure App Manager fronting LB. (LB is hosted in a remote instance)<br/> 2. Try to login to publisher.</p> <p><b>Issue</b> : SSO redirection URL is generated with default 9443 port. Please refer the following redirection header.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> Connection:keep-alive Content-Length:0 Content-Type:text/html;charset=UTF-8 Date:Mon, 21 Dec 2015 06:46:25 GMT Location:https:<span class="code-comment">//app11.wso2.com:9443/commonauth?sessionDataKey=f3491ef2-0a78-4239-92b2-abcb34d59367&amp;amp;type=samlsso </span>Server:nginx/1.7.11 </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1204'>https://wso2.org/jira/browse/APPM-1204</a></p>

**Comment by geethkokila** [comment]
Tested on IoT server 3.1.0 cluster and issue did not occur. hence  closing
