### ISSUE TITLE
[APPM-1171] [Intermittent] Duplicated entries are shown after adding a webapp

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#883]
<p>After creating a webapp duplicate entries were displayed. Please refer the attached screenshot.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1171'>https://wso2.org/jira/browse/APPM-1171</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
