### ISSUE TITLE
[APPM-1168] Cannot handle multiple tracking codes

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#884]
<p>carbon-appmn/carbon-appmgt/components/org.wso2.carbon.appmgt.impl/src/main/java/org/wso2/carbon/appmgt/impl/dao/AppMDAO.java</p> <p>In the class mentioned above has to get the version of the app. As ersion part of the app is dropped from the url in the snapshot version we have to do a database call. To do that we have to identify the correct trackingCode of the app. to do that we need a hash code. To create the hash code we need the version of the app again. To do this without making another database call in the runtime we need a way to pass the app version.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1168'>https://wso2.org/jira/browse/APPM-1168</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
