### ISSUE TITLE
[APPM-1096] When Skip Creating Proxying WebApp is enabled, Clicking on the subscribed app in My Subscriptions page redirects to Gateway URL

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#885]
<p>I have created an app with <b>Skip Creating Proxying WebApp</b> enabled.</p> <p>After subscribing to the application, in "My subscriptions" page, when trying to access an application I am redirected to <a href="http://localhost:8280/app1/1/" class="external-link" rel="nofollow">http://localhost:8280/app1/1/</a></p> <p>Following error is displayed</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-xml"> <span class="code-tag">&amp;lt;am:fault&amp;gt;</span> <span class="code-tag">&amp;lt;am:code&amp;gt;</span>0<span class="code-tag">&amp;lt;/am:code&amp;gt;</span> <span class="code-tag">&amp;lt;am:type&amp;gt;</span>Status report<span class="code-tag">&amp;lt;/am:type&amp;gt;</span> <span class="code-tag">&amp;lt;am:message&amp;gt;</span>Runtime Error<span class="code-tag">&amp;lt;/am:message&amp;gt;</span> <span class="code-tag">&amp;lt;am:description&amp;gt;</span>Error occured in the mediation of the class mediator<span class="code-tag">&amp;lt;/am:description&amp;gt;</span> <span class="code-tag">&amp;lt;/am:fault&amp;gt;</span> </pre> </div></div> <p>log:</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> INFO - LogMediator STATUS = Message dispatched to the main sequence. Invalid URL., RESOURCE = /app1/1/ INFO - LogMediator STATUS = Executing <span class="code-keyword">default</span> 'fault' sequence, ERROR_CODE = 0, ERROR_MESSAGE = Error occured in the mediation of the class mediator </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1096'>https://wso2.org/jira/browse/APPM-1096</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
