### ISSUE TITLE
[APPM-1088] Mobile Devices modal is not responsive in App Manager when loading mobile devices

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#886]
<p>Mobile Devices modal is not responsive in App Manager when loading mobile devices.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1088'>https://wso2.org/jira/browse/APPM-1088</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
