### ISSUE TITLE
[APPM-1071] Incorrect user agent version string in axis2.xml

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#887]
<p>In 1.0.0 pack, axis2.xml has following for userAgent and server,</p> <p> &amp;lt;!-- User agent and the server details to be used in the http communication --&amp;gt;<br/> &amp;lt;parameter name="userAgent" locked="true"&amp;gt;WSO2 AM 1.4.1&amp;lt;/parameter&amp;gt;<br/> &amp;lt;parameter name="server" locked="true"&amp;gt;WSO2 AM 1.4.1&amp;lt;/parameter&amp;gt;</p> <p>This should be renamed to reflect correct product name and version</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1071'>https://wso2.org/jira/browse/APPM-1071</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
