### ISSUE TITLE
[APPM-1068] AppM Publisher - Create New Web Application - Reset Button Issue

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#888]
<p>App Publisher, when entering a new app the reset button does not clear text entered on Tags &amp;amp; Restrict Visibility text boxes. <br/> Further when the data entry fields are re-entered and when trying to save it gives an error that Tags &amp;amp; Restrict Visibility text boxes are blank even these values are visible. The user has to manually remove and re-enter these fields for they system to work.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1068'>https://wso2.org/jira/browse/APPM-1068</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
