### ISSUE TITLE
[APPM-1059] Page goes to inifinite loop when accessing app

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#889]
<p>1) Access a subscribed application <br/> 2) And then access a not subscribed application using the same session.<br/> 3) Refresh the page</p> <p>The page goes into a infinite loop</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> org.wso2.carbon.appmgt.gateway.handlers.security.saml2.SAML2Authenticator} - Access failure <span class="code-keyword">for</span> WebApp: /app1, version: v1.0.0, samlssoTokenId: c3f280fc-d665-41e9-839b-e7fd7bcc097c org.wso2.carbon.appmgt.gateway.handlers.security.saml2.SAML2Authenticator} - Access failure <span class="code-keyword">for</span> WebApp: /app1, version: v1.0.0, samlssoTokenId: c3f280fc-d665-41e9-839b-e7fd7bcc097c org.wso2.carbon.appmgt.gateway.handlers.security.saml2.SAML2Authenticator} - Access failure <span class="code-keyword">for</span> WebApp: /app1, version: v1.0.0, samlssoTokenId: c3f280fc-d665-41e9-839b-e7fd7bcc097c org.wso2.carbon.appmgt.gateway.handlers.security.saml2.SAML2Authenticator} - Access failure <span class="code-keyword">for</span> WebApp: /app1, version: v1.0.0, samlssoTokenId: c3f280fc-d665-41e9-839b-e7fd7bcc097c </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1059'>https://wso2.org/jira/browse/APPM-1059</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
