### ISSUE TITLE
[APPM-1017] [Postgres] WSO2_AM_DB tables creation script error

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#890]
<p>ERROR: relation "am_api_sequence" does not exist</p> <ul> <li> <ul> <li> <ul> <li> <ul> <li> <ul> <li> <ul> <li> <ul> <li> <ul> <li> <ul> <li> <ul> <li>Error **********</li> </ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul> </li> </ul> <p>ERROR: relation "am_api_sequence" does not exist<br/> SQL state: 42P01</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1017'>https://wso2.org/jira/browse/APPM-1017</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
