### ISSUE TITLE
[APPM-301] [PostgreSQL] A Warn Shown when viewing all webApplications

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#891]
<p>After login into the publisher click on "All Web Applications" link, following Warn with a lengthy data set is shown in the back-end.</p> <p>WARN - injector Not returning actions of asset as it does not have a lifecycle.Make sure that it has a lifecycle.Artifact: {"id" : "95814230-492a-41f2-afbb-e0ed44ee97cf", "type" : "webapp", "path" : "/_system/governance/apimgt/applicationdata/provider/admin/Test/1.0/webapp", "lifecycle" : null, "lifecycleState" : null, "mediaType" : "application/vnd.wso2-webapp+xml", "attributes" : </p> {"uritemplate_httpVerb4" : "OPTIONS", "uritemplate_httpVerb5" : "null", "uritemplate_httpVerb6" : "null", "uritemplate_httpVerb7" : "null", "uritemplate_urlPattern17" : "null", "uritemplate_httpVerb0" : "GET", "uritemplate_urlPattern18" : "null", "uritemplate_httpVerb1" : "POST", "uritemplate_urlPattern19" : "null", "uritemplate_httpVerb2" : "PUT", "uritemplate_httpVerb3" : "DELETE", "uritemplate_userRoles9" : "null", "uritemplate_httpVerb8" : "null", "uritemplate_httpVerb9" : "null", "sso_idpProviderUrl" : "https://localhost:9444/samlsso/", "uritemplate_userRoles14" : "null", "uritemplate_userRoles15" : "null", "uritemplate_userRoles16" : "null", "uritemplate_userRoles17" : "null", "uritemplate_httpVerb10" : "null", "uritemplate_userRoles10" : "null", "uritemplate_userRoles11" : "null", "uritemplate_urlPattern20" : "null", "uritemplate_userRoles12" : "null", "uritemplate_userRoles13" : "null", "uritemplate_httpVerb18" : "null", "uritemplate_httpVerb17" : "null", "uritemplate_httpVerb16" : "null", "uritemplate_httpVerb15" : "null", "uritemplate_httpVerb14" : "null", "uritemplate_httpVerb13" : "null", "uritemplate_httpVerb12" : "null", "uritemplate_httpVerb11" : "null", "oauthapis_apiConsumerSecret1" : " ", "sso_ssoProvider" : "wso2is-5.0.0", "oauthapis_apiConsumerSecret2" : " ", "oauthapis_apiConsumerSecret3" : " ", "images_thumbnail" : "2e1039cc-df53-476d-a901-2f720b6ab603/2745311892_a5e022ea01_o.jpg", "uritemplate_httpVerb19" : "null", "sso_singleSignOn" : "Enabled", "oauthapis_webappConsumerSecret" : "null", "uritemplate_httpVerb20" : "null", "images_banner" : "737a6e2d-09ce-4153-8fd5-0551fae07bab/ubuntu-wallpaper-6.jpg", "uritemplate_tier0" : "Unlimited", "uritemplate_tier1" : "Unlimited", "uritemplate_tier2" : "Unlimited", "uritemplate_tier7" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier8" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier9" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier3" : "Unlimited", "uritemplate_tier4" : "Unlimited", "uritemplate_tier5" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier6" : "Gold,Silver,Bronze,Unlimited", "uritemplate_skipthrottle9" : "False,True", "uritemplate_skipthrottle8" : "False,True", "uritemplate_skipthrottle7" : "False,True", "uritemplate_skipthrottle6" : "False,True", "uritemplate_skipthrottle5" : "False,True", "uritemplate_skipthrottle4" : "False", "uritemplate_skipthrottle3" : "False", "uritemplate_skipthrottle2" : "False", "oauthapis_apiConsumerKey3" : " ", "uritemplate_userRoles5" : "null", "oauthapis_apiConsumerKey2" : " ", "uritemplate_userRoles6" : "null", "uritemplate_userRoles7" : "null", "uritemplate_userRoles8" : "null", "uritemplate_userRoles1" : " ", "uritemplate_userRoles2" : " ", "oauthapis_apiConsumerKey1" : " ", "uritemplate_userRoles3" : " ", "uritemplate_userRoles4" : " ", "uritemplate_urlPattern12" : "null", "uritemplate_skipthrottle0" : "False", "uritemplate_urlPattern11" : "null", "uritemplate_skipthrottle1" : "False", "uritemplate_urlPattern10" : "null", "uritemplate_userRoles0" : " ", "uritemplate_urlPattern16" : "null", "uritemplate_urlPattern15" : "null", "uritemplate_urlPattern14" : "null", "uritemplate_urlPattern13" : "null", "overview_tier" : "Unlimited", "overview_transports" : "http,https", "sso_saml2SsoIssuer" : " ", "uritemplate_urlPattern5" : "null", "uritemplate_urlPattern4" : "/*", "uritemplate_urlPattern3" : "/*", "uritemplate_urlPattern2" : "/*", "uritemplate_urlPattern9" : "null", "uritemplate_urlPattern8" : "null", "uritemplate_urlPattern7" : "null", "uritemplate_urlPattern6" : "null", "uritemplate_skipthrottle20" : "False,True", "overview_provider" : "admin", "uritemplate_urlPattern1" : "/*", "uritemplate_urlPattern0" : "/*", "uritemplate_skipthrottle19" : "False,True", "overview_webAppUrl" : "www.test01.com", "uritemplate_skipthrottle17" : "False,True", "uritemplate_skipthrottle18" : "False,True", "overview_logoutUrl" : " ", "uritemplate_skipthrottle11" : "False,True", "uritemplate_skipthrottle12" : "False,True", "uritemplate_skipthrottle10" : "False,True", "uritemplate_skipthrottle15" : "False,True", "uritemplate_skipthrottle16" : "False,True", "uritemplate_skipthrottle13" : "False,True", "uritemplate_skipthrottle14" : "False,True", "oauthapis_apiTokenEndpoint3" : " ", "oauthapis_apiName2" : " ", "oauthapis_apiName3" : " ", "oauthapis_apiName1" : " ", "uritemplate_tier20" : "Gold,Silver,Bronze,Unlimited", "uritemplate_entitlementPolicyPartialMappings20" : "null", "uritemplate_entitlementPolicyPartialMappings18" : "null", "uritemplate_entitlementPolicyPartialMappings17" : "null", "overview_description" : "The provider has not given a description.", "uritemplate_entitlementPolicyPartialMappings16" : "null", "uritemplate_entitlementPolicyPartialMappings15" : "null", "uritemplate_entitlementPolicyPartialMappings14" : "null", "overview_context" : "/ctx", "uritemplate_entitlementPolicyPartialMappings13" : "null", "uritemplate_entitlementPolicyPartialMappings12" : "null", "uritemplate_entitlementPolicyPartialMappings11" : "null", "oauthapis_webappConsumerKey" : "null", "uritemplate_tier17" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier16" : "Gold,Silver,Bronze,Unlimited", "oauthapis_apiTokenEndpoint1" : " ", "uritemplate_tier19" : "Gold,Silver,Bronze,Unlimited", "oauthapis_apiTokenEndpoint2" : " ", "uritemplate_entitlementPolicyPartialMappings19" : "null", "uritemplate_tier18" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier12" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier13" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier14" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier15" : "Gold,Silver,Bronze,Unlimited", "overview_trackingCode" : "AM_6560252562630922", "overview_name" : "Test", "uritemplate_tier10" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier11" : "Gold,Silver,Bronze,Unlimited", "uritemplate_userRoles18" : "null", "uritemplate_userRoles19" : "null", "uritemplate_entitlementPolicyPartialMappings10" : "null", "uritemplate_policyPartialIds" : "[]", "images_icon" : "null", "uritemplate_entitlementPolicyPartialMappings8" : "null", "uritemplate_entitlementPolicyPartialMappings9" : "null", "overview_version" : "1.0", "uritemplate_entitlementPolicyPartialMappings0" : "[]", "uritemplate_entitlementPolicyPartialMappings1" : "[]", "uritemplate_entitlementPolicyPartialMappings2" : "[]", "uritemplate_entitlementPolicyPartialMappings3" : "[]", "uritemplate_userRoles20" : "null", "uritemplate_entitlementPolicyPartialMappings4" : "[]", "uritemplate_entitlementPolicyPartialMappings5" : "null", "uritemplate_entitlementPolicyPartialMappings6" : "null", "overview_createdtime" : "00000001421054040331", "uritemplate_entitlementPolicyPartialMappings7" : "null"} <p>, "content" : {}}<br/> <span class="error">[2015-01-12 15:14:41,790]</span> WARN - injector Not returning actions of asset as it does not have a lifecycle.Make sure that it has a lifecycle.Artifact: {"id" : "95814230-492a-41f2-afbb-e0ed44ee97cf", "type" : "webapp", "path" : "/_system/governance/apimgt/applicationdata/provider/admin/Test/1.0/webapp", "lifecycle" : null, "lifecycleState" : null, "mediaType" : "application/vnd.wso2-webapp+xml", "attributes" : </p> {"uritemplate_httpVerb4" : "OPTIONS", "uritemplate_httpVerb5" : "null", "uritemplate_httpVerb6" : "null", "uritemplate_httpVerb7" : "null", "uritemplate_urlPattern17" : "null", "uritemplate_httpVerb0" : "GET", "uritemplate_urlPattern18" : "null", "uritemplate_httpVerb1" : "POST", "uritemplate_urlPattern19" : "null", "uritemplate_httpVerb2" : "PUT", "uritemplate_httpVerb3" : "DELETE", "uritemplate_userRoles9" : "null", "uritemplate_httpVerb8" : "null", "uritemplate_httpVerb9" : "null", "sso_idpProviderUrl" : "https://localhost:9444/samlsso/", "uritemplate_userRoles14" : "null", "uritemplate_userRoles15" : "null", "uritemplate_userRoles16" : "null", "uritemplate_userRoles17" : "null", "uritemplate_httpVerb10" : "null", "uritemplate_userRoles10" : "null", "uritemplate_userRoles11" : "null", "uritemplate_urlPattern20" : "null", "uritemplate_userRoles12" : "null", "uritemplate_userRoles13" : "null", "uritemplate_httpVerb18" : "null", "uritemplate_httpVerb17" : "null", "uritemplate_httpVerb16" : "null", "uritemplate_httpVerb15" : "null", "uritemplate_httpVerb14" : "null", "uritemplate_httpVerb13" : "null", "uritemplate_httpVerb12" : "null", "uritemplate_httpVerb11" : "null", "oauthapis_apiConsumerSecret1" : " ", "sso_ssoProvider" : "wso2is-5.0.0", "oauthapis_apiConsumerSecret2" : " ", "oauthapis_apiConsumerSecret3" : " ", "images_thumbnail" : "2e1039cc-df53-476d-a901-2f720b6ab603/2745311892_a5e022ea01_o.jpg", "uritemplate_httpVerb19" : "null", "sso_singleSignOn" : "Enabled", "oauthapis_webappConsumerSecret" : "null", "uritemplate_httpVerb20" : "null", "images_banner" : "737a6e2d-09ce-4153-8fd5-0551fae07bab/ubuntu-wallpaper-6.jpg", "uritemplate_tier0" : "Unlimited", "uritemplate_tier1" : "Unlimited", "uritemplate_tier2" : "Unlimited", "uritemplate_tier7" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier8" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier9" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier3" : "Unlimited", "uritemplate_tier4" : "Unlimited", "uritemplate_tier5" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier6" : "Gold,Silver,Bronze,Unlimited", "uritemplate_skipthrottle9" : "False,True", "uritemplate_skipthrottle8" : "False,True", "uritemplate_skipthrottle7" : "False,True", "uritemplate_skipthrottle6" : "False,True", "uritemplate_skipthrottle5" : "False,True", "uritemplate_skipthrottle4" : "False", "uritemplate_skipthrottle3" : "False", "uritemplate_skipthrottle2" : "False", "oauthapis_apiConsumerKey3" : " ", "uritemplate_userRoles5" : "null", "oauthapis_apiConsumerKey2" : " ", "uritemplate_userRoles6" : "null", "uritemplate_userRoles7" : "null", "uritemplate_userRoles8" : "null", "uritemplate_userRoles1" : " ", "uritemplate_userRoles2" : " ", "oauthapis_apiConsumerKey1" : " ", "uritemplate_userRoles3" : " ", "uritemplate_userRoles4" : " ", "uritemplate_urlPattern12" : "null", "uritemplate_skipthrottle0" : "False", "uritemplate_urlPattern11" : "null", "uritemplate_skipthrottle1" : "False", "uritemplate_urlPattern10" : "null", "uritemplate_userRoles0" : " ", "uritemplate_urlPattern16" : "null", "uritemplate_urlPattern15" : "null", "uritemplate_urlPattern14" : "null", "uritemplate_urlPattern13" : "null", "overview_tier" : "Unlimited", "overview_transports" : "http,https", "sso_saml2SsoIssuer" : " ", "uritemplate_urlPattern5" : "null", "uritemplate_urlPattern4" : "/*", "uritemplate_urlPattern3" : "/*", "uritemplate_urlPattern2" : "/*", "uritemplate_urlPattern9" : "null", "uritemplate_urlPattern8" : "null", "uritemplate_urlPattern7" : "null", "uritemplate_urlPattern6" : "null", "uritemplate_skipthrottle20" : "False,True", "overview_provider" : "admin", "uritemplate_urlPattern1" : "/*", "uritemplate_urlPattern0" : "/*", "uritemplate_skipthrottle19" : "False,True", "overview_webAppUrl" : "www.test01.com", "uritemplate_skipthrottle17" : "False,True", "uritemplate_skipthrottle18" : "False,True", "overview_logoutUrl" : " ", "uritemplate_skipthrottle11" : "False,True", "uritemplate_skipthrottle12" : "False,True", "uritemplate_skipthrottle10" : "False,True", "uritemplate_skipthrottle15" : "False,True", "uritemplate_skipthrottle16" : "False,True", "uritemplate_skipthrottle13" : "False,True", "uritemplate_skipthrottle14" : "False,True", "oauthapis_apiTokenEndpoint3" : " ", "oauthapis_apiName2" : " ", "oauthapis_apiName3" : " ", "oauthapis_apiName1" : " ", "uritemplate_tier20" : "Gold,Silver,Bronze,Unlimited", "uritemplate_entitlementPolicyPartialMappings20" : "null", "uritemplate_entitlementPolicyPartialMappings18" : "null", "uritemplate_entitlementPolicyPartialMappings17" : "null", "overview_description" : "The provider has not given a description.", "uritemplate_entitlementPolicyPartialMappings16" : "null", "uritemplate_entitlementPolicyPartialMappings15" : "null", "uritemplate_entitlementPolicyPartialMappings14" : "null", "overview_context" : "/ctx", "uritemplate_entitlementPolicyPartialMappings13" : "null", "uritemplate_entitlementPolicyPartialMappings12" : "null", "uritemplate_entitlementPolicyPartialMappings11" : "null", "oauthapis_webappConsumerKey" : "null", "uritemplate_tier17" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier16" : "Gold,Silver,Bronze,Unlimited", "oauthapis_apiTokenEndpoint1" : " ", "uritemplate_tier19" : "Gold,Silver,Bronze,Unlimited", "oauthapis_apiTokenEndpoint2" : " ", "uritemplate_entitlementPolicyPartialMappings19" : "null", "uritemplate_tier18" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier12" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier13" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier14" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier15" : "Gold,Silver,Bronze,Unlimited", "overview_trackingCode" : "AM_6560252562630922", "overview_name" : "Test", "uritemplate_tier10" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier11" : "Gold,Silver,Bronze,Unlimited", "uritemplate_userRoles18" : "null", "uritemplate_userRoles19" : "null", "uritemplate_entitlementPolicyPartialMappings10" : "null", "uritemplate_policyPartialIds" : "[]", "images_icon" : "null", "uritemplate_entitlementPolicyPartialMappings8" : "null", "uritemplate_entitlementPolicyPartialMappings9" : "null", "overview_version" : "1.0", "uritemplate_entitlementPolicyPartialMappings0" : "[]", "uritemplate_entitlementPolicyPartialMappings1" : "[]", "uritemplate_entitlementPolicyPartialMappings2" : "[]", "uritemplate_entitlementPolicyPartialMappings3" : "[]", "uritemplate_userRoles20" : "null", "uritemplate_entitlementPolicyPartialMappings4" : "[]", "uritemplate_entitlementPolicyPartialMappings5" : "null", "uritemplate_entitlementPolicyPartialMappings6" : "null", "overview_createdtime" : "00000001421054040331", "uritemplate_entitlementPolicyPartialMappings7" : "null"} <p>, "content" : {}}</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-301'>https://wso2.org/jira/browse/APPM-301</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
