### ISSUE TITLE
[APPM-1048] Infinite redirect looping and creates random session key

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#896]
<p>I followed these steps and found a weird outcome,</p> <p>Steps<br/> 1. Log into the store<br/> 2. Goto a web app (Gateway through Application)<br/> 3. Subscribe to it<br/> 4. click on the web app link<br/> 5. Unsubscribe the web app from the store<br/> 6. Copy the link of the web app and open it on a tab.</p> <p>This creates a random continuos session data key rather sending forbidden access error.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1048'>https://wso2.org/jira/browse/APPM-1048</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
