### ISSUE TITLE
[APPM-1032] Error message popped for 'context' field at a wrong instance

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#897]
<p><ins>Web App Creation</ins></p> <p>Steps to recreate:</p> <ol> <li>Enter values for 'Name' &amp;amp; 'Display Name' (e.g. Plan Your Trip) in the 'Create New Web Application' form.</li> <li>Navigate to another tab.</li> <li>Navigate back to the tab in which AppM Publisher is loaded. You will be displayed with the error message "Context Cannot be null" (REF: Snip20150722_23.png).</li> <li>Even after you enter a value to the 'Context' field (e.g. '/plan-your/trip') or when you reset the form the error message persists (REF: Snip20150722_25.png).</li> </ol><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1032'>https://wso2.org/jira/browse/APPM-1032</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
