### ISSUE TITLE
[APPM-764] Sorted apps list is not persisted when changing page numbers

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#898]
<p><b>Steps to reproduce</b></p> <p>1. Create multiple webapps, so that pagination takes place in publisher.<br/> 2. Now go to all webapps page, and sort the webapp list by the Name.<br/> 3. Now click on next page.</p> <p><b>Issue :</b> Sorted list is not maintained in the second page.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-764'>https://wso2.org/jira/browse/APPM-764</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
