### ISSUE TITLE
[APPM-677] Issue when sorting mobile apps after paginating

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#899]
<p><b>Steps to reproduce</b></p> <p>1. Set the pagination limit to 5 in publisher.json<br/> 2. Now login to publisher and create more than 5 mobile apps.<br/> 3. Sort the apps by created date/Name or any other option.</p> <p><b>Issue</b> : Only few apps are shown in the 1st page. 5 apps should be shown. Refer the screenshot attached. </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-677'>https://wso2.org/jira/browse/APPM-677</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
