### ISSUE TITLE
[APPM-801] Tenant users with email username can't create web apps

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#900]
<p>Enable email user name.<br/> Create a tenant and a tenant user with create and publish permission.<br/> Log in to publisher with the created user ( with email username) and try to create a webapp.<br/> -A notification is displayed stating 'Failed to add asset'<br/> -The following error is logged.<br/> (This blocked 'skip creating webapp proxying+saleforce' tenant scenario verification)</p> <p><span class="error">[2015-04-22 16:18:28,583]</span> WARN - Repository User newpub@wso2.com is not authorized to read the resource /_system/governance/appmgt/applicationdata/provider/newpub-AT-wso2.com-AT-tenant1.com/sf5/1.0.0/webapp.<br/> <span class="error">[2015-04-22 16:18:28,593]</span> ERROR - GovernanceArtifactImpl Invoking lifecycle action "Create" failed<br/> org.wso2.carbon.registry.core.secure.AuthorizationFailedException: User newpub@wso2.com is not authorized to read the resource /_system/governance/appmgt/applicationdata/provider/newpub-AT-wso2.com-AT-tenant1.com/sf5/1.0.0/webapp.<br/> at org.wso2.carbon.registry.core.jdbc.Repository.get(Repository.java:193)<br/> at org.wso2.carbon.registry.core.jdbc.handlers.filters.MediaTypeMatcher.handleGet(MediaTypeMatcher.java:130)<br/> at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.get(HandlerManager.java:2439)<br/> at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.get(HandlerLifecycleManager.java:940)<br/> at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.get(EmbeddedRegistry.java:512)<br/> at org.wso2.carbon.governance.registry.eventing.handlers.GovernanceEventingHandler.invokeAspect(GovernanceEventingHandler.java:256)<br/> at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.invokeAspect(HandlerManager.java:2792)<br/> at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.invokeAspect(HandlerLifecycleManager.java:531)<br/> at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.invokeAspect(EmbeddedRegistry.java:2550)<br/> at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.invokeAspect(CacheBackedRegistry.java:427)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.invokeAspect(UserRegistry.java:1955)<br/> at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:625)<br/> at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:605)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.mozilla.javascript.gen.artifacts_23._c_anonymous_21(artifacts:288)<br/> at org.mozilla.javascript.gen.artifacts_23.call(artifacts)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.scripts.c5._c_anonymous_2(/publisher/modules/ext/scripts/asset.lifecycle.action.save.js:76)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.scripts.c5.call(/publisher/modules/ext/scripts/asset.lifecycle.action.save.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.core.c2._c_anonymous_14(/publisher/modules/ext/core/extension.core.js:235)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.core.c2.call(/publisher/modules/ext/core/extension.core.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.core.c3._c_anonymous_10(/publisher/modules/ext/core/extension.management.js:161)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.core.c3.call(/publisher/modules/ext/core/extension.management.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.core.c3._c_anonymous_8(/publisher/modules/ext/core/extension.management.js:111)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.core.c3.call(/publisher/modules/ext/core/extension.management.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1._c_anonymous_8(/publisher/assets/default/asset.jag:368)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183)<br/> at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1._c_anonymous_1(/publisher/assets/default/asset.jag:785)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_11._c_anonymous_17(<span class="error">[store]</span>/server.js:271)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_11.call(<span class="error">[store]</span>/server.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1._c_script_0(/publisher/assets/default/asset.jag:19)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1.exec(/publisher/assets/default/asset.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:279)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:133)<br/> at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)<br/> at org.jaggeryjs.rhino.publisher.controllers.c4._c_anonymous_1(/publisher/controllers/asset_router.jag:87)<br/> at org.jaggeryjs.rhino.publisher.controllers.c4.call(/publisher/controllers/asset_router.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.jaggeryjs.rhino.publisher.controllers.c4._c_script_0(/publisher/controllers/asset_router.jag:8)<br/> at org.jaggeryjs.rhino.publisher.controllers.c4.call(/publisher/controllers/asset_router.jag)<br/> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)<br/> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)<br/> at org.jaggeryjs.rhino.publisher.controllers.c4.call(/publisher/controllers/asset_router.jag)<br/> at org.jaggeryjs.rhino.publisher.controllers.c4.exec(/publisher/controllers/asset_router.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536)<br/> at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)<br/> at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)<br/> at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378)<br/> at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)<br/> at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/> at java.lang.Thread.run(Thread.java:744)<br/> <span class="error">[2015-04-22 16:18:28,599]</span> ERROR - asset:jag org.mozilla.javascript.WrappedException: Wrapped org.wso2.carbon.governance.api.exception.GovernanceException: Invoking lifecycle action "Create" failed (artifacts#288)<br/> at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)<br/> at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.mozilla.javascript.gen.artifacts_23._c_anonymous_21(artifacts:288)<br/> at org.mozilla.javascript.gen.artifacts_23.call(artifacts)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.scripts.c5._c_anonymous_2(/publisher/modules/ext/scripts/asset.lifecycle.action.save.js:76)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.scripts.c5.call(/publisher/modules/ext/scripts/asset.lifecycle.action.save.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.core.c2._c_anonymous_14(/publisher/modules/ext/core/extension.core.js:235)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.core.c2.call(/publisher/modules/ext/core/extension.core.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.core.c3._c_anonymous_10(/publisher/modules/ext/core/extension.management.js:161)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.core.c3.call(/publisher/modules/ext/core/extension.management.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.core.c3._c_anonymous_8(/publisher/modules/ext/core/extension.management.js:111)<br/> at org.jaggeryjs.rhino.publisher.modules.ext.core.c3.call(/publisher/modules/ext/core/extension.management.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1._c_anonymous_8(/publisher/assets/default/asset.jag:368)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)<br/> at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183)<br/> at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1._c_anonymous_1(/publisher/assets/default/asset.jag:785)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_11._c_anonymous_17(<span class="error">[store]</span>/server.js:271)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_11.call(<span class="error">[store]</span>/server.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433)<br/> at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1._c_script_0(/publisher/assets/default/asset.jag:19)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1.call(/publisher/assets/default/asset.jag)<br/> at org.jaggeryjs.rhino.publisher.assets.default.c1.exec(/publisher/assets/default/asset.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:279)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:133)<br/> at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)<br/> at org.jaggeryjs.rhino.publisher.controllers.c4._c_anonymous_1(/publisher/controllers/asset_router.jag:87)<br/> at org.jaggeryjs.rhino.publisher.controllers.c4.call(/publisher/controllers/asset_router.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.jaggeryjs.rhino.publisher.controllers.c4._c_script_0(/publisher/controllers/asset_router.jag:8)<br/> at org.jaggeryjs.rhino.publisher.controllers.c4.call(/publisher/controllers/asset_router.jag)<br/> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)<br/> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)<br/> at org.jaggeryjs.rhino.publisher.controllers.c4.call(/publisher/controllers/asset_router.jag)<br/> at org.jaggeryjs.rhino.publisher.controllers.c4.exec(/publisher/controllers/asset_router.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536)<br/> at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)<br/> at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)<br/> at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378)<br/> at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)<br/> at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/> at java.lang.Thread.run(Thread.java:744)<br/> Caused by: org.wso2.carbon.governance.api.exception.GovernanceException: Invoking lifecycle action "Create" failed<br/> at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:629)<br/> at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:605)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> ... 98 more<br/> Caused by: org.wso2.carbon.registry.core.secure.AuthorizationFailedException: User newpub@wso2.com is not authorized to read the resource /_system/governance/appmgt/applicationdata/provider/newpub-AT-wso2.com-AT-tenant1.com/sf5/1.0.0/webapp.<br/> at org.wso2.carbon.registry.core.jdbc.Repository.get(Repository.java:193)<br/> at org.wso2.carbon.registry.core.jdbc.handlers.filters.MediaTypeMatcher.handleGet(MediaTypeMatcher.java:130)<br/> at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.get(HandlerManager.java:2439)<br/> at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.get(HandlerLifecycleManager.java:940)<br/> at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.get(EmbeddedRegistry.java:512)<br/> at org.wso2.carbon.governance.registry.eventing.handlers.GovernanceEventingHandler.invokeAspect(GovernanceEventingHandler.java:256)<br/> at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.invokeAspect(HandlerManager.java:2792)<br/> at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.invokeAspect(HandlerLifecycleManager.java:531)<br/> at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.invokeAspect(EmbeddedRegistry.java:2550)<br/> at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.invokeAspect(CacheBackedRegistry.java:427)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.invokeAspect(UserRegistry.java:1955)<br/> at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:625)<br/> ... 104 more</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-801'>https://wso2.org/jira/browse/APPM-801</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
