### ISSUE TITLE
[APPM-355] [Cluster] When IDP is down, the store is indicating a wrong error when trying to login

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#901]
<p><b>Steps to reproduce</b></p> <ul> <li>Cluster AM</li> <li>Shutdown the IDP node.</li> <li>Try to login to the store.</li> </ul> <p>The following error is shown in the front-end. (Refer the screen shot attached.)</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-355'>https://wso2.org/jira/browse/APPM-355</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
