### ISSUE TITLE
[APPM-843] Apps submitted after rejection are not shown in the admin-dashboard

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#903]
<p>1. create an application and submit<br/> 2. go to admin-dashboard and reject the app<br/> 3. re-submit the app for approval</p> <p>The app is not shown in the admin-dashboard although it is submitted for approval.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-843'>https://wso2.org/jira/browse/APPM-843</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
