### ISSUE TITLE
[APPM-711] Logout option is not working for "TravelBooking" web app

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#904]
<p><b>Steps to reproduce</b></p> <p>1. Deploy the samples with the "Deploy Web App Samples" option.<br/> 2. Navigate to "TravelBooking" web-app.<br/> 3. Click on logout option.</p> <p><b>Issue :</b> The logout option is not working. </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-711'>https://wso2.org/jira/browse/APPM-711</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
