### ISSUE TITLE
[APPM-477] Provide the Option to Remove Images of a Published App

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#905]
<p>When editing a published Web app the option should be provided to remove the added banner and thumbnail images if the user wants to use the default ones.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-477'>https://wso2.org/jira/browse/APPM-477</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
