### ISSUE TITLE
[APPM-367] NullPointerException thrown intermittently when trying to login to publisher.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#906]
<p>Will update the ticket with steps to reproduce, if this re-occurs with some fixed steps.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-367'>https://wso2.org/jira/browse/APPM-367</a></p>

**Comment by geethkokila** [comment]
Tested on the IoT 3.1.0 cluster, issue did not appear. hence closing
