### ISSUE TITLE
[APPM-488] When Sorting web-apps by Popularity/Created Date etc. an error indicated in the UI

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#908]
<p><b>Steps to reproduce</b></p> <p>1. Login to the publisher and create a webapp and publish it.<br/> 2. Now login to the store as the subscriber and click on any of the sorting options.</p> <p>Issue 1 : An error shown in the UI unitially. (Refer the screenshot)<br/> Issue 2 : When you click on Sort by popularity following warnings are shown.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> WARN - jag error retrieving asset from store ,information might be stale in social cache. id=webapp:c9ba02a1-13cd-46b0-82ae-5681678a8ad1 [2015-03-09 08:33:31,780] WARN - jag error retrieving asset from store ,information might be stale in social cache. id=webapp:0906b8fa-9309-4cfd-aeaa-5b7e7a4bdcc9 [2015-03-09 08:33:31,781] WARN - jag error retrieving asset from store ,information might be stale in social cache. id=webapp:4f8c3825-3afe-4881-82f9-475a2f3d595a [2015-03-09 08:33:31,786] WARN - jag error retrieving asset from store ,information might be stale in social cache. id=webapp:6ce79314-01be-4032-a8ef-aac83ceeda3e [2015-03-09 08:33:31,788] WARN - jag error retrieving asset from store ,information might be stale in social cache. id=webapp:c9ba02a1-13cd-46b0-82ae-5681678a8ad1 [2015-03-09 08:33:31,789] WARN - jag error retrieving asset from store ,information might be stale in social cache. id=webapp:0906b8fa-9309-4cfd-aeaa-5b7e7a4bdcc9 [2015-03-09 08:33:31,790] WARN - jag error retrieving asset from store ,information might be stale in social cache. id=webapp:4f8c3825-3afe-4881-82f9-475a2f3d595a [2015-03-09 08:33:31,795] WARN - jag error retrieving asset from store ,information might be stale in social cache. id=webapp:6ce79314-01be-4032-a8ef-aac83ceeda3 </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-488'>https://wso2.org/jira/browse/APPM-488</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
