### ISSUE TITLE
[APPM-447] App Store - No way to recover password !!

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#910]
<p>'Forgot password' type of option only appear in the dialog soon after Register.<br/> Even there its not functional.</p> <p>Beyond this point 'Forgot password' is not shown anywhere.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-447'>https://wso2.org/jira/browse/APPM-447</a></p>

**Comment by geethkokila** [comment]
It is available in devicemgt ui. hence closing
