### ISSUE TITLE
[APPM-836] XACML policies assigned for tenant applications are not evaluated

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#911]
<p>Although it is possible to assign xacml policies to a web application in the tenant mode, these policies are not evaluated.<br/> When a xacml policy is added by logging into admin-dashboard as the tenant admin, the policy is publishedin the super tenant's space.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-836'>https://wso2.org/jira/browse/APPM-836</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
