### ISSUE TITLE
[APPM-160] Server startup error (maybe coming from ES)

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#913]
<p>ERROR - QueryProcessor Unable to initialize MemoryMeter (jamm not specified as javaagent). This means Cassandra will be unable to measure object sizes accurately and may consequently OOM.</p> <p>Same as <a href="https://wso2.org/jira/browse/STORE-468" class="external-link" rel="nofollow">https://wso2.org/jira/browse/STORE-468</a></p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-160'>https://wso2.org/jira/browse/APPM-160</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
