### ISSUE TITLE
[APPM-884] Not all applications shown when searching from store home

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#915]
<p>1. create more than 20+ apps such as "Sample Application X" (X=1,2,3,...)<br/> 2. from store home search with "sample"</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> &amp;lt;host&amp;gt;/store/?query=sample </pre> </div></div> <p>Search result provides only 15 results with no pagination options. but when searched after going to web applications</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> &amp;lt;host&amp;gt;/store/assets/webapp/?query=sample </pre> </div></div> <p>pagination is available.</p> <p>But, when clicked on to goto the next page all applications are shown (not just applications with "Sample")</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-884'>https://wso2.org/jira/browse/APPM-884</a></p>

**Comment by harshanL** [comment]
This will be fixed when the new app manager is released.
