### ISSUE TITLE
[APPM-990] Issue with Active Directory Connection

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#916]
<p>User creation , Role creation and Application life cycle related activities are extremely slow with Active directory as the user store.</p> <p>In addition the following error is logged during app creation.</p> <p><span class="error">[2015-05-26 15:11:29,902]</span> ERROR - JDBCResourceDAO Failed to check the existence of the resource /_system/governance/appmgt/applicationdata/provider/creator1. Timeout trying to lock table "REG_RESOURCE"; SQL statement:<br/> SELECT REG_VERSION FROM REG_RESOURCE WHERE REG_PATH_ID=? AND REG_NAME IS NULL AND REG_TENANT_ID=? <span class="error">[50200-140]</span><br/> org.h2.jdbc.JdbcSQLException: Timeout trying to lock table "REG_RESOURCE"; SQL statement:<br/> SELECT REG_VERSION FROM REG_RESOURCE WHERE REG_PATH_ID=? AND REG_NAME IS NULL AND REG_TENANT_ID=? <span class="error">[50200-140]</span><br/> at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)<br/> at org.h2.message.DbException.get(DbException.java:167)<br/> at org.h2.message.DbException.get(DbException.java:144)<br/> at org.h2.table.RegularTable.doLock(RegularTable.java:466)<br/> at org.h2.table.RegularTable.lock(RegularTable.java:404)<br/> at org.h2.table.TableFilter.lock(TableFilter.java:139)<br/> at org.h2.command.dml.Select.queryWithoutCache(Select.java:554)<br/> at org.h2.command.dml.Query.query(Query.java:241)<br/> at org.h2.command.CommandContainer.query(CommandContainer.java:80)<br/> at org.h2.command.Command.executeQuery(Command.java:132)<br/> at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:96)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.getVersion(JDBCResourceDAO.java:184)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:147)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:156)<br/> at org.wso2.carbon.registry.core.jdbc.Repository.resourceExists(Repository.java:134)<br/> at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.resourceExists(EmbeddedRegistry.java:644)<br/> at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.resourceExists(CacheBackedRegistry.java:293)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.resourceExistsInternal(UserRegistry.java:777)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.access$800(UserRegistry.java:60)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:760)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:757)<br/> at java.security.AccessController.doPrivileged(Native Method)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.resourceExists(UserRegistry.java:757)<br/> at org.wso2.carbon.registry.indexing.ResourceSubmitter.submitResource(ResourceSubmitter.java:153)<br/> at org.wso2.carbon.registry.indexing.ResourceSubmitter.run(ResourceSubmitter.java:83)<br/> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/> at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)<br/> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)<br/> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)<br/> <span class="error">[2015-05-26 15:11:29,903]</span> WARN - ResourceSubmitter An error occurred while submitting the resource for indexing, path: /_system/governance/appmgt/applicationdata/provider/creator1<br/> org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to check the existence of the resource /_system/governance/appmgt/applicationdata/provider/creator1. Timeout trying to lock table "REG_RESOURCE"; SQL statement:<br/> SELECT REG_VERSION FROM REG_RESOURCE WHERE REG_PATH_ID=? AND REG_NAME IS NULL AND REG_TENANT_ID=? <span class="error">[50200-140]</span><br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.getVersion(JDBCResourceDAO.java:206)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:147)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:156)<br/> at org.wso2.carbon.registry.core.jdbc.Repository.resourceExists(Repository.java:134)<br/> at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.resourceExists(EmbeddedRegistry.java:644)<br/> at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.resourceExists(CacheBackedRegistry.java:293)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.resourceExistsInternal(UserRegistry.java:777)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.access$800(UserRegistry.java:60)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:760)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:757)<br/> at java.security.AccessController.doPrivileged(Native Method)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.resourceExists(UserRegistry.java:757)<br/> at org.wso2.carbon.registry.indexing.ResourceSubmitter.submitResource(ResourceSubmitter.java:153)<br/> at org.wso2.carbon.registry.indexing.ResourceSubmitter.run(ResourceSubmitter.java:83)<br/> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/> at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)<br/> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)<br/> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)<br/> Caused by: org.h2.jdbc.JdbcSQLException: Timeout trying to lock table "REG_RESOURCE"; SQL statement:<br/> SELECT REG_VERSION FROM REG_RESOURCE WHERE REG_PATH_ID=? AND REG_NAME IS NULL AND REG_TENANT_ID=? <span class="error">[50200-140]</span><br/> at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)<br/> at org.h2.message.DbException.get(DbException.java:167)<br/> at org.h2.message.DbException.get(DbException.java:144)<br/> at org.h2.table.RegularTable.doLock(RegularTable.java:466)<br/> at org.h2.table.RegularTable.lock(RegularTable.java:404)<br/> at org.h2.table.TableFilter.lock(TableFilter.java:139)<br/> at org.h2.command.dml.Select.queryWithoutCache(Select.java:554)<br/> at org.h2.command.dml.Query.query(Query.java:241)<br/> at org.h2.command.CommandContainer.query(CommandContainer.java:80)<br/> at org.h2.command.Command.executeQuery(Command.java:132)<br/> at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:96)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.getVersion(JDBCResourceDAO.java:184)<br/> ... 20 more<br/> <span class="error">[2015-05-26 15:11:31,906]</span> ERROR - JDBCResourceDAO Failed to check the existence of the resource /_system/governance/appmgt/applicationdata/provider/creator1/kkk. Timeout trying to lock table "REG_RESOURCE"; SQL statement:<br/> SELECT REG_VERSION FROM REG_RESOURCE WHERE REG_PATH_ID=? AND REG_NAME IS NULL AND REG_TENANT_ID=? <span class="error">[50200-140]</span><br/> org.h2.jdbc.JdbcSQLException: Timeout trying to lock table "REG_RESOURCE"; SQL statement:<br/> SELECT REG_VERSION FROM REG_RESOURCE WHERE REG_PATH_ID=? AND REG_NAME IS NULL AND REG_TENANT_ID=? <span class="error">[50200-140]</span><br/> at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)<br/> at org.h2.message.DbException.get(DbException.java:167)<br/> at org.h2.message.DbException.get(DbException.java:144)<br/> at org.h2.table.RegularTable.doLock(RegularTable.java:466)<br/> at org.h2.table.RegularTable.lock(RegularTable.java:404)<br/> at org.h2.table.TableFilter.lock(TableFilter.java:139)<br/> at org.h2.command.dml.Select.queryWithoutCache(Select.java:554)<br/> at org.h2.command.dml.Query.query(Query.java:241)<br/> at org.h2.command.CommandContainer.query(CommandContainer.java:80)<br/> at org.h2.command.Command.executeQuery(Command.java:132)<br/> at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:96)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.getVersion(JDBCResourceDAO.java:184)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:147)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:156)<br/> at org.wso2.carbon.registry.core.jdbc.Repository.resourceExists(Repository.java:134)<br/> at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.resourceExists(EmbeddedRegistry.java:644)<br/> at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.resourceExists(CacheBackedRegistry.java:293)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.resourceExistsInternal(UserRegistry.java:777)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.access$800(UserRegistry.java:60)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:760)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:757)<br/> at java.security.AccessController.doPrivileged(Native Method)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.resourceExists(UserRegistry.java:757)<br/> at org.wso2.carbon.registry.indexing.ResourceSubmitter.submitResource(ResourceSubmitter.java:153)<br/> at org.wso2.carbon.registry.indexing.ResourceSubmitter.run(ResourceSubmitter.java:83)<br/> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/> at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)<br/> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)<br/> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)<br/> <span class="error">[2015-05-26 15:11:31,907]</span> WARN - ResourceSubmitter An error occurred while submitting the resource for indexing, path: /_system/governance/appmgt/applicationdata/provider/creator1/kkk<br/> org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to check the existence of the resource /_system/governance/appmgt/applicationdata/provider/creator1/kkk. Timeout trying to lock table "REG_RESOURCE"; SQL statement:<br/> SELECT REG_VERSION FROM REG_RESOURCE WHERE REG_PATH_ID=? AND REG_NAME IS NULL AND REG_TENANT_ID=? <span class="error">[50200-140]</span><br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.getVersion(JDBCResourceDAO.java:206)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:147)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:156)<br/> at org.wso2.carbon.registry.core.jdbc.Repository.resourceExists(Repository.java:134)<br/> at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.resourceExists(EmbeddedRegistry.java:644)<br/> at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.resourceExists(CacheBackedRegistry.java:293)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.resourceExistsInternal(UserRegistry.java:777)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.access$800(UserRegistry.java:60)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:760)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:757)<br/> at java.security.AccessController.doPrivileged(Native Method)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.resourceExists(UserRegistry.java:757)<br/> at org.wso2.carbon.registry.indexing.ResourceSubmitter.submitResource(ResourceSubmitter.java:153)<br/> at org.wso2.carbon.registry.indexing.ResourceSubmitter.run(ResourceSubmitter.java:83)<br/> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/> at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)<br/> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)<br/> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)<br/> Caused by: org.h2.jdbc.JdbcSQLException: Timeout trying to lock table "REG_RESOURCE"; SQL statement:<br/> SELECT REG_VERSION FROM REG_RESOURCE WHERE REG_PATH_ID=? AND REG_NAME IS NULL AND REG_TENANT_ID=? <span class="error">[50200-140]</span><br/> at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)<br/> at org.h2.message.DbException.get(DbException.java:167)<br/> at org.h2.message.DbException.get(DbException.java:144)<br/> at org.h2.table.RegularTable.doLock(RegularTable.java:466)<br/> at org.h2.table.RegularTable.lock(RegularTable.java:404)<br/> at org.h2.table.TableFilter.lock(TableFilter.java:139)<br/> at org.h2.command.dml.Select.queryWithoutCache(Select.java:554)<br/> at org.h2.command.dml.Query.query(Query.java:241)<br/> at org.h2.command.CommandContainer.query(CommandContainer.java:80)<br/> at org.h2.command.Command.executeQuery(Command.java:132)<br/> at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:96)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.getVersion(JDBCResourceDAO.java:184)<br/> ... 20 more<br/> <span class="error">[2015-05-26 15:11:37,725]</span> INFO - EmbeddedRegistryService Configured Registry in 2ms<br/> <span class="error">[2015-05-26 15:11:39,583]</span> INFO - assets_router:jag Emitting event : login<br/> <span class="error">[2015-05-26 15:11:39,586]</span> INFO - assets_router:jag Emitting event : login<br/> <span class="error">[2015-05-26 15:11:39,915]</span> ERROR - JDBCResourceDAO Failed to check the existence of the resource /_system/governance/appmgt/applicationdata/provider/creator1/kkk/1.0.0. Timeout trying to lock table "REG_RESOURCE"; SQL statement:<br/> SELECT REG_VERSION FROM REG_RESOURCE WHERE REG_PATH_ID=? AND REG_NAME IS NULL AND REG_TENANT_ID=? <span class="error">[50200-140]</span><br/> org.h2.jdbc.JdbcSQLException: Timeout trying to lock table "REG_RESOURCE"; SQL statement:<br/> SELECT REG_VERSION FROM REG_RESOURCE WHERE REG_PATH_ID=? AND REG_NAME IS NULL AND REG_TENANT_ID=? <span class="error">[50200-140]</span><br/> at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)<br/> at org.h2.message.DbException.get(DbException.java:167)<br/> at org.h2.message.DbException.get(DbException.java:144)<br/> at org.h2.table.RegularTable.doLock(RegularTable.java:466)<br/> at org.h2.table.RegularTable.lock(RegularTable.java:404)<br/> at org.h2.table.TableFilter.lock(TableFilter.java:139)<br/> at org.h2.command.dml.Select.queryWithoutCache(Select.java:554)<br/> at org.h2.command.dml.Query.query(Query.java:241)<br/> at org.h2.command.CommandContainer.query(CommandContainer.java:80)<br/> at org.h2.command.Command.executeQuery(Command.java:132)<br/> at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:96)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.getVersion(JDBCResourceDAO.java:184)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:147)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:156)<br/> at org.wso2.carbon.registry.core.jdbc.Repository.resourceExists(Repository.java:134)<br/> at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.resourceExists(EmbeddedRegistry.java:644)<br/> at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.resourceExists(CacheBackedRegistry.java:293)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.resourceExistsInternal(UserRegistry.java:777)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.access$800(UserRegistry.java:60)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:760)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:757)<br/> at java.security.AccessController.doPrivileged(Native Method)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.resourceExists(UserRegistry.java:757)<br/> at org.wso2.carbon.registry.indexing.ResourceSubmitter.submitResource(ResourceSubmitter.java:153)<br/> at org.wso2.carbon.registry.indexing.ResourceSubmitter.run(ResourceSubmitter.java:83)<br/> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/> at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)<br/> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)<br/> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)<br/> <span class="error">[2015-05-26 15:11:39,916]</span> WARN - ResourceSubmitter An error occurred while submitting the resource for indexing, path: /_system/governance/appmgt/applicationdata/provider/creator1/kkk/1.0.0<br/> org.wso2.carbon.registry.core.exceptions.RegistryException: Failed to check the existence of the resource /_system/governance/appmgt/applicationdata/provider/creator1/kkk/1.0.0. Timeout trying to lock table "REG_RESOURCE"; SQL statement:<br/> SELECT REG_VERSION FROM REG_RESOURCE WHERE REG_PATH_ID=? AND REG_NAME IS NULL AND REG_TENANT_ID=? <span class="error">[50200-140]</span><br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.getVersion(JDBCResourceDAO.java:206)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:147)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.resourceExists(JDBCResourceDAO.java:156)<br/> at org.wso2.carbon.registry.core.jdbc.Repository.resourceExists(Repository.java:134)<br/> at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.resourceExists(EmbeddedRegistry.java:644)<br/> at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.resourceExists(CacheBackedRegistry.java:293)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.resourceExistsInternal(UserRegistry.java:777)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.access$800(UserRegistry.java:60)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:760)<br/> at org.wso2.carbon.registry.core.session.UserRegistry$9.run(UserRegistry.java:757)<br/> at java.security.AccessController.doPrivileged(Native Method)<br/> at org.wso2.carbon.registry.core.session.UserRegistry.resourceExists(UserRegistry.java:757)<br/> at org.wso2.carbon.registry.indexing.ResourceSubmitter.submitResource(ResourceSubmitter.java:153)<br/> at org.wso2.carbon.registry.indexing.ResourceSubmitter.run(ResourceSubmitter.java:83)<br/> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/> at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)<br/> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)<br/> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)<br/> Caused by: org.h2.jdbc.JdbcSQLException: Timeout trying to lock table "REG_RESOURCE"; SQL statement:<br/> SELECT REG_VERSION FROM REG_RESOURCE WHERE REG_PATH_ID=? AND REG_NAME IS NULL AND REG_TENANT_ID=? <span class="error">[50200-140]</span><br/> at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)<br/> at org.h2.message.DbException.get(DbException.java:167)<br/> at org.h2.message.DbException.get(DbException.java:144)<br/> at org.h2.table.RegularTable.doLock(RegularTable.java:466)<br/> at org.h2.table.RegularTable.lock(RegularTable.java:404)<br/> at org.h2.table.TableFilter.lock(TableFilter.java:139)<br/> at org.h2.command.dml.Select.queryWithoutCache(Select.java:554)<br/> at org.h2.command.dml.Query.query(Query.java:241)<br/> at org.h2.command.CommandContainer.query(CommandContainer.java:80)<br/> at org.h2.command.Command.executeQuery(Command.java:132)<br/> at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:96)<br/> at org.wso2.carbon.registry.core.jdbc.dao.JDBCResourceDAO.getVersion(JDBCResourceDAO.java:184)<br/> ... 20 more<br/> <span class="error">[2015-05-26 15:11:49,841]</span> INFO - CarbonAuthenticationUtil 'Administrator@carbon.super <span class="error">[-1234]</span>' logged in at <span class="error">[2015-05-26 15:11:49,841+0530]</span><br/> <span class="error">[2015-05-26 15:11:54,683]</span> INFO - CarbonAuthenticationUtil 'Administrator@carbon.super <span class="error">[-1234]</span>' logged in at <span class="error">[2015-05-26 15:11:54,683+0530]</span><br/> <span class="error">[2015-05-26 15:11:59,887]</span> INFO - CarbonAuthenticationUtil 'Administrator@carbon.super <span class="error">[-1234]</span>' logged in at <span class="error">[2015-05-26 15:11:59,887+0530]</span><br/> <span class="error">[2015-05-26 15:12:05,056]</span> INFO - CarbonAuthenticationUtil 'Administrator@carbon.super <span class="error">[-1234]</span>' logged in at <span class="error">[2015-05-26 15:12:05,056+0530]</span><br/> <span class="error">[2015-05-26 15:12:15,501]</span> INFO - SSOConfiguratorUtil SSO Provider wso2is 5.0.0 configured for kkk</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-990'>https://wso2.org/jira/browse/APPM-990</a></p>

**Comment by amalhub** [comment]
Tested the functionality in latest IoT 3.1.0 pack by connecting to an external Active Directory LDAP. Everything seems to be running smoothly without any delay and there were no exceptions thrown during app creation using a user defined in LDAP. Therefore resolving the issue.
