### ISSUE TITLE
[APPM-987] IllegalStateException when logging into webapplication after idle time

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#917]
<p>1. login to the web application<br/> 2. logout from the web application<br/> 3. keep idle for some time (approx: 20 mins)<br/> 4. try to login to the web application</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> [2015-05-26 18:01:29,457] INFO - LogoutRequestSender single logout request is sent to : https:<span class="code-comment">//localhost:9443/social/acs is returned with OK </span>[2015-05-26 18:01:29,457] INFO - LogoutRequestSender single logout request is sent to : https:<span class="code-comment">//localhost:9443/store/acs is returned with OK </span>[2015-05-26 18:34:55,088] ERROR - NativeWorkerPool Uncaught exception java.lang.IllegalStateException: The cache status is not STARTED at org.wso2.carbon.caching.impl.CacheImpl.checkStatusStarted(CacheImpl.java:287) at org.wso2.carbon.caching.impl.CacheImpl.get(CacheImpl.java:171) at org.wso2.carbon.appmgt.impl.token.DefaultClaimsRetriever.getClaims(DefaultClaimsRetriever.java:77) at org.wso2.carbon.appmgt.impl.token.JWTGenerator.populateCustomClaims(JWTGenerator.java:406) at org.wso2.carbon.appmgt.impl.token.JWTGenerator.generateToken(JWTGenerator.java:338) at org.wso2.carbon.appmgt.gateway.handlers.security.saml2.SAML2AuthenticationHandler.generateJWTAndAddToTransportHeaders(SAML2AuthenticationHandler.java:777) at org.wso2.carbon.appmgt.gateway.handlers.security.saml2.SAML2AuthenticationHandler.handleAuthorizationUsingSAMLResponse(SAML2AuthenticationHandler.java:1063) at org.wso2.carbon.appmgt.gateway.handlers.security.saml2.SAML2AuthenticationHandler.handleRequest(SAML2AuthenticationHandler.java:211) at org.apache.synapse.<span class="code-keyword">rest</span>.API.process(API.java:284) at org.apache.synapse.<span class="code-keyword">rest</span>.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:83) at org.apache.synapse.<span class="code-keyword">rest</span>.RESTRequestHandler.process(RESTRequestHandler.java:64) at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:220) at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:83) at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:344) at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:385) at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:183) at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) [2015-05-26 18:35:55,140] WARN - SourceHandler Connection time out after request is read: http-incoming-20 </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-987'>https://wso2.org/jira/browse/APPM-987</a></p>

**Comment by madhawap** [comment]
This issue is not related to IoT server, hence closed.

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
