### ISSUE TITLE
[APPM-744] [Cluster] Syncing Issue in GW Nodes on Web-app Update

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#918]
<p><b>Steps to reproduce</b></p> <p>1. Login to publisher as admin and create a webap.<br/> 2. Now publish the created webapp.<br/> 3. Go to store and subscribe to the webapp.<br/> 4. Go to publisher and open the created webapp in edit mode, navigate to Global Policies and check "Allow Anonymous Option"<br/> 5. Now invoke the app, </p> <p><b>Issue :</b> The config change is only visible in the GW management node. I had to recycle the app to make the changes synced. </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-744'>https://wso2.org/jira/browse/APPM-744</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
