### ISSUE TITLE
[APPM-937] LDAP user store roles are not listed for visibility and access restriction roles on publisher

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#920]
<p>Secondary LDAP user store roles are not listed for visibility and access restriction roles on publisher.<br/> This issue is reproduced for Primanry external read/write LDAP users stores intermittently.<br/> The user store here is a read/write LDAP.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-937'>https://wso2.org/jira/browse/APPM-937</a></p>

**Comment by harshanL** [comment]
This issue will be fixed with the latest App Manager release.
