### ISSUE TITLE
[APPM-984] Error shown while server startup when AD is configured.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#921]
<p>The following error was thrown when AD is configured.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> ERROR - AbstractUserStoreManager org.wso2.carbon.user.core.UserStoreException: Error occurred <span class="code-keyword">while</span> getting LDAP role names </pre> </div></div> <div class="code panel" style="border-width: 1px;"><div class="codeHeader panelHeader" style="border-bottom-width: 1px;"><b>AD Configuration in user-mgt.xml</b></div><div class="codeContent panelContent"> <pre class="code-java"> &amp;lt;UserStoreManager class=<span class="code-quote">"org.wso2.carbon.user.core.ldap.ActiveDirectoryUserStoreManager"</span>&amp;gt; &amp;lt;Property name=<span class="code-quote">"TenantManager"</span>&amp;gt;org.wso2.carbon.user.core.tenant.CommonHybridLDAPTenantManager&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"defaultRealmName"</span>&amp;gt;WSO2.TEST&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"Disabled"</span>&amp;gt;<span class="code-keyword">false</span>&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"kdcEnabled"</span>&amp;gt;<span class="code-keyword">false</span>&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"ConnectionURL"</span>&amp;gt;[connection URL]&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"ConnectionName"</span>&amp;gt;CN=Administrator,CN=Users,DC=WSO2,DC=TEST&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"ConnectionPassword"</span>&amp;gt;[connection password]&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"passwordHashMethod"</span>&amp;gt;PLAIN_TEXT&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"UserSearchBase"</span>&amp;gt;CN=Users,DC=WSO2,DC=TEST&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"UserEntryObjectClass"</span>&amp;gt;user&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"UserNameAttribute"</span>&amp;gt;cn&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"isADLDSRole"</span>&amp;gt;<span class="code-keyword">false</span>&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"userAccountControl"</span>&amp;gt;512&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"UserNameListFilter"</span>&amp;gt;(objectClass=user)&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"UserNameSearchFilter"</span>&amp;gt;(&amp;amp;amp;(objectClass=user)(cn=?))&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"UsernameJavaRegEx"</span>&amp;gt;[a-zA-Z0-9._-|<span class="code-comment">//]{3,30}$&amp;lt;/Property&amp;gt; </span> &amp;lt;Property name=<span class="code-quote">"UsernameJavaScriptRegEx"</span>&amp;gt;^[\S]{3,30}$&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"PasswordJavaScriptRegEx"</span>&amp;gt;^[\S]{5,30}$&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"RolenameJavaScriptRegEx"</span>&amp;gt;^[\S]{3,30}$&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"RolenameJavaRegEx"</span>&amp;gt;[a-zA-Z0-9._-|<span class="code-comment">//]{3,30}$&amp;lt;/Property&amp;gt; </span> &amp;lt;Property name=<span class="code-quote">"ReadGroups"</span>&amp;gt;<span class="code-keyword">true</span>&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"WriteGroups"</span>&amp;gt;<span class="code-keyword">true</span>&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"EmptyRolesAllowed"</span>&amp;gt;<span class="code-keyword">true</span>&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"GroupSearchBase"</span>&amp;gt;CN=Users,DC=WSO2,DC=TEST&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"GroupEntryObjectClass"</span>&amp;gt;group&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"GroupNameAttribute"</span>&amp;gt;cn&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"SharedGroupNameAttribute"</span>&amp;gt;cn&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"SharedGroupSearchBase"</span>&amp;gt;ou=SharedGroups,dc=wso2,dc=org&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"SharedGroupEntryObjectClass"</span>&amp;gt;groups&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"SharedTenantNameListFilter"</span>&amp;gt;(object=organizationalUnit)&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"SharedTenantNameAttribute"</span>&amp;gt;ou&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"SharedTenantObjectClass"</span>&amp;gt;organizationalUnit&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"MembershipAttribute"</span>&amp;gt;member&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"GroupNameListFilter"</span>&amp;gt;(objectcategory=group)&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"GroupNameSearchFilter"</span>&amp;gt;(&amp;amp;amp;(objectClass=group)(cn=?))&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"UserRolesCacheEnabled"</span>&amp;gt;<span class="code-keyword">true</span>&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"Referral"</span>&amp;gt;follow&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"BackLinksEnabled"</span>&amp;gt;<span class="code-keyword">true</span>&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"MaxRoleNameListLength"</span>&amp;gt;100&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"MaxUserNameListLength"</span>&amp;gt;100&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"SCIMEnabled"</span>&amp;gt;<span class="code-keyword">false</span>&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"ConnectionPoolingEnabled"</span>&amp;gt;<span class="code-keyword">false</span>&amp;lt;/Property&amp;gt; &amp;lt;Property name=<span class="code-quote">"UserDNPattern"</span>&amp;gt;cn={0},CN=Users,DC=WSO2,DC=TEST&amp;lt;/Property&amp;gt; &amp;lt;/UserStoreManager&amp;gt; </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-984'>https://wso2.org/jira/browse/APPM-984</a></p>

**Comment by hasuniea** [comment]
This issue doesn't exist in IoT pack
