### ISSUE TITLE
[APPM-924] Remove/rename API manager related entries from cipher-tool.properties and cipher-text.properties files

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#922]
<p>cipher-text.properties and cipher-too..properties files still contain API Manager related entries.</p> <p>eg : <br/> #APIGateway.Password=<span class="error">[admin]</span><br/> #APIUsageTracking.BAMPassword=<span class="error">[admin]</span><br/> #APIUsageTracking.JDBCPassword=<span class="error">[wso2carbon]</span><br/> #APIKeyManager.Password=<span class="error">[admin]</span></p> <p>#AuthManager.Password=api-manager.xml//APIManager/AuthManager/Password,true<br/> #APIGateway.Password=api-manager.xml//APIManager/APIGateway/Environments/Environment/Password,true<br/> #APIUsageTracking.BAMPassword=api-manager.xml//APIManager/APIUsageTracking/BAMPassword,true<br/> #APIUsageTracking.JDBCPassword=api-manager.xml//APIManager/APIUsageTracking/JDBCPassword,true<br/> #APIKeyManager.Password=api-manager.xml//APIManager/APIKeyManager/Password,true<br/> #Database.Password=api-manager.xml//APIManager/Database/Password,true</p> <p>In addition there are some entries which are not applicable.</p> <p>eg: </p> <p>#APIUsageTracking.JDBCPassword=app-manager.xml//APIManager/APIUsageTracking/JDBCPassword,true<br/> #Database.Password=app-manager.xml//APIManager/Database/Password,true</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-924'>https://wso2.org/jira/browse/APPM-924</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
