### ISSUE TITLE
[APPM-939] App Invocation failure when secondary user store user's are involved

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#923]
<p>Create, publish and subscriber to a webapp using users (with roles) from an external secondary read/write LDAP user store.</p> <p>Try to access the application via gateway URL given on the store.<br/> The following is logged.</p> <p>This is not reproduced when the same LDAP is plugged in as the primary user store.</p> <p><span class="error">[2015-05-20 11:40:27,891]</span> ERROR - AppMDAO Unable to find the WebApp: APIIdentifier</p> {providerName='SECOND1:sappmcreator@appmten1.com', apiName='sec', version='1.0.0'} <p> in the database<br/> <span class="error">[2015-05-20 11:40:27,892]</span> ERROR - APIStoreHostObject Error from Registry WebApp while getting get WebApp Information on sec<br/> org.wso2.carbon.appmgt.api.AppManagementException: Unable to find the WebApp: APIIdentifier</p> {providerName='SECOND1:sappmcreator@appmten1.com', apiName='sec', version='1.0.0'} <p> in the database<br/> at org.wso2.carbon.appmgt.impl.dao.AppMDAO.getAPIID(AppMDAO.java:4642)<br/> at org.wso2.carbon.appmgt.impl.dao.AppMDAO.getUserRating(AppMDAO.java:3314)<br/> at org.wso2.carbon.appmgt.impl.dao.AppMDAO.getUserRating(AppMDAO.java:3264)<br/> at org.wso2.carbon.appmgt.impl.APIConsumerImpl.getUserRating(APIConsumerImpl.java:807)<br/> at org.wso2.carbon.appmgt.impl.UserAwareAPIConsumer.getUserRating(UserAwareAPIConsumer.java:35)<br/> at org.wso2.carbon.appmgt.hostobjects.APIStoreHostObject.jsFunction_getAPI(APIStoreHostObject.java:1133)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.modules.webapp.c1._c_anonymous_1(/store/extensions/assets/webapp/modules/webapp/webapp.jag:9)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.modules.webapp.c1.call(/store/extensions/assets/webapp/modules/webapp/webapp.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.modules.webapp.c0._c_anonymous_1(/store/extensions/assets/webapp/modules/webapp/module.jag:5)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.modules.webapp.c0.call(/store/extensions/assets/webapp/modules/webapp/module.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.services.c3._c_anonymous_4(/store/extensions/assets/webapp/services/api-information.js:81)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.services.c3.call(/store/extensions/assets/webapp/services/api-information.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.pages.c0._c_anonymous_1(/store/extensions/assets/webapp/pages/asset.jag:275)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.pages.c0.call(/store/extensions/assets/webapp/pages/asset.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.store.modules.c1._c_anonymous_68(/store/modules/store.js:1070)<br/> at org.jaggeryjs.rhino.store.modules.c1.call(/store/modules/store.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_11._c_anonymous_17(<span class="error">[store]</span>/server.js:271)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_11.call(<span class="error">[store]</span>/server.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.store.modules.c1._c_anonymous_67(/store/modules/store.js:1065)<br/> at org.jaggeryjs.rhino.store.modules.c1.call(/store/modules/store.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.pages.c0._c_script_0(/store/extensions/assets/webapp/pages/asset.jag:31)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.pages.c0.call(/store/extensions/assets/webapp/pages/asset.jag)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.pages.c0.exec(/store/extensions/assets/webapp/pages/asset.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:279)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:133)<br/> at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)<br/> at org.jaggeryjs.rhino.store.controllers.routers.c1._c_anonymous_1(/store/controllers/routers/assets.jag:55)<br/> at org.jaggeryjs.rhino.store.controllers.routers.c1.call(/store/controllers/routers/assets.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.jaggeryjs.rhino.store.controllers.routers.c1._c_script_0(/store/controllers/routers/assets.jag:3)<br/> at org.jaggeryjs.rhino.store.controllers.routers.c1.call(/store/controllers/routers/assets.jag)<br/> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)<br/> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)<br/> at org.jaggeryjs.rhino.store.controllers.routers.c1.call(/store/controllers/routers/assets.jag)<br/> at org.jaggeryjs.rhino.store.controllers.routers.c1.exec(/store/controllers/routers/assets.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536)<br/> at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)<br/> at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)<br/> at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378)<br/> at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)<br/> at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/> at java.lang.Thread.run(Thread.java:744)<br/> <span class="error">[2015-05-20 11:40:27,896]</span> ERROR - WebAppManager org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.JavaScriptException: true (/store/extensions/assets/webapp/services/api-information.js#85) (/store/controllers/routers/assets.jag#55)<br/> org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.JavaScriptException: true (/store/extensions/assets/webapp/services/api-information.js#85) (/store/controllers/routers/assets.jag#55)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536)<br/> at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:735)<br/> at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)<br/> at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)<br/> at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:378)<br/> at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)<br/> at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21)<br/> at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)<br/> at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)<br/> at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)<br/> at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)<br/> at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)<br/> at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)<br/> at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47)<br/> at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56)<br/> at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47)<br/> at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156)<br/> at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)<br/> at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52)<br/> at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)<br/> at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)<br/> at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)<br/> at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1736)<br/> at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1695)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)<br/> at java.lang.Thread.run(Thread.java:744)<br/> Caused by: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.JavaScriptException: true (/store/extensions/assets/webapp/services/api-information.js#85) (/store/controllers/routers/assets.jag#55)<br/> at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148)<br/> at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)<br/> at org.jaggeryjs.rhino.store.controllers.routers.c1._c_anonymous_1(/store/controllers/routers/assets.jag:55)<br/> at org.jaggeryjs.rhino.store.controllers.routers.c1.call(/store/controllers/routers/assets.jag)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.jaggeryjs.rhino.store.controllers.routers.c1._c_script_0(/store/controllers/routers/assets.jag:3)<br/> at org.jaggeryjs.rhino.store.controllers.routers.c1.call(/store/controllers/routers/assets.jag)<br/> at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)<br/> at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)<br/> at org.jaggeryjs.rhino.store.controllers.routers.c1.call(/store/controllers/routers/assets.jag)<br/> at org.jaggeryjs.rhino.store.controllers.routers.c1.exec(/store/controllers/routers/assets.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> ... 37 more<br/> Caused by: org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.JavaScriptException: true (/store/extensions/assets/webapp/services/api-information.js#85)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:279)<br/> at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:133)<br/> at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source)<br/> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/> at java.lang.reflect.Method.invoke(Method.java:606)<br/> at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)<br/> ... 49 more<br/> Caused by: org.mozilla.javascript.JavaScriptException: true (/store/extensions/assets/webapp/services/api-information.js#85)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.services.c3._c_anonymous_4(/store/extensions/assets/webapp/services/api-information.js:85)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.services.c3.call(/store/extensions/assets/webapp/services/api-information.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.pages.c0._c_anonymous_1(/store/extensions/assets/webapp/pages/asset.jag:275)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.pages.c0.call(/store/extensions/assets/webapp/pages/asset.jag)<br/> at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430)<br/> at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269)<br/> at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.store.modules.c1._c_anonymous_68(/store/modules/store.js:1070)<br/> at org.jaggeryjs.rhino.store.modules.c1.call(/store/modules/store.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_11._c_anonymous_17(<span class="error">[store]</span>/server.js:271)<br/> at org.mozilla.javascript.gen.<em>store</em>_server_js_11.call(<span class="error">[store]</span>/server.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42)<br/> at org.jaggeryjs.rhino.store.modules.c1._c_anonymous_67(/store/modules/store.js:1065)<br/> at org.jaggeryjs.rhino.store.modules.c1.call(/store/modules/store.js)<br/> at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.pages.c0._c_script_0(/store/extensions/assets/webapp/pages/asset.jag:31)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.pages.c0.call(/store/extensions/assets/webapp/pages/asset.jag)<br/> at org.jaggeryjs.rhino.store.extensions.assets.webapp.pages.c0.exec(/store/extensions/assets/webapp/pages/asset.jag)<br/> at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567)<br/> ... 56 more</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-939'>https://wso2.org/jira/browse/APPM-939</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
