### ISSUE TITLE
[APPM-936] Permission assigned for secondary store users via newly defined roles are not applied

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#924]
<p>Plug in a secondary external read/write LDAP user store for a tenant.<br/> Create a new creator role.<br/> Create a new user and assign it to the role.<br/> View user roles<br/> -Role is not listed.<br/> View user's for the role.<br/> -The user is listed<br/> Unless the user has an internal role applied , log in fails<br/> -Not reproducible when the same user store is plugged in as a primary user store.</p> <p>This works when an internal role is applied instead of a new role</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-936'>https://wso2.org/jira/browse/APPM-936</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
