### ISSUE TITLE
[APPM-658] Errors thrown while garcefull server restart

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#925]
<p>The following errors are thrown while on server restart (Grace full restart through admin console)</p> <p><span class="error">[2015-03-26 15:06:54,695]</span> ERROR - WebappClassLoader The web application <span class="error">[/shindig]</span> appears to have started a thread named <span class="error">[com.google.inject.internal.util.$Finalizer]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:54,759]</span> ERROR - WebappClassLoader The web application <span class="error">[/shindig]</span> created a ThreadLocal with key of type <span class="error">[com.google.inject.internal.InjectorImpl$1]</span> (value <span class="error">[com.google.inject.internal.InjectorImpl$1@7b9abef3]</span>) and a value of type [java.lang.Object[]] (value [<span class="error">[Ljava.lang.Object;@6c6e82ea]</span>) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.<br/> <span class="error">[2015-03-26 15:06:54,806]</span> INFO - WebApplication Unloaded webapp: StandardEngine<span class="error">[Catalina]</span>.StandardHost<span class="error">[localhost]</span>.StandardContext<span class="error">[/shindig]</span><br/> <span class="error">[2015-03-26 15:06:54,951]</span> INFO - WebApplication Unloaded webapp: StandardEngine<span class="error">[Catalina]</span>.StandardHost<span class="error">[localhost]</span>.StandardContext<span class="error">[/appmoauth2]</span><br/> <span class="error">[2015-03-26 15:06:55,020]</span> INFO - WebApplication Unloaded webapp: StandardEngine<span class="error">[Catalina]</span>.StandardHost<span class="error">[localhost]</span>.StandardContext<span class="error">[/authenticationendpoint]</span><br/> <span class="error">[2015-03-26 15:06:55,032]</span> INFO - WebApplication Unloaded webapp: StandardEngine<span class="error">[Catalina]</span>.StandardHost<span class="error">[localhost]</span>.StandardContext<span class="error">[/store]</span><br/> <span class="error">[2015-03-26 15:06:55,043]</span> INFO - WebApplication Unloaded webapp: StandardEngine<span class="error">[Catalina]</span>.StandardHost<span class="error">[localhost]</span>.StandardContext<span class="error">[/social]</span><br/> <span class="error">[2015-03-26 15:06:55,063]</span> INFO - WebApplication Unloaded webapp: StandardEngine<span class="error">[Catalina]</span>.StandardHost<span class="error">[localhost]</span>.StandardContext<span class="error">[/portal]</span><br/> <span class="error">[2015-03-26 15:06:55,101]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[MultiThreadedHttpConnectionManager cleanup]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,102]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-61-thread-1]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,102]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-1]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,102]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-2]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,103]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-34-thread-1]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,104]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-34-thread-2]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,104]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-3]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,105]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-34-thread-3]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,105]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-34-thread-4]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,106]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-4]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,106]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-5]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,107]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-34-thread-5]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,107]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-6]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,108]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-7]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,108]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-8]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,109]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-9]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,109]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-10]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,110]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-11]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,110]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-12]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,111]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-13]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,111]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-17]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,112]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-18]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,112]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-19]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,113]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-20]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,113]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-21]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,114]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-22]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,114]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-23]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,115]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-24]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,115]</span> ERROR - WebappClassLoader The web application <span class="error">[/publisher]</span> appears to have started a thread named <span class="error">[pool-60-thread-25]</span> but has failed to stop it. This is very likely to create a memory leak.<br/> <span class="error">[2015-03-26 15:06:55,124]</span> INFO - WebApplication Unloaded webapp: StandardEngine<span class="error">[Catalina]</span>.StandardHost<span class="error">[localhost]</span>.StandardContext<span class="error">[/publisher]</span><br/> <span class="error">[2015-03-26 15:06:55,134]</span> INFO - WebApplication Unloaded webapp: StandardEngine<span class="error">[Catalina]</span>.StandardHost<span class="error">[localhost]</span>.StandardContext<span class="error">[/admin-dashboard]</span><br/> <span class="error">[2015-03-26 15:06:55,149]</span> INFO - WebApplication Unloaded webapp: StandardEngine<span class="error">[Catalina]</span>.StandardHost<span class="error">[localhost]</span>.StandardContext<span class="error">[/dashboard]</span><br/> <span class="error">[2015-03-26 15:06:55,149]</span> INFO - ServerManagement All deployment tasks have been completed.<br/> <span class="error">[2015-03-26 15:06:55,202]</span> INFO - ServerManagement Waiting for server task completion...<br/> <span class="error">[2015-03-26 15:06:55,208]</span> INFO - RegistryCoreServiceComponent Writing logs </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-658'>https://wso2.org/jira/browse/APPM-658</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
