### ISSUE TITLE
[APPM-908] Publisher permissions are not applied unless the user has the internal/publisher role assinged

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#928]
<p>Create a publisher role with publisher specific permission<br/> Assign it to a user.<br/> Log in from a creator , create and app and submit it for review.<br/> Log in from the above created publisher and load the apps.<br/> -The created app is not listed.<br/> But if you assign the internal/publisher role, the apps are listed</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-908'>https://wso2.org/jira/browse/APPM-908</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
