### ISSUE TITLE
[APPM-933] Error on server start up during table creation when configured with mysql

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#929]
<p>The following error is logged during server start up with -Dsetup option for the first time , when App Manager is configured with mysql. The server contains a port offset of 5 and a change default admin role and user.</p> <p><span class="error">[2015-05-19 17:33:19,385]</span> ERROR - ThriftAuthenticationServiceComponent Unable to start thrift Authenticator Service</p> <p>__________________</p> <p><span class="error">[2015-05-19 17:32:57,136]</span> INFO - AppManagerMobileComponent WSO2EMM MDM is bound to App Manager<br/> <span class="error">[2015-05-19 17:32:57,137]</span> INFO - AppManagerMobileComponent App Manger Mobile Component activated<br/> <span class="error">[2015-05-19 17:32:57,213]</span> INFO - CarbonCoreActivator Starting WSO2 Carbon...<br/> <span class="error">[2015-05-19 17:32:57,213]</span> INFO - CarbonCoreActivator Operating System : Linux 3.8.0-33-generic, amd64<br/> <span class="error">[2015-05-19 17:32:57,213]</span> INFO - CarbonCoreActivator Java Home : /home/kaushie/jdk1.7.0_45/jre<br/> <span class="error">[2015-05-19 17:32:57,213]</span> INFO - CarbonCoreActivator Java Version : 1.7.0_45<br/> <span class="error">[2015-05-19 17:32:57,214]</span> INFO - CarbonCoreActivator Java VM : Java HotSpot(TM) 64-Bit Server VM 24.45-b08,Oracle Corporation<br/> <span class="error">[2015-05-19 17:32:57,214]</span> INFO - CarbonCoreActivator Carbon Home : /home/kaushie/release/appm1.0/usersotres/mysqlnewadminoffset<br/> <span class="error">[2015-05-19 17:32:57,214]</span> INFO - CarbonCoreActivator Java Temp Dir : /home/kaushie/release/appm1.0/usersotres/mysqlnewadminoffset/tmp<br/> <span class="error">[2015-05-19 17:32:57,214]</span> INFO - CarbonCoreActivator User : kaushie, en-US, Asia/Colombo<br/> <span class="error">[2015-05-19 17:32:57,283]</span> WARN - ValidationResultPrinter The default keystore (wso2carbon.jks) is currently being used. To maximize security when deploying to a production environment, configure a new keystore with a unique password in the production server profile.<br/> <span class="error">[2015-05-19 17:32:57,290]</span> INFO - AgentHolder Agent created !<br/> <span class="error">[2015-05-19 17:32:57,312]</span> INFO - AgentDS Successfully deployed Agent Client<br/> <span class="error">[2015-05-19 17:32:57,601]</span> INFO - Activator Integrated Windows Authenticator enabled in the system<br/> <span class="error">[2015-05-19 17:32:57,741]</span> INFO - DirectoryActivator Embedded LDAP is disabled.<br/> <span class="error">[2015-05-19 17:33:06,181]</span> INFO - TaglibUriRule TLD skipped. URI: <a href="http://tiles.apache.org/tags-tiles" class="external-link" rel="nofollow">http://tiles.apache.org/tags-tiles</a> is already defined<br/> <span class="error">[2015-05-19 17:33:08,508]</span> INFO - CarbonRemoteUserStoreDSComponent Carbon Remote User Store activated successfully.<br/> <span class="error">[2015-05-19 17:33:19,377]</span> INFO - EmbeddedRegistryService Configured Registry in 10748ms<br/> <span class="error">[2015-05-19 17:33:19,385]</span> ERROR - ThriftAuthenticationServiceComponent Unable to start thrift Authenticator Service<br/> <span class="error">[2015-05-19 17:33:29,480]</span> INFO - EmbeddedRegistryService Connected to mount at govregistry in 9978ms<br/> <span class="error">[2015-05-19 17:33:29,481]</span> INFO - EmbeddedRegistryService Connected to mount at configregistry in 9979ms<br/> <span class="error">[2015-05-19 17:33:29,968]</span> INFO - EmbeddedRegistryService Connected to mount at govregistry in 0ms<br/> <span class="error">[2015-05-19 17:33:29,968]</span> INFO - EmbeddedRegistryService Connected to mount at configregistry in 0ms<br/> <span class="error">[2015-05-19 17:33:31,518]</span> INFO - RegistryCoreServiceComponent Registry Mode : READ-WRITE<br/> <span class="error">[2015-05-19 17:33:32,062]</span> INFO - EntitlementServiceComponent Started thrift entitlement service at port:10505</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-933'>https://wso2.org/jira/browse/APPM-933</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
