### ISSUE TITLE
[APPM-934] Error when adding a secondary user store for a tenant for the first time

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#930]
<p>The following is logged when a secondary user store is added to a tenant for the first time.</p> <p><span class="error">[2015-05-19 17:48:47,378]</span> INFO - ReadWriteLDAPUserStoreManager LDAP connection created successfully in read-write mode<br/> <span class="error">[2015-05-19 17:48:47,495]</span> INFO - ReadWriteLDAPUserStoreManager LDAP connection created successfully in read-write mode<br/> <span class="error">[2015-05-19 17:48:47,497]</span> INFO - DeploymentEngine org.apache.axis2.deployment.DeploymentException: The deployment of second1.xml is not valid.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-934'>https://wso2.org/jira/browse/APPM-934</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
