### ISSUE TITLE
[APPM-922] Management console UI issue on on IE

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#931]
<p>Please note the tab selection menu on the left hand corner of the management console , attached. <br/> Tab labels are horizontally aligned.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-922'>https://wso2.org/jira/browse/APPM-922</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
