### ISSUE TITLE
[APPM-917] Error when executing oracle stat analyzer script for BAM

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#933]
<p>The following error is logged when the oracle stat analyzer script is being executed on BAM 2.5.0</p> <p><span class="error">[2015-05-14 15:28:00,003]</span> INFO </p> {org.wso2.carbon.analytics.hive.task.HiveScriptExecutorTask} - Running script executor task for script am_stats_analyzer. <span class="error">[Thu May 14 15:28:00 IST 2015]</span><br/> Hive history file=/home/kaushie/release/appm1.0/bam/wso2bam-2.5.0/tmp/hive/root-querylogs/hive_job_log_kaushie_201505141528_292156655.txt<br/> FAILED: Error in metadata: MetaException(message:Error while creating the keyspace - EVENT_KS in cassandranull)<br/> <span class="error">[2015-05-14 15:28:02,435]</span> ERROR {org.apache.hadoop.hive.ql.exec.Task} - FAILED: Error in metadata: MetaException(message:Error while creating the keyspace - EVENT_KS in cassandranull)<br/> org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Error while creating the keyspace - EVENT_KS in cassandranull)<br/> at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:546)<br/> at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:3479)<br/> at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:225)<br/> at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:129)<br/> at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:62)<br/> at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1351)<br/> at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1126)<br/> at org.apache.hadoop.hive.ql.Driver.run(Driver.java:934)<br/> at org.apache.hadoop.hive.service.HiveServer$HiveServerHandler.execute(HiveServer.java:201)<br/> at org.apache.hadoop.hive.jdbc.HiveStatement.executeQuery(HiveStatement.java:187)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.executeHiveQuery(HiveExecutorServiceImpl.java:578)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.call(HiveExecutorServiceImpl.java:286)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.call(HiveExecutorServiceImpl.java:189)<br/> at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)<br/> Caused by: MetaException(message:Error while creating the keyspace - EVENT_KS in cassandranull)<br/> at org.apache.hadoop.hive.cassandra.CassandraManager.checkAndCreateEventKeyspace(CassandraManager.java:290)<br/> at org.apache.hadoop.hive.cassandra.CassandraManager.createKeyspaceIfNotExisting(CassandraManager.java:260)<br/> at org.apache.hadoop.hive.cassandra.CassandraStorageHandler.preCreateTable(CassandraStorageHandler.java:293)<br/> at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:396)<br/> at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:540)<br/> ... 16 more<br/> <br/> FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask<br/> <span class="error">[2015-05-14 15:28:02,436]</span> ERROR {org.apache.hadoop.hive.ql.Driver} - FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask<br/> <span class="error">[2015-05-14 15:28:02,439]</span> ERROR {org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl} - Error while executing Hive script.<br/> Query returned non-zero code: 9, cause: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask<br/> java.sql.SQLException: Query returned non-zero code: 9, cause: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask<br/> at org.apache.hadoop.hive.jdbc.HiveStatement.executeQuery(HiveStatement.java:189)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.executeHiveQuery(HiveExecutorServiceImpl.java:578)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.call(HiveExecutorServiceImpl.java:286)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.call(HiveExecutorServiceImpl.java:189)<br/> at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)<br/> <span class="error">[2015-05-14 15:28:02,440]</span> ERROR {org.wso2.carbon.analytics.hive.task.HiveScriptExecutorTask} <p> - Error while executing script : am_stats_analyzer<br/> org.wso2.carbon.analytics.hive.exception.HiveExecutionException: Error while executing Hive script.Query returned non-zero code: 9, cause: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl.execute(HiveExecutorServiceImpl.java:115)<br/> at org.wso2.carbon.analytics.hive.task.HiveScriptExecutorTask.execute(HiveScriptExecutorTask.java:70)<br/> at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)<br/> at org.quartz.core.JobRunShell.run(JobRunShell.java:213)<br/> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/> at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)</p> <p><span class="error">[2015-05-14 15:30:00,001]</span> INFO </p> {org.wso2.carbon.analytics.hive.task.HiveScriptExecutorTask} - Running script executor task for script am_stats_analyzer. <span class="error">[Thu May 14 15:30:00 IST 2015]</span><br/> Hive history file=/home/kaushie/release/appm1.0/bam/wso2bam-2.5.0/tmp/hive/root-querylogs/hive_job_log_kaushie_201505141528_1065416025.txt<br/> FAILED: Error in metadata: MetaException(message:Error while creating the keyspace - EVENT_KS in cassandranull)<br/> <span class="error">[2015-05-14 15:30:00,051]</span> ERROR {org.apache.hadoop.hive.ql.exec.Task} - FAILED: Error in metadata: MetaException(message:Error while creating the keyspace - EVENT_KS in cassandranull)<br/> org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Error while creating the keyspace - EVENT_KS in cassandranull)<br/> at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:546)<br/> at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:3479)<br/> at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:225)<br/> at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:129)<br/> at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:62)<br/> at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1351)<br/> at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1126)<br/> at org.apache.hadoop.hive.ql.Driver.run(Driver.java:934)<br/> at org.apache.hadoop.hive.service.HiveServer$HiveServerHandler.execute(HiveServer.java:201)<br/> at org.apache.hadoop.hive.jdbc.HiveStatement.executeQuery(HiveStatement.java:187)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.executeHiveQuery(HiveExecutorServiceImpl.java:578)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.call(HiveExecutorServiceImpl.java:286)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.call(HiveExecutorServiceImpl.java:189)<br/> at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)<br/> Caused by: MetaException(message:Error while creating the keyspace - EVENT_KS in cassandranull)<br/> at org.apache.hadoop.hive.cassandra.CassandraManager.checkAndCreateEventKeyspace(CassandraManager.java:290)<br/> at org.apache.hadoop.hive.cassandra.CassandraManager.createKeyspaceIfNotExisting(CassandraManager.java:260)<br/> at org.apache.hadoop.hive.cassandra.CassandraStorageHandler.preCreateTable(CassandraStorageHandler.java:293)<br/> at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:396)<br/> at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:540)<br/> ... 16 more<br/> <br/> FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask<br/> <span class="error">[2015-05-14 15:30:00,051]</span> ERROR {org.apache.hadoop.hive.ql.Driver} - FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask<br/> <span class="error">[2015-05-14 15:30:00,052]</span> ERROR {org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl} - Error while executing Hive script.<br/> Query returned non-zero code: 9, cause: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask<br/> java.sql.SQLException: Query returned non-zero code: 9, cause: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask<br/> at org.apache.hadoop.hive.jdbc.HiveStatement.executeQuery(HiveStatement.java:189)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.executeHiveQuery(HiveExecutorServiceImpl.java:578)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.call(HiveExecutorServiceImpl.java:286)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.call(HiveExecutorServiceImpl.java:189)<br/> at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)<br/> <span class="error">[2015-05-14 15:30:00,052]</span> ERROR {org.wso2.carbon.analytics.hive.task.HiveScriptExecutorTask} <p> - Error while executing script : am_stats_analyzer<br/> org.wso2.carbon.analytics.hive.exception.HiveExecutionException: Error while executing Hive script.Query returned non-zero code: 9, cause: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl.execute(HiveExecutorServiceImpl.java:115)<br/> at org.wso2.carbon.analytics.hive.task.HiveScriptExecutorTask.execute(HiveScriptExecutorTask.java:70)<br/> at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67)<br/> at org.quartz.core.JobRunShell.run(JobRunShell.java:213)<br/> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<br/> at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)<br/> <span class="error">[2015-05-14 15:32:00,002]</span> INFO </p> {org.wso2.carbon.analytics.hive.task.HiveScriptExecutorTask} <p> - Running script executor task for script am_stats_analyzer. <span class="error">[Thu May 14 15:32:00 IST 2015]</span><br/> Hive history file=/home/kaushie/release/appm1.0/bam/wso2bam-2.5.0/tmp/hive/root-querylogs/hive_job_log_kaushie_201505141528_733828515.txt<br/> FAILED: Error in metadata: MetaException(message:Error while creating the keyspace - EVENT_KS in cassandranull)<br/> <span class="error">[2015-05-14 15:32:00,064]</span> ERROR </p> {org.apache.hadoop.hive.ql.exec.Task} <p> - FAILED: Error in metadata: MetaException(message:Error while creating the keyspace - EVENT_KS in cassandranull)<br/> org.apache.hadoop.hive.ql.metadata.HiveException: MetaException(message:Error while creating the keyspace - EVENT_KS in cassandranull)<br/> at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:546)<br/> at org.apache.hadoop.hive.ql.exec.DDLTask.createTable(DDLTask.java:3479)<br/> at org.apache.hadoop.hive.ql.exec.DDLTask.execute(DDLTask.java:225)<br/> at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:129)<br/> at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:62)<br/> at org.apache.hadoop.hive.ql.Driver.launchTask(Driver.java:1351)<br/> at org.apache.hadoop.hive.ql.Driver.execute(Driver.java:1126)<br/> at org.apache.hadoop.hive.ql.Driver.run(Driver.java:934)<br/> at org.apache.hadoop.hive.service.HiveServer$HiveServerHandler.execute(HiveServer.java:201)<br/> at org.apache.hadoop.hive.jdbc.HiveStatement.executeQuery(HiveStatement.java:187)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.executeHiveQuery(HiveExecutorServiceImpl.java:578)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.call(HiveExecutorServiceImpl.java:286)<br/> at org.wso2.carbon.analytics.hive.impl.HiveExecutorServiceImpl$ScriptCallable.call(HiveExecutorServiceImpl.java:189)<br/> at java.util.concurrent.FutureTask.run(FutureTask.java:262)<br/> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)<br/> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<br/> at java.lang.Thread.run(Thread.java:744)<br/> Caused by: MetaException(message:Error while creating the keyspace - EVENT_KS in cassandranull)<br/> at org.apache.hadoop.hive.cassandra.CassandraManager.checkAndCreateEventKeyspace(CassandraManager.java:290)<br/> at org.apache.hadoop.hive.cassandra.CassandraManager.createKeyspaceIfNotExisting(CassandraManager.java:260)<br/> at org.apache.hadoop.hive.cassandra.CassandraStorageHandler.preCreateTable(CassandraStorageHandler.java:293)<br/> at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:396)<br/> at org.apache.hadoop.hive.ql.metadata.Hive.createTable(Hive.java:540)<br/> ... 16 more</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-917'>https://wso2.org/jira/browse/APPM-917</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server 3.1.0, hence closing
