### ISSUE TITLE
[APPM-855] Unable to Register a new SAML SSO Service Provider

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#934]
<p>Register New Service Provider (SAML SAML 2.0 based Single Sign-On) UI cannot be view. Instead of the "Register New Provider" form, an empty UI is shown.</p> <p>Steps to reproduce:<br/> 1. Start the AppM server and login to carbon console using admin/admin credentials.<br/> 2. Go to <em>Main</em> &amp;gt; <em>Manage</em> &amp;gt; <em>SAML SSO</em>.<br/> 3. Click on <em>Register New Service Provider</em> link.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-855'>https://wso2.org/jira/browse/APPM-855</a></p>

**Comment by geethkokila** [comment]
Tested on IoT server 3.1.0 cluster, issue did not appear, hence closing the issue
