### ISSUE TITLE
[APPM-572] Exception thrown when adding a duplicate Mobile App with same Title and Version

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#935]
<p><b>Steps to Reproduce</b></p> <p>1. Login to publisher and create a public mobile app with title "App01" and version "1.0"<br/> 2. Now try to create another mobile app with the same information, title "App01" and version "1.0".</p> <p><b>Issue</b> : Following stack-trace is logged in the logs.</p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> ERROR - GovernanceArtifactManager Failed to add artifact: artifact id: 33b672f3-5d65-4678-b1d1-c7fc5680d974. Governance artifact Title already exists at /mobileapps/creator2/android/Title/1.0 org.wso2.carbon.governance.api.exception.GovernanceException: Governance artifact Title already exists at /mobileapps/creator2/android/Title/1.0 at org.wso2.carbon.governance.api.common.GovernanceArtifactManager.addGovernanceArtifact(GovernanceArtifactManager.java:189) at org.wso2.carbon.governance.api.<span class="code-keyword">generic</span>.GenericArtifactManager.addGenericArtifact(GenericArtifactManager.java:170) at sun.reflect.GeneratedMethodAccessor345.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.mozilla.javascript.gen.artifacts_17._c_anonymous_16(artifacts:235) at org.mozilla.javascript.gen.artifacts_17.call(artifacts) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.publisher.modules.ext.scripts.c2._c_anonymous_4(/publisher/modules/ext/scripts/mobile.action.save.js:89) at org.jaggeryjs.rhino.publisher.modules.ext.scripts.c2.call(/publisher/modules/ext/scripts/mobile.action.save.js) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.publisher.modules.ext.core.c2._c_anonymous_14(/publisher/modules/ext/core/extension.core.js:235) at org.jaggeryjs.rhino.publisher.modules.ext.core.c2.call(/publisher/modules/ext/core/extension.core.js) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.publisher.modules.ext.core.c3._c_anonymous_10(/publisher/modules/ext/core/extension.management.js:145) at org.jaggeryjs.rhino.publisher.modules.ext.core.c3.call(/publisher/modules/ext/core/extension.management.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.modules.ext.core.c3._c_anonymous_8(/publisher/modules/ext/core/extension.management.js:111) at org.jaggeryjs.rhino.publisher.modules.ext.core.c3.call(/publisher/modules/ext/core/extension.management.js) at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85) at org.jaggeryjs.rhino.publisher.apis.v_1.c7._c_addNewMobileApp_24(/publisher/apis/v1/asset_api_router.jag:886) at org.jaggeryjs.rhino.publisher.apis.v_1.c7.call(/publisher/apis/v1/asset_api_router.jag) at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63) at org.jaggeryjs.rhino.publisher.apis.v_1.c7._c_anonymous_16(/publisher/apis/v1/asset_api_router.jag:309) at org.jaggeryjs.rhino.publisher.apis.v_1.c7.call(/publisher/apis/v1/asset_api_router.jag) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183) at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.apis.v_1.c7._c_anonymous_1(/publisher/apis/v1/asset_api_router.jag:1081) at org.jaggeryjs.rhino.publisher.apis.v_1.c7.call(/publisher/apis/v1/asset_api_router.jag) at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430) at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269) at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23) at org.mozilla.javascript.gen._store__server_js_5._c_anonymous_17([store]/server.js:271) at org.mozilla.javascript.gen._store__server_js_5.call([store]/server.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.publisher.apis.v_1.c7._c_script_0(/publisher/apis/v1/asset_api_router.jag:17) at org.jaggeryjs.rhino.publisher.apis.v_1.c7.call(/publisher/apis/v1/asset_api_router.jag) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) at org.jaggeryjs.rhino.publisher.apis.v_1.c7.call(/publisher/apis/v1/asset_api_router.jag) at org.jaggeryjs.rhino.publisher.apis.v_1.c7.exec(/publisher/apis/v1/asset_api_router.jag) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567) at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273) at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536) at org.jaggeryjs.jaggery.core.JaggeryServlet.doPost(JaggeryServlet.java:29) at javax.servlet.http.HttpServlet.service(HttpServlet.java:755) at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749) at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487) at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:379) at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339) at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178) at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47) at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56) at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141) at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936) at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1653) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-572'>https://wso2.org/jira/browse/APPM-572</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
