### ISSUE TITLE
[APPM-811] Warning on 'Unable to find the throttle policy for role' when logging in via an IDP (Enterprise subscription)

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#936]
<p>Configure enterprise subscription.<br/> Enter the webapplication gateway URL on the browser.<br/> -Select the required IDP<br/> Specify login details.<br/> -The user is logged in but the following warning is given.</p> <p>Warning on 'Unable to find the throttle policy for role' when logging in using an IDP (Enterprise subscription)</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-811'>https://wso2.org/jira/browse/APPM-811</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, Hence closing
