### ISSUE TITLE
[APPM-809] All IDP's assigned to the Service provider are listed regardless of the IDP's selected in the enterprise subscription list on store

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#937]
<p>Please refer to screenshot1.png and screenshot2.png attached</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-809'>https://wso2.org/jira/browse/APPM-809</a></p>

**Comment by geethkokila** [comment]
Not related IoT server, hence closing
