### ISSUE TITLE
[APPM-798] Single log out does not work for skip creating proxying webapp+salesforce

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#938]
<p>Configure and publish a web app with the option 'skip creating proxying webapp' with salesforce as the endpoint. (<a href="http://sandapa.blogspot.com/2014/03/how-to-configure-saml-sso-for.html" class="external-link" rel="nofollow">http://sandapa.blogspot.com/2014/03/how-to-configure-saml-sso-for.html</a>)<br/> Login to sales force using the URL provided on the store (Actual backend URL given when creating the webapp)<br/> Log out.<br/> -Log out is unsuccessful.</p> <p>HTTP/?.? 302 Found<br/> Location: <a href="https://10.100.5.40:9446/authenticationendpoint/samlsso_notification.do?status=Not" class="external-link" rel="nofollow">https://10.100.5.40:9446/authenticationendpoint/samlsso_notification.do?status=Not</a> a valid SAML 2.0 Request Message!&amp;amp;statusMsg=The message was not recognized by the SAML 2.0 SSO Provider. Please check the logs for more details<br/> Content-Type: text/html;charset=UTF-8<br/> Content-Length: 0<br/> Date: Wed, 22 Apr 2015 10:11:21 GMT<br/> Server: WSO2 Carbon Server</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-798'>https://wso2.org/jira/browse/APPM-798</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing
