### ISSUE TITLE
[APPM-747] The throttleout message doesn't honour the Content-Type

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#939]
<p>Following are the throttle out messages sent</p> <p><b>POST Request</b></p> <p><b>Request</b></p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> POST http:<span class="code-comment">//gw.am.wso2.com:8285/restapi01/1.0/<span class="code-keyword">rest</span>/user/add </span> POST data: {<span class="code-quote">"employeeId"</span>:3,<span class="code-quote">"firstName"</span>:<span class="code-quote">"Andy1"</span>,<span class="code-quote">"lastName"</span>:<span class="code-quote">"Perera"</span>,<span class="code-quote">"salary"</span>:133000.0,<span class="code-quote">"status"</span>:<span class="code-quote">"NOTSUSPENDED"</span>} Request Headers: Connection: keep-alive Content-Type: application/json Accept: application/json Content-Length: 98 Host: gw.am.wso2.com:8285 </pre> </div></div> <p><b>Response</b></p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> {<span class="code-quote">"fault"</span>:{<span class="code-quote">"code"</span>:<span class="code-quote">"900800"</span>,<span class="code-quote">"message"</span>:<span class="code-quote">"Message Throttled Out"</span>,<span class="code-quote">"description"</span>:<span class="code-quote">"You have exceeded your quota"</span>},<span class="code-quote">"firstName"</span>:<span class="code-quote">"Andy1"</span>,<span class="code-quote">"lastName"</span>:<span class="code-quote">"Perera"</span>,<span class="code-quote">"salary"</span>:<span class="code-quote">"133000.0"</span>,<span class="code-quote">"status"</span>:<span class="code-quote">"NOTSUSPENDED"</span>} </pre> </div></div> <p><b>DELETE request</b></p> <p><b>Request</b></p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> DELETE http:<span class="code-comment">//gw.am.wso2.com:8285/restapi01/1.0/<span class="code-keyword">rest</span>/user/delete/3 </span> DELETE data: Request Headers: Connection: keep-alive Content-Type: application/json Accept: application/json Content-Length: 0 Host: gw.am.wso2.com:8285 User-Agent: Apache-HttpClient/4.2.6 (java 1.5) </pre> </div></div> <p><b>Response</b></p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> &amp;lt;amt:fault xmlns:amt=<span class="code-quote">"http:<span class="code-comment">//wso2.org/apimanager/throttling"</span>&amp;gt;&amp;lt;amt:code&amp;gt;900800&amp;lt;/amt:code&amp;gt;&amp;lt;amt:message&amp;gt;Message Throttled Out&amp;lt;/amt:message&amp;gt;&amp;lt;amt:description&amp;gt;You have exceeded your quota&amp;lt;/amt:description&amp;gt;&amp;lt;/amt:fault&amp;gt;</span> </pre> </div></div> <p><b>Issue :</b> As visible above two different responses are sent to the front end, which will be difficult to handle from the front-end. </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-747'>https://wso2.org/jira/browse/APPM-747</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue
