### ISSUE TITLE
[APPM-745] POST data is resent with the throttleout message

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#940]
<p><b>Request</b></p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> POST http:<span class="code-comment">//gw.am.wso2.com:8285/restapi01/1.0/<span class="code-keyword">rest</span>/user/add </span> POST data: {<span class="code-quote">"employeeId"</span>:3,<span class="code-quote">"firstName"</span>:<span class="code-quote">"Andy1"</span>,<span class="code-quote">"lastName"</span>:<span class="code-quote">"Perera"</span>,<span class="code-quote">"salary"</span>:133000.0,<span class="code-quote">"status"</span>:<span class="code-quote">"NOTSUSPENDED"</span>} </pre> </div></div> <p><b>Response</b></p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> {<span class="code-quote">"fault"</span>:{<span class="code-quote">"code"</span>:<span class="code-quote">"900800"</span>,<span class="code-quote">"message"</span>:<span class="code-quote">"Message Throttled Out"</span>,<span class="code-quote">"description"</span>:<span class="code-quote">"You have exceeded your quota"</span>},<span class="code-quote">"firstName"</span>:<span class="code-quote">"Andy1"</span>,<span class="code-quote">"lastName"</span>:<span class="code-quote">"Perera"</span>,<span class="code-quote">"salary"</span>:<span class="code-quote">"133000.0"</span>,<span class="code-quote">"status"</span>:<span class="code-quote">"NOTSUSPENDED"</span>} </pre> </div></div> <p><b>Issue :</b> The POST data is sent back with the request. </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-745'>https://wso2.org/jira/browse/APPM-745</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing
