### ISSUE TITLE
[APPM-741] Wrong task description for application subscription workflow

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#941]
<p>Application subscription workflow task description is stated as an API subscriptino to the 'Default Application' in the admin dashboard and on BPS</p> <p>Approve API [ yahoo - 1.0.0 ] subscription creation request from subscriber - testuser4 for the application - DefaultApplication</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-741'>https://wso2.org/jira/browse/APPM-741</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing
