### ISSUE TITLE
[APPM-617] Web page continuously redirect when refreshing a web app after unsubscribe

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#943]
<p>When refreshing a logged web app after unsubscribing from it, the web page keep redirecting endlessly. Webpage shows the following message.<br/> "You are now redirected back to <a href="http://10.100.7.45:8280/plan-your-trip/1.0.0/" class="external-link" rel="nofollow">http://10.100.7.45:8280/plan-your-trip/1.0.0/</a> If the redirection fails, please click the post button."</p> <p>Steps to reproduce<br/> 1. Login to the App Store.<br/> 2. Subscribe to a web app form App Store.<br/> 3. Go to the web app using the 'Gateway Endpoint' URL.<br/> 4. Go to the App Store tab &amp;amp; unsubscribe from that app.<br/> 5. Now go to the web app tab &amp;amp; refresh the web page.</p> <p>Executed web app: Plan Your Trip (plan-your-trip.war) from web app sample "Demonstrating JSON Web Token (JWT) Usage - Plan Your Trip App"</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-617'>https://wso2.org/jira/browse/APPM-617</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing.
