### ISSUE TITLE
[APPM-554] [Intermittent] Error when publishing a webapp - {java.lang.ArrayIndexOutOfBoundsException: 3 (/publisher/controllers/assets_router.jag#101)}

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#944]
<p>Following exception was observed when publishing a webapp. This was observed intermittently. Couldn't reproduce continuously. </p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-java"> ERROR - WebAppManager org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: java.lang.ArrayIndexOutOfBoundsException: 3 (/publisher/controllers/assets_router.jag#101) org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: java.lang.ArrayIndexOutOfBoundsException: 3 (/publisher/controllers/assets_router.jag#101) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571) at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273) at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536) at org.jaggeryjs.jaggery.core.JaggeryServlet.doGet(JaggeryServlet.java:24) at javax.servlet.http.HttpServlet.service(HttpServlet.java:735) at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749) at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487) at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:379) at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339) at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178) at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47) at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56) at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141) at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936) at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1653) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.<span class="code-object">Thread</span>.run(<span class="code-object">Thread</span>.java:745) Caused by: org.mozilla.javascript.WrappedException: Wrapped org.jaggeryjs.scriptengine.exceptions.ScriptException: java.lang.ArrayIndexOutOfBoundsException: 3 (/publisher/controllers/assets_router.jag#101) at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1754) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:148) at org.mozilla.javascript.FunctionObject.call(FunctionObject.java:386) at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63) at org.jaggeryjs.rhino.publisher.controllers.c2._c_anonymous_1(/publisher/controllers/assets_router.jag:101) at org.jaggeryjs.rhino.publisher.controllers.c2.call(/publisher/controllers/assets_router.jag) at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23) at org.jaggeryjs.rhino.publisher.controllers.c2._c_script_0(/publisher/controllers/assets_router.jag:8) at org.jaggeryjs.rhino.publisher.controllers.c2.call(/publisher/controllers/assets_router.jag) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) at org.jaggeryjs.rhino.publisher.controllers.c2.call(/publisher/controllers/assets_router.jag) at org.jaggeryjs.rhino.publisher.controllers.c2.exec(/publisher/controllers/assets_router.jag) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567) ... 35 more Caused by: org.jaggeryjs.scriptengine.exceptions.ScriptException: java.lang.ArrayIndexOutOfBoundsException: 3 at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571) at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273) at org.jaggeryjs.jaggery.core.manager.WebAppManager.executeScript(WebAppManager.java:279) at org.jaggeryjs.jaggery.core.manager.WebAppManager.include(WebAppManager.java:133) at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) ... 47 more Caused by: java.lang.ArrayIndexOutOfBoundsException: 3 at org.mozilla.javascript.NativeArray.indexOfHelper(NativeArray.java:1524) at org.mozilla.javascript.NativeArray.execIdCall(NativeArray.java:308) at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.publisher.modules.filters.c0._c_addAdminRole_7(/publisher/modules/filters/permission.asset.filter.js:133) at org.jaggeryjs.rhino.publisher.modules.filters.c0.call(/publisher/modules/filters/permission.asset.filter.js) at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63) at org.jaggeryjs.rhino.publisher.modules.filters.c0._c_obtainPermissibleRoles_6(/publisher/modules/filters/permission.asset.filter.js:119) at org.jaggeryjs.rhino.publisher.modules.filters.c0.call(/publisher/modules/filters/permission.asset.filter.js) at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63) at org.jaggeryjs.rhino.publisher.modules.filters.c0._c_execute_3(/publisher/modules/filters/permission.asset.filter.js:56) at org.jaggeryjs.rhino.publisher.modules.filters.c0.call(/publisher/modules/filters/permission.asset.filter.js) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.publisher.modules.c10._c_anonymous_7(/publisher/modules/filter.manager.js:125) at org.jaggeryjs.rhino.publisher.modules.c10.call(/publisher/modules/filter.manager.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.assets.<span class="code-keyword">default</span>.c0._c_anonymous_5(/publisher/assets/<span class="code-keyword">default</span>/assets.jag:155) at org.jaggeryjs.rhino.publisher.assets.<span class="code-keyword">default</span>.c0.call(/publisher/assets/<span class="code-keyword">default</span>/assets.jag) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183) at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.assets.<span class="code-keyword">default</span>.c0._c_anonymous_1(/publisher/assets/<span class="code-keyword">default</span>/assets.jag:272) at org.jaggeryjs.rhino.publisher.assets.<span class="code-keyword">default</span>.c0.call(/publisher/assets/<span class="code-keyword">default</span>/assets.jag) at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430) at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269) at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23) at org.mozilla.javascript.gen._store__server_js_5._c_anonymous_17([store]/server.js:271) at org.mozilla.javascript.gen._store__server_js_5.call([store]/server.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.publisher.assets.<span class="code-keyword">default</span>.c0._c_script_0(/publisher/assets/<span class="code-keyword">default</span>/assets.jag:13) at org.jaggeryjs.rhino.publisher.assets.<span class="code-keyword">default</span>.c0.call(/publisher/assets/<span class="code-keyword">default</span>/assets.jag) at org.jaggeryjs.rhino.publisher.assets.<span class="code-keyword">default</span>.c0.exec(/publisher/assets/<span class="code-keyword">default</span>/assets.jag) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567) ... 54 more </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-554'>https://wso2.org/jira/browse/APPM-554</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing.
