### ISSUE TITLE
[APPM-583] Mobile app creation form gets reseted if a faulty .apk is added

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#945]
<p><b>Steps to reproduce</b></p> <p>1. Login to publisher and click on Add New Mobile Applications<br/> 2. Select "Store Type:" as "Enterprise" and click on next without uploading a .apk.<br/> 3. Now fill all the mandatory fields and click on submit, you will be directed to the Initial page.<br/> 4. Now add a faulty apk (Upload a .jpg or something) now click on next.</p> <p><b>Issue</b> : All the mandatory fields get reset. </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-583'>https://wso2.org/jira/browse/APPM-583</a></p>

**Comment by geethkokila** [comment]
App manager component for IoT server is bieng rewritten. hence closing this issue.
