### ISSUE TITLE
[APPM-497] Bullets in documentation are not reflected on the final documentation page

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#946]
<p><b>Steps to reproduce</b></p> <p>1. Login to publisher and create a webapp.<br/> 2. Add an Inline document.<br/> 3. Add content to the created document with bullet points.<br/> 4. Save the Document and publish the app.<br/> 5. Login to the store and view the published document.</p> <p>Issue : Added bullet points are not reflected in the final page. (Refer the screenshot) </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-497'>https://wso2.org/jira/browse/APPM-497</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
