### ISSUE TITLE
[APPM-438] example code references Boeing

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#947]
<p>NPE demonstrates package names have not changed from com.boeing</p> <p> Exception report</p> <p>java.lang.NullPointerException<br/> com.boeing.example.app.ProcessJWT.process(ProcessJWT.java:61)</p> <p>org.apache.jsp.index_jsp._jspService(index_jsp.java:111)</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-438'>https://wso2.org/jira/browse/APPM-438</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing
