### ISSUE TITLE
[APPM-437] attempting to access CorpTravelApp throws NPE

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#948]
<p>Subscribe myself to CorpTravelApp by alex-AT-wso2.com<br/> Goto mysubscription page<br/> When click on the App, receive a NPE and server exception:</p> <p>Type Exception report</p> <p>message java.lang.NullPointerException</p> <p>description The server encountered an internal error that prevented it from fulfilling this request.</p> <p>exception</p> <p>org.apache.jasper.JasperException: java.lang.NullPointerException<br/> org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:549)<br/> org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:470)<br/> org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)<br/> org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)<br/> javax.servlet.http.HttpServlet.service(HttpServlet.java:728)<br/> org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)<br/> root cause</p> <p>java.lang.NullPointerException<br/> com.boeing.example.app.ProcessJWT.process(ProcessJWT.java:61)<br/> org.apache.jsp.index_jsp._jspService(index_jsp.java:111)<br/> org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)<br/> javax.servlet.http.HttpServlet.service(HttpServlet.java:728)<br/> org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)<br/> org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)<br/> org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)<br/> javax.servlet.http.HttpServlet.service(HttpServlet.java:728)<br/> org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)<br/> note The full stack trace of the root cause is available in the Apache Tomcat/7.0.50 logs.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-437'>https://wso2.org/jira/browse/APPM-437</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing
