### ISSUE TITLE
[APPM-435] User Review section of store not recognizing login

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#949]
<p>a) login in to store<br/> b) choose app<br/> c) click on 'user review' tab<br/> BUG: the application asks you for your login credentials!</p> <p>why doesn't the user review section recognize that the user is currently signed into the store? </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-435'>https://wso2.org/jira/browse/APPM-435</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
