### ISSUE TITLE
[APPM-420] [Cluster][Intermittent] An Exception thrown when submitting a webapp

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#950]
<p>The following exception was observed intermittently while submitting a newly created webapp. </p> <div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent"> <pre class="code-xml"> ERROR {org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl} - Invoking lifecycle action <span class="code-quote">"Submit"</span> failed {org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl} org.wso2.carbon.registry.core.exceptions.RegistryException: An exception occurred while executing handler chain. null at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.invokeAspect(HandlerManager.java:2814) at org.wso2.carbon.registry.core.jdbc.handlers.HandlerLifecycleManager.invokeAspect(HandlerLifecycleManager.java:531) at org.wso2.carbon.registry.core.jdbc.EmbeddedRegistry.invokeAspect(EmbeddedRegistry.java:2550) at org.wso2.carbon.registry.core.caching.CacheBackedRegistry.invokeAspect(CacheBackedRegistry.java:427) at org.wso2.carbon.registry.core.session.UserRegistry.invokeAspect(UserRegistry.java:1955) at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:625) at org.wso2.carbon.governance.api.common.dataobjects.GovernanceArtifactImpl.invokeAction(GovernanceArtifactImpl.java:605) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126) at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.mozilla.javascript.gen.artifacts_19._c_anonymous_21(artifacts:283) at org.mozilla.javascript.gen.artifacts_19.call(artifacts) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.apis.v_1.c5._c_anonymous_9(/publisher/apis/v1/lifecycle_api_router.jag:180) at org.jaggeryjs.rhino.publisher.apis.v_1.c5.call(/publisher/apis/v1/lifecycle_api_router.jag) at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32) at org.jaggeryjs.rhino.publisher.modules.c4._c_anonymous_12(/publisher/modules/router-g.js:183) at org.jaggeryjs.rhino.publisher.modules.c4.call(/publisher/modules/router-g.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.apis.v_1.c5._c_anonymous_1(/publisher/apis/v1/lifecycle_api_router.jag:453) at org.jaggeryjs.rhino.publisher.apis.v_1.c5.call(/publisher/apis/v1/lifecycle_api_router.jag) at org.mozilla.javascript.ScriptRuntime.applyOrCall(ScriptRuntime.java:2430) at org.mozilla.javascript.BaseFunction.execIdCall(BaseFunction.java:269) at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_17(/publisher/modules/publisher.js:438) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23) at org.mozilla.javascript.gen._store__server_js_25._c_anonymous_17([store]/server.js:271) at org.mozilla.javascript.gen._store__server_js_25.call([store]/server.js) at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:42) at org.jaggeryjs.rhino.publisher.modules.c6._c_anonymous_16(/publisher/modules/publisher.js:433) at org.jaggeryjs.rhino.publisher.modules.c6.call(/publisher/modules/publisher.js) at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:52) at org.jaggeryjs.rhino.publisher.apis.v_1.c5._c_script_0(/publisher/apis/v1/lifecycle_api_router.jag:24) at org.jaggeryjs.rhino.publisher.apis.v_1.c5.call(/publisher/apis/v1/lifecycle_api_router.jag) at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) at org.jaggeryjs.rhino.publisher.apis.v_1.c5.call(/publisher/apis/v1/lifecycle_api_router.jag) at org.jaggeryjs.rhino.publisher.apis.v_1.c5.exec(/publisher/apis/v1/lifecycle_api_router.jag) at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:567) at org.jaggeryjs.scriptengine.engine.RhinoEngine.exec(RhinoEngine.java:273) at org.jaggeryjs.jaggery.core.manager.WebAppManager.execute(WebAppManager.java:536) at org.jaggeryjs.jaggery.core.JaggeryServlet.doPut(JaggeryServlet.java:39) at javax.servlet.http.HttpServlet.service(HttpServlet.java:758) at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749) at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:487) at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:379) at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:339) at org.jaggeryjs.jaggery.core.JaggeryFilter.doFilter(JaggeryFilter.java:21) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.continueInvocation(CompositeValve.java:178) at org.wso2.carbon.tomcat.ext.valves.CarbonTomcatValve$1.invoke(CarbonTomcatValve.java:47) at org.wso2.carbon.webapp.mgt.TenantLazyLoaderValve.invoke(TenantLazyLoaderValve.java:56) at org.wso2.carbon.tomcat.ext.valves.TomcatValveContainer.invokeValves(TomcatValveContainer.java:47) at org.wso2.carbon.tomcat.ext.valves.CompositeValve.invoke(CompositeValve.java:141) at org.wso2.carbon.tomcat.ext.valves.CarbonStuckThreadDetectionValve.invoke(CarbonStuckThreadDetectionValve.java:156) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936) at org.wso2.carbon.tomcat.ext.valves.CarbonContextCreatorValve.invoke(CarbonContextCreatorValve.java:52) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1653) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at java.lang.Thread.run(Thread.java:745) Caused by: java.lang.NullPointerException at org.wso2.carbon.appmgt.impl.APIProviderImpl.changeAPIStatus(APIProviderImpl.java:771) at org.wso2.carbon.appmgt.impl.UserAwareAPIProvider.changeAPIStatus(UserAwareAPIProvider.java:72) at org.wso2.carbon.appmgt.impl.workflow.PublishAPPSimpleWorkflowExecutor.execute(PublishAPPSimpleWorkflowExecutor.java:60) at org.wso2.carbon.appmgt.impl.extensions.custom.PublishActionEventExecutor.execute(PublishActionEventExecutor.java:145) at org.wso2.jaggery.scxml.aspects.JaggeryTravellingPermissionLifeCycle.runCustomExecutorsCode(JaggeryTravellingPermissionLifeCycle.java:702) at org.wso2.jaggery.scxml.aspects.JaggeryTravellingPermissionLifeCycle.invoke(JaggeryTravellingPermissionLifeCycle.java:439) at org.wso2.carbon.governance.registry.eventing.handlers.GovernanceEventingHandler.invokeAspect(GovernanceEventingHandler.java:243) at org.wso2.carbon.registry.core.jdbc.handlers.HandlerManager.invokeAspect(HandlerManager.java:2792) ... 79 more </pre> </div></div><p>Reference: <a href='https://wso2.org/jira/browse/APPM-420'>https://wso2.org/jira/browse/APPM-420</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing.
