### ISSUE TITLE
[APPM-414] [Cluster][Intermittent] Wrong state shown in the UI for published web apps.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#951]
<p>As shown in Screen shot (attached), wrong states were shown in the UI for published webapps. </p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-414'>https://wso2.org/jira/browse/APPM-414</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing
