### ISSUE TITLE
[APPM-344] [MySQL] WARN When login into the publisher

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#952]
<ul> <li>Steps to Reproduce *</li> </ul> <ul> <li>Configure AM with MYSQL (All H2 DBs pointed to MySQL)</li> <li>Now try to login to the publisher</li> </ul> <p>Note : This is also reported here <a href="https://wso2.org/jira/browse/APPM-301" title="[PostgreSQL] A Warn Shown when viewing all webApplications" class="issue-link" data-issue-key="APPM-301">APPM-301</a> specific to PostgreSQL</p> <p>Following WARN is thrown in the backend.</p> <p>======= Error ===============</p> <p>WARN - injector Not returning actions of asset as it does not have a lifecycle.Make sure that it has a lifecycle.Artifact: {"id" : "84f1fe39-bd29-4f54-a640-3f2c0ee880f7", "type" : "webapp", "path" : "/_system/governance/apimgt/applicationdata/provider/admin/Google/1.0/webapp", "lifecycle" : null, "lifecycleState" : null, "mediaType" : "application/vnd.wso2-webapp+xml", "attributes" : </p> {"uritemplate_httpVerb4" : "OPTIONS", "uritemplate_httpVerb5" : "null", "uritemplate_httpVerb6" : "null", "uritemplate_httpVerb7" : "null", "uritemplate_urlPattern17" : "null", "uritemplate_httpVerb0" : "GET", "uritemplate_urlPattern18" : "null", "uritemplate_httpVerb1" : "POST", "uritemplate_urlPattern19" : "null", "uritemplate_httpVerb2" : "PUT", "uritemplate_httpVerb3" : "DELETE", "uritemplate_userRoles9" : "null", "uritemplate_httpVerb8" : "null", "uritemplate_httpVerb9" : "null", "sso_idpProviderUrl" : "https://localhost:9444/samlsso/", "uritemplate_userRoles14" : "null", "uritemplate_userRoles15" : "null", "uritemplate_userRoles16" : "null", "uritemplate_userRoles17" : "null", "uritemplate_httpVerb10" : "null", "uritemplate_userRoles10" : "null", "uritemplate_userRoles11" : "null", "uritemplate_urlPattern20" : "null", "uritemplate_userRoles12" : "null", "uritemplate_userRoles13" : "null", "uritemplate_httpVerb18" : "null", "uritemplate_httpVerb17" : "null", "uritemplate_httpVerb16" : "null", "uritemplate_httpVerb15" : "null", "uritemplate_httpVerb14" : "null", "uritemplate_httpVerb13" : "null", "uritemplate_httpVerb12" : "null", "uritemplate_httpVerb11" : "null", "oauthapis_apiConsumerSecret1" : " ", "sso_ssoProvider" : "wso2is-5.0.0", "oauthapis_apiConsumerSecret2" : " ", "oauthapis_apiConsumerSecret3" : " ", "images_thumbnail" : "0ec979ed-0c89-493f-b1c8-63b475cbf509/linux-asus-hd-kb-762563.jpg", "uritemplate_httpVerb19" : "null", "sso_singleSignOn" : "Enabled", "oauthapis_webappConsumerSecret" : "null", "uritemplate_httpVerb20" : "null", "images_banner" : "4794ff2f-e5b5-420b-9311-16d8337549f1/full-hd-wallpaper-animals-95.jpg", "uritemplate_tier0" : "Unlimited", "uritemplate_tier1" : "Unlimited", "uritemplate_tier2" : "Unlimited", "uritemplate_tier7" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier8" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier9" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier3" : "Unlimited", "uritemplate_tier4" : "Unlimited", "uritemplate_tier5" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier6" : "Gold,Silver,Bronze,Unlimited", "uritemplate_skipthrottle9" : "False,True", "uritemplate_skipthrottle8" : "False,True", "uritemplate_skipthrottle7" : "False,True", "uritemplate_skipthrottle6" : "False,True", "uritemplate_skipthrottle5" : "False,True", "uritemplate_skipthrottle4" : "False", "uritemplate_skipthrottle3" : "False", "uritemplate_skipthrottle2" : "False", "oauthapis_apiConsumerKey3" : " ", "uritemplate_userRoles5" : "null", "oauthapis_apiConsumerKey2" : " ", "uritemplate_userRoles6" : "null", "uritemplate_userRoles7" : "null", "uritemplate_userRoles8" : "null", "uritemplate_userRoles1" : " ", "uritemplate_userRoles2" : " ", "oauthapis_apiConsumerKey1" : " ", "uritemplate_userRoles3" : " ", "uritemplate_userRoles4" : " ", "uritemplate_urlPattern12" : "null", "uritemplate_skipthrottle0" : "False", "uritemplate_urlPattern11" : "null", "uritemplate_skipthrottle1" : "False", "uritemplate_urlPattern10" : "null", "uritemplate_userRoles0" : " ", "uritemplate_urlPattern16" : "null", "uritemplate_urlPattern15" : "null", "uritemplate_urlPattern14" : "null", "uritemplate_urlPattern13" : "null", "overview_tier" : "Unlimited", "overview_transports" : "http", "sso_saml2SsoIssuer" : " ", "uritemplate_urlPattern5" : "null", "uritemplate_urlPattern4" : "/*", "uritemplate_urlPattern3" : "/*", "uritemplate_urlPattern2" : "/*", "uritemplate_urlPattern9" : "null", "uritemplate_urlPattern8" : "null", "uritemplate_urlPattern7" : "null", "uritemplate_urlPattern6" : "null", "uritemplate_skipthrottle20" : "False,True", "overview_provider" : "admin", "uritemplate_urlPattern1" : "/*", "uritemplate_urlPattern0" : "/*", "uritemplate_skipthrottle19" : "False,True", "overview_webAppUrl" : "http://www.google.com", "uritemplate_skipthrottle17" : "False,True", "uritemplate_skipthrottle18" : "False,True", "overview_logoutUrl" : " ", "uritemplate_skipthrottle11" : "False,True", "uritemplate_skipthrottle12" : "False,True", "uritemplate_skipthrottle10" : "False,True", "uritemplate_skipthrottle15" : "False,True", "uritemplate_skipthrottle16" : "False,True", "uritemplate_skipthrottle13" : "False,True", "uritemplate_skipthrottle14" : "False,True", "oauthapis_apiTokenEndpoint3" : " ", "oauthapis_apiName2" : " ", "oauthapis_apiName3" : " ", "oauthapis_apiName1" : " ", "uritemplate_tier20" : "Gold,Silver,Bronze,Unlimited", "uritemplate_entitlementPolicyPartialMappings20" : "null", "uritemplate_entitlementPolicyPartialMappings18" : "null", "uritemplate_entitlementPolicyPartialMappings17" : "null", "overview_description" : "Description", "uritemplate_entitlementPolicyPartialMappings16" : "null", "uritemplate_entitlementPolicyPartialMappings15" : "null", "uritemplate_entitlementPolicyPartialMappings14" : "null", "overview_context" : "/google", "uritemplate_entitlementPolicyPartialMappings13" : "null", "uritemplate_entitlementPolicyPartialMappings12" : "null", "uritemplate_entitlementPolicyPartialMappings11" : "null", "oauthapis_webappConsumerKey" : "null", "uritemplate_tier17" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier16" : "Gold,Silver,Bronze,Unlimited", "oauthapis_apiTokenEndpoint1" : " ", "uritemplate_tier19" : "Gold,Silver,Bronze,Unlimited", "oauthapis_apiTokenEndpoint2" : " ", "uritemplate_entitlementPolicyPartialMappings19" : "null", "uritemplate_tier18" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier12" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier13" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier14" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier15" : "Gold,Silver,Bronze,Unlimited", "overview_trackingCode" : "AM_7061913623474538", "overview_name" : "Google", "uritemplate_tier10" : "Gold,Silver,Bronze,Unlimited", "uritemplate_tier11" : "Gold,Silver,Bronze,Unlimited", "uritemplate_userRoles18" : "null", "uritemplate_userRoles19" : "null", "uritemplate_entitlementPolicyPartialMappings10" : "null", "uritemplate_policyPartialIds" : "[]", "images_icon" : "null", "uritemplate_entitlementPolicyPartialMappings8" : "null", "uritemplate_entitlementPolicyPartialMappings9" : "null", "overview_version" : "1.0", "uritemplate_entitlementPolicyPartialMappings0" : "[]", "uritemplate_entitlementPolicyPartialMappings1" : "[]", "uritemplate_entitlementPolicyPartialMappings2" : "[]", "uritemplate_entitlementPolicyPartialMappings3" : "[]", "uritemplate_userRoles20" : "null", "uritemplate_entitlementPolicyPartialMappings4" : "[]", "uritemplate_entitlementPolicyPartialMappings5" : "null", "uritemplate_entitlementPolicyPartialMappings6" : "null", "overview_createdtime" : "00000001421819714943", "uritemplate_entitlementPolicyPartialMappings7" : "null"} <p>, "content" : {}}</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-344'>https://wso2.org/jira/browse/APPM-344</a></p>

**Comment by geethkokila** [comment]
Tested on Mysql cluster, not seen the issue, hence closing.
