### ISSUE TITLE
[APPM-321] WARNs when starting the server

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#953]
<p>Following WARNs were observed when starting the server,</p> <p>WARN - BasicSecurityTokenCodec Token TTL for container "</p> {0}" was {1} and will be ignored.<br/> WARN - BasicSecurityTokenCodec Token TTL for container "{0} <p>" was </p> {1} <p> and will be ignored.</p> <p>WARN - OAuthModule couldNotLoadSignedKey</p> <p>WARN - DefaultSchemaGenerator We don't support method overloading. Ignoring <span class="error">[validateAudienceRestriction]</span></p> <p>WARN - FileBasedConfigManager sso-idp-config.xml does not exist in the 'conf' directory. The system maydepend on the service providers added through the UI.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-321'>https://wso2.org/jira/browse/APPM-321</a></p>

**Comment by geethkokila** [comment]
Not related IoT server, hence closing.
