### ISSUE TITLE
[APPM-317] [Intermittent Issue] Error thrown when trying to Login to Publisher.

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#954]
<p>Backend error :</p> <p><span class="error">[2015-01-14 13:53:04,644]</span> ERROR - DefaultRequestCoordinator Context does not exist. Probably due to invalidated cache</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-317'>https://wso2.org/jira/browse/APPM-317</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing.
