### ISSUE TITLE
[APPM-293] sign-out of app redirects to login page

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#955]
<p>Steps:</p> <p>1) user logs into app manager<br/> 2) user clicks on gateway endpoint url and access HardwareRepository application<br/> 3) user signs out of application using the HardwareRepository application sign-out link</p> <p>when signing out of an application, the current user experience takes the user to a login page. </p> <p>if a user is already logged into the app-mgr portal, why is app-mgr asking them to login again?</p> <p>I would assume the correct behavior would be to redirect to App Manager portal, where the user has all their app links.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-293'>https://wso2.org/jira/browse/APPM-293</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
