### ISSUE TITLE
[APPM-292] Attempt to access HouseManager app fails

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#956]
<p>Attempt to access the House Manager app by clicking on the gateway endpoint url. My browser attempts to authenticate then a failure page is displayed:</p> <p>House Manager<br/> Sorry we encountered an internal server error. Try again later.</p> <p>clicking the 'House Manager' URL brings up this page:<br/> &amp;lt;am:fault&amp;gt;&amp;lt;am:code&amp;gt;404&amp;lt;/am:code&amp;gt;&amp;lt;am:type&amp;gt;Status report&amp;lt;/am:type&amp;gt;&amp;lt;am:message&amp;gt;Not Found&amp;lt;/am:message&amp;gt;&amp;lt;am:description&amp;gt;The requested resource (/HouseManagement/index.jag) is not available.&amp;lt;/am:description&amp;gt;&amp;lt;/am:fault&amp;gt;</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-292'>https://wso2.org/jira/browse/APPM-292</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
