### ISSUE TITLE
[APPM-290] ssl exception viewing user review tab in testbed

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#957]
<p>when attempting to view the 'User Review' tab for an app, Firefox displays a fatal ssl security exception:</p> <p>92.168.56.44:9443 uses an invalid security certificate. The certificate is not trusted because it is self-signed. The certificate is only valid for localhost (Error code: sec_error_unknown_issuer)</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-290'>https://wso2.org/jira/browse/APPM-290</a></p>

**Comment by geethkokila** [comment]
This is not related to IoT server, hence closing.
