### ISSUE TITLE
[APPM-104] Select "Always send back the authenticated list of identity providers" option when auto creating a service provider

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#961]
<p>"Always send back the authenticated list of identity providers" is needed for enterprise subscriptions.</p> <p>This option is under "Local &amp;amp; Outbound Authentication Configuration" section.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-104'>https://wso2.org/jira/browse/APPM-104</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
