### ISSUE TITLE
[APPM-24] Additional context and query parameters getting lost when accessing a applicaition

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#962]
<p>Lets say there is a foo application which having a gateway url as : <a href="http://localhost:8280/bar/1.0.0/" class="external-link" rel="nofollow">http://localhost:8280/bar/1.0.0/</a></p> <p>And say someone wants to access particular page of this application like following,<br/> <a href="http://localhost:8280/bar/1.0.0/company/?member=darshana" class="external-link" rel="nofollow">http://localhost:8280/bar/1.0.0/company/?member=darshana</a><br/> and type this url directly in the browser and if that browser do not have a authenticated session, it will ask for authentication and after that it won't directed to that requested url but it always directed to gateway url .</p> <p>This is because, saml response is redirected to the ACS of that service provider and when registering service providers the gateway url of that app is used as ACS url.</p> <p>To overcome this there are two options,<br/> 1. Relay state parameter should be added to saml request to keep track what is the requested url. And when processing the saml response, it should check for relay state parameter of the response and direct user to requested url.<br/> (According to the spec, in the saml response IdP should return relay state parameter without changing its value if the saml request contains a relay state parameter)<br/> 2. Set ACS as the requested url in the saml request and sign the saml request. In this case since the saml request is signed by the SP, IdP should honour the ACS value given in saml request. Here the saml response will be directed to ACS given in saml request without considering the ACS used when registering the SP in the IS.</p> <p>Considering these two options, AFAIK the first one is widely used in many applications and more likely supported by IdPs than option two.</p> <p>From the Identity Server point of view, the second method supports only in IS 5.0.0 onwards.</p> <p>Thanks,</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-24'>https://wso2.org/jira/browse/APPM-24</a></p>

**Comment by geethkokila** [comment]
Not related to IoT server, hence closing the issue.
