### ISSUE TITLE
[APPM-1639] Subscriber permission need to be added for mobile apps

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#966]
<p>Currently we only have webapp/subscribe permission. This is essential to login to app-store. but there can be a situation, user is only interested in mobileapps. In that case, user should be able to login with mobileapp/subscribe permission.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1639'>https://wso2.org/jira/browse/APPM-1639</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
