### ISSUE TITLE
[APPM-865] Anonymous Tenant user's can't view apps with default visibility

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#971]
<p>Since it is not possible to load a tenant store, anonymous tenant users can't view applications with default visibility.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-865'>https://wso2.org/jira/browse/APPM-865</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
