### ISSUE TITLE
[APPM-1399] Mobileaps -Version doesn;t get cleared after saving

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#973]
<p>Create a Mobile app<br/> Try to create another mobile app soon after.<br/> Version has not cleared and it shows the previous value</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1399'>https://wso2.org/jira/browse/APPM-1399</a></p>

**Comment by geethkokila** [comment]
Tested on the IoT 3.1.0 cluster, issue did not appear. And app manager component is being rewritten for IoT server, Hence closing the issue.
