### ISSUE TITLE
[APPM-1397] IOS - Public app (invalid appId water mark guideline)

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#974]
<p>Create a mobile app (IOS &amp;gt; Public)<br/> There if asks for an App Identifier which is mandatory.<br/> And as a help it whats a watermark guide"pakcakge name eg:com.companyname.appname" which is wrong and only applicable for Android. For Apple it should be something lie App Id (an integer)</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1397'>https://wso2.org/jira/browse/APPM-1397</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
