### ISSUE TITLE
[APPM-1216] Add an option to change the time zone of the app created time stamp

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#976]
<p>ATM the time zone of the App created time is picked by the system. It will be useful if you have a option to specify the timezone used when generating the time stamp.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1216'>https://wso2.org/jira/browse/APPM-1216</a></p>

**Comment by geethkokila** [comment]
This is not related to IoT App managements, hence closing the issue.
