### ISSUE TITLE
[APPM-755] On rejection notification is not required for the users who has both "Create" and "Publish" permissions

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#977]
<p>Under current implementation the rejection notification is mandatory for all users, if you are the admin or a user who has both create and publish permissions it doesn't make much sense to send the notification to your self.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-755'>https://wso2.org/jira/browse/APPM-755</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
