### ISSUE TITLE
[APPM-1431] Lifecycle state transition visualization

### ISSUE THREAD

**Issue by madhawap** [wso2/product-iots#980]
<p>In order to clarify the possible state transitions, which can take place for a particular application in WSO2 AppM, it's best to provide an illustration at the App Publisher.</p><p>Reference: <a href='https://wso2.org/jira/browse/APPM-1431'>https://wso2.org/jira/browse/APPM-1431</a></p>

**Comment by geethkokila** [comment]
App manager component is being rewritten for IoT server, and this will be addressed there. Hence closing the issue.
